/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.KnownIn1980s.EllipticCurves.TateCurve

/-!
# Torsion representatives under Tate uniformization

These lemmas derive the elementary torsion calculations from the repository's
Tate uniformization. The uniformization and its Galois equivariance are existing
admitted inputs; no Frey-specific local representation theorem is assumed.
-/

@[expose] public section

open scoped WeierstrassCurve.Affine
open ValuativeRel

namespace WeierstrassCurve

variable {k : Type*} [Field k] [ValuativeRel k] [TopologicalSpace k]
  [IsNonarchimedeanLocalField k]
variable (E : WeierstrassCurve k) [E.IsElliptic]
  [E.HasSplitMultiplicativeReduction 𝒪[k]]
variable (Ω : Type*) [Field Ω] [Algebra k Ω] [IsSepClosed Ω]
  [Algebra.IsSeparable k Ω] [DecidableEq Ω]

omit [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- Tate uniformization takes multiplication of units to addition of points. -/
theorem tatePoint_mul (u v : Ωˣ) :
    E.tatePoint Ω (u * v) = E.tatePoint Ω u + E.tatePoint Ω v := by
  unfold tatePoint
  rw [QuotientGroup.mk_mul]
  exact (E.tateEquivSepClosure Ω).map_add _ _

omit [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- Powers of a unit correspond to multiples of its Tate point. -/
theorem tatePoint_pow (u : Ωˣ) (n : ℕ) :
    E.tatePoint Ω (u ^ n) = n • E.tatePoint Ω u := by
  unfold tatePoint
  rw [QuotientGroup.mk_pow]
  exact (E.tateEquivSepClosure Ω).toAddMonoidHom.map_nsmul n _

omit [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- The kernel of Tate uniformization is precisely the powers of its parameter. -/
theorem tatePoint_eq_zero_iff (u : Ωˣ) :
    E.tatePoint Ω u = 0 ↔ u ∈ Subgroup.zpowers (E.qUnitSepClosure Ω) := by
  change E.tateEquivSepClosure Ω (Additive.ofMul ↑u) = 0 ↔ _
  rw [map_eq_zero_iff _ (E.tateEquivSepClosure Ω).injective]
  exact QuotientGroup.eq_one_iff u

/-- A Tate point is killed by `n` exactly when the `n`-th power of its
representative is an integral power of the Tate parameter. -/
theorem tatePoint_mem_torsionBy_iff (u : Ωˣ) (n : ℕ) :
    E.tatePoint Ω u ∈ AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ) ↔
      ∃ m : ℤ, u ^ n = E.qUnitSepClosure Ω ^ m := by
  rw [AddSubgroup.torsionBy.nsmul_iff, ← E.tatePoint_pow,
    E.tatePoint_eq_zero_iff, Subgroup.mem_zpowers_iff]
  exact exists_congr fun _ ↦ eq_comm

/-- Every torsion point has a unit representative whose power lies in the
cyclic group generated by the Tate parameter. -/
theorem exists_tatePoint_torsionBy_rep (n : ℕ)
    (P : AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ)) :
    ∃ (u : Ωˣ) (m : ℤ), E.tatePoint Ω u = P ∧ u ^ n = E.qUnitSepClosure Ω ^ m := by
  obtain ⟨x, hx⟩ := (E.tateEquivSepClosure Ω).surjective P
  obtain ⟨u, hu⟩ := QuotientGroup.mk_surjective x.toMul
  have hp : E.tatePoint Ω u = P := by
    change E.tateEquivSepClosure Ω (Additive.ofMul ↑u) = P
    rw [hu]
    exact hx
  obtain ⟨m, hm⟩ := (E.tatePoint_mem_torsionBy_iff Ω u n).mp (hp ▸ P.property)
  exact ⟨u, m, hp, hm⟩

end WeierstrassCurve
