/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.KnownIn1980s.EllipticCurves.TateCurve
public import Mathlib.Algebra.Module.ZMod

/-!
# Torsion representatives under Tate uniformization

These lemmas derive the elementary torsion calculations from the repository's
Tate uniformization. The uniformization and its Galois equivariance are existing
admitted inputs; no Frey-specific local representation theorem is assumed.
-/

@[expose] public section

open scoped WeierstrassCurve.Affine
open ValuativeRel

namespace WeierstrassCurve

variable {k : Type*} [Field k] [ValuativeRel k] [TopologicalSpace k]
  [IsNonarchimedeanLocalField k]
variable (E : WeierstrassCurve k) [E.IsElliptic]
  [E.HasSplitMultiplicativeReduction 𝒪[k]]
variable (Ω : Type*) [Field Ω] [Algebra k Ω] [DecidableEq Ω]

/-- Tate uniformization takes multiplication of units to addition of points. -/
theorem tatePoint_mul (u v : Ωˣ) :
    E.tatePoint Ω (u * v) = E.tatePoint Ω u + E.tatePoint Ω v := by
  unfold tatePoint
  rw [QuotientGroup.mk_mul]
  exact (E.tateEquivSepClosure Ω).map_add _ _

/-- Powers of a unit correspond to multiples of its Tate point. -/
theorem tatePoint_pow (u : Ωˣ) (n : ℕ) :
    E.tatePoint Ω (u ^ n) = n • E.tatePoint Ω u := by
  unfold tatePoint
  rw [QuotientGroup.mk_pow]
  exact (E.tateEquivSepClosure Ω).toAddMonoidHom.map_nsmul n _

/-- The kernel of Tate uniformization is precisely the powers of its parameter. -/
theorem tatePoint_eq_zero_iff (u : Ωˣ) :
    E.tatePoint Ω u = 0 ↔ u ∈ Subgroup.zpowers (E.qUnitSepClosure Ω) := by
  change E.tateEquivSepClosure Ω (Additive.ofMul ↑u) = 0 ↔ _
  rw [map_eq_zero_iff _ (E.tateEquivSepClosure Ω).injective]
  exact QuotientGroup.eq_one_iff u

/-- A Tate point is killed by `n` exactly when the `n`-th power of its
representative is an integral power of the Tate parameter. -/
theorem tatePoint_mem_torsionBy_iff (u : Ωˣ) (n : ℕ) :
    E.tatePoint Ω u ∈ AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ) ↔
      ∃ m : ℤ, u ^ n = E.qUnitSepClosure Ω ^ m := by
  rw [AddSubgroup.torsionBy.nsmul_iff, ← E.tatePoint_pow,
    E.tatePoint_eq_zero_iff, Subgroup.mem_zpowers_iff]
  exact exists_congr fun _ ↦ eq_comm

/-- Every torsion point has a unit representative whose power lies in the
cyclic group generated by the Tate parameter. -/
theorem exists_tatePoint_torsionBy_rep (n : ℕ)
    (P : AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ)) :
    ∃ (u : Ωˣ) (m : ℤ), E.tatePoint Ω u = P ∧ u ^ n = E.qUnitSepClosure Ω ^ m := by
  obtain ⟨x, hx⟩ := (E.tateEquivSepClosure Ω).surjective P
  obtain ⟨u, hu⟩ := QuotientGroup.mk_surjective x.toMul
  have hp : E.tatePoint Ω u = P := by
    change E.tateEquivSepClosure Ω (Additive.ofMul ↑u) = P
    rw [hu]
    exact hx
  obtain ⟨m, hm⟩ := (E.tatePoint_mem_torsionBy_iff Ω u n).mp (hp ▸ P.property)
  exact ⟨u, m, hp, hm⟩

omit [DecidableEq Ω] in
/-- The Tate parameter has infinite order, also after extending the coefficient field. -/
theorem qUnitSepClosure_not_isOfFinOrder : ¬ IsOfFinOrder (E.qUnitSepClosure Ω) := by
  rw [isOfFinOrder_iff_pow_eq_one]
  rintro ⟨n, hn, heq⟩
  have hk : E.q ^ n = 1 := by
    apply (algebraMap k Ω).injective
    have h := congrArg (fun u : Ωˣ ↦ (u : Ω)) heq
    simpa [qUnitSepClosure, qUnit] using h
  have hv := congrArg (valuation k) hk
  rw [map_pow, map_one] at hv
  exact (pow_lt_one₀ zero_le E.valuation_q_lt_one hn.ne').ne hv

/-- Equal Tate points have the same torsion exponent modulo `n`. -/
theorem tatePoint_exponent_eq {n : ℕ} {u v : Ωˣ} {a b : ℤ}
    (hu : u ^ n = E.qUnitSepClosure Ω ^ a)
    (hv : v ^ n = E.qUnitSepClosure Ω ^ b)
    (h : E.tatePoint Ω u = E.tatePoint Ω v) : (a : ZMod n) = b := by
  have hquot : (u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) = v :=
    (E.tateEquivSepClosure Ω).injective h
  obtain ⟨c, hc⟩ := QuotientGroup.eq_iff_div_mem.mp hquot
  dsimp only at hc
  have hp : E.qUnitSepClosure Ω ^ (c * n) = E.qUnitSepClosure Ω ^ (a - b) := by
    rw [zpow_mul, zpow_natCast, hc, div_pow, hu, hv, zpow_sub, div_eq_mul_inv]
  have hab : c * n = a - b :=
    (injective_zpow_iff_not_isOfFinOrder.mpr (E.qUnitSepClosure_not_isOfFinOrder Ω)) hp
  have hz : ((a - b : ℤ) : ZMod n) = 0 := by
    rw [← hab]
    simp
  apply sub_eq_zero.mp
  simpa only [Int.cast_sub] using hz

/-- The exponent modulo `n` of any unit representative of a Tate torsion point. -/
noncomputable def tateTorsionExponent (n : ℕ)
    (P : AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ)) : ZMod n :=
  ((E.exists_tatePoint_torsionBy_rep Ω n P).choose_spec.choose : ℤ)

/-- Compute the exponent map using any representative, independently of its choice. -/
theorem tateTorsionExponent_eq {n : ℕ}
    (P : AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ)) (u : Ωˣ) (m : ℤ)
    (hu : E.tatePoint Ω u = P) (hm : u ^ n = E.qUnitSepClosure Ω ^ m) :
    E.tateTorsionExponent Ω n P = m := by
  let h := E.exists_tatePoint_torsionBy_rep Ω n P
  exact E.tatePoint_exponent_eq Ω h.choose_spec.choose_spec.2 hm
    (h.choose_spec.choose_spec.1.trans hu.symm)

/-- The Tate torsion exponent is an additive map to `ℤ/nℤ`. -/
noncomputable def tateTorsionQuotient (n : ℕ) :
    AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ) →+ ZMod n where
  toFun := E.tateTorsionExponent Ω n
  map_zero' := by
    rw [← Int.cast_zero]
    apply E.tateTorsionExponent_eq Ω _ 1 0
    · exact (E.tateEquivSepClosure Ω).map_zero
    · simp
  map_add' P Q := by
    obtain ⟨u, a, hu, ha⟩ := E.exists_tatePoint_torsionBy_rep Ω n P
    obtain ⟨v, b, hv, hb⟩ := E.exists_tatePoint_torsionBy_rep Ω n Q
    rw [E.tateTorsionExponent_eq Ω P u a hu ha,
      E.tateTorsionExponent_eq Ω Q v b hv hb]
    rw [← Int.cast_add]
    apply E.tateTorsionExponent_eq Ω (P + Q) (u * v) (a + b)
    · rw [E.tatePoint_mul, hu, hv]
      rfl
    · rw [mul_pow, ha, hb, zpow_add]

omit [DecidableEq Ω] in
/-- Galois automorphisms fix the Tate parameter in the extension field. -/
theorem qUnitSepClosure_galois (σ : Ω ≃ₐ[k] Ω) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom (E.qUnitSepClosure Ω) =
      E.qUnitSepClosure Ω := by
  ext
  exact σ.commutes _

/-- The quotient of Tate torsion is fixed by the entire local Galois group,
so in particular it is fixed by inertia. -/
theorem tateTorsionQuotient_galois [IsSepClosed Ω] [Algebra.IsSeparable k Ω] (n : ℕ) (σ : Ω ≃ₐ[k] Ω)
    (P Q : AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ))
    (hQ : (Q : (E⁄Ω).Point) = Affine.Point.map σ.toAlgHom P) :
    E.tateTorsionQuotient Ω n Q = E.tateTorsionQuotient Ω n P := by
  obtain ⟨u, m, hu, hm⟩ := E.exists_tatePoint_torsionBy_rep Ω n P
  change E.tateTorsionExponent Ω n Q = E.tateTorsionExponent Ω n P
  rw [E.tateTorsionExponent_eq Ω P u m hu hm]
  apply E.tateTorsionExponent_eq Ω Q (Units.map σ.toAlgHom.toRingHom.toMonoidHom u) m
  · rw [← E.tatePoint_galois, hu, hQ]
  · rw [← map_pow, hm, map_zpow, E.qUnitSepClosure_galois]

omit [DecidableEq Ω] in
/-- Over a separably closed field, the Tate parameter has an `n`-th root
whenever `n` is nonzero in the field. -/
theorem exists_pow_eq_qUnitSepClosure [IsSepClosed Ω] (n : ℕ) [NeZero (n : Ω)] :
    ∃ r : Ωˣ, r ^ n = E.qUnitSepClosure Ω := by
  obtain ⟨r, hr⟩ := IsSepClosed.exists_pow_nat_eq (E.qUnitSepClosure Ω : Ω) n
  have hn : n ≠ 0 := by
    intro h
    exact NeZero.ne (n : Ω) (by simp [h])
  have hr0 : r ≠ 0 := by
    intro h
    rw [h, zero_pow hn] at hr
    exact (E.qUnitSepClosure Ω).ne_zero hr.symm
  exact ⟨Units.mk0 r hr0, Units.ext hr⟩

/-- The Tate torsion quotient hits `1`, hence is nonzero for `n > 1`. -/
theorem exists_tateTorsionQuotient_eq_one [IsSepClosed Ω] (n : ℕ) [NeZero (n : Ω)] :
    ∃ P, E.tateTorsionQuotient Ω n P = 1 := by
  obtain ⟨r, hr⟩ := E.exists_pow_eq_qUnitSepClosure Ω n
  let P : AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ) :=
    ⟨E.tatePoint Ω r, (E.tatePoint_mem_torsionBy_iff Ω r n).mpr
      ⟨1, by simpa only [zpow_one] using hr⟩⟩
  refine ⟨P, ?_⟩
  change E.tateTorsionExponent Ω n P = 1
  rw [← Int.cast_one]
  apply E.tateTorsionExponent_eq Ω P r 1 rfl
  simpa only [zpow_one] using hr

/-- The Galois-invariant quotient supplied by Tate uniformization is surjective. -/
theorem tateTorsionQuotient_surjective [IsSepClosed Ω] (n : ℕ) [NeZero (n : Ω)] :
    Function.Surjective (E.tateTorsionQuotient Ω n) := by
  obtain ⟨P, hP⟩ := E.exists_tateTorsionQuotient_eq_one Ω n
  intro x
  obtain ⟨a, rfl⟩ := ZMod.intCast_surjective x
  refine ⟨a • P, ?_⟩
  rw [map_zsmul, hP, zsmul_eq_mul, mul_one]

/-- The torsion exponent quotient as a linear map, for any compatible
`ZMod n` module structure on the torsion group. -/
noncomputable def tateTorsionQuotientLinear (n : ℕ)
    [Module (ZMod n) (AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ))] :
    AddSubgroup.torsionBy (E⁄Ω).Point (n : ℤ) →ₗ[ZMod n] ZMod n :=
  (E.tateTorsionQuotient Ω n).toZModLinearMap n

/-- Split multiplicative reduction supplies a nonzero Galois-invariant linear
functional on geometric `p`-torsion. This proves the local Tate case without
assuming any Frey-specific representation theorem. -/
theorem exists_invariant_tateTorsion_functional [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
    (p : ℕ) [Fact p.Prime] [NeZero (p : Ω)]
    [Module (ZMod p) (AddSubgroup.torsionBy (E⁄Ω).Point (p : ℤ))] :
    ∃ r : AddSubgroup.torsionBy (E⁄Ω).Point (p : ℤ) →ₗ[ZMod p] ZMod p,
      r ≠ 0 ∧ ∀ (σ : Ω ≃ₐ[k] Ω) (P Q : AddSubgroup.torsionBy (E⁄Ω).Point (p : ℤ)),
        (Q : (E⁄Ω).Point) = Affine.Point.map σ.toAlgHom P → r Q = r P := by
  refine ⟨E.tateTorsionQuotientLinear Ω p, ?_, ?_⟩
  · obtain ⟨P, hP⟩ := E.exists_tateTorsionQuotient_eq_one Ω p
    intro h
    have hz : E.tateTorsionQuotient Ω p P = 0 := LinearMap.congr_fun h P
    exact zero_ne_one (hz.symm.trans hP)
  · exact E.tateTorsionQuotient_galois Ω p

end WeierstrassCurve
