/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mathlib.RingTheory.FlatIdealBaseChange
public import FLT.Mathlib.RingTheory.LocalRing.GeneratorDescent
public import Mathlib.RingTheory.Regular.RegularSequence

/-! # Descending the number of generators of an ideal under a flat local map -/

@[expose] public noncomputable section

namespace Ideal

variable {R : Type*} [CommRing R] [IsLocalRing R]
  (S : Type*) [CommRing S] [IsLocalRing S] [Algebra R S]
  [IsLocalHom (algebraMap R S)] [Module.Flat R S]

/-- A finite ideal generated by n elements after flat local extension has an
n-element generating list over the original ring. The list is constructed by
lifting a residue basis and padding with zero if necessary. -/
theorem exists_ofList_of_map_eq_span (I : Ideal R) [Module.Finite R I] {n : ℕ}
    (v : Fin n → S) (hv : I.map (algebraMap R S) = Ideal.span (Set.range v)) :
    ∃ rs : List R, rs.length = n ∧ Ideal.ofList rs = I := by
  let J := I.map (algebraMap R S)
  have hm (i : Fin n) : v i ∈ J := by
    change v i ∈ I.map (algebraMap R S)
    rw [hv]
    exact Ideal.subset_span ⟨i, rfl⟩
  have hs : Submodule.span S (Set.range fun i ↦ (⟨v i, hm i⟩ : J)) = ⊤ :=
    (Submodule.span_range_subtype_eq_top_iff J hm).mpr hv.symm
  obtain ⟨d, hd, w, hw⟩ := IsLocalRing.exists_generators_of_isBaseChange
    (isBaseChange_idealMap S I) (fun i ↦ (⟨v i, hm i⟩ : J)) hs
  let qs : List R := List.ofFn fun i ↦ (w i : R)
  have hqs : Ideal.ofList qs = I := by
    have h := (Submodule.span_range_subtype_eq_top_iff I (fun i ↦ (w i).property)).mp hw
    change Submodule.span R {r | r ∈ qs} = I
    rw [← h]
    congr 1
    ext r
    simp [qs]
  have hz : Ideal.ofList (List.replicate (n - d) (0 : R)) = ⊥ := by
    apply le_antisymm _ bot_le
    apply Ideal.span_le.mpr
    intro r hr
    have he := (List.mem_replicate.mp hr).2
    change r = 0
    exact he
  refine ⟨qs ++ List.replicate (n - d) 0, ?_, ?_⟩
  · simp only [List.length_append, List.length_replicate, qs, List.length_ofFn]
    omega
  · rw [Ideal.ofList_append, hqs, hz, sup_bot_eq]

end Ideal
