/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.RingTheory.LocalRing.Module

/-! # Lifting a residue basis to a minimal generating family -/

@[expose] public noncomputable section

open scoped TensorProduct

namespace IsLocalRing

variable (R M : Type*) [CommRing R] [IsLocalRing R] [AddCommGroup M] [Module R M]
  [Module.Finite R M]

/-- A finite module over a local ring is generated by as many elements as the
dimension of its residue module. -/
theorem exists_generators_of_residue_basis :
    ∃ v : Fin (Module.finrank (ResidueField R) (ResidueField R ⊗[R] M)) → M,
      Submodule.span R (Set.range v) = ⊤ := by
  let b := Module.finBasis (ResidueField R) (ResidueField R ⊗[R] M)
  have hs := TensorProduct.mk_surjective R M (ResidueField R) residue_surjective
  choose v hv using fun i ↦ hs (b i)
  exact ⟨v, span_eq_top_of_tmul_eq_basis v b hv⟩

/-- A bound on the residue dimension bounds a generating family over the original ring. -/
theorem exists_generators_of_residue_finrank_le {n : ℕ}
    (h : Module.finrank (ResidueField R) (ResidueField R ⊗[R] M) ≤ n) :
    ∃ d ≤ n, ∃ v : Fin d → M, Submodule.span R (Set.range v) = ⊤ := by
  obtain ⟨v, hv⟩ := exists_generators_of_residue_basis R M
  exact ⟨_, h, v, hv⟩

end IsLocalRing
