/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GaloisRepresentation.HardlyRamified.AugmentedField
public import FLT.GaloisRepresentation.HardlyRamified.FiniteFlatUnramified
public import FLT.GaloisRepresentation.HardlyRamified.PointFieldBaseChange
public import FLT.GroupScheme.LocalPointField
public import FLT.GroupScheme.ModelBaseChange
public import FLT.GroupScheme.PadicPatchingRings

/-!
# The augmented finite flat model over the three-adic integers

The coordinate algebra is the scalar extension of the given global model.
Its points are the local restriction of the original global point group, so
augmentation followed by base change preserves annihilation by three.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false

open scoped TensorProduct

namespace ThreeAdicPlan

/-- Two is invertible in the three-adic coefficient ring. -/
local instance : Fact (¬ ((3 : ℕ) : ℤ) ∣ 2) := ⟨by norm_num⟩

/-- The localization map to the three-adic integers. -/
local instance : Algebra ZInvTwo ℤ_[3] :=
  (PadicPatching.baseToLocal 3 2).toAlgebra

/-- The induced map to the three-adic field. -/
local instance : Algebra ZInvTwo ℚ_[3] :=
  Algebra.compHom ℚ_[3] (PadicPatching.baseToLocal 3 2)

/-- The localization maps are compatible with the integral inclusion. -/
local instance : IsScalarTower ZInvTwo ℤ_[3] ℚ_[3] := zInvTwo_scalarTower _ _

/-- The rational and integral embeddings of the coefficient ring agree over `ℚ₃`. -/
local instance : IsScalarTower ZInvTwo ℚ ℚ_[3] := zInvTwo_scalarTower _ _

/-- The actual scalar extension of a global model to the three-adic integers. -/
def FiniteFlatObject.localModelAtThree (H : FiniteFlatObject ZInvTwo) :
    HasFiniteFlatModel ℤ_[3] H.points.localAtThree := H.model.baseChange ℤ_[3] ℚ_[3]

/-- The local model in the format used by the local different bound. -/
def FiniteFlatObject.localFFAtThree (H : FiniteFlatObject ZInvTwo) : FF ℤ_[3] ℚ_[3] :=
  H.localModelAtThree.toFF

/-- The local model has the tensor-product coordinate ring of genuine base change. -/
theorem FiniteFlatObject.localFFAtThree_coordinateRing (H : FiniteFlatObject ZInvTwo) :
    H.localFFAtThree.CoordinateRing = ℤ_[3] ⊗[ZInvTwo] H.model.CoordinateRing := rfl

/-- Local restriction retains the exact annihilating integer. -/
theorem FiniteFlatObject.killedBy_localFFAtThree (H : FiniteFlatObject ZInvTwo)
    (n : ℕ) (h : KilledByQ n H) : KilledBy n H.localFFAtThree := h

/-- Base-changing the augmented object gives a three-adic model killed by three. -/
theorem augmentedObject_localFFAtThree_killedBy_three
    {H : FiniteFlatObject ZInvTwo} (hs : Simple H) (hD : InCategoryD H) :
    KilledBy 3 (augmentedObject H).localFFAtThree :=
  (augmentedObject H).killedBy_localFFAtThree 3 (augmentedObject_killedBy_three hs hD)

/-- The local point action kernel is the inverse image of the global point action kernel. -/
theorem FiniteFlatObject.localFFAtThree_pointActionKernel (H : FiniteFlatObject ZInvTwo) :
    H.localFFAtThree.pointActionKernel = H.points.pointActionKernel.comap
      (Field.absoluteGaloisGroup.map (algebraMap ℚ ℚ_[3])).toMonoidHom := by
  ext σ
  rw [FF.mem_pointActionKernel, Subgroup.mem_comap,
    FiniteContinuousGaloisModule.mem_pointActionKernel]
  rfl

/-- The local point field is cut out by the restricted full global action. -/
theorem FiniteFlatObject.localPointField_eq_fixedField (H : FiniteFlatObject ZInvTwo) :
    LocalPointField H.localFFAtThree = IntermediateField.fixedField
      (H.points.pointActionKernel.comap
        (Field.absoluteGaloisGroup.map (algebraMap ℚ ℚ_[3])).toMonoidHom) := by
  rw [LocalPointField, H.localFFAtThree_pointActionKernel]

/-- The local model's full point field is generated by the global full point field over `ℚ₃`. -/
theorem FiniteFlatObject.localPointField_eq_adjoin (H : FiniteFlatObject ZInvTwo) :
    LocalPointField H.localFFAtThree =
      IntermediateField.adjoin ℚ_[3] (Set.range (H.points.pointFieldEmbedding ℚ_[3])) :=
  H.model.localPointField_baseChange ℤ_[3] ℚ_[3]

end ThreeAdicPlan
