/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GaloisRepresentation.HardlyRamified.AugmentedCompletionDifferent
public import FLT.GroupScheme.CompletionDifferent

/-!
# Global different exponents of augmented point fields

The actual global different exponent equals the different exponent of each
completion above three. Thus the local Fontaine hypothesis bounds the global
primewise exponent with the same normalization.
-/

@[expose] public noncomputable section

open NumberField

namespace ThreeAdicPlan

/-- The rational place chosen for three-adic point fields is the ideal generated by three. -/
theorem threeAdicPointFieldPlace_asIdeal :
    threeAdicPointFieldPlace.asIdeal = Ideal.span {(3 : 𝓞 ℚ)} := by
  change (Ideal.span {(3 : ℤ)}).map
    (Rat.IsIntegralClosure.intEquiv (𝓞 ℚ)).symm.toRingHom = _
  rw [Ideal.map_span, Set.image_singleton, map_ofNat]

/-- Every extension of the chosen rational place contains three. -/
theorem three_mem_pointFieldPlace_extension
    {L : Type*} [Field L] [NumberField L]
    (w : threeAdicPointFieldPlace.Extension (𝓞 L)) : (3 : 𝓞 L) ∈ w.1.asIdeal := by
  have h : (3 : 𝓞 ℚ) ∈ (w.1.under (𝓞 ℚ)).asIdeal := by
    rw [w.2, threeAdicPointFieldPlace_asIdeal]
    exact Ideal.subset_span (Set.mem_singleton _)
  change algebraMap (𝓞 ℚ) (𝓞 L) (3 : 𝓞 ℚ) ∈ w.1.asIdeal at h
  simpa only [map_ofNat] using h

/-- The global normalized different of a full point field is the actual
normalized different of each completion above three. -/
theorem FiniteFlatObject.global_normalizedDifferent_eq_completion
    (H : FiniteFlatObject ZInvTwo)
    (w : threeAdicPointFieldPlace.Extension (𝓞 (PointField H))) :
    NumberField.normalizedDifferentExponentAt (PointField H) w.1.asIdeal =
      pointFieldCompletionNormalizedDifferent H w := by
  let eO : threeAdicPointFieldPlace.adicCompletionIntegers ℚ ≃ₐ[ℤ] ℤ_[3] :=
    (PadicInt.adicCompletionIntegersEquiv (𝓞 ℚ) ⟨3, Nat.prime_three⟩).symm.toAlgEquiv
  exact (normalizedDifferentExponent_completion_eq threeAdicPointFieldPlace
    threeAdicPointFieldBaseEquiv eO
    (fun z ↦ PadicInt.coe_adicCompletionIntegersEquiv_apply (𝓞 ℚ) ⟨3, Nat.prime_three⟩ z)
    w (three_mem_pointFieldPlace_extension w)).symm

/-- For every augmented point field, the global and completed different
exponents agree with the normalization `v(3) = 1`. -/
theorem augmentedField_normalizedDifferent_eq_completion
    (H : FiniteFlatObject ZInvTwo)
    (w : threeAdicPointFieldPlace.Extension (𝓞 (AugmentedField H))) :
    NumberField.normalizedDifferentExponentAt (AugmentedField H) w.1.asIdeal =
      pointFieldCompletionNormalizedDifferent (augmentedObject H) w :=
  (augmentedObject H).global_normalizedDifferent_eq_completion w

/-- Fontaine's local hypothesis now bounds the actual global different exponent
at every augmented-field prime above three. -/
theorem augmentedField_normalizedDifferent_lt
    (hF : FontaineDifferentBoundKilledThree)
    {H : FiniteFlatObject ZInvTwo} (hs : Simple H) (hD : InCategoryD H)
    (w : threeAdicPointFieldPlace.Extension (𝓞 (AugmentedField H))) :
    NumberField.normalizedDifferentExponentAt (AugmentedField H) w.1.asIdeal < (3 / 2 : ℚ) := by
  rw [augmentedField_normalizedDifferent_eq_completion H w]
  exact augmentedField_completion_normalizedDifferent_lt hF hs hD w

end ThreeAdicPlan
