/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GaloisRepresentation.HardlyRamified.KummerTwoField
public import Mathlib.Analysis.Real.Pi.Bounds
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.RingTheory.DedekindDomain.Factorization
public import Mathlib.RingTheory.Trace.Basic

/-!
# Class number one for the sextic Kummer field

The residue units at three are exactly `±1`. The primes above two and three are
principal, and no ideal has norm five. Six explicit integral elements have
discriminant `-34992`, giving a sufficient bound on the field discriminant.
The Minkowski bound is then strictly less than six, proving class number one.
-/

@[expose] public section

noncomputable section

namespace ThreeAdicPlan

open NumberField Polynomial
open scoped nonZeroDivisors

/-- Every residue unit at the specified prime above three is a power of `-1`,
expressed as the equivalent assertion that it is either `1` or `-1`. -/
def ResidueUnitsGeneratedByNegOne (K : Type*) [Field K] [NumberField K] : Prop :=
  ∀ u : (𝓞 K ⧸ primeAboveThree K)ˣ, u = 1 ∨ u = -1

/-- A residue field isomorphic to `𝔽₃` has only the two units `±1`. -/
theorem ResidueFieldAtThreeIsF3.residueUnitsGeneratedByNegOne
    {K : Type*} [Field K] [NumberField K] (h : ResidueFieldAtThreeIsF3 K) :
    ResidueUnitsGeneratedByNegOne K := by
  obtain ⟨e⟩ := h
  intro u
  have hcases : ∀ x : ZMod 3, x ≠ 0 → x = 1 ∨ x = -1 := by decide
  have hu : e (u : 𝓞 K ⧸ primeAboveThree K) ≠ 0 := by
    exact fun hzero ↦ u.ne_zero (e.injective (hzero.trans e.map_zero.symm))
  rcases hcases _ hu with h1 | h1
  · left
    apply Units.ext
    apply e.injective
    simpa using h1
  · right
    apply Units.ext
    apply e.injective
    simpa using h1

/-- The residue units of the sextic Kummer field at three are generated by `-1`. -/
theorem residueUnitsGeneratedByNegOne_kummerTwoField : ResidueUnitsGeneratedByNegOne K₀ :=
  residueFieldAtThreeIsF3_kummerTwoField.residueUnitsGeneratedByNegOne

/-- There is exactly one prime above two. -/
theorem primesOver_two_eq_singleton (P : Ideal (𝓞 K₀)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(2 : ℤ)})] :
    (Ideal.span {(2 : ℤ)}).primesOver (𝓞 K₀) = {P} := by
  classical
  have : (Ideal.span {(2 : ℤ)}).IsMaximal := Int.ideal_span_isMaximal_of_prime 2
  have hsum := Ideal.sum_ramification_inertia_eq_finrank
    (Ideal.span {(2 : ℤ)}) (𝓞 K₀)
  have hall : ∀ q : (Ideal.span {(2 : ℤ)}).primesOver (𝓞 K₀),
      q.1.ramificationIdx ℤ * q.1.inertiaDeg ℤ = 6 := by
    intro q
    obtain ⟨he, hf⟩ := ramification_inertia_at_two q.1
    rw [he, hf]
  simp only [hall, Finset.sum_const, Finset.card_univ, smul_eq_mul,
    RingOfIntegers.rank, finrank_kummerTwoField] at hsum
  have hcard : Fintype.card ((Ideal.span {(2 : ℤ)}).primesOver (𝓞 K₀)) = 1 := by omega
  have : Subsingleton ((Ideal.span {(2 : ℤ)}).primesOver (𝓞 K₀)) :=
    Fintype.card_le_one_iff_subsingleton.mp (by omega)
  apply Set.eq_singleton_iff_unique_mem.mpr
  refine ⟨⟨inferInstance, inferInstance⟩, ?_⟩
  intro Q hQ
  exact congrArg Subtype.val (Subsingleton.elim
    (⟨Q, hQ⟩ : (Ideal.span {(2 : ℤ)}).primesOver (𝓞 K₀))
    ⟨P, inferInstance, inferInstance⟩)

/-- The prime above two has cube equal to `(2)`. -/
theorem primeAboveTwo_cube (P : Ideal (𝓞 K₀)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(2 : ℤ)})] :
    P ^ 3 = Ideal.span {(2 : 𝓞 K₀)} := by
  have : (Ideal.span {(2 : ℤ)}).IsMaximal := Int.ideal_span_isMaximal_of_prime 2
  have h := Ideal.map_algebraMap_eq_finsetProd_pow (R := 𝓞 K₀)
    (p := Ideal.span {(2 : ℤ)}) (by simp)
  simpa [primesOver_two_eq_singleton P, Ideal.map_span, Set.image_singleton,
    ramificationIdx_at_two P] using h.symm

/-- The prime above two is generated by any integral cube root of two. -/
theorem primeAboveTwo_eq_span_cubeRoot (P : Ideal (𝓞 K₀)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(2 : ℤ)})] (a : 𝓞 K₀) (ha : a ^ 3 = 2) :
    P = Ideal.span {a} := by
  apply pow_left_injective (by decide : 3 ≠ 0)
  change P ^ 3 = Ideal.span {a} ^ 3
  rw [primeAboveTwo_cube P, Ideal.span_singleton_pow, ha]

/-- Every prime above two is principal. -/
theorem isPrincipal_primeAboveTwo (P : Ideal (𝓞 K₀)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(2 : ℤ)})] : P.IsPrincipal := by
  obtain ⟨a, ha⟩ := exists_integral_cubeRoot_two
  rw [primeAboveTwo_eq_span_cubeRoot P a ha]
  infer_instance

/-- The specified prime above three has sixth power equal to `(3)`. -/
theorem primeAboveThree_sixth_pow :
    primeAboveThree K₀ ^ 6 = Ideal.span {(3 : 𝓞 K₀)} := by
  have : Fact (Nat.Prime 3) := ⟨by decide⟩
  have : (Ideal.span {(3 : ℤ)}).IsMaximal := Int.ideal_span_isMaximal_of_prime 3
  have h := Ideal.map_algebraMap_eq_finsetProd_pow (R := 𝓞 K₀)
    (p := Ideal.span {(3 : ℤ)}) (by simp)
  have hsingle : (Ideal.span {(3 : ℤ)}).primesOver (𝓞 K₀) = {primeAboveThree K₀} :=
    uniquePrimeAboveThree_kummerTwoField
  simpa [hsingle, Ideal.map_span, Set.image_singleton,
    (ramification_inertia_at_three (primeAboveThree K₀)).1] using h.symm

/-- The square of the prime above three is generated by `∛2 + 1`. -/
theorem primeAboveThree_sq_eq_span (a : 𝓞 K₀) (ha : a ^ 3 = 2) :
    primeAboveThree K₀ ^ 2 = Ideal.span {a + 1} := by
  have hu : IsUnit (a ^ 2 + a + 1) := by
    apply isUnit_iff_exists_inv.mpr
    refine ⟨a - 1, ?_⟩
    calc
      (a ^ 2 + a + 1) * (a - 1) = a ^ 3 - 1 := by ring
      _ = 1 := by rw [ha]; norm_num
  have hpow : (a + 1) ^ 3 = 3 * (a ^ 2 + a + 1) := by
    calc
      (a + 1) ^ 3 = a ^ 3 + 3 * a ^ 2 + 3 * a + 1 := by ring
      _ = 3 * (a ^ 2 + a + 1) := by rw [ha]; ring
  apply pow_left_injective (by decide : 3 ≠ 0)
  change (primeAboveThree K₀ ^ 2) ^ 3 = Ideal.span {a + 1} ^ 3
  rw [← pow_mul, show 2 * 3 = 6 from rfl, primeAboveThree_sixth_pow,
    Ideal.span_singleton_pow, hpow, ← Ideal.span_singleton_mul_span_singleton,
    Ideal.span_singleton_eq_top.mpr hu, Ideal.mul_top]

/-- The cube of the prime above three is generated by `√(-3)`. -/
theorem primeAboveThree_cube_eq_span (b : 𝓞 K₀) (hb : b ^ 2 = -3) :
    primeAboveThree K₀ ^ 3 = Ideal.span {b} := by
  apply pow_left_injective (by decide : 2 ≠ 0)
  change (primeAboveThree K₀ ^ 3) ^ 2 = Ideal.span {b} ^ 2
  rw [← pow_mul, show 3 * 2 = 6 from rfl, primeAboveThree_sixth_pow,
    Ideal.span_singleton_pow, hb, Ideal.span_singleton_neg]

/-- The specified prime above three is principal: its square and cube have trivial class. -/
theorem isPrincipal_primeAboveThree : (primeAboveThree K₀).IsPrincipal := by
  have hP : primeAboveThree K₀ ∈ (Ideal (𝓞 K₀))⁰ :=
    mem_nonZeroDivisors_of_ne_zero (Ideal.ne_bot_of_liesOver_of_ne_bot
      (p := Ideal.span {(3 : ℤ)}) (by simp) _)
  let I : (Ideal (𝓞 K₀))⁰ := ⟨primeAboveThree K₀, hP⟩
  have h2 : ClassGroup.mk0 I ^ 2 = 1 := by
    rw [← map_pow, ClassGroup.mk0_eq_one_iff]
    obtain ⟨a, ha⟩ := exists_integral_cubeRoot_two
    change (primeAboveThree K₀ ^ 2).IsPrincipal
    rw [primeAboveThree_sq_eq_span a ha]
    infer_instance
  have h3 : ClassGroup.mk0 I ^ 3 = 1 := by
    rw [← map_pow, ClassGroup.mk0_eq_one_iff]
    obtain ⟨b, hb⟩ := exists_integral_sqrt_neg_three
    change (primeAboveThree K₀ ^ 3).IsPrincipal
    rw [primeAboveThree_cube_eq_span b hb]
    infer_instance
  apply (ClassGroup.mk0_eq_one_iff hP).mp
  change ClassGroup.mk0 I = 1
  simpa [pow_succ, h2] using h3

/-- No ideal of the Kummer field has norm five. -/
theorem absNorm_ne_five (P : Ideal (𝓞 K₀)) : Ideal.absNorm P ≠ 5 := by
  intro hcard
  have hc : Nat.card (𝓞 K₀ ⧸ P) = 5 := hcard
  have : Finite (𝓞 K₀ ⧸ P) := Nat.finite_of_card_ne_zero (by omega)
  let := Fintype.ofFinite (𝓞 K₀ ⧸ P)
  let e : (𝓞 K₀ ⧸ P) ≃+* ZMod 5 :=
    (ZMod.ringEquivOfPrime (𝓞 K₀ ⧸ P) (by decide)
      (by simpa only [Nat.card_eq_fintype_card] using hc)).symm
  obtain ⟨z, hz⟩ := exists_integral_thirdRoot
  have he := congrArg (e.toRingHom.comp (Ideal.Quotient.mk P)) hz
  simp only [map_add, map_pow, map_one, map_zero] at he
  have hn : ∀ x : ZMod 5, x ^ 2 + x + 1 ≠ 0 := by decide
  exact hn _ he

/-- The Kummer field has no real places. -/
theorem nrRealPlaces_kummerTwoField : InfinitePlace.nrRealPlaces K₀ = 0 := by
  classical
  apply Fintype.card_eq_zero_iff.mpr
  refine ⟨fun ⟨w, hw⟩ ↦ ?_⟩
  obtain ⟨b, hb⟩ := exists_integral_sqrt_neg_three
  let f := (InfinitePlace.embedding_of_isReal hw).comp (algebraMap (𝓞 K₀) K₀)
  have he := congrArg f hb
  simp only [map_pow, map_neg, map_ofNat] at he
  nlinarith [sq_nonneg (f b)]

/-- The sextic Kummer field has three complex places. -/
theorem nrComplexPlaces_kummerTwoField : InfinitePlace.nrComplexPlaces K₀ = 3 := by
  have h := InfinitePlace.card_add_two_mul_card_eq_rank K₀
  rw [nrRealPlaces_kummerTwoField, finrank_kummerTwoField] at h
  omega

/-- The remaining Minkowski estimate suffices for class number one. -/
theorem classNumber_kummerTwoField_of_minkowski_bound
    (hbound : (4 / Real.pi) ^ InfinitePlace.nrComplexPlaces K₀ *
      (Nat.factorial (Module.finrank ℚ K₀) / (Module.finrank ℚ K₀ : ℝ) ^ Module.finrank ℚ K₀ *
        Real.sqrt |(discr K₀ : ℝ)|) < 6) : classNumber K₀ = 1 := by
  classical
  apply classNumber_eq_one_iff.mpr
  apply RingOfIntegers.isPrincipalIdealRing_of_isPrincipal_of_pow_le_of_mem_primesOver_of_mem_Icc
  intro p hp hprime P hP hnorm
  have hp5 : p ≤ 5 := by
    have hf := (Nat.floor_lt (n := 6) (by positivity)).mpr hbound
    have := (Finset.mem_Icc.mp hp).2
    omega
  have hchoices : p = 2 ∨ p = 3 ∨ p = 5 := by
    have hp2 := hprime.two_le
    have hp4 : p ≠ 4 := by
      rintro rfl
      exact (by decide : ¬Nat.Prime 4) hprime
    omega
  have : P.IsPrime := hP.1
  have : P.LiesOver (Ideal.span {(p : ℤ)}) := hP.2
  rcases hchoices with rfl | rfl | rfl
  · exact isPrincipal_primeAboveTwo P
  · have heq : P = primeAboveThree K₀ := by
      have : P ∈ ({primeAboveThree K₀} : Set (Ideal (𝓞 K₀))) :=
        uniquePrimeAboveThree_kummerTwoField ▸ hP
      exact Set.mem_singleton_iff.mp this
    rw [heq]
    exact isPrincipal_primeAboveThree
  · have : Fact (Nat.Prime 5) := ⟨by decide⟩
    have : (Ideal.span {(5 : ℤ)}).IsMaximal := Int.ideal_span_isMaximal_of_prime 5
    have : Infinite (𝓞 K₀) := Infinite.of_injective (fun n : ℕ ↦ (n : 𝓞 K₀))
      Nat.cast_injective
    have hf := P.inertiaDeg_pos ℤ
    have hn : 5 ^ P.inertiaDeg ℤ = Ideal.absNorm P :=
      Ideal.natAbs_pow_inertiaDeg (5 : ℤ) P
    have hlow : 5 ≤ 5 ^ P.inertiaDeg ℤ := Nat.le_pow hf
    have hhigh : 5 ^ P.inertiaDeg ℤ < 6 :=
      lt_of_le_of_lt hnorm ((Nat.floor_lt (n := 6) (by positivity)).mpr hbound)
    exact (absNorm_ne_five P (by omega)).elim

/-- The discriminant bound `34992 = 2⁴ · 3⁷` gives a Minkowski bound strictly below six. -/
theorem minkowski_bound_kummerTwoField_of_discr_le
    (hdiscr : |discr K₀| ≤ 34992) :
    (4 / Real.pi) ^ InfinitePlace.nrComplexPlaces K₀ *
      (Nat.factorial (Module.finrank ℚ K₀) /
        (Module.finrank ℚ K₀ : ℝ) ^ Module.finrank ℚ K₀ *
          Real.sqrt |(discr K₀ : ℝ)|) < 6 := by
  rw [nrComplexPlaces_kummerTwoField, finrank_kummerTwoField]
  have hd : |(discr K₀ : ℝ)| ≤ 34992 := by exact_mod_cast hdiscr
  have hs : Real.sqrt |(discr K₀ : ℝ)| < 188 := by
    apply (Real.sqrt_lt' (by norm_num : (0 : ℝ) < 188)).mpr
    nlinarith
  have hp : 4 / Real.pi ≤ (200 / 157 : ℝ) := by
    apply (div_le_iff₀ Real.pi_pos).mpr
    nlinarith [Real.pi_gt_d2]
  have hp3 := pow_le_pow_left₀ (by positivity : (0 : ℝ) ≤ 4 / Real.pi) hp 3
  calc
    (4 / Real.pi) ^ 3 *
        (Nat.factorial 6 / (6 : ℝ) ^ 6 * Real.sqrt |(discr K₀ : ℝ)|) ≤
        (200 / 157 : ℝ) ^ 3 *
          (Nat.factorial 6 / (6 : ℝ) ^ 6 * Real.sqrt |(discr K₀ : ℝ)|) :=
      mul_le_mul_of_nonneg_right hp3 (by positivity)
    _ < (200 / 157 : ℝ) ^ 3 * (Nat.factorial 6 / (6 : ℝ) ^ 6 * 188) := by
      gcongr
    _ < 6 := by norm_num [Nat.factorial]

/-- The sole remaining discriminant bound implies class number one. -/
theorem classNumber_kummerTwoField_of_discr_le (hdiscr : |discr K₀| ≤ 34992) :
    classNumber K₀ = 1 :=
  classNumber_kummerTwoField_of_minkowski_bound
    (minkowski_bound_kummerTwoField_of_discr_le hdiscr)

/-- All R6 arithmetic data, conditional only on the indicated discriminant bound. -/
theorem kummer_two_field_data_of_discr_le (hdiscr : |discr K₀| ≤ 34992) :
    Module.finrank ℚ K₀ = 6 ∧ classNumber K₀ = 1 ∧
      UniquePrimeAboveThree K₀ ∧ ResidueFieldAtThreeIsF3 K₀ ∧
      ResidueUnitsGeneratedByNegOne K₀ ∧
      ∀ (P : Ideal (𝓞 K₀)) [P.IsPrime] [P.LiesOver (Ideal.span {(2 : ℤ)})],
        P.ramificationIdx ℤ = 3 := by
  obtain ⟨hdegree, hprime, hresidue, htwo⟩ := kummer_two_field_data_without_classNumber
  exact ⟨hdegree, classNumber_kummerTwoField_of_discr_le hdiscr, hprime, hresidue,
    residueUnitsGeneratedByNegOne_kummerTwoField, htwo⟩

open IntermediateField


/-- Any cube root of two in the Kummer field has trace zero. -/
theorem trace_cubeRoot_two (a : K₀) (ha : a ^ 3 = 2) : Algebra.trace ℚ K₀ a = 0 := by
  have he : aeval a kummerTwoPolynomial = 0 := by simp [kummerTwoPolynomial, ha]
  have hm := minpoly.eq_of_irreducible_of_monic kummerTwoPolynomial_irreducible he
    (monic_X_pow_sub_C (2 : ℚ) (by decide : 3 ≠ 0))
  rw [trace_eq_finrank_mul_minpoly_nextCoeff, ← hm]
  simp [kummerTwoPolynomial, Polynomial.nextCoeff]

/-- The polynomial `X³ - 4` is irreducible over the rationals. -/
theorem cube_four_polynomial_irreducible : Irreducible (X ^ 3 - C 4 : ℚ[X]) := by
  apply irreducible_of_degree_le_three_of_not_isRoot
  · norm_num
  · intro x hx
    have hx3 : x ^ 3 = 4 := by simpa only [IsRoot.def, eval_sub, eval_pow, eval_X,
      eval_C, sub_eq_zero] using hx
    have hroot : IsRoot kummerTwoPolynomial (x ^ 2 / 2) := by
      simp only [IsRoot.def, kummerTwoPolynomial, eval_sub, eval_pow, eval_X, eval_C,
        sub_eq_zero]
      calc
        (x ^ 2 / 2) ^ 3 = (x ^ 3) ^ 2 / 8 := by ring
        _ = 2 := by rw [hx3]; norm_num
    have hnone := (irreducible_iff_roots_eq_zero_of_degree_le_three
      (p := kummerTwoPolynomial) (by simp) (by simp)).mp kummerTwoPolynomial_irreducible
    have hmem := (mem_roots kummerTwoPolynomial_irreducible.ne_zero).mpr hroot
    simp [hnone] at hmem

/-- Any cube root of four in the Kummer field has trace zero. -/
theorem trace_cubeRoot_four (a : K₀) (ha : a ^ 3 = 4) : Algebra.trace ℚ K₀ a = 0 := by
  have he : aeval a (X ^ 3 - C 4 : ℚ[X]) = 0 := by simp [ha]
  have hm := minpoly.eq_of_irreducible_of_monic cube_four_polynomial_irreducible he
    (monic_X_pow_sub_C (4 : ℚ) (by decide : 3 ≠ 0))
  rw [trace_eq_finrank_mul_minpoly_nextCoeff, ← hm]
  simp [Polynomial.nextCoeff]

/-- A root of `X² + X + 1` in the sextic field has trace minus three. -/
theorem trace_thirdRoot (z : K₀) (hz : z ^ 2 + z + 1 = 0) :
    Algebra.trace ℚ K₀ z = -3 := by
  have hi : Irreducible (X ^ 2 + X + 1 : ℚ[X]) := by
    apply irreducible_of_degree_le_three_of_not_isRoot
    · norm_num [natDegree_add_eq_left_of_natDegree_lt]
    · intro x hx
      have hx' : x ^ 2 + x + 1 = 0 := by simpa using hx
      nlinarith [sq_nonneg (2 * x + 1)]
  have hmon : (X ^ 2 + X + 1 : ℚ[X]).Monic := by
    simpa only [add_assoc] using
      (monic_X_pow_add (R := ℚ) (n := 2) (p := X + 1) (by compute_degree; norm_num))
  have he : aeval z (X ^ 2 + X + 1 : ℚ[X]) = 0 := by simpa using hz
  have hm := minpoly.eq_of_irreducible_of_monic hi he hmon
  have hdeg : Module.finrank ℚ ℚ⟮z⟯ = 2 := by
    rw [IntermediateField.adjoin.finrank (IsIntegral.of_finite ℚ z), ← hm]
    compute_degree!
  have ht := Module.finrank_mul_finrank ℚ ℚ⟮z⟯ K₀
  rw [hdeg, finrank_kummerTwoField] at ht
  have ht3 : Module.finrank ℚ⟮z⟯ K₀ = 3 := by omega
  rw [trace_eq_finrank_mul_minpoly_nextCoeff, ← hm, ht3]
  norm_num [Polynomial.nextCoeff, natDegree_add_eq_left_of_natDegree_lt, coeff_one]


open scoped Matrix
set_option maxHeartbeats 800000 in
-- The 36 polynomial reductions and the determinant exceed the default tactic budget.
/-- The explicit sextic family has discriminant `-34992` over the rationals. -/
theorem discr_sextic_family (a z : K₀) (ha : a ^ 3 = 2)
    (hz : z ^ 2 + z + 1 = 0) :
    Algebra.discr ℚ (![1, a, a ^ 2, z, a * z, (a + 1) ^ 2 * (z + 2) / 3] : Fin 6 → K₀) =
      -34992 := by
  let w : Fin 6 → K₀ := ![1, a, a ^ 2, z, a * z, (a + 1) ^ 2 * (z + 2) / 3]
  have hz3 : z ^ 3 = 1 := by linear_combination (z - 1) * hz
  have hz2 : z ^ 2 = -z - 1 := by linear_combination hz
  have ha4 : a ^ 4 = 2 * a := by linear_combination a * ha
  have h1 : Algebra.trace ℚ K₀ 1 = 6 := by
    simpa [finrank_kummerTwoField] using
      (Algebra.trace_algebraMap (R := ℚ) (S := K₀) 1)
  have ha1 := trace_cubeRoot_two a ha
  have ha2 := trace_cubeRoot_four (a ^ 2) (by rw [← pow_mul, mul_comm 2 3, pow_mul, ha]; norm_num)
  have hz1 := trace_thirdRoot z hz
  have haz := trace_cubeRoot_two (a * z) (by rw [mul_pow, ha, hz3, mul_one])
  have ha2z := trace_cubeRoot_four (a ^ 2 * z)
    (by rw [mul_pow, hz3, mul_one, ← pow_mul, mul_comm 2 3, pow_mul, ha]; norm_num)
  have ht (c0 c1 c2 c3 c4 c5 : ℚ) :
      Algebra.trace ℚ K₀ (c0 • (1 : K₀) + c1 • a + c2 • a ^ 2 + c3 • z +
        c4 • (a * z) + c5 • (a ^ 2 * z)) = 6 * c0 - 3 * c3 := by
    simp only [map_add, map_smul, h1, ha1, ha2, hz1, haz, ha2z, smul_eq_mul]
    ring
  -- Coefficients of the products in the family `1, a, a², z, az, a²z`.
  let c : Fin 6 → Fin 6 → Fin 6 → ℚ := ![
    ![![1, 0, 0, 0, 0, 0],
      ![0, 1, 0, 0, 0, 0],
      ![0, 0, 1, 0, 0, 0],
      ![0, 0, 0, 1, 0, 0],
      ![0, 0, 0, 0, 1, 0],
      ![2/3, 4/3, 2/3, 1/3, 2/3, 1/3]],
    ![![0, 1, 0, 0, 0, 0],
      ![0, 0, 1, 0, 0, 0],
      ![2, 0, 0, 0, 0, 0],
      ![0, 0, 0, 0, 1, 0],
      ![0, 0, 0, 0, 0, 1],
      ![4/3, 2/3, 4/3, 2/3, 1/3, 2/3]],
    ![![0, 0, 1, 0, 0, 0],
      ![2, 0, 0, 0, 0, 0],
      ![0, 2, 0, 0, 0, 0],
      ![0, 0, 0, 0, 0, 1],
      ![0, 0, 0, 2, 0, 0],
      ![8/3, 4/3, 2/3, 4/3, 2/3, 1/3]],
    ![![0, 0, 0, 1, 0, 0],
      ![0, 0, 0, 0, 1, 0],
      ![0, 0, 0, 0, 0, 1],
      ![-1, 0, 0, -1, 0, 0],
      ![0, -1, 0, 0, -1, 0],
      ![-1/3, -2/3, -1/3, 1/3, 2/3, 1/3]],
    ![![0, 0, 0, 0, 1, 0],
      ![0, 0, 0, 0, 0, 1],
      ![0, 0, 0, 2, 0, 0],
      ![0, -1, 0, 0, -1, 0],
      ![0, 0, -1, 0, 0, -1],
      ![-2/3, -1/3, -2/3, 2/3, 1/3, 2/3]],
    ![![2/3, 4/3, 2/3, 1/3, 2/3, 1/3],
      ![4/3, 2/3, 4/3, 2/3, 1/3, 2/3],
      ![8/3, 4/3, 2/3, 4/3, 2/3, 1/3],
      ![-1/3, -2/3, -1/3, 1/3, 2/3, 1/3],
      ![-2/3, -1/3, -2/3, 2/3, 1/3, 2/3],
      ![3, 2, 2, 3, 2, 2]]]
  have he (i j : Fin 6) : w i * w j =
      c i j 0 • (1 : K₀) + c i j 1 • a + c i j 2 • a ^ 2 + c i j 3 • z +
        c i j 4 • (a * z) + c i j 5 • (a ^ 2 * z) := by
    fin_cases i <;> fin_cases j <;> norm_num [w, c, Algebra.smul_def] <;>
      ring_nf <;> simp only [ha, ha4, hz2] <;> ring
  have hmatrix : Algebra.traceMatrix ℚ w =
      Matrix.of ![![6, 0, 0, -3, 0, 3], ![0, 0, 12, 0, 0, 6],
        ![0, 12, 0, 0, -6, 12], ![-3, 0, 0, -3, 0, -3],
        ![0, 0, -6, 0, 0, -6], ![3, 6, 12, -3, -6, 9]] := by
    ext i j
    simp only [Algebra.traceMatrix_apply, Algebra.traceForm_apply, he, ht]
    fin_cases i <;> fin_cases j <;> norm_num [c, Matrix.of_apply]
  change (Algebra.traceMatrix ℚ w).det = _
  rw [hmatrix]
  norm_num [Matrix.det_succ_row_zero, Fin.sum_univ_succ, Matrix.det_unique,
    Matrix.of_apply, Fin.succAbove]

/-- The element `(∛2 + 1)² (ζ₃ + 2) / 3` is integral, by divisibility of ideals. -/
theorem exists_integral_discriminantElement (a z : 𝓞 K₀) (ha : a ^ 3 = 2)
    (hz : z ^ 2 + z + 1 = 0) : ∃ r : 𝓞 K₀, 3 * r = (a + 1) ^ 2 * (z + 2) := by
  let b := 2 * z + 1
  have hb : b ^ 2 = -3 := by dsimp [b]; linear_combination 4 * hz
  have hle : Ideal.span {(a + 1) ^ 2} ≤ Ideal.span {b} := by
    rw [← Ideal.span_singleton_pow, ← primeAboveThree_sq_eq_span a ha,
      ← primeAboveThree_cube_eq_span b hb, ← pow_mul]
    exact Ideal.pow_le_pow_right (by decide : 3 ≤ 2 * 2)
  obtain ⟨t, ht⟩ := Ideal.mem_span_singleton.mp (hle (Ideal.mem_span_singleton_self _))
  refine ⟨t * z, ?_⟩
  have hfactor : b * (z + 2) = 3 * z := by dsimp [b]; linear_combination 2 * hz
  calc
    3 * (t * z) = t * (b * (z + 2)) := by rw [hfactor]; ring
    _ = (a + 1) ^ 2 * (z + 2) := by rw [← mul_assoc, mul_comm t b, ht]

/-- The field discriminant divides the discriminant of any six integral elements. -/
theorem discr_dvd_integral_family (v : Fin 6 → 𝓞 K₀) :
    discr K₀ ∣ Algebra.discr ℤ v := by
  let b := Module.finBasisOfFinrankEq ℤ (𝓞 K₀)
    (by rw [RingOfIntegers.rank, finrank_kummerTwoField])
  have h := Algebra.discr_of_matrix_vecMul b (b.toMatrix v)
  rw [b.toMatrix_map_vecMul, NumberField.discr_eq_discr K₀ b] at h
  rw [h]
  exact dvd_mul_left _ _

/-- Computing the discriminant of integral elements commutes with passage to `ℚ`. -/
theorem coe_discr_integral_family (v : Fin 6 → 𝓞 K₀) :
    (Algebra.discr ℤ v : ℚ) = Algebra.discr ℚ (fun i ↦ (v i : K₀)) := by
  change (algebraMap ℤ ℚ) (Algebra.discr ℤ v) = _
  unfold Algebra.discr
  rw [RingHom.map_det]
  congr 1
  ext i j
  change (algebraMap ℤ ℚ) (Algebra.trace ℤ (𝓞 K₀) (v i * v j)) =
    Algebra.trace ℚ K₀ ((v i : K₀) * (v j : K₀))
  have h := Algebra.trace_localization ℤ (nonZeroDivisors ℤ) (Rₘ := ℚ) (Sₘ := K₀)
    (v i * v j)
  simpa only [map_mul] using h.symm

/-- The explicit integral family bounds the absolute field discriminant by `34992`. -/
theorem abs_discr_kummerTwoField_le : |discr K₀| ≤ 34992 := by
  obtain ⟨a, ha⟩ := exists_integral_cubeRoot_two
  obtain ⟨z, hz⟩ := exists_integral_thirdRoot
  obtain ⟨r, hr⟩ := exists_integral_discriminantElement a z ha hz
  let v : Fin 6 → 𝓞 K₀ := ![1, a, a ^ 2, z, a * z, r]
  have ha' : (a : K₀) ^ 3 = 2 := by
    have h := congrArg (algebraMap (𝓞 K₀) K₀) ha
    simpa only [map_pow, map_ofNat] using h
  have hz' : (z : K₀) ^ 2 + (z : K₀) + 1 = 0 := by
    have h := congrArg (algebraMap (𝓞 K₀) K₀) hz
    simpa only [map_pow, map_add, map_one, map_zero] using h
  have hr' : (r : K₀) = ((a : K₀) + 1) ^ 2 * ((z : K₀) + 2) / 3 := by
    have h := congrArg (algebraMap (𝓞 K₀) K₀) hr
    simp only [map_mul, map_ofNat, map_pow, map_add, map_one] at h
    apply (eq_div_iff (by norm_num : (3 : K₀) ≠ 0)).mpr
    simpa only [mul_comm] using h
  have hv : (fun i ↦ (v i : K₀)) =
      (![1, (a : K₀), (a : K₀) ^ 2, (z : K₀), (a : K₀) * (z : K₀),
        ((a : K₀) + 1) ^ 2 * ((z : K₀) + 2) / 3] : Fin 6 → K₀) := by
    ext i
    fin_cases i <;> simp [v, hr']
  have hd : Algebra.discr ℤ v = -34992 := by
    apply Int.cast_injective (α := ℚ)
    rw [coe_discr_integral_family, hv, discr_sextic_family _ _ ha' hz']
    norm_num
  have hdvd : discr K₀ ∣ (34992 : ℤ) := by
    have h := discr_dvd_integral_family v
    rw [hd] at h
    exact dvd_neg.mp h
  exact Int.le_of_dvd (by norm_num) ((abs_dvd _ _).mpr hdvd)

/-- The sextic Kummer field has class number one. -/
theorem classNumber_kummerTwoField : classNumber K₀ = 1 :=
  classNumber_kummerTwoField_of_discr_le abs_discr_kummerTwoField_le

/-- The arithmetic data for the sextic Kummer field required in R6. -/
theorem kummer_two_field_data :
    Module.finrank ℚ K₀ = 6 ∧ classNumber K₀ = 1 ∧
      UniquePrimeAboveThree K₀ ∧ ResidueFieldAtThreeIsF3 K₀ ∧
      ResidueUnitsGeneratedByNegOne K₀ ∧
      ∀ (P : Ideal (𝓞 K₀)) [P.IsPrime] [P.LiesOver (Ideal.span {(2 : ℤ)})],
        P.ramificationIdx ℤ = 3 :=
  kummer_two_field_data_of_discr_le abs_discr_kummerTwoField_le

end ThreeAdicPlan
