/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GaloisRepresentation.HardlyRamified.InertiaTwoSquareZero
public import FLT.GaloisRepresentation.HardlyRamified.KummerObject

/-!
# The point field and inertia of the Kummer object

The complete action on the three Kummer components cuts out the splitting
field of `X³ - 2`. Inertia at two fixes cube roots of unity, so its difference
from the identity has square zero on the Kummer point group.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

open Polynomial

namespace ThreeAdicPlan

/-- Restriction of Kummer points commutes with the absolute Galois action. -/
theorem kummerTwoPointEquiv_smul (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (P : kummerTwoPoints) :
    kummerTwoPointEquiv (σ • P) =
      (σ.toAlgHom.restrictScalars ZInvTwo).comp (kummerTwoPointEquiv P) := rfl

/-- A Galois automorphism acts on a Kummer point by acting on its root coordinate. -/
theorem kummerTwoRootPoint_smul (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (i : Fin 3) (x : AlgebraicClosure ℚ) (hx : x ^ 3 = 2 ^ i.val) :
    σ • kummerTwoRootPoint i x hx =
      kummerTwoRootPoint i (σ x) (by rw [← map_pow, hx, map_pow, map_ofNat]) := by
  apply kummerTwoPointEquiv.injective
  rw [kummerTwoPointEquiv_smul]
  simp only [kummerTwoRootPoint, Equiv.apply_symm_apply, KummerAlgebra.comp_rootPoint]
  rfl

/-- The root coordinate is determined by the geometric point. -/
theorem kummerTwoRootPoint_root_injective {i j : Fin 3} {x y : AlgebraicClosure ℚ}
    {hx : x ^ 3 = 2 ^ i.val} {hy : y ^ 3 = 2 ^ j.val}
    (h : kummerTwoRootPoint i x hx = kummerTwoRootPoint j y hy) : x = y := by
  have he := congrArg (fun P ↦ kummerTwoPointEquiv P
    (fun k ↦ AdjoinRoot.root (KummerAlgebra.equation ZInvTwo 3 kummerTwoUnit k))) h
  simpa [kummerTwoRootPoint, KummerAlgebra.rootPoint] using he

/-- Fixing all cube roots of two fixes the roots in every Kummer component. -/
theorem fixes_kummerTwoRoots_of_fixes_cubeRoots
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (hσ : ∀ x : AlgebraicClosure ℚ, x ^ 3 = 2 → σ x = x)
    (i : Fin 3) (x : AlgebraicClosure ℚ) (hx : x ^ 3 = 2 ^ i.val) : σ x = x := by
  obtain ⟨a, ha⟩ := IsAlgClosed.exists_pow_nat_eq (2 : AlgebraicClosure ℚ) (by decide : 0 < 3)
  have ha0 : a ≠ 0 := by intro h; rw [h] at ha; norm_num at ha
  fin_cases i
  · have hx' : x ^ 3 = 1 := by simpa using hx
    have hxa : (x * a) ^ 3 = 2 := by rw [mul_pow, hx', ha, one_mul]
    exact mul_right_cancel₀ ha0 (by simpa only [map_mul, hσ a ha] using hσ (x * a) hxa)
  · exact hσ x (by simpa using hx)
  · have hx' : x ^ 3 = 4 := by norm_num at hx; exact hx
    have hxa : (x / a) ^ 3 = 2 := by rw [div_pow, hx', ha]; norm_num
    apply (div_left_inj' ha0).mp
    simpa only [map_div₀, hσ a ha] using hσ (x / a) hxa

/-- The kernel of the full point action is exactly the subgroup fixing all cube roots of two. -/
theorem mem_kummerTwoPointActionKernel (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) :
    σ ∈ kummerTwoPoints.pointActionKernel ↔
      ∀ x : AlgebraicClosure ℚ, x ^ 3 = 2 → σ x = x := by
  rw [FiniteContinuousGaloisModule.mem_pointActionKernel]
  constructor
  · intro h x hx
    have he := h (kummerTwoRootPoint 1 x (by simpa using hx))
    rw [kummerTwoRootPoint_smul] at he
    exact kummerTwoRootPoint_root_injective he
  · intro h P
    obtain ⟨i, x, hx, rfl⟩ := kummerTwoRootPoint_surjective P
    rw [kummerTwoRootPoint_smul]
    exact kummerTwoRootPoint_congr rfl (fixes_kummerTwoRoots_of_fixes_cubeRoots σ h i x hx)

/-- The roots of the Kummer polynomial are precisely the cube roots of two. -/
theorem mem_kummerTwoPolynomial_rootSet (x : AlgebraicClosure ℚ) :
    x ∈ kummerTwoPolynomial.rootSet (AlgebraicClosure ℚ) ↔ x ^ 3 = 2 := by
  rw [Polynomial.mem_rootSet_of_ne kummerTwoPolynomial_irreducible.ne_zero]
  simp [kummerTwoPolynomial, sub_eq_zero]

/-- The full point field is generated by the roots of `X³ - 2`. -/
theorem kummerTwoPointField_eq_adjoin :
    kummerTwoPoints.pointField =
      IntermediateField.adjoin ℚ (kummerTwoPolynomial.rootSet (AlgebraicClosure ℚ)) := by
  have hker : kummerTwoPoints.pointActionKernel =
      (IntermediateField.adjoin ℚ
        (kummerTwoPolynomial.rootSet (AlgebraicClosure ℚ))).fixingSubgroup := by
    ext σ
    rw [mem_kummerTwoPointActionKernel, IntermediateField.mem_fixingSubgroup_iff]
    constructor
    · intro h x hx
      induction hx using IntermediateField.adjoin_induction with
      | mem x hx => exact h x ((mem_kummerTwoPolynomial_rootSet x).mp hx)
      | algebraMap x => exact σ.commutes x
      | add x y _ _ hx hy => simp [hx, hy]
      | inv x _ hx => simp [hx]
      | mul x y _ _ hx hy => simp [hx, hy]
    · intro h x hx
      exact h x (IntermediateField.subset_adjoin _ _
        ((mem_kummerTwoPolynomial_rootSet x).mpr hx))
  rw [FiniteContinuousGaloisModule.pointField, hker,
    InfiniteGalois.fixedField_fixingSubgroup]

instance : Polynomial.IsSplittingField ℚ (PointField kummerTwoObject) kummerTwoPolynomial := by
  change Polynomial.IsSplittingField ℚ kummerTwoPoints.pointField kummerTwoPolynomial
  rw [kummerTwoPointField_eq_adjoin]
  exact IntermediateField.adjoin_rootSet_isSplittingField (IsAlgClosed.splits _)

/-- The field cut out by the full Kummer point action is the specified sextic field `K₀`. -/
def kummerTwoPointFieldEquiv : PointField kummerTwoObject ≃ₐ[ℚ] K₀ :=
  Polynomial.IsSplittingField.algEquiv _ kummerTwoPolynomial

/-- Fixing cube roots of unity makes the Kummer action square-zero unipotent. -/
theorem kummerTwo_squareZero_of_fixes_rootsOfUnity
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (hσ : ∀ z : AlgebraicClosure ℚ, z ^ 3 = 1 → σ z = z) (P : kummerTwoPoints) :
    σ • (σ • P - P) - (σ • P - P) = 0 := by
  obtain ⟨i, x, hx, rfl⟩ := kummerTwoRootPoint_surjective P
  have hx0 : x ≠ 0 := by
    intro h
    rw [h, zero_pow (by decide)] at hx
    exact (pow_ne_zero i.val (by norm_num : (2 : AlgebraicClosure ℚ) ≠ 0)) hx.symm
  have hz : (σ x / x) ^ 3 = 1 := by
    rw [div_pow, ← map_pow, hx, map_pow, map_ofNat, div_self (pow_ne_zero _ (by norm_num))]
  let Q := kummerTwoRootPoint 0 (σ x / x) (by simpa using hz)
  have hQ : σ • Q = Q := by
    dsimp [Q]
    rw [kummerTwoRootPoint_smul]
    exact kummerTwoRootPoint_congr rfl (hσ _ hz)
  have hd : σ • kummerTwoRootPoint i x hx = Q + kummerTwoRootPoint i x hx := by
    dsimp [Q]
    rw [kummerTwoRootPoint_smul, kummerTwoRootPoint_add]
    apply kummerTwoRootPoint_congr
    · apply Fin.ext
      simp [KummerAlgebra.sumComponent, Nat.mod_eq_of_lt i.isLt]
    · simp [Nat.div_eq_of_lt i.isLt, hx0]
  rw [hd, add_sub_cancel_right, hQ, sub_self]

/-- Inertia at two fixes all cube roots of unity in the global algebraic closure. -/
theorem inertiaTwo_fixes_cubeRootsOfUnity
    (σ : Field.absoluteGaloisGroup
      (Nat.prime_two.toHeightOneSpectrumRingOfIntegersRat.adicCompletion ℚ))
    (hσ : σ ∈ localInertiaGroup Nat.prime_two.toHeightOneSpectrumRingOfIntegersRat)
    (z : AlgebraicClosure ℚ) (hz : z ^ 3 = 1) :
    Field.absoluteGaloisGroup.map (algebraMap ℚ
      (Nat.prime_two.toHeightOneSpectrumRingOfIntegersRat.adicCompletion ℚ)) σ z = z := by
  let f := algebraMap ℚ
    (Nat.prime_two.toHeightOneSpectrumRingOfIntegersRat.adicCompletion ℚ)
  apply (AlgebraicClosure.map f).injective
  rw [Field.absoluteGaloisGroup.lift_map]
  exact localInertia_fixes_of_pow_eq_one 3 2 (by decide) Nat.prime_two (by decide)
    σ hσ (AlgebraicClosure.map f z) (by rw [← map_pow, hz, map_one])

/-- The explicit Kummer model belongs to category D. -/
theorem kummerTwoObject_inCategoryD : InCategoryD kummerTwoObject := by
  constructor
  · exact ⟨2, kummerTwoPoints_card⟩
  · intro σ hσ P
    exact kummerTwo_squareZero_of_fixes_rootsOfUnity _
      (inertiaTwo_fixes_cubeRootsOfUnity σ hσ) P

/-- The actual three-torsion Kummer extension attached to two has full point field `K₀`. -/
theorem exists_kummer_two_model :
    ∃ G₂ : FFQ ZInvTwo, KilledBy 3 G₂ ∧ InCategoryD G₂ ∧ Nonempty (PointField G₂ ≃ₐ[ℚ] K₀) :=
  ⟨kummerTwoObject, kummerTwoObject_killedBy_three, kummerTwoObject_inCategoryD,
    ⟨kummerTwoPointFieldEquiv⟩⟩

end ThreeAdicPlan
