/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexDeRhamFiltration
public import FLT.PadicHodgeTheory.ComplexIntegerInvertP

/-! # The actual C_p residue map of B_dR^+ -/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- The original localized theta quotient identifies with the actual completed field. -/
def complexThetaResidueEquiv :
    ComplexAinfInvertP p ⧸ ComplexDeRhamIdeal p ≃+* ℂ_[p] :=
  ((complexThetaInvertP p).quotientKerEquivOfSurjective (complexThetaInvertP_surjective p)).trans
    (complexIntegerInvertPEquiv p).toRingEquiv

/-- Extend theta to the actual B_dR^+, with target the actual C_p. -/
def complexDeRhamTheta : ComplexBDeRhamPlus p →+* ℂ_[p] :=
  (complexThetaResidueEquiv p).toRingHom.comp
    (AdicCompletion.evalOneₐ (ComplexDeRhamIdeal p)).toRingHom

/-- The completed theta map is onto C_p. -/
theorem complexDeRhamTheta_surjective : Function.Surjective (complexDeRhamTheta p) :=
  (complexThetaResidueEquiv p).surjective.comp (complexDeRham_evalOne_surjective p)

/-- On A_inf, completed theta agrees with the original integral theta and inclusion. -/
theorem complexDeRhamTheta_algebraMap (x : Ainf p) :
    complexDeRhamTheta p (algebraMap (ComplexAinfInvertP p) (ComplexBDeRhamPlus p)
      (algebraMap (Ainf p) (ComplexAinfInvertP p) x)) = (complexTheta p x : ℂ_[p]) := by
  change complexIntegerInvertPEquiv p
    (complexThetaInvertP p (algebraMap (Ainf p) (ComplexAinfInvertP p) x)) = _
  rw [complexThetaInvertP_algebraMap, complexIntegerInvertPEquiv_algebraMap]

/-- The completed theta kernel is generated by the actual completed parameter. -/
theorem complexDeRhamTheta_ker : RingHom.ker (complexDeRhamTheta p) =
    Ideal.span {complexDeRhamParameter p} := by
  have h : RingHom.ker (complexDeRhamTheta p) =
      RingHom.ker (AdicCompletion.evalOneₐ (ComplexDeRhamIdeal p)).toRingHom := by
    ext x
    change complexThetaResidueEquiv p (AdicCompletion.evalOneₐ (ComplexDeRhamIdeal p) x) = 0 ↔ _
    exact map_eq_zero_iff (complexThetaResidueEquiv p) (complexThetaResidueEquiv p).injective
  exact h.trans (complexDeRham_evalOne_ker p)

/-- The actual completion is nontrivial since it maps onto C_p. -/
instance instNontrivialComplexDeRham : Nontrivial (ComplexBDeRhamPlus p) :=
  (complexDeRhamTheta p).domain_nontrivial

/-- The parameter ideal is maximal, with residue field C_p. -/
instance instIsMaximalComplexDeRhamParameter :
    (Ideal.span {complexDeRhamParameter p}).IsMaximal := by
  rw [← complexDeRhamTheta_ker]
  exact RingHom.ker_isMaximal_of_surjective _ (complexDeRhamTheta_surjective p)

/-- Completeness at the actual maximal ideal makes B_dR^+ a local ring. -/
instance instIsLocalRingComplexDeRham : IsLocalRing (ComplexBDeRhamPlus p) :=
  isLocalRing_of_isAdicComplete_maximal (Ideal.span {complexDeRhamParameter p})

/-- Its maximal ideal is the actual parameter ideal. -/
theorem complexDeRham_maximalIdeal : IsLocalRing.maximalIdeal (ComplexBDeRhamPlus p) =
    Ideal.span {complexDeRhamParameter p} :=
  (IsLocalRing.eq_maximalIdeal (instIsMaximalComplexDeRhamParameter p)).symm

end PadicHodgeTheory
