/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexPadicScalars
public import FLT.PadicHodgeTheory.RelativePDPresentation
public import Mathlib.RingTheory.DividedPowers.Padic

/-!
# Relative compatibility for the actual integral theta ideal

The relative presentation uses the theta kernel plus p, and the canonical
PD structure on `(p)` in the original p-adic integers. No PD structure on
this presentation or comparison with the embedded theta hull is asserted.
-/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- The ideal to be divided includes both the theta kernel and the base PD ideal. -/
def complexRelativeThetaIdeal : Ideal (Ainf p) :=
  RingHom.ker (complexTheta p) ⊔
    (Ideal.span {(p : ℤ_[p])}).map (complexPadicIntToAinf p)

/-- The base part of this ideal is exactly the ideal generated by p. -/
theorem complexRelativeThetaIdeal_eq :
    complexRelativeThetaIdeal p = RingHom.ker (complexTheta p) ⊔ Ideal.span {(p : Ainf p)} := by
  simp only [complexRelativeThetaIdeal, Ideal.map_span, Set.image_singleton, map_natCast]

/-- The original base PD ideal maps into the actual relative theta ideal. -/
theorem complexRelativeThetaIdeal_base (x : Ideal.span {(p : ℤ_[p])}) :
    complexPadicIntToAinf p x ∈ complexRelativeThetaIdeal p :=
  (show (Ideal.span {(p : ℤ_[p])}).map (complexPadicIntToAinf p) ≤
    complexRelativeThetaIdeal p from le_sup_right) (Ideal.mem_map_of_mem _ x.property)

/-- The original integral scalar map used only in this relative presentation. -/
local instance complexRelativeBaseAlgebra : Algebra ℤ_[p] (Ainf p) :=
  (complexPadicIntToAinf p).toAlgebra

/-- The actual relative quotient, using the original integral scalar map. -/
abbrev ComplexRelativePDPresentation :=
  RelativePDPresentation (Ideal.span {(p : ℤ_[p])}) (PadicInt.dividedPowers p)
    (complexRelativeThetaIdeal p) (complexRelativeThetaIdeal_base p)

/-- Compatibility with every canonical base divided power is a proved equation. -/
theorem complexRelativePDSymbol_base (n : ℕ) (x : Ideal.span {(p : ℤ_[p])}) :
    relativePDSymbol _ (PadicInt.dividedPowers p) _ (complexRelativeThetaIdeal_base p) n
      ⟨complexPadicIntToAinf p x, complexRelativeThetaIdeal_base p x⟩ =
        algebraMap (Ainf p) (ComplexRelativePDPresentation p)
          (complexPadicIntToAinf p ((PadicInt.dividedPowers p).dpow n x)) :=
  relativePDSymbol_base _ _ _ _ n x

end PadicHodgeTheory
