/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexRelativePDHull

/-!
# Descending the enlarged divided powers modulo p

Compatibility with the canonical p-adic divided powers makes the ideal
(p) a sub-PD ideal of the enlarged hull ideal. Thus the operations descend
to the characteristic-p quotient, retaining the original quotient map.
-/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- The integral base ideal inside the hull, before taking any quotient. -/
def complexPDHullBaseIdeal : Ideal (ComplexAinfPDHull p) :=
  (Ideal.span {(p : ℤ_[p])}).map (complexPadicIntToPDHull p)

/-- It is the principal ideal generated by p in this same hull. -/
theorem complexPDHullBaseIdeal_eq :
    complexPDHullBaseIdeal p = Ideal.span {(p : ComplexAinfPDHull p)} := by
  simp only [complexPDHullBaseIdeal, Ideal.map_span, Set.image_singleton, map_natCast]

/-- Its divided-power stability follows from the proved base compatibility. -/
theorem complexPDHullBaseIdeal_isSubDP :
    (complexRelativePDHullDividedPowers p).IsSubDPIdeal (complexPDHullBaseIdeal p) :=
  DividedPowers.isSubDPIdeal_map (complexRelativePDHull_base p)

/-- The characteristic-p quotient of the original embedded hull. -/
abbrev ComplexPDHullModP := ComplexAinfPDHull p ⧸ complexPDHullBaseIdeal p

/-- The enlarged ideal's image in the quotient. -/
def complexPDHullModPIdeal : Ideal (ComplexPDHullModP p) :=
  (complexRelativePDHullIdeal p).map (Ideal.Quotient.mk (complexPDHullBaseIdeal p))

/-- Actual descended divided powers, with stability proved rather than postulated. -/
def complexPDHullModPDividedPowers : DividedPowers (complexPDHullModPIdeal p) :=
  DividedPowers.Quotient.dividedPowers (complexRelativePDHullDividedPowers p) (by
    rw [inf_eq_left.mpr (complexPDHullBaseIdeal_isSubDP p).isSubideal]
    exact complexPDHullBaseIdeal_isSubDP p)

/-- Descent agrees with every original integral operation on the enlarged ideal. -/
theorem complexPDHullModP_dpow (n : ℕ) {x : ComplexAinfPDHull p}
    (hx : x ∈ complexRelativePDHullIdeal p) :
    (complexPDHullModPDividedPowers p).dpow n (Ideal.Quotient.mk (complexPDHullBaseIdeal p) x) =
      Ideal.Quotient.mk (complexPDHullBaseIdeal p)
        ((complexRelativePDHullDividedPowers p).dpow n x) :=
  DividedPowers.Quotient.dpow_apply _ _ hx

/-- The quotient map is a PD morphism. -/
theorem complexPDHullModP_isDPMorphism :
    (complexRelativePDHullDividedPowers p).IsDPMorphism (complexPDHullModPDividedPowers p)
      (Ideal.Quotient.mk (complexPDHullBaseIdeal p)) :=
  DividedPowers.Quotient.isDPMorphism _ _

/-- The quotient really kills p. -/
theorem complexPDHullModP_prime_eq_zero : (p : ComplexPDHullModP p) = 0 := by
  rw [← map_natCast (Ideal.Quotient.mk (complexPDHullBaseIdeal p))]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  rw [complexPDHullBaseIdeal_eq]
  exact Ideal.subset_span rfl

end PadicHodgeTheory
