/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexIntegerGalois

/-! # Galois actions on the mod-p integer ring and its actual perfection -/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- The Galois action preserves the principal ideal generated by p. -/
theorem complexIntegerGalois_preserves_p (σ : PadicGalois p) :
    Ideal.span {(p : 𝓞_ℂ_[p])} ≤
      (Ideal.span {(p : 𝓞_ℂ_[p])}).comap (complexIntegerGalois p σ) := by
  rw [Ideal.span_singleton_le_iff_mem, Ideal.mem_comap, map_natCast]
  exact Ideal.subset_span (Set.mem_singleton _)

/-- The induced action on O_C/(p). -/
def complexModPGalois (σ : PadicGalois p) :
    ModP 𝓞_ℂ_[p] p →+* ModP 𝓞_ℂ_[p] p :=
  Ideal.quotientMap _ (complexIntegerGalois p σ) (complexIntegerGalois_preserves_p p σ)

/-- Reduction modulo p commutes with the action. -/
@[simp] theorem complexModPGalois_mk (σ : PadicGalois p) (x : 𝓞_ℂ_[p]) :
    complexModPGalois p σ (Ideal.Quotient.mk _ x) =
      Ideal.Quotient.mk _ (complexIntegerGalois p σ x) := rfl

/-- The quotient action respects the identity. -/
@[simp] theorem complexModPGalois_one (x : ModP 𝓞_ℂ_[p] p) :
    complexModPGalois p 1 x = x := by
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective x
  simp

/-- The quotient action respects multiplication. -/
theorem complexModPGalois_mul (σ τ : PadicGalois p) (x : ModP 𝓞_ℂ_[p] p) :
    complexModPGalois p (σ * τ) x = complexModPGalois p σ (complexModPGalois p τ x) := by
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective x
  simp only [complexModPGalois_mk, complexIntegerGalois_mul]

/-- Functoriality of perfection gives the action on the actual integral tilt. -/
def complexTiltGalois (σ : PadicGalois p) : IntegralTilt p →+* IntegralTilt p :=
  Perfection.map p (complexModPGalois p σ)

/-- Every inverse-Frobenius coordinate has the original quotient action. -/
@[simp] theorem complexTiltGalois_coeff (σ : PadicGalois p) (x : IntegralTilt p) (n : ℕ) :
    PreTilt.coeff n (complexTiltGalois p σ x) = complexModPGalois p σ (PreTilt.coeff n x) :=
  rfl

/-- The tilt action respects the identity. -/
@[simp] theorem complexTiltGalois_one (x : IntegralTilt p) : complexTiltGalois p 1 x = x := by
  apply Perfection.ext
  intro n
  exact complexModPGalois_one p _

/-- The tilt action respects multiplication. -/
theorem complexTiltGalois_mul (σ τ : PadicGalois p) (x : IntegralTilt p) :
    complexTiltGalois p (σ * τ) x = complexTiltGalois p σ (complexTiltGalois p τ x) := by
  apply Perfection.ext
  intro n
  exact complexModPGalois_mul p σ τ _

/-- The actual integral tilt carries the induced action by ring automorphisms. -/
instance instMulSemiringActionIntegralTilt :
    MulSemiringAction (PadicGalois p) (IntegralTilt p) where
  smul σ x := complexTiltGalois p σ x
  one_smul := complexTiltGalois_one p
  mul_smul := complexTiltGalois_mul p
  smul_zero σ := map_zero (complexTiltGalois p σ)
  smul_add σ := map_add (complexTiltGalois p σ)
  smul_one σ := map_one (complexTiltGalois p σ)
  smul_mul σ := map_mul (complexTiltGalois p σ)

end PadicHodgeTheory
