/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexCyclotomicKernel
public import FLT.PadicHodgeTheory.ComplexThetaPrincipal
public import FLT.PadicHodgeTheory.ComplexThetaUnitReflection

/-! # The cyclotomic geometric sum generates the actual theta kernel -/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- Frobenius followed by theta sends the cyclotomic geometric sum to p. -/
theorem complexCyclotomicKernel_theta_frobenius :
    complexTheta p (complexWittFrobenius p (complexCyclotomicKernel p)) = p := by
  simp only [complexCyclotomicKernel, map_sum, map_pow,
    complexWittFrobenius_teichmuller, complexCyclotomicShift_pow,
    complexCyclotomicShift_zero, complexTheta_teichmuller, complexCyclotomicTilt_sharp,
    one_pow, Finset.sum_const, Finset.card_range, nsmul_eq_mul, mul_one]

/-- The old generator has a simple theta value after Frobenius. -/
theorem complexThetaGenerator_theta_frobenius :
    complexTheta p (complexWittFrobenius p (complexThetaGenerator p)) =
      (p : 𝓞_ℂ_[p]) ^ p - p := by
  rw [complexThetaGenerator, map_sub, map_natCast, complexWittFrobenius_teichmuller,
    map_sub, map_natCast, complexTheta_teichmuller, map_pow, complexPrimeTilt_sharp]

/-- Every quotient by the old generator is a unit; no valuation formula is needed. -/
theorem complexCyclotomicKernel_factor_isUnit (b : Ainf p)
    (hb : complexCyclotomicKernel p = complexThetaGenerator p * b) : IsUnit b := by
  apply complexWitt_isUnit_of_theta_frobenius
  have h := congrArg (fun x ↦ complexTheta p (complexWittFrobenius p x)) hb
  rw [complexCyclotomicKernel_theta_frobenius, map_mul, map_mul,
    complexThetaGenerator_theta_frobenius] at h
  have hp : (p : 𝓞_ℂ_[p]) ≠ 0 := by exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hpow : (p : 𝓞_ℂ_[p]) ^ p - p = p * ((p : 𝓞_ℂ_[p]) ^ (p - 1) - 1) := by
    rw [mul_sub, ← pow_succ', Nat.sub_add_cancel (Fact.out : p.Prime).one_le, mul_one]
  rw [hpow, mul_assoc] at h
  have he : 1 = ((p : 𝓞_ℂ_[p]) ^ (p - 1) - 1) *
      complexTheta p (complexWittFrobenius p b) :=
    mul_left_cancel₀ hp (by simpa only [mul_one] using h)
  exact IsUnit.of_mul_eq_one _ (by simpa only [mul_comm] using he.symm)

/-- The cyclotomic sum is associated to the previously constructed generator. -/
theorem complexCyclotomicKernel_associated :
    Associated (complexThetaGenerator p) (complexCyclotomicKernel p) := by
  obtain ⟨b, hb⟩ := (complexTheta_eq_zero_iff_dvd p _).mp
    (complexCyclotomicKernel_mem_ker p)
  obtain ⟨u, hu⟩ := complexCyclotomicKernel_factor_isUnit p b hb
  exact ⟨u, by rw [hu, ← hb]⟩

/-- The actual integral theta kernel is generated by the cyclotomic geometric sum. -/
theorem complexCyclotomicKernel_ker_eq_span :
    RingHom.ker (complexTheta p) = Ideal.span {complexCyclotomicKernel p} := by
  rw [complexTheta_ker_eq_span]
  exact Ideal.span_singleton_eq_span_singleton.mpr (complexCyclotomicKernel_associated p)

end PadicHodgeTheory
