/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexIntegralPDPresentation
public import FLT.PadicHodgeTheory.ComplexRelativePDPresentation
public import FLT.PadicHodgeTheory.RationalPDSum

/-!
# The enlarged p-compatible divided-power ideal in the actual hull

The theta PD ideal plus the image of the canonical p-adic PD ideal carries
constructed integral operations. The relative presentation maps to this
compatible target; injectivity and operations on the presentation remain separate.
-/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- The original integral p-adic scalar map, used for the relative symbols. -/
local instance complexPDHullBaseAlgebra : Algebra ℤ_[p] (Ainf p) :=
  (complexPadicIntToAinf p).toAlgebra

/-- The original p-adic scalar map into the embedded hull. -/
def complexPadicIntToPDHull : ℤ_[p] →+* ComplexAinfPDHull p :=
  (complexAinfToPDHull p).comp (complexPadicIntToAinf p)

/-- The enlarged integral ideal includes both theta and the base PD ideal. -/
def complexRelativePDHullIdeal : Ideal (ComplexAinfPDHull p) :=
  complexPDHullIdeal p ⊔ (Ideal.span {(p : ℤ_[p])}).map (complexPadicIntToPDHull p)

/-- The enlargement is precisely the theta ideal plus the principal ideal generated by p. -/
theorem complexRelativePDHullIdeal_eq :
    complexRelativePDHullIdeal p =
      complexPDHullIdeal p ⊔ Ideal.span {(p : ComplexAinfPDHull p)} := by
  simp only [complexRelativePDHullIdeal, Ideal.map_span, Set.image_singleton, map_natCast]

/-- Actual operations on the enlarged integral ideal, built from rational factorial values. -/
def complexRelativePDHullDividedPowers : DividedPowers (complexRelativePDHullIdeal p) :=
  DividedPowers.rationalPDSum (complexAinfPDHullSubring p).subtype
    (complexPDHullIdeal p) (complexPDHullDividedPowers p) (complexPadicIntToPDHull p)
      (Ideal.span {(p : ℤ_[p])}) (PadicInt.dividedPowers p) Subtype.val_injective

/-- The enlarged operations retain all the original theta operations. -/
theorem complexRelativePDHull_restrict (n : ℕ) {x : ComplexAinfPDHull p}
    (hx : x ∈ complexPDHullIdeal p) :
    (complexRelativePDHullDividedPowers p).dpow n x =
      (complexPDHullDividedPowers p).dpow n x :=
  DividedPowers.rationalPDSum_restrict _ _ _ _ _ _ _ n hx

/-- The p-adic scalar map is compatible with its canonical divided powers. -/
theorem complexRelativePDHull_base :
    (PadicInt.dividedPowers p).IsDPMorphism (complexRelativePDHullDividedPowers p)
      (complexPadicIntToPDHull p) :=
  DividedPowers.rationalPDSum_isDPMorphism _ _ _ _ _ _ _

/-- The entire original theta-plus-p ideal maps into the constructed PD ideal. -/
theorem complexRelativeTheta_toPDHull (x : complexRelativeThetaIdeal p) :
    complexAinfToPDHull p x ∈ complexRelativePDHullIdeal p := by
  have h : (complexRelativeThetaIdeal p).map (complexAinfToPDHull p) ≤
      complexRelativePDHullIdeal p := by
    rw [complexRelativeThetaIdeal, Ideal.map_sup, Ideal.map_map]
    apply sup_le
    · apply le_trans _ le_sup_left
      exact Ideal.map_le_iff_le_comap.mpr fun x hx ↦ complexThetaKernel_toPDHull p ⟨x, hx⟩
    · exact le_sup_right
  exact h (Ideal.mem_map_of_mem _ x.property)

/-- The relative integral presentation maps into the enlarged p-compatible hull. -/
def complexRelativePDToHull : ComplexRelativePDPresentation p →+* ComplexAinfPDHull p := by
  let : Algebra (Ainf p) (ComplexAinfPDHull p) := (complexAinfToPDHull p).toAlgebra
  let : Algebra ℤ_[p] (ComplexAinfPDHull p) := (complexPadicIntToPDHull p).toAlgebra
  let : IsScalarTower ℤ_[p] (Ainf p) (ComplexAinfPDHull p) :=
    IsScalarTower.of_algebraMap_eq' rfl
  exact (relativePDTargetMap _ (PadicInt.dividedPowers p) _ (complexRelativeThetaIdeal_base p)
    _ (complexRelativePDHullDividedPowers p) (complexRelativeTheta_toPDHull p)
      (complexRelativePDHull_base p)).toRingHom

/-- The comparison retains the original integral Witt coefficient map. -/
theorem complexRelativePDToHull_base (x : Ainf p) :
    complexRelativePDToHull p (algebraMap (Ainf p) (ComplexRelativePDPresentation p) x) =
      complexAinfToPDHull p x := by
  let : Algebra (Ainf p) (ComplexAinfPDHull p) := (complexAinfToPDHull p).toAlgebra
  let : Algebra ℤ_[p] (ComplexAinfPDHull p) := (complexPadicIntToPDHull p).toAlgebra
  let : IsScalarTower ℤ_[p] (Ainf p) (ComplexAinfPDHull p) :=
    IsScalarTower.of_algebraMap_eq' rfl
  exact (relativePDTargetMap _ (PadicInt.dividedPowers p) _ (complexRelativeThetaIdeal_base p)
    _ (complexRelativePDHullDividedPowers p) (complexRelativeTheta_toPDHull p)
      (complexRelativePDHull_base p)).commutes x

/-- The comparison evaluates every relative symbol as the constructed integral operation. -/
theorem complexRelativePDToHull_symbol (n : ℕ) (x : complexRelativeThetaIdeal p) :
    complexRelativePDToHull p
      (relativePDSymbol _ (PadicInt.dividedPowers p) _ (complexRelativeThetaIdeal_base p) n x) =
        (complexRelativePDHullDividedPowers p).dpow n (complexAinfToPDHull p x) := by
  let : Algebra (Ainf p) (ComplexAinfPDHull p) := (complexAinfToPDHull p).toAlgebra
  let : Algebra ℤ_[p] (ComplexAinfPDHull p) := (complexPadicIntToPDHull p).toAlgebra
  let : IsScalarTower ℤ_[p] (Ainf p) (ComplexAinfPDHull p) :=
    IsScalarTower.of_algebraMap_eq' rfl
  exact relativePDTargetMap_symbol _ (PadicInt.dividedPowers p) _
    (complexRelativeThetaIdeal_base p) _ (complexRelativePDHullDividedPowers p)
      (complexRelativeTheta_toPDHull p) (complexRelativePDHull_base p) n x

end PadicHodgeTheory
