/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexDeRhamRings
public import FLT.PadicHodgeTheory.ComplexThetaPrincipal
public import Mathlib.RingTheory.Localization.Algebra

/-! # The principal kernel after inverting p -/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- Theta carries the powers used for the source localization to the target powers. -/
theorem complexTheta_map_powers :
    (Submonoid.powers (p : Ainf p)).map (complexTheta p) =
      Submonoid.powers (p : 𝓞_ℂ_[p]) := by
  rw [Submonoid.map_powers, map_natCast]

/-- The existing localized theta is the functorial localization map. -/
theorem complexThetaInvertP_eq_map : complexThetaInvertP p =
    IsLocalization.map (Localization.Away (p : 𝓞_ℂ_[p])) (complexTheta p)
      ((complexTheta_map_powers p).symm ▸ (Submonoid.powers (p : Ainf p)).le_comap_map) := by
  apply IsLocalization.ringHom_ext (Submonoid.powers (p : Ainf p))
  ext x
  simp only [RingHom.comp_apply, complexThetaInvertP_algebraMap, IsLocalization.map_eq]

/-- Surjectivity of actual theta survives localization. -/
theorem complexThetaInvertP_surjective : Function.Surjective (complexThetaInvertP p) := by
  rw [complexThetaInvertP_eq_map]
  let : IsLocalization ((Submonoid.powers (p : Ainf p)).map (complexTheta p))
      (Localization.Away (p : 𝓞_ℂ_[p])) := by
    rw [complexTheta_map_powers]
    infer_instance
  exact IsLocalization.map_surjective_of_surjective _ _ _ (complexTheta_surjective p)

/-- The localized actual theta kernel is generated by the image of [p-flat] - p. -/
theorem complexThetaInvertP_ker_eq_span : RingHom.ker (complexThetaInvertP p) =
    Ideal.span {algebraMap (Ainf p) (ComplexAinfInvertP p) (complexThetaGenerator p)} := by
  rw [complexThetaInvertP_eq_map, IsLocalization.ker_map _ _ (complexTheta_map_powers p),
    complexTheta_ker_eq_span, Ideal.map_span, Set.image_singleton]

/-- In particular the ideal defining the de Rham completion is finitely generated. -/
theorem complexThetaInvertP_ker_fg : (RingHom.ker (complexThetaInvertP p)).FG := by
  rw [complexThetaInvertP_ker_eq_span]
  exact Submodule.fg_span_singleton _

end PadicHodgeTheory
