/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexThetaLocalized
public import Mathlib.RingTheory.AdicCompletion.LocalRing

/-! # The actual theta-adic filtration on B_dR^+

These are completeness and filtration statements. A nonzero regular
uniformizer and a field residue quotient are still needed for the DVR claim.
-/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [Fact p.Prime]

/-- The actual ideal used in the de Rham completion. -/
abbrev ComplexDeRhamIdeal : Ideal (ComplexAinfInvertP p) := RingHom.ker (complexThetaInvertP p)

/-- The completion retains its canonical algebra over A_inf[1/p]. -/
instance instAlgebraComplexDeRham : Algebra (ComplexAinfInvertP p) (ComplexBDeRhamPlus p) :=
  inferInstanceAs (Algebra (ComplexAinfInvertP p)
    (AdicCompletion (ComplexDeRhamIdeal p) (ComplexAinfInvertP p)))

/-- The theta generator mapped into the actual completed ring. -/
def complexDeRhamParameter : ComplexBDeRhamPlus p :=
  algebraMap (ComplexAinfInvertP p) (ComplexBDeRhamPlus p)
    (algebraMap (Ainf p) (ComplexAinfInvertP p) (complexThetaGenerator p))

/-- The completed theta ideal is generated by the constructed parameter. -/
theorem complexDeRhamIdeal_map :
    (ComplexDeRhamIdeal p).map
      (algebraMap (ComplexAinfInvertP p) (ComplexBDeRhamPlus p)) =
      Ideal.span {complexDeRhamParameter p} := by
  unfold ComplexDeRhamIdeal
  rw [complexThetaInvertP_ker_eq_span, Ideal.map_span, Set.image_singleton]
  rfl

/-- B_dR^+ is complete for the powers of its actual parameter. -/
instance instIsAdicCompleteComplexDeRham :
    IsAdicComplete (Ideal.span {complexDeRhamParameter p}) (ComplexBDeRhamPlus p) := by
  rw [← complexDeRhamIdeal_map]
  exact AdicCompletion.isAdicComplete_self _ (complexThetaInvertP_ker_fg p)

/-- Each source-ideal filtration level is exactly the kernel of finite-level evaluation. -/
theorem complexDeRham_filtration_eq_ker (n : ℕ) :
    (ComplexDeRhamIdeal p) ^ n • (⊤ : Submodule (ComplexAinfInvertP p) (ComplexBDeRhamPlus p)) =
      (AdicCompletion.eval (ComplexDeRhamIdeal p) (ComplexAinfInvertP p) n).ker :=
  AdicCompletion.pow_smul_top_eq_ker_eval (complexThetaInvertP_ker_fg p)

/-- The completion's zeroth residue map is onto the actual localized theta quotient. -/
theorem complexDeRham_evalOne_surjective :
    Function.Surjective (AdicCompletion.evalOneₐ (ComplexDeRhamIdeal p)) :=
  AdicCompletion.evalOneₐ_surjective _

/-- Its kernel is the principal completed theta ideal. -/
theorem complexDeRham_evalOne_ker :
    RingHom.ker (AdicCompletion.evalOneₐ (ComplexDeRhamIdeal p)).toRingHom =
      Ideal.span {complexDeRhamParameter p} := by
  exact (AdicCompletion.ker_evalOneₐ_eq_map _ (complexThetaInvertP_ker_fg p)).trans
    (complexDeRhamIdeal_map p)

end PadicHodgeTheory
