/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.FractionalPrincipalFiltration
public import Mathlib.LinearAlgebra.Quotient.Basic
public import Mathlib.RingTheory.Ideal.Span

/-! # Actual consecutive quotients of the integer principal filtration -/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable {R K : Type*} [CommRing R] [IsDomain R] [Field K] [Algebra R K]
  [IsFractionRing R K]

/-- The actual next level, pulled back to the subtype of the current level. -/
def fractionalPrincipalNext (t : R) (n : ℤ) :
    Submodule R (fractionalPrincipalFiltration (K := K) t n) :=
  (fractionalPrincipalFiltration t (n + 1)).comap (fractionalPrincipalFiltration t n).subtype

/-- Consecutive actual submodules in the field define the integer graded piece. -/
abbrev FractionalPrincipalGradedPiece (t : R) (n : ℤ) :=
  fractionalPrincipalFiltration (K := K) t n ⧸ fractionalPrincipalNext (K := K) t n

/-- In coefficient coordinates the actual next level is precisely the ideal generated by t. -/
theorem fractionalPrincipalNext_comap {t : R} (ht : t ≠ 0) (n : ℤ) :
    (fractionalPrincipalNext t n).comap
      (fractionalPrincipalEquiv (K := K) ht n).toLinearMap = Ideal.span {t} := by
  have htK : algebraMap R K t ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective R K)).mpr ht
  ext a
  change (fractionalPrincipalEquiv (K := K) ht n a : K) ∈
    fractionalPrincipalFiltration t (n + 1) ↔ a ∈ Ideal.span {t}
  rw [fractionalPrincipalEquiv_coe, fractionalPrincipalFiltration,
    Submodule.mem_span_singleton, Ideal.mem_span_singleton]
  simp only [Algebra.smul_def]
  constructor
  · rintro ⟨b, hb⟩
    change algebraMap R K b * (algebraMap R K t) ^ (n + 1) = _ at hb
    rw [zpow_add₀ htK, zpow_one] at hb
    have he : algebraMap R K (t * b) * (algebraMap R K t) ^ n =
        algebraMap R K a * (algebraMap R K t) ^ n := by rw [map_mul]; convert hb using 1; ring
    exact ⟨b, ((IsFractionRing.injective R K)
      (mul_right_cancel₀ (zpow_ne_zero n htK) he)).symm⟩
  · rintro ⟨b, rfl⟩
    refine ⟨b, ?_⟩
    change algebraMap R K b * (algebraMap R K t) ^ (n + 1) =
      algebraMap R K (t * b) * (algebraMap R K t) ^ n
    rw [zpow_add₀ htK, zpow_one, map_mul]
    ring

/-- Dividing by t^n induces a residue-module equivalence on the actual quotient. -/
def fractionalPrincipalGradedEquiv {t : R} (ht : t ≠ 0) (n : ℤ) :
    (R ⧸ Ideal.span {t}) ≃ₗ[R] FractionalPrincipalGradedPiece (K := K) t n :=
  Submodule.Quotient.equiv _ _ (fractionalPrincipalEquiv ht n) (by
    rw [← fractionalPrincipalNext_comap (K := K) ht n]
    exact Submodule.map_comap_eq_of_surjective
      (fractionalPrincipalEquiv (K := K) ht n).surjective _)

/-- The residue class of a maps to the actual class of a*t^n. -/
theorem fractionalPrincipalGradedEquiv_mk {t : R} (ht : t ≠ 0) (n : ℤ) (a : R) :
    fractionalPrincipalGradedEquiv (K := K) ht n (Submodule.Quotient.mk a) =
      (fractionalPrincipalNext (K := K) t n).mkQ (fractionalPrincipalEquiv ht n a) := rfl

end PadicHodgeTheory
