/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.PadicHodgeTheory.ComplexGaloisAction
public import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots
public import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed

/-! # The actual cyclotomic subfields of the algebraic p-adic closure -/

@[expose] public noncomputable section
namespace PadicHodgeTheory
variable (p : ℕ) [hp : Fact p.Prime]

/-- The nth level is generated by all actual p^n-th roots of unity. -/
def padicCyclotomicTower (n : ℕ) : IntermediateField ℚ_[p] (PadicAlgCl p) :=
  IntermediateField.adjoin ℚ_[p]
    {x : PadicAlgCl p | ∃ k ∈ ({p ^ n} : Set ℕ), k ≠ 0 ∧ x ^ k = 1}

/-- Every actual p^n-th root is in the nth level. -/
theorem padicCyclotomicTower_root_mem (n : ℕ) (x : PadicAlgCl p) (hx : x ^ (p ^ n) = 1) :
    x ∈ padicCyclotomicTower p n :=
  IntermediateField.subset_adjoin ℚ_[p] _ ⟨p ^ n, rfl, pow_ne_zero _ hp.out.ne_zero, hx⟩

/-- The root-generated fields form an increasing tower. -/
theorem padicCyclotomicTower_mono : Monotone (padicCyclotomicTower p) := by
  intro n m hnm
  apply IntermediateField.adjoin.mono
  rintro x ⟨k, hk, _, hx⟩
  obtain rfl : k = p ^ n := hk
  refine ⟨p ^ m, rfl, pow_ne_zero _ hp.out.ne_zero, ?_⟩
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hnm
  rw [pow_add, pow_mul, hx, one_pow]

/-- The actual field inclusion between two levels. -/
def padicCyclotomicInclusion {n m : ℕ} (h : n ≤ m) :
    padicCyclotomicTower p n →ₐ[ℚ_[p]] padicCyclotomicTower p m :=
  IntermediateField.inclusion (padicCyclotomicTower_mono p h)

/-- The inclusion does not change the element of the original algebraic closure. -/
@[simp] theorem padicCyclotomicInclusion_coe {n m : ℕ} (h : n ≤ m)
    (x : padicCyclotomicTower p n) :
    (padicCyclotomicInclusion p h x : PadicAlgCl p) = x :=
  Subalgebra.coe_inclusion (padicCyclotomicTower_mono p h) x

/-- These subfields are cyclotomic extensions in the standard sense. -/
instance instIsCyclotomicExtensionPadicTower (n : ℕ) :
    IsCyclotomicExtension {p ^ n} ℚ_[p] (padicCyclotomicTower p n) := by
  apply IntermediateField.isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot
    ({p ^ n} : Set ℕ) ℚ_[p] (PadicAlgCl p)
  intro k _ hk
  let : NeZero k := ⟨hk⟩
  exact HasEnoughRootsOfUnity.exists_primitiveRoot (PadicAlgCl p) k

/-- Each actual cyclotomic level is finite over Q_p. -/
instance instFiniteDimensionalPadicCyclotomicTower (n : ℕ) :
    FiniteDimensional ℚ_[p] (padicCyclotomicTower p n) :=
  IsCyclotomicExtension.finiteDimensional {p ^ n} ℚ_[p] _

/-- Each level is the simple field generated by any primitive root at that level. -/
theorem padicCyclotomicTower_eq_adjoin (n : ℕ) (ζ : PadicAlgCl p)
    (hζ : IsPrimitiveRoot ζ (p ^ n)) :
    padicCyclotomicTower p n = IntermediateField.adjoin ℚ_[p] {ζ} := by
  let : NeZero (p ^ n) := ⟨pow_ne_zero _ hp.out.ne_zero⟩
  exact (IntermediateField.isCyclotomicExtension_singleton_iff_eq_adjoin
    (n := p ^ n) (K := ℚ_[p]) (L := PadicAlgCl p) (padicCyclotomicTower p n) hζ).mp inferInstance

/-- The zeroth cyclotomic level is precisely the original scalar subfield. -/
theorem padicCyclotomicTower_zero : padicCyclotomicTower p 0 = ⊥ := by
  rw [padicCyclotomicTower_eq_adjoin p 0 1 (by simp)]
  apply le_antisymm _ bot_le
  exact IntermediateField.adjoin_le_iff.mpr (by simp)

end PadicHodgeTheory
