/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.RingTheory.Finiteness.Cardinality
public import Mathlib.NumberTheory.Padics.RingHoms

/-! # Finite sets from finite modules over finite residue rings -/

@[expose] public noncomputable section
namespace Module
variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- A finitely generated module killed by an ideal with finite quotient is a finite set. -/
theorem finite_of_finite_quotient [Module.Finite R M] (I : Ideal R) [Finite (R ⧸ I)]
    (hM : IsTorsionBySet R M I) : Finite M := by
  let := hM.module
  let : Module.Finite (R ⧸ I) M :=
    Module.Finite.of_surjective hM.semilinearMap Function.surjective_id
  exact Module.finite_of_finite (R ⧸ I)

/-- The preceding statement for the ideal generated by one scalar. -/
theorem finite_of_scalar_annihilator [Module.Finite R M] (r : R)
    [Finite (R ⧸ Ideal.span {r})] (hM : ∀ x : M, r • x = 0) : Finite M :=
  finite_of_finite_quotient (Ideal.span {r})
    ((isTorsionBySet_span_singleton_iff r).mpr hM)

end Module
namespace PadicInt
variable (p : ℕ) [Fact p.Prime]

/-- The actual p-power residue ring of Z_p is finite, including level zero. -/
theorem finite_quotient_span_pow (n : ℕ) : Finite (ℤ_[p] ⧸ Ideal.span {(p : ℤ_[p]) ^ n}) := by
  let e := (Ideal.quotEquivOfEq (PadicInt.ker_toZModPow (p := p) n).symm).trans
    (RingHom.quotientKerEquivOfSurjective (ZMod.ringHom_surjective (PadicInt.toZModPow (p := p) n)))
  exact Finite.of_injective e e.injective

/-- An actual integer-ring identification transports finiteness of all p-power residues. -/
theorem finite_quotient_span_pow_of_equiv {R : Type*} [CommRing R]
    (e : R ≃+* ℤ_[p]) (n : ℕ) : Finite (R ⧸ Ideal.span {(p : R) ^ n}) := by
  let := finite_quotient_span_pow p n
  let q := Ideal.quotientEquiv (Ideal.span {(p : R) ^ n})
    (Ideal.span {(p : ℤ_[p]) ^ n}) e (by rw [Ideal.map_span]; simp)
  exact Finite.of_injective q q.injective

end PadicInt
