/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mathlib.RingTheory.FrobeniusImage
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Killing Frobenius powers of the augmentation ideal

For an augmented algebra in characteristic `p`, quotienting by the ideal
generated by the `p`-th powers in the augmentation ideal gives a height-one
augmented algebra. Over a perfect field this is the ideal extended from the
augmentation ideal of the Frobenius image.
-/

@[expose] public noncomputable section

namespace Ideal

variable {A : Type*} [CommRing A] (p : ℕ) [Fact p.Prime] [CharP A p]

/-- The ideal generated by the `p`-th powers of elements of an ideal. -/
def frobeniusPower (I : Ideal A) : Ideal A := I.map (frobenius A p)

/-- Every generating Frobenius power belongs to the Frobenius power ideal. -/
theorem pow_mem_frobeniusPower (I : Ideal A) {a : A} (ha : a ∈ I) :
    a ^ p ∈ I.frobeniusPower p := Ideal.mem_map_of_mem _ ha

/-- Frobenius powers lie in the ordinary `p`-th ideal power. -/
theorem frobeniusPower_le_pow (I : Ideal A) : I.frobeniusPower p ≤ I ^ p := by
  exact Ideal.map_le_iff_le_comap.mpr fun _ ha ↦ Ideal.pow_mem_pow ha p

/-- A Frobenius power ideal is contained in the original ideal. -/
theorem frobeniusPower_le (I : Ideal A) : I.frobeniusPower p ≤ I :=
  (I.frobeniusPower_le_pow p).trans (Ideal.pow_le_self (Fact.out : p.Prime).ne_zero)

/-- Killing Frobenius powers introduces no linear relations at the augmentation. -/
theorem frobeniusPower_le_sq (I : Ideal A) : I.frobeniusPower p ≤ I ^ 2 :=
  (I.frobeniusPower_le_pow p).trans (Ideal.pow_le_pow_right (Fact.out : p.Prime).two_le)

/-- Frobenius powers of any ideal generating family generate its Frobenius power ideal. -/
theorem frobeniusPower_span {ι : Type*} (x : ι → A) :
    (Ideal.span (Set.range x)).frobeniusPower p =
      Ideal.span (Set.range (fun i ↦ x i ^ p)) := by
  simp only [frobeniusPower, Ideal.map_span, ← Set.range_comp, Function.comp_def, frobenius_def]

end Ideal

namespace AlgHom

variable {k A : Type*} [Field k] [CommRing A] [Algebra k A]
variable (p : ℕ) [Fact p.Prime] [CharP A p] (ε : A →ₐ[k] k)

/-- The augmentation on the quotient by Frobenius powers of its kernel. -/
def frobeniusQuotientAugmentation :
    (A ⧸ (RingHom.ker ε).frobeniusPower p) →ₐ[k] k :=
  Ideal.Quotient.liftₐ _ ε fun _ ha ↦ (RingHom.ker ε).frobeniusPower_le p ha

/-- The quotient augmentation agrees with the original augmentation on representatives. -/
@[simp] theorem frobeniusQuotientAugmentation_mk (a : A) :
    ε.frobeniusQuotientAugmentation p
      (Ideal.Quotient.mk ((RingHom.ker ε).frobeniusPower p) a) = ε a := rfl

/-- In the Frobenius quotient, every `p`-th power is its augmented scalar. -/
theorem pow_eq_augmentation_frobeniusQuotient
    (a : A ⧸ (RingHom.ker ε).frobeniusPower p) :
    a ^ p = algebraMap k _ ((ε.frobeniusQuotientAugmentation p a) ^ p) := by
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
  have ha : a - algebraMap k A (ε a) ∈ RingHom.ker ε := by simp [RingHom.mem_ker]
  have h := Ideal.Quotient.eq_zero_iff_mem.mpr
    ((RingHom.ker ε).pow_mem_frobeniusPower p ha)
  rw [sub_pow_char, map_sub, sub_eq_zero] at h
  simpa only [frobeniusQuotientAugmentation_mk, map_pow,
    Ideal.Quotient.mk_algebraMap] using h

/-- The augmentation ideal of the Frobenius quotient is killed elementwise by `p`-th powers. -/
theorem pow_eq_zero_on_ker_frobeniusQuotient
    (a : A ⧸ (RingHom.ker ε).frobeniusPower p)
    (ha : ε.frobeniusQuotientAugmentation p a = 0) : a ^ p = 0 := by
  rw [ε.pow_eq_augmentation_frobeniusQuotient p a, ha,
    zero_pow (Fact.out : p.Prime).ne_zero, map_zero]

variable [CharP k p] [PerfectRing k p]

/-- The height-one quotient ideal is the extension of the augmentation ideal
of the Frobenius image, as required for induction through a Hopf subalgebra. -/
theorem frobeniusPower_ker_eq_map_ker_frobeniusImage :
    (RingHom.ker ε).frobeniusPower p =
      (RingHom.ker (ε.comp (Algebra.frobeniusImage k A p 1).val)).map
        (Algebra.frobeniusImage k A p 1).val := by
  apply le_antisymm
  · apply Ideal.map_le_iff_le_comap.mpr
    intro a ha
    let b : Algebra.frobeniusImage k A p 1 :=
      ⟨a ^ p, ⟨a, by simp only [iterateFrobenius_def, pow_one]⟩⟩
    exact Ideal.mem_map_of_mem (Algebra.frobeniusImage k A p 1).val
      (show b ∈ RingHom.ker (ε.comp (Algebra.frobeniusImage k A p 1).val) from by
        change ε (a ^ p) = 0
        rw [map_pow, show ε a = 0 from ha, zero_pow (Fact.out : p.Prime).ne_zero])
  · apply Ideal.map_le_iff_le_comap.mpr
    intro b hb
    obtain ⟨a, ha⟩ := b.property
    have hab : a ^ p = (b : A) := by simpa only [iterateFrobenius_def, pow_one] using ha
    have hε : ε a = 0 := by
      have hpow : (ε a) ^ p = 0 := by
        rw [← map_pow, hab]
        exact hb
      exact (pow_eq_zero_iff (Fact.out : p.Prime).ne_zero).mp hpow
    change (b : A) ∈ (RingHom.ker ε).frobeniusPower p
    rw [← hab]
    exact (RingHom.ker ε).pow_mem_frobeniusPower p hε

end AlgHom
