/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mathlib.RingTheory.PowerBasisDifferentials

/-!
# A polynomial Bézout identity from differential annihilation

For a power-basis algebra, an element of the base ring annihilating the
Kähler differentials lies in the polynomial ideal generated by the defining
polynomial and its derivative. This identity also controls the derivative at
approximate roots, where there is not yet an algebra map to the original ring.
-/

@[expose] public noncomputable section

open Polynomial

namespace PowerBasis

variable {R B : Type*} [CommRing R] [CommRing B] [Algebra R B]

/-- The kernel of evaluation at a power-basis generator is generated by its
minimal polynomial, even when the algebra is not a domain. -/
theorem minpoly_dvd_iff_aeval_eq_zero (pb : PowerBasis R B) (f : R[X]) :
    minpoly R pb.gen ∣ f ↔ aeval pb.gen f = 0 := by
  constructor
  · rintro ⟨q, rfl⟩
    simp
  · intro hf
    nontriviality R
    rw [← modByMonic_eq_zero_iff_dvd (minpoly.monic pb.isIntegral_gen)]
    by_contra hne
    have hr := (aeval_modByMonic_eq_self_of_root (minpoly.aeval R pb.gen)).trans hf
    have hd := pb.dim_le_degree_of_root hne hr
    have hlt := degree_modByMonic_lt f (minpoly.monic pb.isIntegral_gen)
    rw [pb.degree_minpoly] at hlt
    exact hd.not_gt hlt

/-- An annihilator of the differentials gives a Bézout identity for the
minimal polynomial and its derivative over the original base ring. -/
theorem exists_minpoly_derivative_bezout (pb : PowerBasis R B) (a : R)
    (ha : ∀ ω : KaehlerDifferential R B, a • ω = 0) :
    ∃ q r : R[X], C a = q * (minpoly R pb.gen).derivative + r * minpoly R pb.gen := by
  have hb : ∀ ω : KaehlerDifferential R B, algebraMap R B a • ω = 0 := by
    intro ω
    simpa only [algebraMap_smul] using ha ω
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton.mp
    ((pb.smul_kaehlerDifferential_eq_zero_iff _).mp hb)
  obtain ⟨q, hq⟩ := pb.exists_eq_aeval' b
  have hz : aeval pb.gen (C a - q * (minpoly R pb.gen).derivative) = 0 := by
    simp only [map_sub, aeval_C, map_mul, ← hq]
    rw [hb]
    ring
  obtain ⟨r, hr⟩ := (pb.minpoly_dvd_iff_aeval_eq_zero _).mpr hz
  refine ⟨q, r, ?_⟩
  linear_combination hr

end PowerBasis
