/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.Polynomial.Derivation
public import Mathlib.Algebra.TrivSqZeroExt.Basic
public import Mathlib.RingTheory.Kaehler.Basic
public import Mathlib.RingTheory.PowerBasis

/-!
# Differentials of a monogenic algebra

For an algebra with a power basis, the annihilator of its Kähler differentials
is generated by the derivative of the minimal polynomial at the generator.
-/

@[expose] public noncomputable section

open Polynomial

namespace TrivSqZeroExt

variable {R B N : Type*} [CommRing R] [CommRing B] [Algebra R B]
  [AddCommGroup N] [Module B N] [Module R N] [IsScalarTower R B N]
  [Module Bᵐᵒᵖ N] [IsCentralScalar B N] [IsScalarTower R Bᵐᵒᵖ N]

/-- Evaluation in a square-zero extension has the expected first component. -/
theorem fst_aeval (x : TrivSqZeroExt B N) (f : R[X]) :
    (aeval x f).fst = aeval x.fst f :=
  (aeval_algHom_apply (fstHom R B N) x f).symm

/-- The second component of polynomial evaluation is its first derivative. -/
theorem snd_aeval (x : TrivSqZeroExt B N) (f : R[X]) :
    (aeval x f).snd = aeval x.fst (derivative f) • x.snd := by
  induction f using Polynomial.induction_on' with
  | add f g hf hg => simp [hf, hg, add_smul]
  | monomial n r =>
    simp [aeval_monomial, derivative_monomial, snd_mul, snd_pow,
      algebraMap_eq_inl', mul_smul, Nat.cast_smul_eq_nsmul]

end TrivSqZeroExt

namespace PowerBasis

variable {R B : Type*} [CommRing R] [CommRing B] [Algebra R B]

/-- A derivation on a power-basis algebra vanishes if it vanishes at the generator. -/
theorem derivation_eq_zero {N : Type*} [AddCommGroup N] [Module B N] [Module R N]
    (pb : PowerBasis R B) (d : Derivation R B N)
    (h : d pb.gen = 0) : d = 0 := by
  ext b
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' b
  simp [Derivation.map_aeval, h]

/-- The minimal-polynomial derivative annihilates all Kähler differentials. -/
theorem minpoly_derivative_smul_kaehlerDifferential (pb : PowerBasis R B)
    (ω : KaehlerDifferential R B) :
    aeval pb.gen (derivative (minpoly R pb.gen)) • ω = 0 := by
  have hd : aeval pb.gen (derivative (minpoly R pb.gen)) •
      KaehlerDifferential.D R B = 0 := by
    apply pb.derivation_eq_zero
    have h := (KaehlerDifferential.D R B).comp_aeval_eq pb.gen (minpoly R pb.gen)
    simpa using h.symm
  have h : (aeval pb.gen (derivative (minpoly R pb.gen)) • LinearMap.id :
      KaehlerDifferential R B →ₗ[B] KaehlerDifferential R B) = 0 := by
    apply Derivation.liftKaehlerDifferential_unique
    exact hd
  exact LinearMap.congr_fun h ω

/-- Any value killed by the minimal-polynomial derivative defines a derivation. -/
theorem exists_derivation_apply_gen {N : Type*} [AddCommGroup N] [Module B N]
    [Module R N] [IsScalarTower R B N] (pb : PowerBasis R B) (m : N)
    (hm : aeval pb.gen (derivative (minpoly R pb.gen)) • m = 0) :
    ∃ d : Derivation R B N, d pb.gen = m := by
  let : Module Bᵐᵒᵖ N := Module.compHom _ ((RingHom.id B).fromOpposite mul_comm)
  let : IsCentralScalar B N := ⟨fun _ _ ↦ rfl⟩
  let : IsScalarTower R Bᵐᵒᵖ N := ⟨fun r b x ↦ smul_assoc r b.unop x⟩
  let x : TrivSqZeroExt B N := ⟨pb.gen, m⟩
  have hx : aeval x (minpoly R pb.gen) = 0 := by
    apply TrivSqZeroExt.ext
    · rw [TrivSqZeroExt.fst_aeval]
      exact minpoly.aeval R pb.gen
    · rw [TrivSqZeroExt.snd_aeval]
      exact hm
  let F := pb.lift x hx
  have hF : (TrivSqZeroExt.fstHom R B N).comp F = AlgHom.id R B := by
    apply pb.algHom_ext
    change (F pb.gen).fst = pb.gen
    rw [PowerBasis.lift_gen]
    rfl
  have hfst (b : B) : (F b).fst = b := AlgHom.congr_fun hF b
  let d : Derivation R B N :=
    { toLinearMap := (TrivSqZeroExt.sndHom B N).restrictScalars R ∘ₗ F.toLinearMap
      map_one_eq_zero' := by simp
      leibniz' := fun a b ↦ by
        change (F (a * b)).snd = a • (F b).snd + b • (F a).snd
        simp [TrivSqZeroExt.snd_mul, hfst, op_smul_eq_smul] }
  refine ⟨d, ?_⟩
  change (F pb.gen).snd = m
  rw [PowerBasis.lift_gen]
  rfl

/-- An element annihilates the differentials precisely when it is divisible by
the minimal-polynomial derivative at a power-basis generator. -/
theorem smul_kaehlerDifferential_eq_zero_iff (pb : PowerBasis R B) (b : B) :
    (∀ ω : KaehlerDifferential R B, b • ω = 0) ↔
      b ∈ Ideal.span {aeval pb.gen (derivative (minpoly R pb.gen))} := by
  let I : Ideal B := Ideal.span {aeval pb.gen (derivative (minpoly R pb.gen))}
  constructor
  · intro hb
    have hm : aeval pb.gen (derivative (minpoly R pb.gen)) • (1 : B ⧸ I) = 0 := by
      change Ideal.Quotient.mk I _ * 1 = 0
      rw [mul_one, Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.mem_span_singleton_self _
    obtain ⟨d, hd⟩ := pb.exists_derivation_apply_gen (1 : B ⧸ I) hm
    have h := congrArg d.liftKaehlerDifferential (hb (KaehlerDifferential.D R B pb.gen))
    rw [map_smul, Derivation.liftKaehlerDifferential_comp_D, hd, map_zero] at h
    change Ideal.Quotient.mk I b * 1 = 0 at h
    exact Ideal.Quotient.eq_zero_iff_mem.mp (by simpa using h)
  · intro hb ω
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.mp hb
    rw [hc, mul_smul, pb.minpoly_derivative_smul_kaehlerDifferential]

/-- The differential annihilator in a power-basis algebra is the derivative ideal. -/
theorem annihilator_kaehlerDifferential (pb : PowerBasis R B) :
    Module.annihilator B (KaehlerDifferential R B) =
      Ideal.span {aeval pb.gen (derivative (minpoly R pb.gen))} := by
  ext b
  exact Module.mem_annihilator.trans (pb.smul_kaehlerDifferential_eq_zero_iff b)

end PowerBasis
