/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mathlib.RingTheory.DifferentPowerBasis
public import Mathlib.Algebra.Polynomial.Splits

/-!
# Conjugate differences in a monogenic algebra

An endomorphism's displacement ideal is generated by its displacement of
any power-basis generator. When the generator's minimal polynomial splits
and is separable, its derivative is the product of these displacements over
the nonidentity endomorphisms.
-/

@[expose] public noncomputable section

namespace PowerBasis

open Polynomial

variable {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]

/-- Every displacement is divisible by the displacement of a power-basis generator. -/
theorem genSubHomDvdSubHom (pb : PowerBasis A B) (σ : B →ₐ[A] B) (x : B) :
    pb.gen - σ pb.gen ∣ x - σ x := by
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  rw [← aeval_algHom_apply]
  simpa only [eval_map_algebraMap] using
    sub_dvd_eval_sub pb.gen (σ pb.gen) (f.map (algebraMap A B))

/-- A power-basis generator computes the ideal of all endomorphism displacements. -/
theorem spanSubHomEqSpanGen (pb : PowerBasis A B) (σ : B →ₐ[A] B) :
    Ideal.span (Set.range fun x : B ↦ x - σ x) = Ideal.span {pb.gen - σ pb.gen} := by
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro _ ⟨x, rfl⟩
    exact Ideal.mem_span_singleton.mpr (pb.genSubHomDvdSubHom σ x)
  · apply Ideal.span_mono
    rintro _ rfl
    exact ⟨pb.gen, rfl⟩

variable [IsDomain B] [Fintype (B →ₐ[A] B)]

/-- For a separable split power basis, the minimal polynomial factors over
the algebra endomorphisms, with each endomorphism appearing once. -/
theorem minpolyEqProdHom (pb : PowerBasis A B)
    (hsplit : ((minpoly A pb.gen).map (algebraMap A B)).Splits)
    (hnodup : ((minpoly A pb.gen).aroots B).Nodup) :
    (minpoly A pb.gen).map (algebraMap A B) =
      ∏ σ : B →ₐ[A] B, (X - C (σ pb.gen)) := by
  classical
  rw [hsplit.eq_prod_roots_of_monic ((minpoly.monic pb.isIntegral_gen).map _)]
  rw [Fintype.prod_equiv pb.liftEquiv' (fun σ ↦ X - C (σ pb.gen))
    (fun x ↦ X - C (x : B)) (fun _ ↦ rfl)]
  rw [Finset.prod_mem_multiset _ _ (fun x ↦ X - C x) (fun _ ↦ rfl),
    Finset.prod_eq_multiset_prod, Multiset.toFinset_val,
    Multiset.dedup_eq_self.mpr hnodup]

open scoped Classical in
/-- Evaluating the minimal-polynomial derivative at a power-basis generator
gives the product of its nonidentity conjugate differences. -/
theorem minpolyDerivativeEqProdHom (pb : PowerBasis A B)
    (hsplit : ((minpoly A pb.gen).map (algebraMap A B)).Splits)
    (hnodup : ((minpoly A pb.gen).aroots B).Nodup) :
    aeval pb.gen (derivative (minpoly A pb.gen)) =
      ∏ σ ∈ Finset.univ.erase (AlgHom.id A B), (pb.gen - σ pb.gen) := by
  classical
  rw [← eval_map_algebraMap, ← derivative_map, pb.minpolyEqProdHom hsplit hnodup,
    ← Finset.mul_prod_erase _ _ (Finset.mem_univ (AlgHom.id A B))]
  simp [derivative_mul, eval_prod]

end PowerBasis
