/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mathlib.RingTheory.Polynomial.Eisenstein.Perturbation
public import Mathlib.RingTheory.DiscreteValuationRing.TFAE
public import Mathlib.RingTheory.Ideal.GoingUp

/-!
# Discrete valuation rings from Eisenstein polynomials

The quotient by a monic Eisenstein polynomial over a discrete valuation
ring is a discrete valuation ring whose uniformizer is the adjoined root.
-/

@[expose] public noncomputable section

open Polynomial IsLocalRing

namespace Polynomial.IsEisensteinAt

variable {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  {P : R[X]}

/-- The constant coefficient of a positive-degree Eisenstein polynomial is
an irreducible element of the base discrete valuation ring. -/
theorem irreducibleCoeffZero (hP : P.IsEisensteinAt (maximalIdeal R))
    (hdeg : 0 < P.natDegree) : Irreducible (P.coeff 0) := by
  refine ⟨hP.mem hdeg, fun x y hxy => ?_⟩
  by_contra h
  push Not at h
  apply hP.notMem
  rw [hxy, pow_two]
  exact Ideal.mul_mem_mul h.1 h.2

end Polynomial.IsEisensteinAt

namespace AdjoinRoot

variable {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  {P : R[X]}

/-- Every maximal ideal of an Eisenstein quotient is generated by its root. -/
theorem maximalIdealEqSpanRootOfEisenstein (hP : P.IsEisensteinAt (maximalIdeal R))
    (hPm : P.Monic) (hdeg : 0 < P.natDegree)
    (M : Ideal (AdjoinRoot P)) (hM : M.IsMaximal) : M = Ideal.span {root P} := by
  let instFinite : Module.Finite R (AdjoinRoot P) := hPm.finite_adjoinRoot
  let instIntegral : Algebra.IsIntegral R (AdjoinRoot P) := .of_finite R _
  let instMaximal : M.IsMaximal := hM
  have hcomap : M.comap (algebraMap R (AdjoinRoot P)) = maximalIdeal R :=
    eq_maximalIdeal (Ideal.isMaximal_under_of_isIntegral_of_isMaximal M)
  let J : Ideal (AdjoinRoot P) := Ideal.span {root P}
  have hdiff (p : R[X]) : mk P p - algebraMap R (AdjoinRoot P) (p.coeff 0) ∈ J := by
    apply Ideal.mem_span_singleton.mpr
    simpa using _root_.map_dvd (aeval (root P)) (X_dvd_sub_C (p := p))
  have hconst : algebraMap R (AdjoinRoot P) (P.coeff 0) ∈ J := by
    have h := hdiff P
    simpa using J.neg_mem h
  have hmap : (maximalIdeal R).map (algebraMap R (AdjoinRoot P)) ≤ J := by
    rw [(hP.irreducibleCoeffZero hdeg).maximalIdeal_eq, Ideal.map_span,
      Set.image_singleton, Ideal.span_le, Set.singleton_subset_iff]
    exact hconst
  have hmapM : (maximalIdeal R).map (algebraMap R (AdjoinRoot P)) ≤ M := by
    rw [Ideal.map_le_iff_le_comap, hcomap]
  have hroot : root P ∈ M := by
    apply hM.isPrime.mem_of_pow_mem (P.map (algebraMap R (AdjoinRoot P))).natDegree
    apply hmapM
    exact hP.isWeaklyEisensteinAt.pow_natDegree_le_of_aeval_zero_of_monic_mem_map
      (by simp) hPm _ le_rfl
  have hJM : J ≤ M := Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hroot)
  apply le_antisymm ?_ hJM
  intro x hx
  obtain ⟨p, rfl⟩ := mk_surjective x
  have hp : p.coeff 0 ∈ maximalIdeal R := by
    rw [← hcomap]
    change algebraMap R (AdjoinRoot P) (p.coeff 0) ∈ M
    simpa using M.sub_mem hx (hJM (hdiff p))
  simpa using J.add_mem (hdiff p) (hmap (Ideal.mem_map_of_mem _ hp))

/-- A monic positive-degree Eisenstein quotient is local. -/
theorem isLocalRingOfEisenstein (hP : P.IsEisensteinAt (maximalIdeal R))
    (hPm : P.Monic) (hdeg : 0 < P.natDegree) : IsLocalRing (AdjoinRoot P) := by
  let instNontrivial : Nontrivial (AdjoinRoot P) :=
    (nontrivial_iff_of_monic hPm).mpr (natDegree_pos_iff_degree_pos.mp hdeg)
  obtain ⟨M, hM, _⟩ := Ideal.exists_le_maximal (⊥ : Ideal (AdjoinRoot P)) bot_ne_top
  apply IsLocalRing.of_unique_max_ideal
  refine ⟨M, hM, fun N hN => ?_⟩
  exact (maximalIdealEqSpanRootOfEisenstein hP hPm hdeg N hN).trans
    (maximalIdealEqSpanRootOfEisenstein hP hPm hdeg M hM).symm

/-- A monic positive-degree Eisenstein quotient is a discrete valuation ring,
and its root is an irreducible element. -/
theorem isDiscreteValuationRingOfEisenstein
    (hP : P.IsEisensteinAt (maximalIdeal R)) (hPm : P.Monic)
    (hdeg : 0 < P.natDegree) [IsDomain (AdjoinRoot P)] :
    IsDiscreteValuationRing (AdjoinRoot P) ∧ Irreducible (root P) := by
  let instFinite : Module.Finite R (AdjoinRoot P) := hPm.finite_adjoinRoot
  let instIntegral : Algebra.IsIntegral R (AdjoinRoot P) := .of_finite R _
  let instLocal : IsLocalRing (AdjoinRoot P) := isLocalRingOfEisenstein hP hPm hdeg
  have hinj : Function.Injective (algebraMap R (AdjoinRoot P)) :=
    of.injective_of_monic_of_degree_pos hPm (natDegree_pos_iff_degree_pos.mp hdeg)
  have hnotfield : ¬IsField (AdjoinRoot P) := fun h =>
    IsDiscreteValuationRing.not_isField R (isField_of_isIntegral_of_isField hinj h)
  have hmax : maximalIdeal (AdjoinRoot P) = Ideal.span {root P} :=
    maximalIdealEqSpanRootOfEisenstein hP hPm hdeg _ inferInstance
  let instDvr : IsDiscreteValuationRing (AdjoinRoot P) :=
    ((IsDiscreteValuationRing.TFAE (AdjoinRoot P) hnotfield).out 5 1).mp
      (by rw [hmax]; infer_instance)
  exact ⟨instDvr, (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr hmax⟩

end AdjoinRoot

namespace Polynomial.IsEisensteinAt

variable {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  {P : R[X]}

/-- Subtracting the leading monomial of a monic Eisenstein polynomial leaves
a uniformizer times a polynomial with unit constant coefficient. -/
theorem existsUniformizerDecomposition (hP : P.IsEisensteinAt (maximalIdeal R))
    (hPm : P.Monic) (hdeg : 0 < P.natDegree) {π : R} (hπ : Irreducible π) :
    ∃ H : R[X], P - X ^ P.natDegree = C π * H ∧ IsUnit (H.coeff 0) := by
  have hd : C π ∣ P - X ^ P.natDegree := by
    rw [C_dvd_iff_dvd_coeff]
    intro i
    rw [coeff_sub, coeff_X_pow]
    by_cases hi : i = P.natDegree
    · simp [hi, hPm.coeff_natDegree]
    · simp only [ite_eq_right hi, sub_zero]
      exact Ideal.mem_span_singleton.mp (hπ.maximalIdeal_eq ▸ hP.coeff_mem hi)
  obtain ⟨H, hH⟩ := hd
  refine ⟨H, hH, ?_⟩
  have hc : P.coeff 0 = π * H.coeff 0 := by
    have h := congrArg (fun f : R[X] => f.coeff 0) hH
    simpa [coeff_C_mul, hdeg.ne', hdeg.ne'.symm] using h
  exact ((hP.irreducibleCoeffZero hdeg).isUnit_or_isUnit hc).resolve_left hπ.not_isUnit

omit [IsDomain R] [IsDiscreteValuationRing R] in
/-- At a nonunit root of an Eisenstein polynomial in a local algebra, the
quotient by the leading monomial evaluates to a unit. -/
theorem isUnitAevalDecomposition {S : Type*} [CommRing S] [IsLocalRing S] [Algebra R S]
    {y : S} (hy : y ∈ maximalIdeal S) {H : R[X]} (hH : IsUnit (H.coeff 0)) :
    IsUnit (aeval y H) := by
  have hd : y ∣ aeval y H - algebraMap R S (H.coeff 0) := by
    simpa using _root_.map_dvd (aeval y) (X_dvd_sub_C (p := H))
  have hm : aeval y H - algebraMap R S (H.coeff 0) ∈ maximalIdeal S :=
    (maximalIdeal S).mem_of_dvd hd hy
  rw [← residue_ne_zero_iff_isUnit]
  have heq : residue S (aeval y H) = residue S (algebraMap R S (H.coeff 0)) := by
    exact sub_eq_zero.mp (by simpa using (residue_eq_zero_iff _).mpr hm)
  rw [heq]
  exact (residue_ne_zero_iff_isUnit _).mpr (hH.map (algebraMap R S))

/-- The image of a base uniformizer has valuation equal to the degree times
the root valuation in any DVR algebra containing an Eisenstein root. -/
theorem addValUniformizerEqDegreeMul {S : Type*} [CommRing S] [IsDomain S]
    [IsDiscreteValuationRing S] [Algebra R S]
    (hP : P.IsEisensteinAt (maximalIdeal R)) (hPm : P.Monic)
    (hdeg : 0 < P.natDegree) {π : R} (hπ : Irreducible π)
    {y : S} (hy : y ∈ maximalIdeal S) (hroot : aeval y P = 0) :
    IsDiscreteValuationRing.addVal S (algebraMap R S π) =
      P.natDegree • IsDiscreteValuationRing.addVal S y := by
  obtain ⟨H, hH, hH0⟩ := hP.existsUniformizerDecomposition hPm hdeg hπ
  have heq : -(y ^ P.natDegree) = algebraMap R S π * aeval y H := by
    have h := congrArg (aeval y) hH
    simpa [hroot] using h
  have hunit := isUnitAevalDecomposition hy hH0
  have hv := congrArg (IsDiscreteValuationRing.addVal S) heq
  simpa only [AddValuation.map_neg, IsDiscreteValuationRing.addVal_pow,
    IsDiscreteValuationRing.addVal_mul,
    IsDiscreteValuationRing.addVal_eq_zero_iff.mpr hunit, add_zero] using hv.symm

end Polynomial.IsEisensteinAt
