/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.MvPolynomial.Expand
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Descent of relative Frobenius relations

If an algebra has the expected relative pure-power presentation over an
algebra generated by the coordinate powers, then its absolute kernel is
the extension of the smaller algebra's kernel under polynomial expansion.
-/

@[expose] public noncomputable section

namespace MvPolynomial

variable {k R A ι : Type*} [CommRing k] [CommRing R] [CommRing A]
  [Algebra k R] [Algebra k A] [Algebra R A] [IsScalarTower k R A]

/-- A relative pure-power presentation turns absolute relations into
expanded relations of the algebra generated by the coordinate powers. -/
theorem ker_aeval_eq_map_expand_of_relative_presentation
    (x : ι → A) (p : ℕ) (z : ι → R)
    (hz : Function.Surjective (aeval (R := k) z))
    (hpow : ∀ i, x i ^ p = algebraMap R A (z i))
    (hrel : RingHom.ker (aeval (R := R) x) =
      Ideal.span (Set.range (fun i ↦ (X i : MvPolynomial ι R) ^ p - C (z i)))) :
    RingHom.ker (aeval (R := k) x) =
      (RingHom.ker (aeval (R := k) z)).map (expand p).toRingHom := by
  classical
  let K := RingHom.ker (aeval (R := k) z)
  let J := K.map (expand p).toRingHom
  let q := Ideal.Quotient.mkₐ k J
  have ht : K ≤ RingHom.ker (q.comp (expand p)) := by
    intro f hf
    exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_map_of_mem (expand p) hf)
  let α : R →ₐ[k] MvPolynomial ι k ⧸ J :=
    (aeval (R := k) z).liftOfSurjective hz (q.comp (expand p)) ht
  have hα (i : ι) : α (z i) = q ((X i) ^ p) := by
    have h := AlgHom.liftOfSurjective_apply (aeval (R := k) z) hz
      (q.comp (expand p)) ht (X i)
    simpa only [aeval_X, AlgHom.comp_apply, expand_X] using h
  let e := eval₂Hom α.toRingHom (fun i ↦ q (X i))
  have he : Ideal.span (Set.range (fun i ↦
      (X i : MvPolynomial ι R) ^ p - C (z i))) ≤ RingHom.ker e := by
    apply Ideal.span_le.mpr
    rintro _ ⟨i, rfl⟩
    change e ((X i) ^ p - C (z i)) = 0
    simp only [e, map_sub, map_pow, coe_eval₂Hom, eval₂_X, eval₂_C,
      show α.toRingHom (z i) = q ((X i) ^ p) from hα i, map_pow, sub_self]
  let m := map (σ := ι) (algebraMap k R)
  have hem : e.comp m = q.toRingHom := by
    apply ringHom_ext
    · intro c
      simp [e, m]
    · intro i
      simp [e, m]
  have hemx : (aeval (R := R) x).toRingHom.comp m = (aeval (R := k) x).toRingHom := by
    apply ringHom_ext
    · intro c
      simp [m, ← IsScalarTower.algebraMap_apply k R A]
    · intro i
      simp [m]
  apply le_antisymm
  · intro f hf
    have hmf : m f ∈ RingHom.ker (aeval (R := R) x) := by
      change ((aeval (R := R) x).toRingHom.comp m) f = 0
      rw [hemx]
      exact hf
    have hef : e (m f) = 0 := he (hrel ▸ hmf)
    change (e.comp m) f = 0 at hef
    rw [hem] at hef
    exact Ideal.Quotient.eq_zero_iff_mem.mp hef
  · apply Ideal.map_le_iff_le_comap.mpr
    intro f hf
    have hc : (aeval (R := k) x).comp (expand p) =
        (IsScalarTower.toAlgHom k R A).comp (aeval (R := k) z) := by
      ext i
      simpa using hpow i
    change ((aeval (R := k) x).comp (expand p)) f = 0
    rw [hc, AlgHom.comp_apply, show aeval (R := k) z f = 0 from hf, map_zero]

end MvPolynomial
