/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.Algebra.CharP.Lemmas
public import Mathlib.Tactic.ByContra

/-!
# Height-one ideals stable under partial differentiation

An ideal contained in the augmentation ideal, containing every `X i ^ p`, and
stable under all partial derivatives is exactly the ideal generated by those
powers. The proof uses induction on total degree and works for any number of
variables over a field of characteristic `p`.
-/

@[expose] public noncomputable section

namespace MvPolynomial

variable {k σ : Type*} [Field k]

/-- Membership in the ideal generated by pure powers is checked monomial by monomial. -/
theorem mem_span_X_pow_iff (p : ℕ) (f : MvPolynomial σ k) :
    f ∈ Ideal.span (Set.range (fun i : σ ↦ (X i : MvPolynomial σ k) ^ p)) ↔
      ∀ d ∈ f.support, ∃ i, p ≤ d i := by
  classical
  simpa only [← Set.range_comp, Function.comp_def, ← X_pow_eq_monomial, Set.mem_range,
    exists_exists_eq_and, Finsupp.single_le_iff] using
    (mem_ideal_span_monomial_image (x := f) (s := Set.range (fun i : σ ↦ Finsupp.single i p)))

/-- A monomial occurring in a partial derivative has degree below the original total degree. -/
theorem sum_lt_totalDegree_of_mem_support_pderiv {f : MvPolynomial σ k} {i : σ}
    {d : σ →₀ ℕ} (hd : d ∈ (pderiv i f).support) :
    d.sum (fun _ n ↦ n) < f.totalDegree := by
  classical
  have hd' : f.coeff (d + Finsupp.single i 1) ≠ 0 := by
    have := mem_support_iff.mp hd
    rw [coeff_pderiv] at this
    exact (mul_ne_zero_iff.mp this).1
  have hle := le_totalDegree (mem_support_iff.mpr hd')
  have heq : (d + Finsupp.single i 1).sum (fun _ n ↦ n) =
      d.sum (fun _ n ↦ n) + 1 := by simp [Finsupp.sum_add_index']
  rw [heq] at hle
  omega

/-- A nonzero partial derivative has strictly smaller total degree. -/
theorem totalDegree_pderiv_lt {f : MvPolynomial σ k} {i : σ} (h : pderiv i f ≠ 0) :
    (pderiv i f).totalDegree < f.totalDegree := by
  classical
  have hpos : 0 < f.totalDegree := by
    obtain ⟨d, hd⟩ := support_nonempty.mpr h
    exact lt_of_le_of_lt (Nat.zero_le _) (sum_lt_totalDegree_of_mem_support_pderiv hd)
  exact (Finset.sup_lt_iff hpos).mpr fun d hd ↦ sum_lt_totalDegree_of_mem_support_pderiv hd

variable (p : ℕ) [CharP k p]

/-- If all derivatives lie in the pure-power ideal and the constant coefficient
vanishes, the polynomial itself lies in that ideal. -/
theorem mem_span_X_pow_of_pderiv_mem (f : MvPolynomial σ k)
    (h0 : f.coeff 0 = 0)
    (hd : ∀ i, pderiv i f ∈
      Ideal.span (Set.range (fun j : σ ↦ (X j : MvPolynomial σ k) ^ p))) :
    f ∈ Ideal.span (Set.range (fun j : σ ↦ (X j : MvPolynomial σ k) ^ p)) := by
  classical
  rw [mem_span_X_pow_iff]
  intro d hdf
  by_contra! hsmall
  have hd0 : d ≠ 0 := by
    intro h
    subst d
    exact mem_support_iff.mp hdf h0
  obtain ⟨i, hi⟩ := Finsupp.ne_iff.mp hd0
  have hi0 : d i ≠ 0 := by simpa using hi
  let e := d - Finsupp.single i 1
  have he : e + Finsupp.single i 1 = d :=
    tsub_add_cancel_of_le (Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr hi0))
  have hei : e i + 1 = d i := by
    simpa only [Finsupp.add_apply, Finsupp.single_eq_same] using congrArg (fun d ↦ d i) he
  have hcast : ((e i + 1 : ℕ) : k) ≠ 0 := by
    rw [hei]
    intro hz
    exact Nat.not_dvd_of_pos_of_lt (Nat.pos_of_ne_zero hi0) (hsmall i)
      ((CharP.cast_eq_zero_iff k p (d i)).mp hz)
  have hedf : e ∈ (pderiv i f).support := by
    rw [mem_support_iff, coeff_pderiv, he]
    exact mul_ne_zero (mem_support_iff.mp hdf) (by simpa using hcast)
  obtain ⟨j, hj⟩ := (mem_span_X_pow_iff p _).mp (hd i) e hedf
  have hele : e ≤ d := tsub_le_self
  exact (not_le_of_gt (hsmall j)) (hj.trans (hele j))

/-- A height-one ideal stable under all partial derivatives has no additional relations. -/
theorem eq_span_X_pow_of_pderiv_mem (I : Ideal (MvPolynomial σ k))
    (hp : ∀ i, (X i : MvPolynomial σ k) ^ p ∈ I)
    (h0 : ∀ f ∈ I, f.coeff 0 = 0)
    (hd : ∀ i f, f ∈ I → pderiv i f ∈ I) :
    I = Ideal.span (Set.range (fun i : σ ↦ (X i : MvPolynomial σ k) ^ p)) := by
  have h : ∀ n : ℕ, ∀ f : MvPolynomial σ k, f.totalDegree = n → f ∈ I →
      f ∈ Ideal.span (Set.range (fun i : σ ↦ (X i : MvPolynomial σ k) ^ p)) := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
      intro f hn hf
      apply mem_span_X_pow_of_pderiv_mem p f (h0 f hf)
      intro i
      by_cases hz : pderiv i f = 0
      · rw [hz]
        exact Ideal.zero_mem _
      · exact ih _ (hn ▸ totalDegree_pderiv_lt hz) _ rfl (hd i f hf)
  apply le_antisymm
  · exact fun f hf ↦ h _ f rfl hf
  · exact Ideal.span_le.mpr (by rintro _ ⟨i, rfl⟩; exact hp i)

end MvPolynomial
