/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GaloisRepresentation.HardlyRamified.Chebotarev.GeneratorPrimes
public import FLT.GaloisRepresentation.HardlyRamified.Chebotarev.NonsplitBound
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Degree-one primes with generating Frobenius

Leaf W2 of `docs/CHEBOTAREV_PLAN.md`, conditional only on the explicitly
quantified W1 statement. Removing higher-degree primes preserves the positive
generator density, and the primes above finitely many excluded or ramified
rational primes form a finite set.

`Generators` lives in `GeneratorPrimes.lean`, since `Generators.lean` already
contains the group-theoretic inclusion-exclusion of H1. The separate W1 worker
can import this definition when the two leaves are integrated.
-/

@[expose] public section

noncomputable section

open NumberField

universe u v

namespace GaloisRepresentation.Chebotarev

/-- A prime has degree one over the rationals when its absolute norm is prime. -/
def DegreeOne (F : Type*) [Field F] [NumberField F] (v : Prime F) : Prop :=
  (norm v).Prime

/-- A rational prime ideal has prime absolute norm. -/
theorem prime_norm_rational (v : Prime ℚ) : (norm v).Prime := by
  let e := Rat.ringOfIntegersEquiv.symm
  have he : e.toRingHom = algebraMap ℤ (𝓞 ℚ) := Subsingleton.elim _ _
  let eqv := Ideal.quotientEquiv (v.asIdeal.under ℤ) v.asIdeal e (by
    change v.asIdeal = Ideal.map e.toRingHom (v.asIdeal.under ℤ)
    rw [he, Ideal.under_def, Ideal.map_comap_of_surjective _ (he ▸ e.surjective)])
  have hn : (v.asIdeal.under ℤ).absNorm = norm v := Nat.card_congr eqv.toEquiv
  rw [← hn]
  exact Nat.absNorm_under_prime v.asIdeal

/-- Outside the higher-degree set, the absolute norm is a rational prime. -/
theorem degreeOne_of_not_mem_higherDegree (F : Type*) [Field F] [NumberField F]
    (v : Prime F) (hv : v ∉ HigherDegree ℚ F) : DegreeOne F v := by
  have hp := Ideal.inertiaDeg_pos v.asIdeal (𝓞 ℚ)
  have hlt : ¬ 2 ≤ v.asIdeal.inertiaDeg (𝓞 ℚ) := fun h ↦
    hv ⟨primeBelow ℚ F v, rfl, h⟩
  have hf : v.asIdeal.inertiaDeg (𝓞 ℚ) = 1 := by omega
  let : v.asIdeal.LiesOver (primeBelow ℚ F v).asIdeal := ⟨rfl⟩
  have hn := Ideal.absNorm_pow_inertiaDeg (primeBelow ℚ F v).asIdeal v.asIdeal
  rw [hf, pow_one] at hn
  change v.asIdeal.absNorm.Prime
  rw [← hn]
  exact prime_norm_rational (primeBelow ℚ F v)

/-- The precise cyclic generator-density input W1, with all field and group
hypotheses explicit. This is a proposition, not an axiom or an instance. -/
def W1Statement : Prop :=
  ∀ (K : Type u) (L : Type v) [Field K] [NumberField K] [Field L] [NumberField L]
    [Algebra K L] [IsGalois K L] [IsCyclic Gal(L/K)],
    LogDensity (Generators K L)
      ((Nat.totient (Nat.card Gal(L/K)) : ℝ) / Nat.card Gal(L/K))

variable (F : Type u) (L : Type v) [Field F] [NumberField F] [Field L] [NumberField L]
  [Algebra F L] [IsGalois F L]

/-- Positive generator density yields degree-one generators outside every
finite rational exclusion, also unramified in the top field over the rationals. -/
theorem exists_degreeOne_generator_of_logDensity
    (hdensity : LogDensity (Generators F L)
      ((Nat.totient (Nat.card Gal(L/F)) : ℝ) / Nat.card Gal(L/F)))
    (S : Finset (Prime ℚ)) (N : ℕ) :
    ∃ v : Prime F, v ∈ Generators F L ∧ DegreeOne F v ∧ N ≤ norm v ∧
      ∀ u : Prime ℚ, v.asIdeal.under (𝓞 ℚ) = u.asIdeal →
        u ∉ S ∧ Unram ℚ L u := by
  classical
  let bad : Set (Prime ℚ) := (S : Set (Prime ℚ)) ∪ {u | ¬ Unram ℚ L u}
  have hbad : bad.Finite := S.finite_toSet.union (finite_ramified ℚ L)
  have habove : (primeBelow ℚ F ⁻¹' bad).Finite :=
    hbad.preimage' fun u _ ↦ finite_primeBelow_fiber ℚ F u
  have hd : 0 < (Nat.totient (Nat.card Gal(L/F)) : ℝ) / Nat.card Gal(L/F) := by
    exact div_pos (Nat.cast_pos.mpr (Nat.totient_pos.mpr Nat.card_pos))
      (Nat.cast_pos.mpr Nat.card_pos)
  have hrem := logDensity_diff (_root_.Chebotarev.summable_primeNorm F)
    (Generators F L) (HigherDegree ℚ F) _ hdensity (higherDegree_primeSum_bounded ℚ F)
  obtain ⟨v, hv, hbadV, hN⟩ := exists_norm_ge_of_logDensity_pos _ _ hd hrem
    habove.toFinset N
  refine ⟨v, hv.1, degreeOne_of_not_mem_higherDegree F v hv.2, hN, ?_⟩
  intro u hu
  have hbelow : primeBelow ℚ F v = u :=
    IsDedekindDomain.HeightOneSpectrum.asIdeal_injective hu
  have huBad : u ∉ bad := by
    intro h
    apply hbadV
    exact habove.mem_toFinset.mpr (by simpa only [Set.mem_preimage, hbelow] using h)
  exact ⟨fun h ↦ huBad (Or.inl h), by
    by_contra h
    exact huBad (Or.inr h)⟩

/-- W2: in the fixed field of the subgroup generated by `g`, there are
arbitrarily large degree-one generator primes avoiding any finite rational
set and every rational prime ramified in `L`. W1 is the sole explicit input. -/
theorem exists_degreeOne_generator [IsGalois ℚ L] (g : Gal(L/ℚ))
    (hW1 : W1Statement.{v, v}) (S : Finset (Prime ℚ)) (N : ℕ) :
    let F := IntermediateField.fixedField (Subgroup.zpowers g)
    ∃ v : Prime F, v ∈ Generators F L ∧ DegreeOne F v ∧ N ≤ norm v ∧
      ∀ u : Prime ℚ, v.asIdeal.under (𝓞 ℚ) = u.asIdeal →
        u ∉ S ∧ Unram ℚ L u := by
  let F := IntermediateField.fixedField (Subgroup.zpowers g)
  let e := IntermediateField.subgroupEquivAlgEquiv (Subgroup.zpowers g)
  let : IsCyclic Gal(L/F) := isCyclic_of_surjective e e.surjective
  exact exists_degreeOne_generator_of_logDensity F L (hW1 (↥F) L) S N

end GaloisRepresentation.Chebotarev
