/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GaloisRepresentation.HardlyRamified.Chebotarev.FrobeniusOrder
public import Mathlib.FieldTheory.Galois.Basic

/-!
# The degree-one generator input to W3

`W2Statement` is precisely the W2 statement in `docs/CHEBOTAREV_PLAN.md`,
universally quantified over finite Galois number fields and their automorphisms.
The predicates `Generators` and `DegreeOne` are expanded here to avoid depending
on definitions under development in the parallel W1/W2 leaves. This file asserts
no arithmetic theorem: W3 takes this proposition as an explicit hypothesis.
-/

@[expose] public section

open NumberField

namespace GaloisRepresentation.Chebotarev

/-- W2: in the fixed field of the cyclic subgroup generated by `g`, there is
a degree-one prime with generating Frobenius, above an allowed rational prime
unramified in `L`, and with arbitrarily large norm. -/
def W2Statement : Prop :=
  ∀ (L : Type*) [Field L] [NumberField L] [IsGalois ℚ L] (g : Gal(L/ℚ))
    (S : Finset (Prime ℚ)) (N : ℕ),
    let F := IntermediateField.fixedField (Subgroup.zpowers g)
    ∃ v : Prime F,
      (Unram F L v ∧ Subgroup.zpowers (frob F L v) = ⊤) ∧
      Nat.Prime v.asIdeal.absNorm ∧ N ≤ v.asIdeal.absNorm ∧
      ∀ u : Prime ℚ, v.asIdeal.under (𝓞 ℚ) = u.asIdeal →
        u ∉ S ∧ Unram ℚ L u

end GaloisRepresentation.Chebotarev
