module

public import Mathlib.NumberTheory.Cyclotomic.Basic
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal

@[expose] public section

open FiniteDimensional Polynomial Algebra Nat Finset Fintype

variable (p : ℕ) (L : Type*) [Field L] [CharZero L] [IsCyclotomicExtension {p} ℚ L]

section IntFacts

open scoped NumberField

open Ideal IsCyclotomicExtension

theorem exists_int_sub_pow_prime_dvd {A : Type*} [CommRing A] [IsCyclotomicExtension {p} ℤ A]
    [hp : Fact p.Prime] (a : A) : ∃ m : ℤ, a ^ p - m ∈ span ({(p : A)} : Set A) := by
  refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ (adjoin_roots (S := {p}) (A := ℤ) a)
  · intro x hx
    use 1
    simp_all
  · intro r
    use r ^ p
    simp
  · rintro x y _ _ ⟨b, hb⟩ ⟨c, hc⟩
    obtain ⟨r, hr⟩ := exists_add_pow_prime_eq hp.out x y
    rw [mul_assoc, mul_assoc] at hr
    rw [hr]
    use c + b
    push_cast
    rw [sub_add_eq_sub_sub, sub_eq_add_neg, sub_eq_add_neg, add_comm (x ^ p + _), add_assoc,
      add_assoc]
    apply Ideal.add_mem _ _
    · convert Ideal.add_mem _ hb hc using 1
      ring
    · rw [mem_span_singleton]
      exact dvd_mul_right _ _
  · rintro x y _ _ ⟨b, hb⟩ ⟨c, hc⟩
    rw [mul_pow]
    use b * c
    have := Ideal.mul_mem_left _ (x ^ p) hc
    rw [mul_sub] at this
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub] at this hb ⊢
    convert this using 2
    rw [Int.cast_mul, _root_.map_mul, _root_.map_mul]
    congr 1
    exact (sub_eq_zero.mp hb).symm

local notation "R" => 𝓞 (CyclotomicField p ℚ)

/-- The principal ideal generated by `x + y ζ^i` for integer `x` and `y` -/
@[nolint unusedArguments]
noncomputable
def fltIdeals [Fact p.Prime] (x y : ℤ) {η : R} (_ : η ∈ nthRootsFinset p 1) : Ideal R :=
  Ideal.span ({x + η * y} : Set R)

variable {p}

theorem mem_fltIdeals [Fact p.Prime] (x y : ℤ) {η : R} (hη : η ∈ nthRootsFinset p 1) :
    ↑x + η * ↑y ∈ fltIdeals p x y hη :=
  mem_span_singleton.mpr dvd_rfl

open IsPrimitiveRoot

theorem prim_coe (ζ : R) (hζ : IsPrimitiveRoot ζ p) :
    IsPrimitiveRoot (ζ : CyclotomicField p ℚ) p :=
  coe_submonoidClass_iff.mpr hζ

theorem aux_lem_flt [Fact p.Prime] {x y z : ℤ} (H : x ^ p + y ^ p = z ^ p)
    (caseI : ¬↑p ∣ x * y * z) : ¬(p : ℤ) ∣ (x + y : ℤ) := by
  intro habs
  replace habs : ↑p ∣ (x + y : ℤ) := by simpa using habs
  rw [← ZMod.intCast_zmod_eq_zero_iff_dvd, Int.cast_add] at habs
  replace H := congr_arg (fun x : ℤ => (x : ZMod p)) H.symm
  simp only [Int.cast_add, Int.cast_pow, ZMod.pow_card, habs,
    ZMod.intCast_zmod_eq_zero_iff_dvd] at H
  exact caseI (Dvd.dvd.mul_left H _)

section NeZero

variable [NeZero p]

set_option backward.isDefEq.respectTransparency false in
instance : IsGalois ℚ (CyclotomicField p ℚ) :=
  IsCyclotomicExtension.isGalois {p} _ _

set_option backward.isDefEq.respectTransparency false in
instance : FiniteDimensional ℚ (CyclotomicField p ℚ) :=
  IsCyclotomicExtension.finiteDimensional {p} _ _

set_option backward.isDefEq.respectTransparency false in
instance : NumberField (CyclotomicField p ℚ) :=
  IsCyclotomicExtension.numberField {p} ℚ _

end NeZero

set_option backward.isDefEq.respectTransparency false in
theorem zeta_sub_one_dvb_p [Fact p.Prime] {η : R} (hη : η ∈ nthRootsFinset p 1)
    (hne1 : η ≠ 1) : 1 - η ∣ (p : R) := by
  have hη : IsPrimitiveRoot (η : CyclotomicField p ℚ) (p ^ 1) := by
    simpa using prim_coe η (isPrimitiveRoot_of_mem_nthRootsFinset Fact.out hη hne1)
  have : IsCyclotomicExtension {p ^ (0 + 1)} ℚ (CyclotomicField p ℚ) := by
    simp only [zero_add, pow_one]
    infer_instance
  convert neg_dvd.2 <| mem_span_singleton.1 <| Rat.p_mem_span_zeta_sub_one p 0 hη using 1
  ext
  simp

set_option backward.isDefEq.respectTransparency false in
theorem one_sub_zeta_prime [Fact p.Prime] {η : R} (hη : η ∈ nthRootsFinset p 1)
    (hne1 : η ≠ 1) : Prime (1 - η) := by
  have h := prim_coe η (isPrimitiveRoot_of_mem_nthRootsFinset Fact.out hη hne1)
  simpa using! h.zeta_sub_one_prime'.neg

theorem diff_of_roots [hp : Fact p.Prime] (ph : 5 ≤ p) {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1) (hη₂ : η₂ ∈ nthRootsFinset p 1) (hdiff : η₁ ≠ η₂)
    (hwlog : η₁ ≠ 1) : ∃ u : Rˣ, η₁ - η₂ = u * (1 - η₁) := by
  have _ : 2 ≤ p := le_trans (by decide) ph
  have h := isPrimitiveRoot_of_mem_nthRootsFinset Fact.out hη₁ hwlog
  rcases h.nthRootsFinset_pairwise_associated_sub_one_sub_of_prime hp.out hη₁ hη₂ hdiff with ⟨u, hu⟩
  refine ⟨-u, by grind [Units.val_neg]⟩

theorem diff_of_roots2 [Fact p.Prime] (ph : 5 ≤ p) {η₁ η₂ : R} (hη₁ : η₁ ∈ nthRootsFinset p 1)
    (hη₂ : η₂ ∈ nthRootsFinset p 1) (hdiff : η₁ ≠ η₂) (hwlog : η₁ ≠ 1) :
    ∃ u : Rˣ, η₂ - η₁ = u * (1 - η₁) := by
  obtain ⟨u, hu⟩ := diff_of_roots ph hη₁ hη₂ hdiff hwlog
  exact ⟨-u, by simp [← hu]⟩

lemma fltIdeals_coprime2_lemma [Fact p.Prime] (ph : 5 ≤ p) {x y : ℤ} {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1)
    (hη₂ : η₂ ∈ nthRootsFinset p 1) (hdiff : η₁ ≠ η₂) (hp : IsCoprime x y)
    (hp2 : ¬(p : ℤ) ∣ (x + y : ℤ)) (hwlog : η₁ ≠ 1) :
    (fltIdeals p x y hη₁) ⊔ (fltIdeals p x y hη₂) = ⊤ := by
  apply by_contradiction
  intro h
  let I := fltIdeals p x y hη₁ ⊔ fltIdeals p x y hη₂
  obtain ⟨P, hP1, hP2⟩ := exists_le_maximal I h
  have hiP : fltIdeals p x y hη₁ ≤ P := le_trans le_sup_left hP2
  have hel1 : ∃ v : Rˣ, (v : R) * y * (1 - η₁) ∈ I := by
    obtain ⟨v, hv⟩ := diff_of_roots ph hη₁ hη₂ hdiff hwlog
    refine ⟨v, ?_⟩
    have := Ideal.sub_mem _
      (mem_sup_left (mem_fltIdeals x y hη₁)) (mem_sup_right (mem_fltIdeals x y hη₂))
    rwa [add_sub_add_left_eq_sub, ← sub_mul, hv, mul_right_comm] at this
  have hel2 : ∃ v : Rˣ, (v : R) * x * (1 - η₁) ∈ I := by
    obtain ⟨v, hv⟩ := diff_of_roots2 ph hη₁ hη₂ hdiff hwlog
    refine ⟨v, ?_⟩
    have := Ideal.add_mem _ (mul_mem_left _ η₂ (mem_sup_left (mem_fltIdeals x y hη₁)))
        (mul_mem_left _ (-η₁) (mem_sup_right (mem_fltIdeals x y hη₂)))
    have h1 : η₂ * (↑x + η₁ * ↑y) + -η₁ * (↑x + η₂ * ↑y) = (η₂ - η₁) * x := by ring
    rwa [h1, hv, mul_right_comm] at this
  have hel11 : (y : R) * (1 - η₁) ∈ P := by
    obtain ⟨v, hv⟩ := hel1
    rw [mul_assoc] at hv
    exact (unit_mul_mem_iff_mem P v.isUnit).1 (hP2 hv)
  have hel22 : (x : R) * (1 - η₁) ∈ P := by
    obtain ⟨v, hv⟩ := hel2
    rw [mul_assoc] at hv
    exact (unit_mul_mem_iff_mem P v.isUnit).1 (hP2 hv)
  have hPrime := hP1.isPrime
  have hprime2 := IsPrime.mem_or_mem hPrime hel11
  have hprime3 := IsPrime.mem_or_mem hPrime hel22
  have HC : 1 - η₁ ∈ P → False := by
    intro h
    have eta_sub_one_ne_zero := sub_ne_zero.mpr (Ne.symm hwlog)
    have hηprime : IsPrime (Ideal.span ({1 - η₁} : Set R)) := by
      rw [span_singleton_prime eta_sub_one_ne_zero]
      apply one_sub_zeta_prime hη₁ hwlog
    have H5 : IsPrime (Ideal.span ({(p : ℤ)} : Set ℤ)) := by
      have h2 : (p : ℤ) ≠ 0 := by simp [NeZero.ne p]
      have h1 : Prime (p : ℤ) := by
        rw [← prime_iff_prime_int]
        exact Fact.out
      rw [span_singleton_prime h2]
      apply h1
    have hηP : Ideal.span ({1 - η₁} : Set R) = P := by
      have hle : Ideal.span ({1 - η₁} : Set R) ≤ P := by
        rw [span_le]
        simp [h]
      apply (@Ring.DimensionLeOne.prime_le_prime_iff_eq _ _ _ _ _ hηprime hPrime _).1 hle
      intro hbot
      rw [span_eq_bot] at hbot
      simp only [Set.mem_singleton_iff, forall_eq, sub_eq_zero] at hbot
      exact hwlog hbot.symm
    have hcapZ : P.comap (Int.castRingHom R) = Ideal.span ({(p : ℤ)} : Set ℤ) := by
      have H1 : Ideal.span ({(p : ℤ)} : Set ℤ) ≤ P.comap (Int.castRingHom R) := by
        rw [← hηP]
        apply le_comap_of_map_le _
        rw [map_span]
        simp only [eq_intCast, Set.image_singleton, Int.cast_natCast]
        rw [span_singleton_le_span_singleton]
        apply zeta_sub_one_dvb_p hη₁ hwlog
      have H2 : IsPrime (P.comap (Int.castRingHom R)) := IsPrime.comap _
      have H4 : Ideal.span ({(p : ℤ)} : Set ℤ) ≠ ⊥ := by simp [NeZero.ne p]
      apply ((@Ring.DimensionLeOne.prime_le_prime_iff_eq _ _ _ _ _ H5 H2 H4).1 H1).symm
    have hxyinP : (x + y : R) ∈ P := by
      have H1 : (x : R) + η₁ * y ∈ P := by
        apply hiP
        apply Submodule.mem_span_singleton_self
      have H2 : η₁ * y = y - y * (1 - η₁) := by ring
      rw [H2] at H1
      have H3 : ↑x + (↑y - ↑y * (1 - η₁)) = ↑x + ↑y + -↑y * (1 - η₁) := by ring
      rw [H3] at H1
      have H4 : -↑y * (1 - η₁) ∈ P := by
        rw [← hηP, Ideal.mem_span_singleton']
        exact ⟨-(y : R), rfl⟩
      apply (Ideal.add_mem_iff_left P H4).1 H1
    have hxyinP2 : x + y ∈ Ideal.span ({(p : ℤ)} : Set ℤ) := by
      rw [← hcapZ]
      simp [hxyinP]
    rw [mem_span_singleton] at hxyinP2
    apply absurd hxyinP2 hp2
  rcases hprime2 with hprime2 | hprime2
  · rcases hprime3 with hprime3 | hprime3
    · obtain ⟨a, b, hab⟩ := hp
      have hone := P.add_mem (Ideal.mul_mem_left P a hprime3) (Ideal.mul_mem_left P b hprime2)
      norm_cast at hone
      rw [hab] at hone
      norm_cast at hone
      rw [← eq_top_iff_one] at hone
      have hcontra := IsPrime.ne_top hPrime
      rw [hone] at hcontra
      simp only [Ne, not_true] at hcontra
    apply HC hprime3
  · apply HC hprime2

theorem fltIdeals_coprime2 [Fact p.Prime] (ph : 5 ≤ p) {x y : ℤ} {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1)
    (hη₂ : η₂ ∈ nthRootsFinset p 1) (hdiff : η₁ ≠ η₂) (hp : IsCoprime x y)
    (hp2 : ¬(p : ℤ) ∣ (x + y : ℤ)) (hwlog : η₁ ≠ 1) :
    IsCoprime (fltIdeals p x y hη₁) (fltIdeals p x y hη₂) := by
  rw [Ideal.isCoprime_iff_add]
  simpa using fltIdeals_coprime2_lemma ph hη₁ hη₂ hdiff hp hp2 hwlog

theorem fltIdeals_coprime (hpri : p.Prime) (p5 : 5 ≤ p) {x y z : ℤ}
    (H : x ^ p + y ^ p = z ^ p) {η₁ η₂ : R} (hxy : IsCoprime x y)
    (hη₁ : η₁ ∈ nthRootsFinset p 1) (hη₂ : η₂ ∈ nthRootsFinset p 1) (hdiff : η₁ ≠ η₂)
    (caseI : ¬↑p ∣ x * y * z) :
    have : Fact p.Prime := ⟨hpri⟩
    IsCoprime (fltIdeals p x y hη₁) (fltIdeals p x y hη₂) := by
  have : Fact p.Prime := ⟨hpri⟩
  by_cases h : η₁ ≠ 1
  · apply fltIdeals_coprime2 p5 hη₁ hη₂ hdiff hxy (aux_lem_flt H caseI) h
  · have h2 : η₂ ≠ 1 := by
      simp only [ne_eq, not_not] at h
      rw [h] at hdiff
      exact hdiff.symm
    have := fltIdeals_coprime2 p5 hη₂ hη₁ hdiff.symm hxy (aux_lem_flt H caseI) h2
    exact this.symm

variable {L}

theorem dvd_last_coeff_cycl_integer [hp : Fact p.Prime] {ζ : 𝓞 L}
    (hζ : IsPrimitiveRoot ζ p) {f : Fin p → ℤ}
    (hf : ∃ i, f i = 0) {m : ℤ} (hdiv : ↑m ∣ ∑ j, f j • ζ ^ (j : ℕ)) :
    m ∣ f ⟨p.pred, pred_lt hp.out.ne_zero⟩ := by
  obtain ⟨i, Hi⟩ := hf
  have hlast :
    (Fin.castOrderIso (succ_pred_prime hp.out)) (Fin.last p.pred) =
    ⟨p.pred, pred_lt hp.out.ne_zero⟩ := Fin.ext rfl
  let ζ' := (ζ : L)
  have hζ' : IsPrimitiveRoot ζ' p := IsPrimitiveRoot.coe_submonoidClass_iff.2 hζ
  set b := hζ'.integralPowerBasis with hb
  have hdim : b.dim = p.pred := by rw [hζ'.integralPowerBasis_dim, totient_prime hp.out,
    pred_eq_sub_one]
  by_cases H : i = ⟨p - 1, pred_lt hp.out.ne_zero⟩
  · simp [H.symm, Hi]
  have hi : ↑i < p - 1 := by
    by_contra! habs
    simp [le_antisymm habs (le_pred_of_lt (Fin.is_lt i))] at H
  obtain ⟨y, hy⟩ := hdiv
  rw [← Equiv.sum_comp (Fin.castOrderIso (succ_pred_prime hp.out)).toEquiv,
    Fin.sum_univ_castSucc] at hy
  simp only [hlast, RelIso.coe_fn_toEquiv, Fin.val_mk] at hy
  rw [hζ.pow_sub_one_eq hp.out.one_lt, ← sum_neg_distrib, smul_sum, sum_range, ← sum_add_distrib,
    ← (Fin.castOrderIso hdim).toEquiv.sum_comp] at hy
  simp only [RelIso.coe_fn_toEquiv, Fin.val_castSucc, Fin.coe_orderIso_apply] at hy
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [smul_neg]
    congr; congr; rfl; congr
    rw [show ζ = hζ'.toInteger from rfl, ← hζ'.integralPowerBasis_gen, ← hb]
    rfl; rfl; congr; congr; rfl; congr
    rw [show ζ = hζ'.toInteger from rfl, ← hζ'.integralPowerBasis_gen, ← hb]
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [← show ∀ y, _ = _ from fun y => congr_fun b.coe_basis y, ← sub_eq_add_neg]
  rw [sum_sub_distrib] at hy
  replace hy := congr_arg (b.basis.coord ((Fin.castOrderIso hdim.symm) ⟨i, hi⟩)) hy
  rw [← b.basis.equivFun_symm_apply, ← b.basis.equivFun_symm_apply, LinearMap.map_sub,
    b.basis.coord_equivFun_symm, b.basis.coord_equivFun_symm, ← smul_eq_mul,
    Int.cast_smul_eq_zsmul] at hy
  obtain ⟨n, hn⟩ := b.basis.dvd_coord_smul ((Fin.castOrderIso hdim.symm) ⟨i, hi⟩) y m
  rw [hn] at hy
  simp only [Fin.castOrderIso_apply, Fin.cast_mk, Fin.castSucc_mk, Fin.eta, Hi, zero_sub,
    neg_eq_iff_eq_neg] at hy
  rw [hy]
  simp [dvd_neg]

theorem dvd_coeff_cycl_integer (hp : p.Prime) {ζ : 𝓞 L} (hζ : IsPrimitiveRoot ζ p)
    {f : Fin p → ℤ} (hf : ∃ i, f i = 0) {m : ℤ} (hdiv : ↑m ∣ ∑ j, f j • ζ ^ (j : ℕ)) :
    ∀ j, m ∣ f j := by
  let ζ' := (ζ : L)
  have : Fact p.Prime := ⟨hp⟩
  have hζ' : IsPrimitiveRoot ζ' p := IsPrimitiveRoot.coe_submonoidClass_iff.2 hζ
  have hlast : (Fin.castOrderIso (succ_pred_prime hp)) (Fin.last p.pred) =
      ⟨p.pred, pred_lt hp.ne_zero⟩ := Fin.ext rfl
  set b := hζ'.integralPowerBasis with hb
  have hdim : b.dim = p.pred := by rw [hζ'.integralPowerBasis_dim, totient_prime hp,
    pred_eq_sub_one]
  have last_dvd := dvd_last_coeff_cycl_integer hζ hf hdiv
  intro j
  by_cases H : j = ⟨p - 1, pred_lt hp.ne_zero⟩
  · simpa [H] using last_dvd
  have hj : ↑j < p - 1 := by
    by_contra! habs
    simp [le_antisymm habs (le_pred_of_lt (Fin.is_lt j))] at H
  obtain ⟨y, hy⟩ := hdiv
  rw [← Equiv.sum_comp (Fin.castOrderIso (succ_pred_prime hp)).toEquiv, Fin.sum_univ_castSucc] at hy
  simp only [hlast, RelIso.coe_fn_toEquiv, Fin.val_mk] at hy
  rw [hζ.pow_sub_one_eq hp.one_lt, ← sum_neg_distrib, smul_sum, sum_range, ← sum_add_distrib,
    ← (Fin.castOrderIso hdim).toEquiv.sum_comp] at hy
  simp only [RelIso.coe_fn_toEquiv, Fin.val_castSucc, Fin.coe_orderIso_apply] at hy
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [smul_neg]
    congr; congr; rfl; congr
    rw [show ζ = hζ'.toInteger from rfl, ← hζ'.integralPowerBasis_gen, ← hb]
    rfl; rfl; congr; congr; rfl; congr
    rw [show ζ = hζ'.toInteger from rfl, ← hζ'.integralPowerBasis_gen, ← hb]
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [← show ∀ y, _ = _ from fun y => congr_fun b.coe_basis y, ← sub_eq_add_neg]
  rw [sum_sub_distrib] at hy
  replace hy := congr_arg (b.basis.coord ((Fin.castOrderIso hdim.symm) ⟨j, hj⟩)) hy
  rw [← b.basis.equivFun_symm_apply, ← b.basis.equivFun_symm_apply, LinearMap.map_sub,
    b.basis.coord_equivFun_symm, b.basis.coord_equivFun_symm] at hy
  simp only [Fin.castOrderIso_apply, Fin.cast_mk, Fin.castSucc_mk, Fin.eta,
    Module.Basis.coord_apply, sub_eq_iff_eq_add] at hy
  obtain ⟨n, hn⟩ := b.basis.dvd_coord_smul ((Fin.cast hdim.symm) ⟨j, hj⟩) y m
  rw [hy, ← smul_eq_mul, Int.cast_smul_eq_zsmul, ← b.basis.coord_apply, ← Fin.cast_mk hdim.symm _
    hj, hn]
  exact dvd_add (dvd_mul_right _ _) last_dvd

end IntFacts
