/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.AmpleCommonDegree
public import FLT.Mazur.GlobalEvaluationSpan

/-!
# A globally generated positive power of an ample line bundle

The common-degree affine section cover gives a finite family whose actual
free-sheaf evaluation is epimorphic.
-/

@[expose] public noncomputable section
open CategoryTheory AlgebraicGeometry
open Scheme.Modules
universe u
namespace FLT.Mazur.FCurve
open ProjectiveSpace ModuleLineBundleTensorPullback
variable {X : Scheme.{u}} {L : X.Modules}

/-- An ample line bundle has a positive power generated by a finite global family. -/
theorem AmpleLineBundle.exists_positive_finite_evaluation (hL : AmpleLineBundle L) :
    ∃ (n : ℕ), 0 < n ∧ ∃ (κ : Type u) (_ : Finite κ)
      (s : κ → Γ(tensorPower L n, ⊤)), Epi (globalEvaluation (tensorPower L n) s) := by
  obtain ⟨κ, hκ, n, hn, s, _, hcover⟩ := hL.common_degree_section_cover
  refine ⟨n, hn, κ, hκ, s, ?_⟩
  exact globalEvaluation_epi_of_sectionHom_isIso s
    (fun i ↦ sectionGeneratorOpen (tensorPower L n) (s i)) hcover id
    (fun i ↦ sectionHom_generatorOpen_isIso (tensorPower L n) (s i))

/-- In some positive degree an ample line bundle is generated by all global sections. -/
theorem AmpleLineBundle.exists_positive_globalEvaluation (hL : AmpleLineBundle L) :
    ∃ (n : ℕ), 0 < n ∧ Epi (globalEvaluation (tensorPower L n)
      (fun s : Γ(tensorPower L n, ⊤) ↦ s)) := by
  obtain ⟨n, hn, κ, _, s, hs⟩ := hL.exists_positive_finite_evaluation
  exact ⟨n, hn, GlobalEvaluationSpan.all_epi_of_epi s⟩

end FLT.Mazur.FCurve
