/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.BlowupReesGrading
public import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal

/-!
# Degree-one generators of the actual Rees irrelevant ideal

Every positive-degree monomial is a sum of products of a degree-one center
monomial with a Rees monomial. Consequently the irrelevant ideal is generated
by the original center, without finiteness or regularity assumptions.
-/

@[expose] public noncomputable section

open Polynomial

namespace FLT.Mazur.BlowupRees

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

variable {A : Type*} [CommRing A] (I : Ideal A)

/-- An ideal containing the center monomials contains every positive homogeneous piece. -/
theorem component_le_of_generators (J : Ideal (reesAlgebra I))
    (hJ : ∀ a (ha : a ∈ I), generator I a ha ∈ J) (n : ℕ) (hn : 0 < n)
    (p : reesAlgebra I) (hp : p ∈ component I n) : p ∈ J := by
  obtain ⟨n, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hn.ne'
  obtain ⟨⟨a, ha⟩, rfl⟩ := hp
  have ha' : a ∈ I * I ^ n := by simpa only [pow_succ'] using ha
  suffices h : ∃ ha : a ∈ I ^ (n + 1), monomialMap I (n + 1) ⟨a, ha⟩ ∈ J by
    exact h.choose_spec
  refine Submodule.mul_induction_on ha' ?_ ?_
  · intro a ha b hb
    have hab : a * b ∈ I ^ (n + 1) := by
      rw [pow_succ']; exact Ideal.mul_mem_mul ha hb
    refine ⟨hab, ?_⟩
    have he : monomialMap I (n + 1) ⟨a * b, hab⟩ =
        generator I a ha * monomialMap I n ⟨b, hb⟩ := by
      apply Subtype.ext
      change Polynomial.monomial (n + 1) (a * b) =
        Polynomial.monomial 1 a * Polynomial.monomial n b
      simpa only [Nat.one_add] using
        (Polynomial.monomial_mul_monomial 1 n a b).symm
    rw [he]
    exact J.mul_mem_right _ (hJ a ha)
  · intro a b iha ihb
    obtain ⟨ha, hma⟩ := iha
    obtain ⟨hb, hmb⟩ := ihb
    refine ⟨Ideal.add_mem _ ha hb, ?_⟩
    change monomialMap I (n + 1) (⟨a, ha⟩ + ⟨b, hb⟩) ∈ J
    rw [map_add]
    exact J.add_mem hma hmb

/-- Containing the original degree-one center monomials suffices for the irrelevant ideal. -/
theorem irrelevant_le_of_generators (J : Ideal (reesAlgebra I))
    (hJ : ∀ a (ha : a ∈ I), generator I a ha ∈ J) :
    (HomogeneousIdeal.irrelevant (component I)).toIdeal ≤ J := by
  apply (HomogeneousIdeal.toIdeal_irrelevant_le (component I)).mpr
  intro n hn p hp
  exact component_le_of_generators I J hJ n hn p hp

/-- The actual Rees irrelevant ideal is generated by all original center monomials. -/
theorem irrelevant_eq_span_generators :
    (HomogeneousIdeal.irrelevant (component I)).toIdeal =
      Ideal.span (Set.range (fun a : I => generator I a a.property)) := by
  apply le_antisymm
  · exact irrelevant_le_of_generators I _ fun a ha =>
      Ideal.subset_span ⟨⟨a, ha⟩, rfl⟩
  · apply Ideal.span_le.mpr
    rintro _ ⟨a, rfl⟩
    exact HomogeneousIdeal.mem_irrelevant_of_mem (component I) (by decide : 0 < 1)
      (generator_mem I a a.property)

end FLT.Mazur.BlowupRees
