/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.RingTheory.ReesAlgebra
public import Mathlib.RingTheory.Localization.Away.Basic

/-!
# Affine fraction algebras of the Rees algebra

Evaluate the Rees parameter at 1/f in A[1/f]. The image is exactly A[I/f],
the fraction algebra used for the f-chart of a blowup. This construction
retains the original ideal and works without a domain hypothesis.
-/

@[expose] public noncomputable section

open Polynomial

namespace FLT.Mazur.BlowupFractionChart

set_option backward.isDefEq.respectTransparency false

variable {A : Type*} [CommRing A] (I : Ideal A) (f : A)

/-- Evaluation of the actual Rees algebra at the inverse chart denominator. -/
def evaluation : reesAlgebra I →ₐ[A] Localization.Away f :=
  (aeval (IsLocalization.Away.invSelf f)).comp (reesAlgebra I).val

/-- The actual Rees evaluation image, viewed inside the original principal localization. -/
def chart : Subalgebra A (Localization.Away f) := (evaluation I f).range

/-- A degree-one Rees element evaluates to its coefficient divided by f. -/
theorem evaluation_degreeOne (a : A) (ha : a ∈ I) :
    evaluation I f ⟨monomial 1 a, reesAlgebra.monomial_mem.mpr (by simpa using ha)⟩ =
      algebraMap A (Localization.Away f) a * IsLocalization.Away.invSelf f := by
  change aeval _ (monomial 1 a) = _
  rw [aeval_monomial, pow_one]

/-- The Rees image is precisely the fraction algebra generated by I/f. -/
theorem chart_eq_adjoin : chart I f = Algebra.adjoin A
    ((fun a : A => algebraMap A (Localization.Away f) a *
      IsLocalization.Away.invSelf f) '' (I : Set A)) := by
  rw [chart, evaluation, Subalgebra.range_comp_val, ← adjoin_monomial_eq_reesAlgebra,
    AlgHom.map_adjoin]
  congr 1
  ext z
  constructor
  · rintro ⟨p, ⟨a, ha, rfl⟩, rfl⟩
    exact ⟨a, ha, by simp only [aeval_monomial, pow_one]⟩
  · rintro ⟨a, ha, rfl⟩
    exact ⟨monomial 1 a, ⟨a, ha, rfl⟩, by simp only [aeval_monomial, pow_one]⟩

/-- It suffices to adjoin the ratios of any generating set of the original ideal. -/
theorem chart_span (S : Set A) : chart (Ideal.span S) f = Algebra.adjoin A
    ((fun a : A => algebraMap A (Localization.Away f) a *
      IsLocalization.Away.invSelf f) '' S) := by
  rw [chart_eq_adjoin]
  apply le_antisymm
  · apply Algebra.adjoin_le
    rintro _ ⟨a, ha, rfl⟩
    induction ha using Submodule.span_induction with
    | mem a ha => exact Algebra.subset_adjoin ⟨a, ha, rfl⟩
    | zero =>
      simp only [map_zero, zero_mul]
      exact Subalgebra.zero_mem _
    | add a b ha hb ih ih' =>
      simp only [map_add, add_mul]
      exact Subalgebra.add_mem _ ih ih'
    | smul a b hb ih =>
      simp only [smul_eq_mul, map_mul, mul_assoc]
      exact Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ a) ih
  · apply Algebra.adjoin_mono
    exact Set.image_mono Ideal.subset_span

/-- The denominator itself contributes only 1 when it belongs to the center ideal. -/
theorem denominator_ratio :
    algebraMap A (Localization.Away f) f * IsLocalization.Away.invSelf f = 1 :=
  IsLocalization.Away.mul_invSelf f

end FLT.Mazur.BlowupFractionChart
