/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.CechSortingCoordinates
public import Mathlib.GroupTheory.FreeAbelianGroup

/-!
# Supported integral tuple chains

These are the augmented tuple chains used for a sorting homotopy. Prepending
one vertex contracts the boundary on cycles, including tuples with arbitrary
repetitions. The support lemmas ensure that coning stays within an intersection.
-/

@[expose] public noncomputable section

open scoped BigOperators

universe u

namespace FLT.Mazur.CechSortingHomotopyCoordinates

variable {ι : Type u}

/-- Integral chains on tuples of length `n`; length zero is the augmentation term. -/
abbrev Chains (n : ℕ) := FreeAbelianGroup (Fin n → ι)

/-- The integral alternating deletion boundary. -/
def boundary (n : ℕ) : Chains (ι := ι) (n + 1) →+ Chains (ι := ι) n :=
  FreeAbelianGroup.lift fun a ↦
    ∑ k : Fin (n + 1), (-1 : ℤ) ^ k.val • FreeAbelianGroup.of (a ∘ k.succAbove)

/-- Prepend a vertex to each tuple in an integral chain. -/
def cone (v : ι) (n : ℕ) : Chains (ι := ι) n →+ Chains (ι := ι) (n + 1) :=
  FreeAbelianGroup.map (fun a : Fin n → ι ↦ Fin.cons v a)

@[simp]
lemma boundary_of (n : ℕ) (a : Fin (n + 1) → ι) :
    boundary n (FreeAbelianGroup.of a) =
      ∑ k : Fin (n + 1), (-1 : ℤ) ^ k.val • FreeAbelianGroup.of (a ∘ k.succAbove) :=
  FreeAbelianGroup.lift_apply_of _ _

@[simp]
lemma cone_of (v : ι) (n : ℕ) (a : Fin n → ι) :
    cone v n (FreeAbelianGroup.of a) = FreeAbelianGroup.of (Fin.cons v a) :=
  FreeAbelianGroup.lift_apply_of _ _

/-- Deleting the first vertex of a cone leaves the original tuple. -/
lemma cone_face_zero (v : ι) (n : ℕ) (a : Fin n → ι) :
    Fin.cons v a ∘ (0 : Fin (n + 1)).succAbove = a := by
  ext i
  simp

/-- The boundary of a coned generator, with its integral signs. -/
lemma boundary_cone_of (v : ι) (n : ℕ) (a : Fin (n + 1) → ι) :
    boundary (n + 1) (cone v (n + 1) (FreeAbelianGroup.of a)) =
      FreeAbelianGroup.of a - cone v n (boundary n (FreeAbelianGroup.of a)) := by
  rw [cone_of, boundary_of, Fin.sum_univ_succ]
  simp only [Fin.val_zero, pow_zero, one_smul, cone_face_zero, boundary_of,
    map_sum, map_zsmul, cone_of, Fin.val_succ, pow_succ, mul_smul, neg_one_smul,
    smul_neg, Fin.cons_comp_succ_succAbove, Finset.sum_neg_distrib, sub_eq_add_neg]
  rfl

/-- The cone identity on arbitrary integral tuple chains. -/
lemma boundary_cone (v : ι) (n : ℕ) (z : Chains (ι := ι) (n + 1)) :
    boundary (n + 1) (cone v (n + 1) z) = z - cone v n (boundary n z) := by
  induction z using FreeAbelianGroup.induction_on with
  | zero => simp
  | of a => exact boundary_cone_of v n a
  | neg a h => simp only [map_neg, h]; abel
  | add x y hx hy => simp only [map_add, hx, hy]; abel

/-- At the augmentation term, the boundary of the cone is the identity. -/
lemma boundary_cone_zero (v : ι) (z : Chains (ι := ι) 0) :
    boundary 0 (cone v 0 z) = z := by
  induction z using FreeAbelianGroup.induction_on with
  | zero => simp
  | of a => simp
  | neg a h => simpa only [map_neg] using congrArg Neg.neg h
  | add x y hx hy => simp only [map_add, hx, hy]

/-- Every nonempty tuple is a cone on its tail. -/
lemma of_eq_cone (n : ℕ) (a : Fin (n + 1) → ι) :
    FreeAbelianGroup.of a = cone (a 0) n (FreeAbelianGroup.of (a ∘ Fin.succ)) := by
  rw [cone_of]
  congr 1
  ext i
  cases i using Fin.cases <;> rfl

/-- The augmented integral tuple boundary squares to zero in all degrees. -/
lemma boundary_sq (n : ℕ) (z : Chains (ι := ι) (n + 2)) :
    boundary n (boundary (n + 1) z) = 0 := by
  induction n with
  | zero =>
    induction z using FreeAbelianGroup.induction_on with
    | zero => simp
    | of a =>
      rw [of_eq_cone 1 a, boundary_cone, map_sub, boundary_cone_zero, sub_self]
    | neg a h => simpa only [map_neg, neg_zero] using congrArg Neg.neg h
    | add x y hx hy => simp only [map_add, hx, hy, add_zero]
  | succ n ih =>
    induction z using FreeAbelianGroup.induction_on with
    | zero => simp
    | of a =>
      rw [of_eq_cone (n + 2) a, boundary_cone, map_sub, boundary_cone, ih,
        map_zero, sub_zero, sub_self]
    | neg a h => simpa only [map_neg, neg_zero] using congrArg Neg.neg h
    | add x y hx hy => simp only [map_add, hx, hy, add_zero]

/-- Coning fills every cycle, without any restriction on repeated vertices. -/
lemma boundary_cone_of_cycle (v : ι) (n : ℕ) (z : Chains (ι := ι) (n + 1))
    (h : boundary n z = 0) : boundary (n + 1) (cone v (n + 1) z) = z := by
  rw [boundary_cone, h, map_zero, sub_zero]

/-- Chains generated by tuples whose entries lie in the given set of vertices. -/
def supported (S : Set ι) (n : ℕ) : AddSubgroup (Chains (ι := ι) n) :=
  AddSubgroup.closure {z | ∃ a : Fin n → ι, (∀ i, a i ∈ S) ∧ FreeAbelianGroup.of a = z}

/-- A tuple generator is supported on any set containing its entries. -/
lemma of_mem_supported (S : Set ι) (n : ℕ) (a : Fin n → ι) (h : ∀ i, a i ∈ S) :
    FreeAbelianGroup.of a ∈ supported S n :=
  AddSubgroup.subset_closure ⟨a, h, rfl⟩

/-- Deletion does not enlarge the set of vertices supporting a chain. -/
lemma boundary_mem_supported (S : Set ι) (n : ℕ) (z : Chains (ι := ι) (n + 1))
    (hz : z ∈ supported S (n + 1)) : boundary n z ∈ supported S n := by
  have h : supported S (n + 1) ≤ (supported S n).comap (boundary n) := by
    apply (AddSubgroup.closure_le _).mpr
    rintro _ ⟨a, ha, rfl⟩
    change boundary n (FreeAbelianGroup.of a) ∈ supported S n
    rw [boundary_of]
    apply AddSubgroup.sum_mem
    intro k _
    exact (supported S n).zsmul_mem (of_mem_supported S n _ (fun i ↦ ha _)) _
  exact h hz

/-- Coning by an existing vertex preserves support, including all repeated tuples. -/
lemma cone_mem_supported (S : Set ι) (v : ι) (hv : v ∈ S) (n : ℕ)
    (z : Chains (ι := ι) n) (hz : z ∈ supported S n) :
    cone v n z ∈ supported S (n + 1) := by
  have h : supported S n ≤ (supported S (n + 1)).comap (cone v n) := by
    apply (AddSubgroup.closure_le _).mpr
    rintro _ ⟨a, ha, rfl⟩
    change cone v n (FreeAbelianGroup.of a) ∈ supported S (n + 1)
    rw [cone_of]
    apply of_mem_supported
    intro i
    cases i using Fin.cases with
    | zero => exact hv
    | succ j => exact ha j
  exact h hz

/-- A supported cycle has an explicit filler on the same set of vertices. -/
lemma supported_cycle_filler (S : Set ι) (v : ι) (hv : v ∈ S) (n : ℕ)
    (z : Chains (ι := ι) (n + 1)) (hz : z ∈ supported S (n + 1))
    (hd : boundary n z = 0) :
    cone v (n + 1) z ∈ supported S (n + 2) ∧
      boundary (n + 1) (cone v (n + 1) z) = z :=
  ⟨cone_mem_supported S v hv (n + 1) z hz, boundary_cone_of_cycle v n z hd⟩

end FLT.Mazur.CechSortingHomotopyCoordinates
