/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.CategoryTheory.Adjunction.Whiskering
public import Mathlib.CategoryTheory.Sites.LeftExact
public import Mathlib.CategoryTheory.Sites.SheafCohomology.Basic
public import Mathlib.Topology.Sheaves.Abelian

/-!
# Free abelian sheaves on opens

Sheafification, the free abelian group adjunction, and Yoneda identify maps out of
`freeOpen W` with sections over `W`. This identification is additive and natural
in both the open and the coefficient sheaf. Composing with the degree-zero Ext
equivalence gives the corresponding evaluation of `Sheaf.H'`.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false

open CategoryTheory CategoryTheory.Limits CategoryTheory.Functor TopologicalSpace Opposite

universe u v

namespace FLT.Mazur.CechFreeOpen

variable {X : TopCat.{u}}

/-- The free abelian sheaf generated by the representable of an open. -/
def freeOpen (W : Opens X) : TopCat.Sheaf AddCommGrpCat.{u} X :=
  (presheafToSheaf (Opens.grothendieckTopology X) AddCommGrpCat).obj
    (yoneda.obj W ⋙ AddCommGrpCat.free)

/-- The map of free sheaves induced by an inclusion of opens. -/
def freeOpenMap {W W' : Opens X} (i : W ⟶ W') : freeOpen W ⟶ freeOpen W' :=
  (presheafToSheaf (Opens.grothendieckTopology X) AddCommGrpCat).map
    (whiskerRight (yoneda.map i) AddCommGrpCat.free)

/-- Evaluation for the free abelian presheaf on a representable. -/
def freePresheafHomEquiv (W : Opens X) (P : (Opens X)ᵒᵖ ⥤ AddCommGrpCat.{u}) :
    (yoneda.obj W ⋙ AddCommGrpCat.free ⟶ P) ≃+ P.obj (op W) where
  toEquiv := ((AddCommGrpCat.adj.whiskerRight (Opens X)ᵒᵖ).homEquiv _ P).trans
    yonedaEquiv
  map_add' f g := by
    change (f + g).app (op W) (FreeAbelianGroup.of (𝟙 W)) =
      f.app (op W) (FreeAbelianGroup.of (𝟙 W)) +
        g.app (op W) (FreeAbelianGroup.of (𝟙 W))
    rfl

lemma freePresheafHomEquiv_apply (W : Opens X)
    (P : (Opens X)ᵒᵖ ⥤ AddCommGrpCat.{u})
    (f : yoneda.obj W ⋙ AddCommGrpCat.free ⟶ P) :
    freePresheafHomEquiv W P f = f.app (op W) (FreeAbelianGroup.of (𝟙 W)) := rfl

/-- Maps from the free sheaf on `W` are sections over `W`. -/
def freeOpenHomEquiv (W : Opens X) (F : TopCat.Sheaf AddCommGrpCat.{u} X) :
    (freeOpen W ⟶ F) ≃+ F.obj.obj (op W) :=
  ((sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat).homAddEquiv _ F).trans
    (freePresheafHomEquiv W F.obj)

/-- Evaluation commutes with a morphism of coefficient sheaves. -/
lemma freeOpenHomEquiv_naturality {F G : TopCat.Sheaf AddCommGrpCat.{u} X} (f : F ⟶ G) (W : Opens X)
    (g : freeOpen W ⟶ F) :
    freeOpenHomEquiv W G (g ≫ f) = f.hom.app (op W) (freeOpenHomEquiv W F g) := by
  change freePresheafHomEquiv W G.obj
    ((sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat).homEquiv _ G (g ≫ f)) =
      f.hom.app (op W) (freePresheafHomEquiv W F.obj
        ((sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat).homEquiv _ F g))
  rw [Adjunction.homEquiv_naturality_right]
  rw [freePresheafHomEquiv_apply, freePresheafHomEquiv_apply]
  rfl

/-- Evaluation sends precomposition along an inclusion to restriction of sections. -/
lemma freeOpenHomEquiv_naturality_open {W W' : Opens X} (i : W ⟶ W')
    (F : TopCat.Sheaf AddCommGrpCat.{u} X) (g : freeOpen W' ⟶ F) :
    freeOpenHomEquiv W F (freeOpenMap i ≫ g) =
      F.obj.map i.op (freeOpenHomEquiv W' F g) := by
  change freePresheafHomEquiv W F.obj
    ((sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat).homEquiv _ F
      ((presheafToSheaf (Opens.grothendieckTopology X) AddCommGrpCat).map _ ≫ g)) = _
  rw [Adjunction.homEquiv_naturality_left]
  let t := (sheafificationAdjunction (Opens.grothendieckTopology X) AddCommGrpCat).homEquiv _ F g
  change freePresheafHomEquiv W F.obj
    (whiskerRight (yoneda.map i) AddCommGrpCat.free ≫ t) =
      F.obj.map i.op (freePresheafHomEquiv W' F.obj t)
  rw [freePresheafHomEquiv_apply, freePresheafHomEquiv_apply]
  have h := ConcreteCategory.congr_hom (t.naturality i.op)
    (FreeAbelianGroup.of (𝟙 W'))
  simpa using h

variable [HasExt.{v} (Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})]

local instance : HasExt.{v} (TopCat.Sheaf AddCommGrpCat.{u} X) :=
  inferInstanceAs (HasExt.{v} (Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}))

/-- Degree-zero cohomology on an open is its group of sections. -/
def hPrimeZeroEquiv (W : Opens X) (F : TopCat.Sheaf AddCommGrpCat.{u} X) :
    F.H' 0 W ≃+ F.obj.obj (op W) :=
  Abelian.Ext.addEquiv₀.trans (freeOpenHomEquiv W F)

/-- Degree-zero evaluation commutes with coefficient morphisms. -/
lemma hPrimeZeroEquiv_naturality {F G : TopCat.Sheaf AddCommGrpCat.{u} X} (f : F ⟶ G) (W : Opens X)
    (x : F.H' 0 W) :
    hPrimeZeroEquiv W G
      (((Sheaf.cohomologyPresheafFunctor (Opens.grothendieckTopology X) 0).map f).app (op W) x) =
      f.hom.app (op W) (hPrimeZeroEquiv W F x) := by
  obtain ⟨g, rfl⟩ := Abelian.Ext.addEquiv₀.symm.surjective x
  change freeOpenHomEquiv W G
    (Abelian.Ext.addEquiv₀.{v}
      ((Abelian.Ext.mk₀ g).comp (Abelian.Ext.mk₀ f) (zero_add 0))) = _
  rw [Abelian.Ext.mk₀_comp_mk₀]
  let eF : Abelian.Ext.{v} (freeOpen W) F 0 ≃+ (freeOpen W ⟶ F) :=
    Abelian.Ext.addEquiv₀
  let eG : Abelian.Ext.{v} (freeOpen W) G 0 ≃+ (freeOpen W ⟶ G) :=
    Abelian.Ext.addEquiv₀
  change freeOpenHomEquiv W G (eG (eG.symm (g ≫ f))) =
    f.hom.app (op W) (freeOpenHomEquiv W F (eF (eF.symm g)))
  rw [eG.apply_symm_apply, eF.apply_symm_apply]
  exact freeOpenHomEquiv_naturality f W g

end FLT.Mazur.CechFreeOpen
