/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Mathlib.RingTheory.AdicCompletion.Algebra
public import Mathlib.RingTheory.MvPowerSeries.Basic

/-!
# Nodes on curves via their completed local rings

At a closed point of a locally finite type curve over an algebraically closed field `k`,
the ordinary double point condition is `Ô_{X,x} ≃ₐ[k] k[[X,Y]]/(XY)` (Stacks 0C46;
DR I, Proposition 5.3, as recorded in `docs/DR_SOURCE_LEDGER.md`). We use this as the
definition and prove its equivalence with a surjective power-series presentation whose
kernel is exactly `(XY)`. No reducedness assumption on the whole curve is added.

The definitions also make sense over arbitrary fields, where the model specifies a
split rational node. `AtWorstNodes` tests only closed points, allowing either membership
in the actual smooth locus or this completed-local-ring model. Finiteness, purity,
connectedness and the genus/dualizing-sheaf conditions belong to the fiber contract.
The étale normal-form theorem and smooth/node disjointness are not proved here.
-/

@[expose] public noncomputable section

open CategoryTheory AlgebraicGeometry

universe u

namespace FLT.Mazur.FCurve.CurveNode

/-- Formal power series in the two branch coordinates. -/
abbrev Series (k : Type u) := MvPowerSeries (Fin 2) k

/-- The principal ideal generated by the product of the two coordinates. -/
def equationIdeal (k : Type u) [Field k] : Ideal (Series k) :=
  Ideal.span {MvPowerSeries.X 0 * MvPowerSeries.X 1}

/-- The completed local algebra of a split rational ordinary double point. -/
abbrev Model (k : Type u) [Field k] := Series k ⧸ equationIdeal k

variable {k : Type u} [Field k]

/-- The two coordinates have zero product in the node model. -/
lemma model_relation :
    Ideal.Quotient.mk (equationIdeal k) (MvPowerSeries.X 0) *
      Ideal.Quotient.mk (equationIdeal k) (MvPowerSeries.X 1) = 0 := by
  rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span (Set.mem_singleton _)

variable {X : Scheme.{u}}

/-- The actual local ring of the scheme at the point. -/
abbrev LocalRing (x : X) := X.presheaf.stalk x

/-- Constants in the stalk, induced by the specified structure morphism. -/
def scalarMap (f : X ⟶ Spec (CommRingCat.of k)) (x : X) : k →+* LocalRing x :=
  ((Scheme.ΓSpecIso (CommRingCat.of k)).inv ≫ f.appTop ≫
    X.presheaf.germ ⊤ x (by trivial)).hom

/-- The scalar action is determined by `f`, rather than a freely chosen stalk algebra. -/
abbrev localAlgebra (f : X ⟶ Spec (CommRingCat.of k)) (x : X) :
    Algebra k (LocalRing x) :=
  (scalarMap f x).toAlgebra

/-- Completion of the actual stalk at its maximal ideal. -/
abbrev CompletedLocalRing (x : X) :=
  AdicCompletion (IsLocalRing.maximalIdeal (LocalRing x)) (LocalRing x)

/-- The completed-local-ring criterion for a split node; over an algebraically closed
field this is the ordinary double point condition at a closed point of a curve. -/
def IsNode (f : X ⟶ Spec (CommRingCat.of k)) (x : X) : Prop :=
  letI := localAlgebra f x
  Nonempty (CompletedLocalRing x ≃ₐ[k] Model k)

/-- An equivalent description by generators and the exact relation ideal. -/
def HasNodePresentation (f : X ⟶ Spec (CommRingCat.of k)) (x : X) : Prop :=
  letI := localAlgebra f x
  ∃ q : Series k →ₐ[k] CompletedLocalRing x,
    Function.Surjective q ∧ RingHom.ker q.toRingHom = equationIdeal k

/-- A quotient model is equivalent to a surjective presentation with exactly its kernel.
This comparison retains the base-field action on both sides. -/
theorem isNode_iff_hasNodePresentation (f : X ⟶ Spec (CommRingCat.of k)) (x : X) :
    IsNode f x ↔ HasNodePresentation f x := by
  let := localAlgebra f x
  constructor
  · rintro ⟨e⟩
    refine ⟨e.symm.toAlgHom.comp (Ideal.Quotient.mkₐ k (equationIdeal k)),
      e.symm.surjective.comp (Ideal.Quotient.mkₐ_surjective k _), ?_⟩
    ext a
    change e.symm (Ideal.Quotient.mk (equationIdeal k) a) = 0 ↔ a ∈ equationIdeal k
    simp only [map_eq_zero_iff _ e.symm.injective, Ideal.Quotient.eq_zero_iff_mem]
  · rintro ⟨q, hq, hker⟩
    exact ⟨(Ideal.quotientKerAlgEquivOfSurjective hq).symm.trans
      (Ideal.quotientEquivAlgOfEq k hker)⟩

/-- Every closed point is either smooth or an ordinary double point. -/
def AtWorstNodes (f : X ⟶ Spec (CommRingCat.of k)) [LocallyOfFinitePresentation f] : Prop :=
  ∀ x : X, IsClosed ({x} : Set X) → x ∈ f.smoothLocus ∨ IsNode f x

/-- The closed-point condition expressed entirely through stalks and power-series relations. -/
theorem atWorstNodes_iff_presentations (f : X ⟶ Spec (CommRingCat.of k))
    [LocallyOfFinitePresentation f] :
    AtWorstNodes f ↔ ∀ x : X, IsClosed ({x} : Set X) →
      (f.stalkMap x).hom.FormallySmooth ∨ HasNodePresentation f x := by
  simp only [AtWorstNodes, Scheme.Hom.mem_smoothLocus, isNode_iff_hasNodePresentation]

/-- It suffices to test the closed points outside the smooth locus. -/
theorem atWorstNodes_iff_nonsmooth (f : X ⟶ Spec (CommRingCat.of k))
    [LocallyOfFinitePresentation f] :
    AtWorstNodes f ↔ ∀ x : X, IsClosed ({x} : Set X) →
      x ∉ f.smoothLocus → IsNode f x := by
  simp only [AtWorstNodes, or_iff_not_imp_left]

/-- A smooth curve satisfies the condition, without imposing smoothness in its definition. -/
theorem atWorstNodes_of_smooth (f : X ⟶ Spec (CommRingCat.of k)) [Smooth f] :
    AtWorstNodes f := by
  intro x _
  left
  rw [f.smoothLocus_eq_top]
  trivial

end FLT.Mazur.FCurve.CurveNode
