/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.EllipticLocalCubicExpansion
public import FLT.Mazur.EllipticLocalValuation

/-!
# Residue-characteristic torsion over an unramified odd local ring

When the maximal ideal is generated by n and two is a unit in the residue field,
the actual parameter of nP is n times the parameter of P times a unit. This
excludes n-primary torsion when n is nonzero. The maximal-ideal hypothesis is an
explicit arithmetic unramifiedness condition, not a specialization-kernel assumption.
-/

@[expose] public section

namespace FLT.Mazur
open IsLocalRing

variable {K : Type*} [Field K] (A : ValuationSubring K) (W : WeierstrassCurve A)
variable [IsAdicComplete (maximalIdeal A) A]

/-- In the unramified odd case the actual multiplication parameter is nt times a unit. -/
theorem infinityParameter_nsmul_unramified_unit (n : ℕ)
    (hm : maximalIdeal A = Ideal.span {(n : A)}) (hn : (n : ResidueField A) = 0)
    (h2 : IsUnit (2 : ResidueField A)) (P : ellipticE1 A W) :
    ∃ u : Aˣ, infinityParameter A W (n • P) = n * infinityParameter A W P * u := by
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton.mp
    (hm ▸ infinityParameter_mem A W P)
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton.mp
    (hm ▸ multiplicationSeries_coeff_two_mem A W n hn h2)
  obtain ⟨r, hr⟩ := infinityParameter_nsmul_cubic_expansion A W n P
  have ht0 := (residue_eq_zero_iff _).mpr (infinityParameter_mem A W P)
  have hu : IsUnit (1 + infinityParameter A W P * (b + a * r)) := by
    apply (residue_ne_zero_iff_isUnit _).mp
    simp [ht0]
  refine ⟨hu.unit, ?_⟩
  rw [hu.unit_spec, hr, hb, ha]
  ring

/-- The actual multiplication parameter has the predicted valuation in the unramified odd case. -/
theorem infinityParameter_nsmul_unramified_valuation (n : ℕ)
    (hm : maximalIdeal A = Ideal.span {(n : A)}) (hn : (n : ResidueField A) = 0)
    (h2 : IsUnit (2 : ResidueField A)) (P : ellipticE1 A W) :
    A.valuation (infinityParameter A W (n • P) : K) =
      A.valuation (n : K) * A.valuation (infinityParameter A W P : K) := by
  obtain ⟨u, hu⟩ := infinityParameter_nsmul_unramified_unit A W n hm hn h2 P
  rw [hu]
  push_cast
  rw [map_mul, map_mul, A.valuation_unit u, mul_one]

/-- A nonzero scalar generating the maximal ideal has trivial kernel when two is a residue unit. -/
theorem ellipticE1_nsmul_eq_zero_iff_unramified (n : ℕ)
    (hm : maximalIdeal A = Ideal.span {(n : A)}) (hn : (n : ResidueField A) = 0)
    (h2 : IsUnit (2 : ResidueField A)) (hn0 : (n : A) ≠ 0) (P : ellipticE1 A W) :
    n • P = 0 ↔ P = 0 := by
  constructor
  · intro h
    obtain ⟨u, hu⟩ := infinityParameter_nsmul_unramified_unit A W n hm hn h2 P
    rw [h, infinityParameter_zero] at hu
    have hz := u.isUnit.mul_left_eq_zero.mp hu.symm
    exact (infinityParameter_eq_zero_iff A W P).mp ((mul_eq_zero.mp hz).resolve_left hn0)
  · rintro rfl
    exact nsmul_zero n

/-- No power-primary torsion survives under the same arithmetic hypotheses. -/
theorem ellipticE1_pow_nsmul_eq_zero_iff_unramified (n k : ℕ)
    (hm : maximalIdeal A = Ideal.span {(n : A)}) (hn : (n : ResidueField A) = 0)
    (h2 : IsUnit (2 : ResidueField A)) (hn0 : (n : A) ≠ 0) (P : ellipticE1 A W) :
    n ^ k • P = 0 ↔ P = 0 := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ, mul_nsmul,
      ellipticE1_nsmul_eq_zero_iff_unramified A W n hm hn h2 hn0, ih]

end FLT.Mazur
