/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.EllipticExtensionPrimeSubgroup
public import FLT.Mazur.EllipticSubgroupChartGeneric

/-!
# Chart closures of the transported prime-order elliptic subgroup

Instantiate the integral chart construction at the subgroup generated by the
actual extension and variable-change map. Its projective form still has p
points; each chart closure has the correct generic fiber and is flat over a
DVR. No finite integral group scheme or Hopf structure is asserted here.
-/

@[expose] public noncomputable section

namespace FLT.Mazur

open WeierstrassCurve
open scoped TensorProduct

variable {R K L : Type*} [CommRing R] [Field K] [Field L]
  [Algebra R K] [Algebra R L] [Algebra K L] [IsScalarTower R K L]
  [DecidableEq K] [DecidableEq L]
  (A : ValuationSubring L) (W : WeierstrassCurve R) (U : WeierstrassCurve A)
  [(W.map (algebraMap R L)).IsElliptic] (C : VariableChange L)
  (hC : C • W.map (algebraMap R L) = U.map (algebraMap A L))
  (P : (W.map (algebraMap R K)).toAffine.Point)

/-- The transported cyclic subgroup in projective coordinates. -/
def ellipticExtensionProjectiveSubgroup :
    AddSubgroup (U.map (algebraMap A L)).toProjective.Point :=
  AddSubgroup.zmultiples
    ((Projective.Point.toAffineAddEquiv (U.map (algebraMap A L))).symm
      (ellipticExtensionPointHom W U C hC P))

/-- Passing to projective coordinates preserves the proven prime subgroup order. -/
theorem ellipticExtensionProjectiveSubgroup_card {p : ℕ} [Fact p.Prime]
    (hP : p • P = 0) (hP0 : P ≠ 0) :
    Nat.card (ellipticExtensionProjectiveSubgroup A W U C hC P) = p := by
  unfold ellipticExtensionProjectiveSubgroup
  rw [Nat.card_zmultiples, AddEquiv.addOrderOf_eq]
  exact ellipticExtensionPoint_addOrderOf W U C hC P hP hP0

/-- The explicit map defining this subgroup's closure in chart j. -/
def ellipticExtensionChartMap (j : Fin 3) :=
  EllipticSubgroupChart.coordinateMap A U (ellipticExtensionProjectiveSubgroup A W U C hC P) j

/-- The integral closure chart of the transported prime-order subgroup. -/
abbrev EllipticExtensionChart (j : Fin 3) :=
  AffineGenericClosure.Coordinate (ellipticExtensionChartMap A W U C hC P j)

/-- Each concrete affine closure chart is flat over the extended DVR. -/
theorem ellipticExtensionChart_flat [IsDedekindDomain A] (j : Fin 3) :
    Module.Flat A (EllipticExtensionChart A W U C hC P j) :=
  EllipticSubgroupChart.closure_flat A U (ellipticExtensionProjectiveSubgroup A W U C hC P) j

/-- The concrete closure chart has exactly the prescribed prime subgroup's generic points. -/
def ellipticExtensionChartGenericEquiv {p : ℕ} [Fact p.Prime]
    (hP : p • P = 0) (hP0 : P ≠ 0) (j : Fin 3) :
    L ⊗[A] EllipticExtensionChart A W U C hC P j ≃ₐ[L]
      (EllipticSubgroupChart.Index A U
        (ellipticExtensionProjectiveSubgroup A W U C hC P) j → L) := by
  let _ := Nat.finite_of_card_ne_zero
    ((ellipticExtensionProjectiveSubgroup_card A W U C hC P hP hP0).trans_ne
      (Fact.out : p.Prime).ne_zero)
  exact EllipticSubgroupChart.genericEquiv A U
    (ellipticExtensionProjectiveSubgroup A W U C hC P) j

end FLT.Mazur
