/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.EllipticSubgroupPointKernels
public import FLT.Mazur.PrincipalLocalizationGeneration

/-!
# An individual subgroup point closure is a base localization

The image of one chart point is generated by its normalized coordinates.
Primitivity supplies the inverse chart denominator in this image. Consequently
its kernel quotient is exactly the corresponding principal open of the base.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false

namespace FLT.Mazur.EllipticSubgroupChart

open WeierstrassIntegralChart

variable {K : Type*} [Field K] (A : ValuationSubring K) (W : WeierstrassCurve A)
  (H : AddSubgroup (W.map (algebraMap A K)).toProjective.Point) (j : Fin 3)
  (P : Index A W H j)

/-- The open of the base on which this point lies in the selected chart. -/
abbrev PointBaseLocalization := Localization.Away ((primitiveLift A W P.1.1).coords j)

/-- The generic embedding of that principal base open. -/
def pointBaseToField : PointBaseLocalization A W H j P →ₐ[A] K :=
  IsLocalization.Away.liftAlgHom ((primitiveLift A W P.1.1).coords j)
    (show IsUnit ((Algebra.ofId A K) ((primitiveLift A W P.1.1).coords j)) from
      isUnit_iff_ne_zero.mpr P.2)

/-- The base localization embeds into the fraction field. -/
theorem pointBaseToField_injective : Function.Injective (pointBaseToField A W H j P) := by
  apply (IsLocalization.injective_iff_map_algebraMap_eq
    (Submonoid.powers ((primitiveLift A W P.1.1).coords j))
    (pointBaseToField A W H j P).toRingHom).mpr
  intro a b
  constructor
  · exact congrArg (pointBaseToField A W H j P)
  · intro h
    change pointBaseToField A W H j P (algebraMap A _ a) =
      pointBaseToField A W H j P (algebraMap A _ b) at h
    rw [AlgHom.commutes, AlgHom.commutes] at h
    exact congrArg (algebraMap A _) (Subtype.coe_injective h)

/-- The distinguished inverse has its expected generic value. -/
theorem pointBaseToField_inverse :
    pointBaseToField A W H j P
        (IsLocalization.Away.invSelf ((primitiveLift A W P.1.1).coords j)) =
      ((primitiveLift A W P.1.1).coords j : K)⁻¹ := by
  apply (mul_right_inj' P.2).mp
  rw [mul_inv_cancel₀ P.2]
  have h := congrArg (pointBaseToField A W H j P)
    (IsLocalization.Away.mul_invSelf (S := PointBaseLocalization A W H j P)
      ((primitiveLift A W P.1.1).coords j))
  rw [map_mul, AlgHom.commutes, map_one] at h
  exact h

/-- Evaluation has precisely the subalgebra generated by the normalized coordinates. -/
theorem pointEvaluation_range :
    (pointEvaluation A W H j P).range =
      Algebra.adjoin A (Set.range (coordinates A W H j P)) := by
  rw [Algebra.adjoin_range_eq_range_aeval]
  ext z
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective b
    exact ⟨p, rfl⟩
  · rintro ⟨p, rfl⟩
    exact ⟨Ideal.Quotient.mk _ (Ideal.Quotient.mk _ p), rfl⟩

/-- Primitivity puts the inverse chart denominator in the actual point image. -/
theorem inverse_mem_pointEvaluation_range :
    ((primitiveLift A W P.1.1).coords j : K)⁻¹ ∈ (pointEvaluation A W H j P).range := by
  obtain ⟨i, hi⟩ := (primitiveLift A W P.1.1).primitive
  have hc : coordinates A W H j P i ∈ (pointEvaluation A W H j P).range :=
    ⟨Ideal.Quotient.mk _ (coord W j i), pointEvaluation_coord A W H j P i⟩
  have hm := (pointEvaluation A W H j P).range.mul_mem hc
    ((pointEvaluation A W H j P).range.algebraMap_mem (↑hi.unit⁻¹ : A))
  convert hm using 1
  change _ = (((primitiveLift A W P.1.1).coords j : K)⁻¹ *
    (primitiveLift A W P.1.1).coords i) * ((↑hi.unit⁻¹ : A) : K)
  rw [mul_assoc]
  have hu : ((primitiveLift A W P.1.1).coords i : K) * ((↑hi.unit⁻¹ : A) : K) = 1 := by
    change (((primitiveLift A W P.1.1).coords i * (↑hi.unit⁻¹ : A) : A) : K) = 1
    have hh : (primitiveLift A W P.1.1).coords i * (↑hi.unit⁻¹ : A) = 1 :=
      Units.mul_inv_eq_one.mpr hi.unit_spec
    exact congrArg (fun a : A => (a : K)) hh
  rw [hu, mul_one]

/-- The point image equals the embedded principal localization of the base. -/
theorem pointEvaluation_range_eq_localization :
    (pointEvaluation A W H j P).range = (pointBaseToField A W H j P).range := by
  apply le_antisymm
  · rw [pointEvaluation_range]
    apply Algebra.adjoin_le
    rintro _ ⟨i, rfl⟩
    refine ⟨IsLocalization.Away.invSelf ((primitiveLift A W P.1.1).coords j) *
      algebraMap A (PointBaseLocalization A W H j P) ((primitiveLift A W P.1.1).coords i), ?_⟩
    change pointBaseToField A W H j P (_ * _) = _
    rw [map_mul, pointBaseToField_inverse, AlgHom.commutes]
    rfl
  · rintro _ ⟨z, rfl⟩
    obtain ⟨a, n, rfl⟩ := PrincipalLocalizationGeneration.fraction_representation
      ((primitiveLift A W P.1.1).coords j) z
    change pointBaseToField A W H j P (_ * _ ^ n) ∈ _
    rw [map_mul, map_pow, AlgHom.commutes, pointBaseToField_inverse]
    exact (pointEvaluation A W H j P).range.mul_mem
      ((pointEvaluation A W H j P).range.algebraMap_mem a)
      ((pointEvaluation A W H j P).range.pow_mem
        (inverse_mem_pointEvaluation_range A W H j P) n)

/-- The individual closed point subscheme of a chart is the corresponding base open. -/
def pointClosureLocalizationEquiv :
    AffineGenericClosure.Coordinate (pointEvaluation A W H j P) ≃ₐ[A]
      PointBaseLocalization A W H j P :=
  (AffineGenericClosure.imageEquiv (pointEvaluation A W H j P)).trans
    ((Subalgebra.equivOfEq _ _ (pointEvaluation_range_eq_localization A W H j P)).trans
      (AlgEquiv.ofInjective (pointBaseToField A W H j P)
        (pointBaseToField_injective A W H j P)).symm)

/-- The individual point quotient carries its actual principal-localization structure. -/
instance pointClosure_isLocalization :
    IsLocalization.Away ((primitiveLift A W P.1.1).coords j)
      (AffineGenericClosure.Coordinate (pointEvaluation A W H j P)) :=
  IsLocalization.isLocalization_of_algEquiv _ (pointClosureLocalizationEquiv A W H j P).symm

end FLT.Mazur.EllipticSubgroupChart
