/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.EtalePrimeParameterIdeals
public import FLT.Mazur.FiniteQuotientLocalSupport
public import Mathlib.RingTheory.Flat.Localization
public import Mathlib.Algebra.Polynomial.FieldDivision
public import Mathlib.RingTheory.RingHom.Etale

/-!
# Cartier equations on finite support in an étale coordinate

At every prime of an étale algebra over a polynomial ring over a field, an
ideal with finite-dimensional quotient is generated by a regular element.
The off-support case is the unit ideal; support points may be nonrational.
-/

@[expose] public noncomputable section
namespace FLT.Mazur.FCurve

variable {K B : Type*} [Field K] [CommRing B] [Algebra K B]

/-- Finite support ideals have regular equations at all primes of an étale curve chart. -/
theorem regular_generator_etale_finite_support
    (g : Polynomial K →ₐ[K] B) (hg : g.toRingHom.Etale)
    (I : Ideal B) [Module.Finite K (B ⧸ I)] (q : Ideal B) [q.IsPrime] :
    ∃ a : Localization.AtPrime q, IsRegular a ∧
      I.map (algebraMap B (Localization.AtPrime q)) = Ideal.span {a} := by
  by_cases hIq : I ≤ q
  · let _ := g.toAlgebra
    let _ : IsScalarTower K (Polynomial K) B :=
      .of_algebraMap_eq' g.comp_algebraMap.symm
    let _ : Algebra.Etale (Polynomial K) B := hg
    let p := q.under (Polynomial K)
    let _ := Localization.AtPrime.algebraOfLiesOver p q
    let _ : Algebra.EssFiniteType (Localization.AtPrime p) (Localization.AtPrime q) :=
      .of_comp (Polynomial K) _ _
    let _ : Algebra.FormallyUnramified (Localization.AtPrime p)
        (Localization.AtPrime q) := .of_restrictScalars (Polynomial K) _ _
    let _ : IsArtinianRing
        (Localization.AtPrime q ⧸ I.map (algebraMap B (Localization.AtPrime q))) :=
      artinian_localized_finite_quotient (K := K) I q.primeCompl _
    exact regular_generator_of_localized_pid_coordinate p
      (coordinate_prime_ne_bot_of_finite_quotient g I q hIq)
      (Localization.AtPrime q) _
  · obtain ⟨x, hxI, hxq⟩ := IsConcreteLE.not_le_iff_exists.mp hIq
    have hu : IsUnit (algebraMap B (Localization.AtPrime q) x) :=
      IsLocalization.map_units _ (⟨x, hxq⟩ : q.primeCompl)
    have htop : I.map (algebraMap B (Localization.AtPrime q)) = ⊤ :=
      Ideal.eq_top_of_isUnit_mem _ (Ideal.mem_map_of_mem _ hxI) hu
    exact ⟨1, isRegular_one, by simpa using htop⟩

end FLT.Mazur.FCurve
