/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.FiniteRelationLocalizationStages
public import Mathlib.RingTheory.Localization.Algebra
public import Mathlib.RingTheory.Ideal.Quotient.PowTransition

/-!
# Kernels of localized finite-relation transitions

The kernel is exactly the ideal generated by the added numerators. This
identifies the relations imposed by a transition, rather than merely detecting
that finitely many elements eventually vanish.
-/

@[expose] public noncomputable section

namespace FLT.Mazur.FiniteRelationLocalization

universe u v

variable (R : Type u) [CommRing R] {P : Type v} [CommRing P] [Algebra R P]
  (I : Ideal P) (r : P)

/-- The numerator map from the presenting ring to a localized stage. -/
def numerator (s : Finset I) : P →+* Stage I r s :=
  (algebraMap _ (Stage I r s)).comp (Ideal.Quotient.mk (FiniteRelationModel.relations I s))

/-- Localized transitions kill precisely the ideal generated by the new relations. -/
theorem ker_transition {s t : Finset I} (h : s ≤ t) :
    RingHom.ker (transition R I r h).toRingHom =
      (FiniteRelationModel.relations I t).map (numerator I r s) := by
  let _ : IsLocalization.Away
      ((FiniteRelationModel.transition R I h).toRingHom
        (Ideal.Quotient.mk (FiniteRelationModel.relations I s) r)) (Stage I r t) :=
    transition_away R I r h
  have hmap := IsLocalization.ker_map (S := Stage I r s) (Stage I r t)
    (FiniteRelationModel.transition R I h).toRingHom
    (Submonoid.map_powers (FiniteRelationModel.transition R I h).toRingHom
      (Ideal.Quotient.mk (FiniteRelationModel.relations I s) r))
  change RingHom.ker (transition R I r h).toRingHom =
    (RingHom.ker (FiniteRelationModel.transition R I h).toRingHom).map
      (algebraMap _ (Stage I r s)) at hmap
  rw [hmap]
  change (RingHom.ker (Ideal.Quotient.factor (FiniteRelationModel.relations_mono I h))).map
    (algebraMap _ (Stage I r s)) = _
  rw [Ideal.Quotient.factor_ker, Ideal.map_map]
  rfl

/-- Original stage relations have zero numerator. -/
theorem numerator_eq_zero (s : Finset I) (x : I) (hx : x ∈ s) :
    numerator I r s x = 0 := by
  change algebraMap (FiniteRelationModel.Stage I s) (Stage I r s)
    (Ideal.Quotient.mk (FiniteRelationModel.relations I s) (x : P)) = 0
  have hz : (x : P) ∈ FiniteRelationModel.relations I s :=
    Ideal.subset_span ⟨x, hx, rfl⟩
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr hz, map_zero]

/-- A transition sends a numerator to the same numerator at the next stage. -/
theorem transition_numerator {s t : Finset I} (h : s ≤ t) (x : P) :
    transition R I r h (numerator I r s x) = numerator I r t x := by
  exact transition_algebraMap R I r h (Ideal.Quotient.mk _ x)

end FLT.Mazur.FiniteRelationLocalization
