/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.GradedProjStructuralMap
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
public import Mathlib.RingTheory.GradedAlgebra.TensorProduct

/-!
# Proj projection for scalar extension

Positive homogeneous tensors lie in the ideal generated by the original
positive degrees. This constructs the projection on Proj for arbitrary base
change, together with its standard-chart description.
-/

@[expose] public noncomputable section
open CategoryTheory AlgebraicGeometry HomogeneousIdeal HomogeneousLocalization
open scoped TensorProduct
universe u
namespace FLT.Mazur.GradedProjBaseChangeMap
variable {R A B : Type u} [CommRing R] [CommRing A] [CommRing B]
  [Algebra R A] [Algebra R B] (𝒜 : ℕ → Submodule R A) [GradedAlgebra 𝒜]
set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

/-- The grading of the scalar-extended algebra. -/
abbrev baseGrade (n : ℕ) : Submodule B (B ⊗[R] A) := (𝒜 n).baseChange B

/-- The scalar extension inclusion as a degree-preserving ring map. -/
def inclusion : 𝒜 →+*ᵍ baseGrade (B := B) 𝒜 where
  __ := (GradedAlgHom.includeRight B 𝒜).toRingHom
  map_mem := fun hs ↦ Submodule.tmul_mem_baseChange_of_mem 1 hs

/-- The original positive degrees generate the extended irrelevant ideal. -/
lemma irrelevant_le_map :
    (baseGrade (B := B) 𝒜)₊ ≤ 𝒜₊.map (inclusion (B := B) 𝒜) := by
  apply toIdeal_le_toIdeal_iff.mp
  apply (toIdeal_irrelevant_le _).mpr
  intro n hn x hx
  obtain ⟨s, rfl⟩ := hx
  induction s using TensorProduct.inductionOn with
  | tmul b a =>
    have ha : inclusion (B := B) 𝒜 a ∈ (𝒜₊.map (inclusion (B := B) 𝒜)).toIdeal :=
      Ideal.mem_map_of_mem _ (mem_irrelevant_of_mem 𝒜 hn a.property)
    have hb := Ideal.mul_mem_left (𝒜₊.map (inclusion (B := B) 𝒜)).toIdeal
      (b ⊗ₜ[R] (1 : A)) ha
    change (b ⊗ₜ[R] (1 : A)) * (1 ⊗ₜ[R] (a : A)) ∈ _ at hb
    change b ⊗ₜ[R] (a : A) ∈ _
    rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul] at hb
    exact hb
  | add s t hs ht => simpa only [map_add] using add_mem hs ht

/-- The natural projection from Proj of the scalar extension to the original Proj. -/
def projection : Proj (baseGrade (B := B) 𝒜) ⟶ Proj 𝒜 :=
  Proj.map (inclusion (B := B) 𝒜) (irrelevant_le_map 𝒜)

/-- The inverse image of a basic open has the original denominator extended by scalars. -/
lemma projection_preimage_basicOpen (f : A) :
    projection (B := B) 𝒜 ⁻¹ᵁ Proj.basicOpen 𝒜 f =
      Proj.basicOpen (baseGrade 𝒜) (1 ⊗ₜ[R] f) := rfl

/-- On standard affine charts, the projection is the homogeneous-localization map. -/
@[reassoc]
lemma awayι_projection {n : ℕ} (hn : 0 < n) (f : A) (hf : f ∈ 𝒜 n) :
    Proj.awayι (baseGrade (B := B) 𝒜) (inclusion (B := B) 𝒜 f)
      ((inclusion (B := B) 𝒜).map_mem hf) hn ≫ projection (B := B) 𝒜 =
    Spec.map (CommRingCat.ofHom (Away.map (inclusion (B := B) 𝒜) f)) ≫ Proj.awayι 𝒜 f hf hn :=
  Proj.awayι_comp_map (inclusion (B := B) 𝒜) (irrelevant_le_map 𝒜) hn f hf

/-- The homogeneous-localization map respects the structural base ring. -/
lemma awayMap_scalar (f : A) (r : R) :
    Away.map (inclusion (B := B) 𝒜) f (GradedProjStructuralMap.scalarToAway 𝒜 f r) =
      GradedProjStructuralMap.scalarToAway (baseGrade (B := B) 𝒜)
        (inclusion 𝒜 f) (algebraMap R B r) := by
  apply HomogeneousLocalization.val_injective
  change Localization.mk (1 ⊗ₜ[R] algebraMap R A r) ⟨1 ⊗ₜ[R] (1 : A), _⟩ =
    Localization.mk (algebraMap R B r ⊗ₜ[R] (1 : A)) ⟨1, _⟩
  have h : (1 : B) ⊗ₜ[R] algebraMap R A r = algebraMap R B r ⊗ₜ[R] (1 : A) :=
    Algebra.TensorProduct.includeRight.commutes r
  simp only [h, ← Algebra.TensorProduct.one_def]

/-- The projection and structural maps give the natural commutative base-change square. -/
@[reassoc]
lemma projection_toSpecBase :
    projection (B := B) 𝒜 ≫ GradedProjStructuralMap.toSpecBase 𝒜 =
      GradedProjStructuralMap.toSpecBase (baseGrade (B := B) 𝒜) ≫
        Spec.map (CommRingCat.ofHom (algebraMap R B)) := by
  apply (Proj.mapAffineOpenCover (inclusion (B := B) 𝒜)
    (irrelevant_le_map 𝒜)).openCover.hom_ext
  intro s
  change Proj.awayι _ _ _ _ ≫ _ = Proj.awayι _ _ _ _ ≫ _
  rw [← Category.assoc, awayι_projection (B := B) 𝒜 s.1.2 s.2 s.2.2, Category.assoc,
    GradedProjStructuralMap.awayι_toSpecBase,
    GradedProjStructuralMap.awayι_toSpecBase_assoc, ← Spec.map_comp, ← Spec.map_comp]
  congr 1
  apply CommRingCat.hom_ext
  apply RingHom.ext
  intro r
  exact awayMap_scalar (B := B) 𝒜 s.2 r

end FLT.Mazur.GradedProjBaseChangeMap
