/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.Algebra.MvPolynomial.CommRing
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Equations for a based Hilbert chart

The parameter ring records multiplication, unit and ambient generator coordinates.
Its quotient imposes commutativity, summed associativity and the left unit law.
There is no restriction on the number of ambient generators or on the rank.
-/

@[expose] public noncomputable section

open scoped BigOperators

namespace FLT.Mazur.HilbertChart

universe u v

/-- Coordinates for a multiplication table, a unit, and ambient generators. -/
inductive Variable (I : Type v) (d : ℕ)
  | mul (i j k : Fin d)
  | unit (k : Fin d)
  | generator (i : I) (k : Fin d)

/-- Indices of the ring-law equations. -/
inductive Equation (d : ℕ)
  | comm (i j k : Fin d)
  | assoc (i j k l : Fin d)
  | unit (i k : Fin d)

variable (R : Type u) [CommRing R] (I : Type v) (d : ℕ)

/-- The polynomial ring of all structure and generator coordinates. -/
abbrev Parameters := MvPolynomial (Variable I d) R

/-- A multiplication coordinate. -/
def mulVar (i j k : Fin d) : Parameters R I d := MvPolynomial.X (.mul i j k)

/-- A coordinate of the unit vector. -/
def unitVar (k : Fin d) : Parameters R I d := MvPolynomial.X (.unit k)

/-- A coordinate of an ambient generator. -/
def generatorVar (i : I) (k : Fin d) : Parameters R I d :=
  MvPolynomial.X (.generator i k)

/-- The explicit ring-law equations; associativity sums intermediate indices. -/
def equation : Equation d → Parameters R I d
  | .comm i j k => mulVar R I d i j k - mulVar R I d j i k
  | .assoc i j k l =>
      (∑ m, mulVar R I d i j m * mulVar R I d m k l) -
        ∑ m, mulVar R I d j k m * mulVar R I d i m l
  | .unit i k =>
      (∑ j, unitVar R I d j * mulVar R I d j i k) - if i = k then 1 else 0

/-- The actual ideal generated by all the ring-law equations. -/
def equationIdeal : Ideal (Parameters R I d) := Ideal.span (Set.range (equation R I d))

/-- The coordinate ring of the scheme of based commutative algebra structures. -/
abbrev Coefficients := Parameters R I d ⧸ equationIdeal R I d

/-- The universal multiplication coefficients. -/
def mulCoeff (i j k : Fin d) : Coefficients R I d :=
  Ideal.Quotient.mk _ (mulVar R I d i j k)

/-- The universal unit coefficients. -/
def unitCoeff (k : Fin d) : Coefficients R I d :=
  Ideal.Quotient.mk _ (unitVar R I d k)

/-- The universal ambient generator coefficients. -/
def generatorCoeff (i : I) (k : Fin d) : Coefficients R I d :=
  Ideal.Quotient.mk _ (generatorVar R I d i k)

/-- Each defining equation vanishes in the actual quotient ring. -/
theorem equation_zero (e : Equation d) :
    Ideal.Quotient.mk (equationIdeal R I d) (equation R I d e) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span ⟨e, rfl⟩)

/-- The universal multiplication coefficients are symmetric. -/
theorem mulCoeff_comm (i j k : Fin d) :
    mulCoeff R I d i j k = mulCoeff R I d j i k := by
  have h := equation_zero R I d (.comm i j k)
  simpa only [equation, map_sub, sub_eq_zero, mulCoeff] using h

/-- The universal multiplication table satisfies the summed associativity law. -/
theorem mulCoeff_assoc (i j k l : Fin d) :
    (∑ m, mulCoeff R I d i j m * mulCoeff R I d m k l) =
      ∑ m, mulCoeff R I d j k m * mulCoeff R I d i m l := by
  have h := equation_zero R I d (.assoc i j k l)
  simpa only [equation, map_sub, map_sum, map_mul, sub_eq_zero, mulCoeff] using h

/-- The universal unit vector is a left identity for each basis vector. -/
theorem unitCoeff_mul (i k : Fin d) :
    (∑ j, unitCoeff R I d j * mulCoeff R I d j i k) = if i = k then 1 else 0 := by
  have h := equation_zero R I d (.unit i k)
  split_ifs with hik <;>
    simpa only [equation, hik, ite_true, ite_false, map_sub, map_sum, map_mul,
      map_one, map_zero, sub_eq_zero, unitCoeff, mulCoeff] using h

end FLT.Mazur.HilbertChart
