/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.HomogeneousLocalizationScalars

/-!
# Homogeneous localization at a degreewise generator

If powers of a homogeneous element freely generate the corresponding
homogeneous pieces over the scalar ring, the degree-zero localization
is precisely that scalar ring.
-/

@[expose] public noncomputable section
open HomogeneousLocalization
universe u
namespace FLT.Mazur.HomogeneousLocalizationGenerator
variable {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
  (𝒜 : ℕ → Submodule R A) [GradedAlgebra 𝒜] {f : A} {d : ℕ}
set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

/-- Multiplication by each denominator power detects structural scalars. -/
lemma scalar_injective (hinj : ∀ n : ℕ, Function.Injective (fun r : R ↦ r • f ^ n)) :
    Function.Injective (GradedProjStructuralMap.scalarToAway 𝒜 f) := by
  intro r s h
  have hv := congrArg HomogeneousLocalization.val h
  change algebraMap A (Localization.Away f) (algebraMap R A r) =
    algebraMap A (Localization.Away f) (algebraMap R A s) at hv
  obtain ⟨⟨_, n, rfl⟩, hn⟩ := (IsLocalization.eq_iff_exists
    (Submonoid.powers f) (Localization.Away f)).mp hv
  apply hinj n
  simpa only [Algebra.smul_def, mul_comm] using hn

/-- Every fraction is scalar when each relevant homogeneous piece is generated by a power. -/
lemma scalar_surjective (hf : f ∈ 𝒜 d)
    (hgen : ∀ (n : ℕ) (a : A), a ∈ 𝒜 (n • d) → ∃ r : R, a = r • f ^ n) :
    Function.Surjective (GradedProjStructuralMap.scalarToAway 𝒜 f) := by
  intro z
  obtain ⟨n, a, ha, rfl⟩ := Away.mk_surjective 𝒜 hf z
  obtain ⟨r, rfl⟩ := hgen n a ha
  refine ⟨r, ?_⟩
  apply HomogeneousLocalization.val_injective
  change algebraMap A (Localization.Away f) (algebraMap R A r) =
    Localization.mk (r • f ^ n) (⟨f ^ n, ⟨n, rfl⟩⟩ : Submonoid.powers f)
  rw [Localization.mk_eq_mk']
  exact IsLocalization.eq_mk'_of_mul_eq (Algebra.smul_def r (f ^ n)).symm

/-- Free generation of the homogeneous pieces identifies the scalar ring with the chart ring. -/
def scalarEquiv (hf : f ∈ 𝒜 d)
    (hinj : ∀ n : ℕ, Function.Injective (fun r : R ↦ r • f ^ n))
    (hgen : ∀ (n : ℕ) (a : A), a ∈ 𝒜 (n • d) → ∃ r : R, a = r • f ^ n) :
    R ≃+* Away 𝒜 f :=
  RingEquiv.ofBijective (GradedProjStructuralMap.scalarToAway 𝒜 f)
    ⟨scalar_injective 𝒜 hinj, scalar_surjective 𝒜 hf hgen⟩

/-- The inverse scalar identification satisfies the numerator-denominator equation. -/
lemma scalarEquiv_symm_mk_smul (hf : f ∈ 𝒜 d)
    (hinj : ∀ n : ℕ, Function.Injective (fun r : R ↦ r • f ^ n))
    (hgen : ∀ (n : ℕ) (a : A), a ∈ 𝒜 (n • d) → ∃ r : R, a = r • f ^ n)
    (n : ℕ) (a : A) (ha : a ∈ 𝒜 (n • d)) :
    (scalarEquiv 𝒜 hf hinj hgen).symm (Away.mk 𝒜 hf n a ha) • f ^ n = a := by
  obtain ⟨r, hr⟩ := hgen n a ha
  have he : scalarEquiv 𝒜 hf hinj hgen r = Away.mk 𝒜 hf n a ha := by
    apply HomogeneousLocalization.val_injective
    change algebraMap A (Localization.Away f) (algebraMap R A r) =
      Localization.mk a (⟨f ^ n, ⟨n, rfl⟩⟩ : Submonoid.powers f)
    rw [Localization.mk_eq_mk']
    exact IsLocalization.eq_mk'_of_mul_eq (by simpa only [Algebra.smul_def] using hr.symm)
  rw [← he, RingEquiv.symm_apply_apply]
  exact hr.symm

end FLT.Mazur.HomogeneousLocalizationGenerator
