/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.AffineModuleEpimorphisms
public import FLT.Mazur.IdealAdicGradedMultiplication

/-!
# Surjectivity of actual ideal-power products

The ideal product is generated by pure products on every affine open.
Consequently the constructed power product and its graded quotient are
sheaf epimorphisms, with surjective maps on affine sections.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

open CategoryTheory Limits AlgebraicGeometry Opposite
open Scheme.Modules FLT.Mazur.FCurve FLT.Mazur.CoherentIdealIntersection
open FLT.Mazur.GlobalIdealPower ModuleSheafTensor

universe u

namespace FLT.Mazur.IdealAdicQuotient

variable {X : Scheme.{u}} [IsLocallyNoetherian X] (I : X.IdealSheafData)

/-- The actual power product is surjective on every affine open. -/
lemma idealPowerMul_affine_surjective (a b : ℕ) (U : X.affineOpens) :
    Function.Surjective ((idealPowerMul I a b).app U.1) := by
  let p := idealPowerMul I a b ≫ idealModuleι (I ^ (a + b))
  have h : (I.ideal U) ^ (a + b) ≤ LinearMap.range (p.val.app (op U.1)).hom := by
    rw [pow_add]
    apply Ideal.mul_le.mpr
    intro r hr s hs
    let x := (idealModuleAffineEquiv (I ^ a) U).symm ⟨r, hr⟩
    let y := (idealModuleAffineEquiv (I ^ b) U).symm ⟨s, hs⟩
    refine ⟨pure _ _ U.1 x y, ?_⟩
    change (idealModuleι (I ^ (a + b))).app U.1
      ((idealPowerMul I a b).app U.1 (pure _ _ U.1 x y)) = r * s
    rw [idealPowerMul_pure, ← idealModuleAffineEquiv_val,
      ← idealModuleAffineEquiv_val]
    dsimp only [x, y]
    rw [LinearEquiv.apply_symm_apply, LinearEquiv.apply_symm_apply]
  intro z
  obtain ⟨t, ht⟩ := h (idealModuleAffineEquiv (I ^ (a + b)) U z).property
  refine ⟨t, ?_⟩
  apply (idealModuleAffineEquiv (I ^ (a + b)) U).injective
  apply Subtype.ext
  rw [idealModuleAffineEquiv_val, idealModuleAffineEquiv_val]
  rw [idealModuleAffineEquiv_val] at ht
  exact ht

/-- Multiplication of the actual ideal-power sheaves is an epimorphism. -/
instance idealPowerMul_epi (a b : ℕ) : Epi (idealPowerMul I a b) :=
  AffineModuleEpimorphisms.epi_of_affineOpen_surjective _
    (fun U hU ↦ idealPowerMul_affine_surjective I a b ⟨U, hU⟩)

/-- Multiplication remains an epimorphism after the two graded quotients. -/
instance idealGradedMul_epi (a b : ℕ) : Epi (idealGradedMul I a b) := by
  have : Epi (ModuleSheafTensor.map (cokernel.π (idealStep I a))
      (cokernel.π (idealStep I b)) ≫ idealGradedMul I a b) := by
    rw [idealGradedMul_projection]
    infer_instance
  exact epi_of_epi (ModuleSheafTensor.map (cokernel.π (idealStep I a))
    (cokernel.π (idealStep I b))) (idealGradedMul I a b)

/-- Every affine graded section is a finite sum of products of the two degrees. -/
lemma idealGradedMul_affine_surjective (a b : ℕ) (U : X.affineOpens) :
    Function.Surjective ((idealGradedMul I a b).app U.1) := by
  have := tensor_coherent (idealGraded I a) (idealGraded I b)
  exact affine_epi_surjective _ U

end FLT.Mazur.IdealAdicQuotient
