/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.IdealAdicBaseGradedGenerators

/-!
# Degree-zero generation over the actual graded base algebra

On each affine source open, the full direct sum of actual extended-ideal
quotients is generated over the graded base algebra by its degree-zero
coefficient. This is a statement about all degrees simultaneously; it does
not assert that degree zero is finite over the ring of base sections.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency.types false

open CategoryTheory AlgebraicGeometry
open Scheme.Modules FLT.Mazur.IdealAdicGradedSections

universe u

namespace FLT.Mazur.IdealAdicGradedPullback

variable {X Y : Scheme.{u}} [IsLocallyNoetherian X] [IsLocallyNoetherian Y] [IsAffine Y]
variable (J : Y.IdealSheafData) (f : X ⟶ Y)

/-- A homogeneous base coefficient acting on a degree-zero scalar is its scalar multiple. -/
lemma localBase_smul_scalar (U : X.Opens) (n : ℕ) (s : Piece J ⊤ n) (r : Γ(X, U)) :
    let := localBaseAlgebra J f U
    of J ⊤ n s • of (J.comap f) U 0 (scalar (J.comap f) U r) =
      of (J.comap f) U n (r • gradedSection J f n U s) := by
  let := localBaseAlgebra J f U
  change localRingHom J f U (of J ⊤ n s) *
    of (J.comap f) U 0 (scalar (J.comap f) U r) = _
  rw [localRingHom_of, mul_of, mul_scalar]
  rfl

/-- All affine graded coefficients together are generated by degree zero over the base algebra. -/
lemma degreeZero_span (U : X.affineOpens) :
    let := localBaseAlgebra J f U.1
    Submodule.span (IdealAdicGradedSections.Sections J ⊤)
      (Set.range (of (J.comap f) U.1 0)) = ⊤ := by
  let := localBaseAlgebra J f U.1
  let P := Submodule.span (IdealAdicGradedSections.Sections J ⊤) (Set.range (of (J.comap f) U.1 0))
  have hgen (n : ℕ) (s : Piece J ⊤ n) (r : Γ(X, U.1)) :
      of (J.comap f) U.1 n (r • gradedSection J f n U.1 s) ∈ P := by
    rw [← localBase_smul_scalar]
    exact P.smul_mem _ (Submodule.subset_span ⟨scalar (J.comap f) U.1 r, rfl⟩)
  have hall (n : ℕ) (t : Piece (J.comap f) U.1 n) :
      ∀ r : Γ(X, U.1), of (J.comap f) U.1 n (r • t) ∈ P := by
    have ht : t ∈ Submodule.span Γ(X, U.1) (Set.range (gradedSection J f n U.1)) := by
      rw [gradedSection_span]
      trivial
    induction ht using Submodule.span_induction with
    | mem t ht =>
      obtain ⟨s, rfl⟩ := ht
      exact hgen n s
    | zero => intro r; simp only [smul_zero, map_zero, Submodule.zero_mem]
    | add x y hx hy ihx ihy =>
      intro r
      rw [smul_add, map_add]
      exact P.add_mem (ihx r) (ihy r)
    | smul r x hx ih =>
      intro s
      rw [← mul_smul]
      exact ih (s * r)
  suffices h : ∀ t, t ∈ P from top_unique (fun t _ ↦ h t)
  intro t
  induction t using DirectSum.induction_on with
  | zero => exact P.zero_mem
  | of n t =>
    change of (J.comap f) U.1 n t ∈ P
    have ht := hall n t 1
    simpa only [one_smul] using ht
  | add x y hx hy => exact P.add_mem hx hy

end FLT.Mazur.IdealAdicGradedPullback
