/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.LineSectionZeroIdealOrbits

/-!
# The full zero ideal in an actual line frame

Evaluation on a framed line has precisely the principal ideal generated by
the scalar of the original section. No regularity assumption is needed for
this identification, so it can be used when constructing regularity.
-/

@[expose] public noncomputable section
open CategoryTheory AlgebraicGeometry Opposite
open Scheme.Modules
namespace FLT.Mazur.LineSectionFrameZeroIdeal
open FCurve
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
variable {X : Scheme.{0}}

/-- Evaluation on a structure-module section gives its principal ideal on every affine open. -/
theorem structure_ideal (s : Γ(X, ⊤)) (U : X.affineOpens) :
    (lineSectionZeroIdeal structureModule_locallyFreeRankOne s).ideal U =
      Ideal.span {X.presheaf.map U.1.leTop.op s} := by
  ext r
  rw [mem_lineSectionZeroIdeal, Ideal.mem_span_singleton]
  change (∃ φ : Γ(moduleSheafDual (structureModule X), U.1),
    moduleDualEval (structureModule X) U.1 φ (X.presheaf.map U.1.leTop.op s) = r) ↔ _
  constructor
  · rintro ⟨φ, rfl⟩
    refine ⟨moduleDualEval (structureModule X) U.1 φ (1 : Γ(X, U)), ?_⟩
    have h := (moduleDualEval (structureModule X) U.1 φ).map_smul
      (X.presheaf.map U.1.leTop.op s) (1 : Γ(X, U))
    simpa only [smul_eq_mul, mul_one] using h
  · rintro ⟨a, rfl⟩
    refine ⟨moduleDualUnitSection U.1 a, ?_⟩
    rw [moduleDualEval_unitSection, mul_comm]

/-- A sheaf frame computes the full zero ideal of the original section. -/
theorem ideal_eq_span {L : X.Modules} (hL : LocallyFreeRankOne L)
    (e : L ≅ structureModule X) (s : Γ(L, ⊤)) (U : X.affineOpens) :
    (lineSectionZeroIdeal hL s).ideal U =
      Ideal.span {X.presheaf.map U.1.leTop.op (e.hom.app ⊤ s)} := by
  rw [lineSectionZeroIdeal_eq_of_iso hL structureModule_locallyFreeRankOne e s
    (e.hom.app ⊤ s) rfl]
  exact structure_ideal _ U

/-- On an affine scheme the full global ideal is generated by the section's scalar. -/
theorem top_ideal_eq_span [IsAffine X] {L : X.Modules} (hL : LocallyFreeRankOne L)
    (e : L ≅ structureModule X) (s : Γ(L, ⊤)) :
    (lineSectionZeroIdeal hL s).ideal ⟨⊤, isAffineOpen_top X⟩ =
      Ideal.span {show Γ(X, ⊤) from e.hom.app ⊤ s} := by
  have h := ideal_eq_span hL e s ⟨⊤, isAffineOpen_top X⟩
  change _ = Ideal.span {X.presheaf.map (𝟙 (op ⊤)) (e.hom.app ⊤ s)} at h
  simpa only [X.presheaf.map_id, CommRingCat.id_apply] using h

end FLT.Mazur.LineSectionFrameZeroIdeal
