/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.ModuleSectionProjectiveTransition
public import FLT.Mazur.ModuleSectionCocycleIso
public import Mathlib.Tactic.IrreducibleDef

/-!
# The hyperplane pullback of a generating section family

The concrete transition calculation identifies the inverse-image cocycle with
the module generated by the sections. Compose its glued generator isomorphism
with the actual cocycle pullback comparison. No immersion is assumed.
-/

open CategoryTheory AlgebraicGeometry
open AlgebraicGeometry.Scheme.Modules
@[expose] public noncomputable section
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
namespace FLT.Mazur.FCurve
open ProjectiveSpace ModuleSheafUnitCocycle.Cocycle
attribute [local instance] MvPolynomial.gradedAlgebra
variable {X : Scheme} (M : X.Modules) {R : Type} [CommRing R] (n : ℕ)
    (t : Fin (n + 1) → Γ(M, ⊤))
    (ht : ⨆ i, sectionGeneratorOpen M (t i) = ⊤) (r : R →+* Γ(X, ⊤))

/-- The actual pullback of O(1) is the module of the generating section family. -/
irreducible_def sectionProjectiveOOneIso :
    (pullback (sectionProjectiveMorphism M n t ht r)).obj (O R n 1) ≅ M :=
  (twistCocycle R (Fin (n + 1)) 1).pullbackIso
    (sectionProjectiveMorphism M n t ht r) (iSup_chart R (Fin (n + 1))) ≪≫
  sectionCocycleIso M
    (fun i ↦ sectionProjectiveMorphism M n t ht r ⁻¹ᵁ chart R (Fin (n + 1)) i)
    t (fun i ↦ (sectionProjectiveMorphism_preimage_chart M n t ht r i).le)
    ((twistCocycle R (Fin (n + 1)) 1).inverseImage (sectionProjectiveMorphism M n t ht r))
    (inverseImage_cover (sectionProjectiveMorphism M n t ht r) (iSup_chart R (Fin (n + 1))))
    (sectionProjectiveMorphism_transition M n t ht r)

end FLT.Mazur.FCurve
