/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Presheaf.Generator
public import Mathlib.Algebra.Category.ModuleCat.Presheaf.Sheafification
public import Mathlib.Topology.Sheaves.Abelian

/-!
# Free module sheaves on opens

The sheafification of the free module presheaf on an open represents sections
on that open. Inclusions of opens induce monomorphisms, and precomposition
corresponds to restriction of sections.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency false

open CategoryTheory CategoryTheory.Limits TopologicalSpace Opposite

universe u

namespace FLT.Mazur.ModuleFreeOpen

variable {X : TopCat.{u}} (R : Sheaf (Opens.grothendieckTopology X) RingCat.{u})

/-- The free module sheaf generated by the representable of an open. -/
def freeOpen (U : Opens X) : SheafOfModules.{u} R :=
  (PresheafOfModules.sheafification (𝟙 R.obj)).obj
    ((PresheafOfModules.free R.obj).obj (yoneda.obj U))

/-- The map of free module sheaves induced by an inclusion of opens. -/
def freeOpenMap {U V : Opens X} (i : U ⟶ V) : freeOpen R U ⟶ freeOpen R V :=
  (PresheafOfModules.sheafification (𝟙 R.obj)).map
    ((PresheafOfModules.free R.obj).map (yoneda.map i))

/-- Maps from the free module sheaf on `U` are sections over `U`. -/
def freeOpenHomEquiv (U : Opens X) (M : SheafOfModules.{u} R) :
    (freeOpen R U ⟶ M) ≃ M.val.obj (op U) :=
  ((PresheafOfModules.sheafificationAdjunction (𝟙 R.obj)).homEquiv _ M).trans
    PresheafOfModules.freeYonedaEquiv

/-- Evaluation commutes with morphisms of module coefficients. -/
lemma freeOpenHomEquiv_naturality {M N : SheafOfModules.{u} R}
    (f : M ⟶ N) (U : Opens X) (g : freeOpen R U ⟶ M) :
    freeOpenHomEquiv R U N (g ≫ f) =
      f.val.app (op U) (freeOpenHomEquiv R U M g) := by
  rfl

/-- Evaluation sends precomposition along an inclusion to section restriction. -/
lemma freeOpenHomEquiv_naturality_open {U V : Opens X} (i : U ⟶ V)
    (M : SheafOfModules.{u} R) (g : freeOpen R V ⟶ M) :
    freeOpenHomEquiv R U M (freeOpenMap R i ≫ g) =
      M.val.map i.op (freeOpenHomEquiv R V M g) := by
  unfold freeOpenHomEquiv freeOpenMap
  simp only [Equiv.trans_apply]
  erw [Adjunction.homEquiv_naturality_left]
  let t := (PresheafOfModules.sheafificationAdjunction (𝟙 R.obj)).homEquiv _ M g
  change (((PresheafOfModules.free R.obj).map (yoneda.map i)) ≫ t).app (op U)
      (ModuleCat.freeMk (𝟙 U)) = M.val.map i.op (t.app (op V) (ModuleCat.freeMk (𝟙 V)))
  have h := ConcreteCategory.congr_hom (t.naturality i.op) (ModuleCat.freeMk (𝟙 V))
  simpa [PresheafOfModules.free, PresheafOfModules.freeObj] using! h

/-- Free presheaves carry inclusions of opens to monomorphisms. -/
instance mono_freeYonedaMap {U V : Opens X} (i : U ⟶ V) :
    Mono ((PresheafOfModules.free R.obj).map (yoneda.map i)) := by
  apply PresheafOfModules.mono_of_injective
  intro W
  apply Finsupp.mapDomain_injective
  intro a b _
  exact Subsingleton.elim (α := W.unop ⟶ U) a b

/-- Sheafification preserves the monomorphism associated to an open inclusion. -/
instance mono_freeOpenMap {U V : Opens X} (i : U ⟶ V) : Mono (freeOpenMap R i) := by
  unfold freeOpenMap
  infer_instance

@[simp]
lemma freeOpenMap_id (U : Opens X) : freeOpenMap R (𝟙 U) = 𝟙 (freeOpen R U) := by
  simp [freeOpenMap, freeOpen]

@[simp]
lemma freeOpenMap_comp {U V W : Opens X} (i : U ⟶ V) (j : V ⟶ W) :
    freeOpenMap R (i ≫ j) = freeOpenMap R i ≫ freeOpenMap R j := by
  simp [freeOpenMap]

end FLT.Mazur.ModuleFreeOpen
