/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.NormalizedSectionLine
public import FLT.Mazur.AffineTildeBaseChangeIso

/-!
# Base change of normalized section submodules

Extending the normalized generator gives an actual line submodule over the
new ring. The coordinatewise coefficient map exhibits scalar extension;
this follows from the proved coordinate trivializations, without flatness.
-/

@[expose] public noncomputable section
open CategoryTheory
universe u
set_option backward.isDefEq.respectTransparency false
namespace FLT.Mazur.NormalizedSectionLine
variable {R S T : Type u} [CommRing R] [CommRing S] [CommRing T] {ι : Type u}

/-- The line generated by the extended normalized section. -/
def baseChange (φ : R →+* S) (i : ι) (L : Chart R ι i) : Chart S ι i :=
  ofTuple S ι i (fun j ↦ φ (generator R ι i L j)) (by simp)

/-- The extended line's generator is obtained by extending each coordinate. -/
lemma generator_baseChange (φ : R →+* S) (i : ι) (L : Chart R ι i) :
    generator S ι i (baseChange φ i L) = fun j ↦ φ (generator R ι i L j) :=
  generator_ofTuple S ι i _ _

/-- Identity extension preserves the actual submodule. -/
lemma baseChange_id (i : ι) (L : Chart R ι i) : baseChange (.id R) i L = L :=
  ofTuple_generator R ι i L

/-- Successive extensions agree as actual submodules. -/
lemma baseChange_comp (φ : R →+* S) (ψ : S →+* T) (i : ι) (L : Chart R ι i) :
    baseChange ψ i (baseChange φ i L) = baseChange (ψ.comp φ) i L := by
  apply (tupleEquiv T ι i).symm.injective
  apply Subtype.ext
  change generator T ι i _ = generator T ι i _
  simp only [generator_baseChange, RingHom.comp_apply]

/-- Coordinate extension takes every vector in the original line into the extended line. -/
lemma coefficient_mem (φ : R →+* S) (i : ι) (L : Chart R ι i) (v : L.val) :
    (fun j ↦ φ (v.val j)) ∈ (baseChange φ i L).val := by
  have he : (fun j ↦ φ (v.val j)) = φ (v.val i) •
      generator S ι i (baseChange φ i L) := by
    rw [eq_smul_generator R ι i L v, generator_baseChange]
    ext j
    simp only [Pi.smul_apply, smul_eq_mul, map_mul, generator_coordinate, mul_one]
  rw [he]
  exact (baseChange φ i L).val.smul_mem _ (generator_mem S ι i _)

/-- The original coordinatewise map, viewed with the target's restricted scalar action. -/
def coefficientMap (φ : R →+* S) (i : ι) (L : Chart R ι i) :
    ModuleCat.of R L.val ⟶ (ModuleCat.restrictScalars φ).obj
      (ModuleCat.of S (baseChange φ i L).val) :=
  ModuleCat.ofHom (X := L.val)
    (Y := (ModuleCat.restrictScalars φ).obj (ModuleCat.of S (baseChange φ i L).val))
    { toFun v := ⟨fun j ↦ φ (v.val j), coefficient_mem φ i L v⟩
      map_add' v w := Subtype.ext (funext fun j ↦ φ.map_add (v.val j) (w.val j))
      map_smul' r v := Subtype.ext (funext fun j ↦ φ.map_mul r (v.val j)) }

/-- The coefficient map really is scalar extension of the original rank-one module. -/
lemma coefficientMap_isBaseChange (φ : R →+* S) (i : ι) (L : Chart R ι i) :
    let _ := φ.toAlgebra
    let _ := AffineTildeBaseChangeIso.restrictScalarTower (CommRingCat.ofHom φ)
      (ModuleCat.of S (baseChange φ i L).val)
    IsBaseChange S (coefficientMap φ i L).hom := by
  let _ := φ.toAlgebra
  let _ := AffineTildeBaseChangeIso.restrictScalarTower (CommRingCat.ofHom φ)
    (ModuleCat.of S (baseChange φ i L).val)
  apply (IsBaseChange.iff_of_equiv_comm (trivialization R ι i L)
    (trivialization S ι i (baseChange φ i L)) (f' := Algebra.linearMap R S) ?_).mpr
    (IsBaseChange.linearMap R S)
  apply LinearMap.ext
  intro v
  rfl

end FLT.Mazur.NormalizedSectionLine
