/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.NormalizedSectionLineSheafBaseChange

/-!
# Principal-open restriction of actual section-line inclusions

Restrict to the basic open and transport along its canonical localization
isomorphism. The resulting line and ambient sheaves are the tilde sheaves
of their localized coefficient modules, with the original inclusion square.
-/

@[expose] public noncomputable section
open CategoryTheory AlgebraicGeometry
open Scheme.Modules
universe u
set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true
namespace FLT.Mazur.NormalizedSectionLine
variable {R : Type u} [CommRing R] {ι : Type u}

/-- Restriction to a principal open expressed on its actual localization spectrum. -/
def principalRestriction (r : R) :
    (Spec (.of R)).Modules ⥤ (Spec (.of (Localization.Away r))).Modules :=
  restrictFunctor (Scheme.Opens.ι (X := Spec (.of R)) (PrimeSpectrum.basicOpen r)) ⋙
    restrictFunctor (basicOpenIsoSpecAway (R := .of R) r).inv

/-- The localization chart followed by the open inclusion is the localization map. -/
lemma principal_chart_comp (r : R) :
    (basicOpenIsoSpecAway (R := .of R) r).inv ≫
        Scheme.Opens.ι (X := Spec (.of R)) (PrimeSpectrum.basicOpen r) =
      Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away r))) := by
  rw [← basicOpenIsoSpecAway_hom_SpecMap (R := .of R) r, Iso.inv_hom_id_assoc]

/-- Restriction on the actual principal chart is naturally the localization pullback. -/
def principalRestrictionIso (r : R) :
    principalRestriction r ≅
      pullback (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away r)))) :=
  (restrictFunctorComp (basicOpenIsoSpecAway (R := .of R) r).inv
    (Scheme.Opens.ι (X := Spec (.of R)) (PrimeSpectrum.basicOpen r))).symm ≪≫
      restrictFunctorIsoPullback _ ≪≫ pullbackCongr (principal_chart_comp r)

/-- The restricted line is the actual line generated by localized coordinates. -/
def sheafPrincipalRestriction (r : R) (i : ι) (L : Chart R ι i) :
    (principalRestriction r).obj (sheaf i L) ≅
      sheaf i (baseChange (algebraMap R (Localization.Away r)) i L) :=
  (principalRestrictionIso r).app (sheaf i L) ≪≫
    sheafBaseChange (algebraMap R (Localization.Away r)) i L

/-- The same principal-open comparison for the finite ambient coordinate sheaf. -/
def vectorPrincipalRestriction [Finite ι] (r : R) :
    (principalRestriction r).obj (tilde (ModuleCat.of R (ι → R))) ≅
      tilde (ModuleCat.of (Localization.Away r) (ι → Localization.Away r)) :=
  (principalRestrictionIso r).app _ ≪≫
    vectorSheafBaseChange ι (algebraMap R (Localization.Away r))

attribute [local irreducible] sheafBaseChange vectorSheafBaseChange
attribute [local irreducible] principalRestriction principalRestrictionIso

/-- Principal restriction identifies the actual inclusions, not just their source objects. -/
lemma sheafPrincipalRestriction_inclusion [Finite ι] (r : R) (i : ι)
    (L : Chart R ι i) :
    (sheafPrincipalRestriction r i L).hom ≫
        sheafInclusion i (baseChange (algebraMap R (Localization.Away r)) i L) =
      (principalRestriction r).map (sheafInclusion i L) ≫
        (vectorPrincipalRestriction (ι := ι) r).hom := by
  dsimp only [sheafPrincipalRestriction, vectorPrincipalRestriction, Iso.trans_hom,
    Iso.app_hom]
  rw [Category.assoc, sheafBaseChange_inclusion]
  exact ((principalRestrictionIso r).hom.naturality_assoc (sheafInclusion i L)
    (vectorSheafBaseChange ι (algebraMap R (Localization.Away r))).hom).symm

end FLT.Mazur.NormalizedSectionLine
