/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.CharP.Basic
public import Mathlib.NumberTheory.Padics.PadicIntegers
public import Mathlib.RingTheory.Valuation.ValuationSubring

/-!
# The rational p-adic valuation ring

Package the usual p-adic integers as a valuation subring of the p-adic field.
Its ring structure is definitionally the usual one, so maximal-ideal generation
and adic completeness are inherited from the existing p-adic integer theorems.
-/

@[expose] public noncomputable section

namespace FLT.Mazur
open IsLocalRing

variable (p : ℕ) [Fact p.Prime]

/-- The ordinary p-adic integers viewed as a valuation subring of the p-adic field. -/
def padicIntegerSubring : ValuationSubring ℚ_[p] where
  __ := PadicInt.subring p
  mem_or_inv_mem' x := by
    by_cases hx : ‖x‖ ≤ 1
    · exact Or.inl hx
    · exact Or.inr (by simpa using inv_le_one_of_one_le₀ (le_of_not_ge hx))

/-- This presentation has exactly the underlying ring of ordinary p-adic integers. -/
def padicIntegerSubringEquiv : padicIntegerSubring p ≃+* ℤ_[p] := RingEquiv.refl _

/-- The actual maximal ideal is generated by p. -/
theorem padicIntegerSubring_maximalIdeal :
    maximalIdeal (padicIntegerSubring p) = Ideal.span {(p : padicIntegerSubring p)} :=
  PadicInt.maximalIdeal_eq_span_p

instance : IsAdicComplete (maximalIdeal (padicIntegerSubring p)) (padicIntegerSubring p) :=
  inferInstanceAs (IsAdicComplete (maximalIdeal ℤ_[p]) ℤ_[p])

/-- The actual residue field has characteristic p. -/
instance : CharP (ResidueField (padicIntegerSubring p)) p := by
  apply (CharP.charP_iff_prime_eq_zero Fact.out).mpr
  rw [← map_natCast (residue (padicIntegerSubring p)), residue_eq_zero_iff,
    padicIntegerSubring_maximalIdeal]
  exact Ideal.subset_span (by simp)

end FLT.Mazur
