/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.PolygonNodeBranches
public import Mathlib.RingTheory.FinitePresentation
public import Mathlib.Algebra.Polynomial.Div

/-!
# Finite presentation of the polygon node charts

The split node is generated by its two branch coordinates. The one-gon chart
is the subalgebra of polynomials with equal values at zero and one.
-/

@[expose] public noncomputable section

open CategoryTheory AlgebraicGeometry Polynomial

namespace FLT.Mazur.PolygonNodePresentation

open PolygonNodeEqualizer PolygonNodeLocalization

variable {R : Type*} [CommRing R]

/-- Evaluation at the common origin of the two branches. -/
def aEval : A (R := R) →ₐ[R] R := (aeval 0).comp first

/-- The two branch coordinates generate the node algebra. -/
theorem a_adjoin : Algebra.adjoin R ({x, y} : Set (A (R := R))) = ⊤ := by
  apply top_unique
  intro p _
  let S := Algebra.adjoin R ({x, y} : Set (A (R := R)))
  have hx : x (R := R) ∈ S := Algebra.subset_adjoin (by simp)
  have hy : y (R := R) ∈ S := Algebra.subset_adjoin (by simp)
  have he : p = aeval x (first p) + aeval y (second p) -
      algebraMap R (A (R := R)) (aEval p) := by
    have hp : (first p).eval 0 = (second p).eval 0 := p.property
    apply Subtype.ext
    apply Prod.ext
    · change first p = first (aeval x (first p) + aeval y (second p) -
        algebraMap R (A (R := R)) (aEval p))
      simp [aEval, aeval_def, coeff_zero_eq_eval_zero, hp]
    · change second p = second (aeval x (first p) + aeval y (second p) -
        algebraMap R (A (R := R)) (aEval p))
      simp [aEval, aeval_def, coeff_zero_eq_eval_zero, add_sub_cancel_left]
  rw [he]
  have hxp : aeval x (first p) ∈ S := by
    simpa only [coe_aeval_mk_apply] using (aeval (⟨x, hx⟩ : S) (first p)).property
  have hyp : aeval y (second p) ∈ S := by
    simpa only [coe_aeval_mk_apply] using (aeval (⟨y, hy⟩ : S) (second p)).property
  exact S.sub_mem (S.add_mem hxp hyp) (S.algebraMap_mem _)

instance a_finiteType : Algebra.FiniteType R (A (R := R)) :=
  ⟨Subalgebra.fg_def.mpr ⟨{x, y}, Set.toFinite _, a_adjoin⟩⟩

/-- Functions on the normalization with its two endpoints identified. -/
def B : Subalgebra R R[X] := AlgHom.equalizer (aeval (0 : R)) (aeval (1 : R))

@[simp]
theorem mem_B (p : R[X]) : p ∈ B (R := R) ↔ p.eval 0 = p.eval 1 := by
  simp [B, AlgHom.equalizer]

/-- Evaluation at the identified endpoints. -/
def bEval : B (R := R) →ₐ[R] R := (aeval 0).comp (B (R := R)).val

/-- The function vanishing at both endpoints. -/
def u : B (R := R) := ⟨X * (X - 1), by simp⟩

/-- A second generator of the one-gon chart. -/
def v : B (R := R) := ⟨X * (X * (X - 1)), by simp⟩

/-- The nodal plane equation, valid over every commutative ring. -/
theorem relation : v (R := R) ^ 2 - u * v - u ^ 3 = 0 := by
  apply Subtype.ext
  change (X * (X * (X - 1))) ^ 2 - X * (X - 1) * (X * (X * (X - 1))) -
    (X * (X - 1)) ^ 3 = (0 : R[X])
  ring

/-- Subtracting the common value leaves a multiple of the conductor. -/
theorem conductor_dvd (p : B (R := R)) :
    X * (X - 1) ∣ p.val - C (bEval p) := by
  have h0 : X ∣ p.val - C (bEval p) := by
    rw [X_dvd_iff]
    simp [bEval, coeff_zero_eq_eval_zero]
  obtain ⟨q, hq⟩ := h0
  have h1 : q.eval 1 = 0 := by
    have h := congrArg (eval (1 : R)) hq
    have hp := (mem_B _).mp p.property
    simpa [bEval, aeval_def, hp] using h.symm
  obtain ⟨r, hr⟩ := (dvd_iff_isRoot (p := q) (a := (1 : R))).mpr h1
  refine ⟨r, ?_⟩
  simpa [hr, mul_assoc] using hq

/-- Conductor monomials belong to the algebra generated by u and v. -/
theorem conductor_monomial_mem (n : ℕ) :
    (X * (X - 1) * X ^ n : R[X]) ∈
      Algebra.adjoin R ({(u (R := R)).val, (v (R := R)).val} : Set R[X]) := by
  let S := Algebra.adjoin R ({(u (R := R)).val, (v (R := R)).val} : Set R[X])
  have hu : X * (X - 1) ∈ S := Algebra.subset_adjoin (by simp [u])
  have hv : X * (X * (X - 1)) ∈ S := Algebra.subset_adjoin (by simp [v])
  induction n using Nat.twoStepInduction with
  | zero => simpa using hu
  | one => simpa [mul_comm] using hv
  | more n hn hn1 =>
    have he : (X * (X - 1) * X ^ (n + 2) : R[X]) =
        (X * (X - 1)) * (X * (X - 1) * X ^ n) + X * (X - 1) * X ^ (n + 1) := by
      ring
    rw [he]
    exact S.add_mem (S.mul_mem hu hn) hn1

/-- Explicit generators for the one-gon chart as a subalgebra of R[X]. -/
theorem b_adjoin :
    Algebra.adjoin R ({(u (R := R)).val, (v (R := R)).val} : Set R[X]) = B := by
  apply le_antisymm
  · exact Algebra.adjoin_le (by
      intro p hp
      rcases hp with rfl | hp
      · exact (u (R := R)).property
      · rcases hp with rfl
        exact (v (R := R)).property)
  · intro p hp
    let S := Algebra.adjoin R ({(u (R := R)).val, (v (R := R)).val} : Set R[X])
    obtain ⟨q, hq⟩ := conductor_dvd (⟨p, hp⟩ : B (R := R))
    have hm : ∀ q : R[X], X * (X - 1) * q ∈ S := by
      intro q
      induction q using Polynomial.induction_on' with
      | add p q hp hq => simpa [mul_add] using S.add_mem hp hq
      | monomial n r =>
        rw [← C_mul_X_pow_eq_monomial]
        simpa only [Algebra.algebraMap_self, algebraMap_eq, mul_comm, mul_left_comm,
          mul_assoc] using
          S.mul_mem (S.algebraMap_mem r) (conductor_monomial_mem (R := R) n)
    have he : p = C (bEval (⟨p, hp⟩ : B (R := R))) + X * (X - 1) * q := by
      linear_combination hq
    rw [he]
    exact S.add_mem (S.algebraMap_mem _) (hm q)

instance b_finiteType : Algebra.FiniteType R (B (R := R)) := by
  rw [← b_adjoin]
  exact Algebra.FiniteType.adjoin_of_finite (Set.toFinite _)

/-- Restriction to the punctured normalization of the one-gon chart. -/
def bPunctureMap : B (R := R) →+* Localization.Away (X * (X - 1) : R[X]) :=
  (algebraMap R[X] _).comp (B (R := R)).val.toRingHom

/-- Inverting the conductor removes precisely the pinching on the ring level. -/
theorem b_isLocalization :
    let := (bPunctureMap (R := R)).toAlgebra
    IsLocalization.Away (u (R := R)) (Localization.Away (X * (X - 1) : R[X])) := by
  let L := Localization.Away (X * (X - 1) : R[X])
  let := (bPunctureMap (R := R)).toAlgebra
  apply IsLocalization.Away.mk
  · exact IsLocalization.Away.algebraMap_isUnit (S := L) (X * (X - 1) : R[X])
  · intro z
    obtain ⟨n, p, hp⟩ := IsLocalization.Away.surj (X * (X - 1) : R[X]) z
    let a : B (R := R) := ⟨X * (X - 1) * p, by simp⟩
    refine ⟨n + 1, a, ?_⟩
    change z * (algebraMap R[X] L (X * (X - 1))) ^ (n + 1) =
      algebraMap R[X] L (X * (X - 1) * p)
    rw [pow_succ, ← mul_assoc, hp]
    simp only [map_mul]
    ring
  · intro a b h
    change algebraMap R[X] L a.val = algebraMap R[X] L b.val at h
    obtain ⟨n, hn⟩ := IsLocalization.Away.exists_of_eq (X * (X - 1) : R[X]) h
    exact ⟨n, Subtype.ext hn⟩

variable (K : Type*) [Field K]

instance a_finitePresentation : Algebra.FinitePresentation K (A (R := K)) :=
  Algebra.FinitePresentation.of_finiteType.mp inferInstance

instance b_finitePresentation : Algebra.FinitePresentation K (B (R := K)) :=
  Algebra.FinitePresentation.of_finiteType.mp inferInstance

/-- Structure morphism of the two-branch chart. -/
abbrev aToBase := PolygonNodeBranches.toBase K

/-- Structure morphism of the one-gon chart. -/
def bToBase : Spec (.of (B (R := K))) ⟶ Spec (.of K) :=
  Spec.map (CommRingCat.ofHom (algebraMap K (B (R := K))))

instance a_locallyOfFinitePresentation : LocallyOfFinitePresentation (aToBase K) := by
  change LocallyOfFinitePresentation (Spec.map (CommRingCat.ofHom
    (algebraMap K (A (R := K)))))
  rw [LocallyOfFinitePresentation.SpecMap_iff]
  change (algebraMap K _).FinitePresentation
  rw [RingHom.finitePresentation_algebraMap]
  infer_instance

instance b_locallyOfFinitePresentation : LocallyOfFinitePresentation (bToBase K) := by
  change LocallyOfFinitePresentation (Spec.map (CommRingCat.ofHom
    (algebraMap K (B (R := K)))))
  rw [LocallyOfFinitePresentation.SpecMap_iff]
  change (algebraMap K _).FinitePresentation
  rw [RingHom.finitePresentation_algebraMap]
  infer_instance

/-- The origin of the two-branch chart. -/
def aOrigin : Spec (.of K) ⟶ PolygonNodeBranches.node K :=
  Spec.map (CommRingCat.ofHom (aEval (R := K)).toRingHom)

/-- The origin of the one-gon chart. -/
def bOrigin : Spec (.of K) ⟶ Spec (.of (B (R := K))) :=
  Spec.map (CommRingCat.ofHom (bEval (R := K)).toRingHom)

/-- The punctured normalization maps to the one-gon chart. -/
def bPuncture : Spec (.of (Localization.Away (X * (X - 1) : K[X]))) ⟶
    Spec (.of (B (R := K))) := Spec.map (CommRingCat.ofHom bPunctureMap)

instance bPuncture_isOpenImmersion : IsOpenImmersion (bPuncture K) := by
  let := (bPunctureMap (R := K)).toAlgebra
  let := b_isLocalization (R := K)
  exact IsOpenImmersion.of_isLocalization (u (R := K))

/-- The puncture is exactly the basic open of the conductor. -/
theorem range_bPuncture : Set.range (bPuncture K) =
    (PrimeSpectrum.basicOpen (u (R := K)) : Set (PrimeSpectrum (B (R := K)))) := by
  let := (bPunctureMap (R := K)).toAlgebra
  let := b_isLocalization (R := K)
  exact PrimeSpectrum.localization_away_comap_range _ (u (R := K))

instance bPuncture_smooth : Smooth (bPuncture K ≫ bToBase K) := by
  let L := Localization.Away (X * (X - 1) : K[X])
  have h : (bPunctureMap (R := K)).comp (algebraMap K (B (R := K))) =
      algebraMap K L := by
    ext r
    exact (IsScalarTower.algebraMap_apply K K[X] L r).symm
  change Smooth (Spec.map _ ≫ Spec.map _)
  rw [← Spec.map_comp, ← CommRingCat.ofHom_comp, h]
  rw [HasRingHomProperty.Spec_iff (P := @Smooth)]
  change (algebraMap K L).Smooth
  rw [RingHom.smooth_algebraMap]
  let : Algebra.Smooth K K[X] := {}
  let : Algebra.Smooth K[X] L := Algebra.Smooth.of_isLocalization_Away (X * (X - 1))
  exact Algebra.Smooth.comp K K[X] L

/-- Both Laurent branches of the split node lie in its smooth locus. -/
theorem a_branches_smooth :
    Set.range (PolygonNodeBranches.left K) ∪ Set.range (PolygonNodeBranches.right K) ⊆
      (aToBase K).smoothLocus := by
  rintro _ (⟨z, rfl⟩ | ⟨z, rfl⟩)
  · change z ∈ (PolygonNodeBranches.left K) ⁻¹ᵁ (aToBase K).smoothLocus
    rw [Scheme.Hom.preimage_smoothLocus_eq, Scheme.Hom.smoothLocus_eq_top]
    trivial
  · change z ∈ (PolygonNodeBranches.right K) ⁻¹ᵁ (aToBase K).smoothLocus
    rw [Scheme.Hom.preimage_smoothLocus_eq, Scheme.Hom.smoothLocus_eq_top]
    trivial

/-- Away from the conductor the one-gon chart is smooth. -/
theorem b_puncture_smooth : Set.range (bPuncture K) ⊆ (bToBase K).smoothLocus := by
  rintro _ ⟨z, rfl⟩
  change z ∈ (bPuncture K) ⁻¹ᵁ (bToBase K).smoothLocus
  rw [Scheme.Hom.preimage_smoothLocus_eq, Scheme.Hom.smoothLocus_eq_top]
  trivial

/-- The closed origin of the split node is cut out by evaluation. -/
theorem range_aOrigin : Set.range (aOrigin K) =
    PrimeSpectrum.zeroLocus (RingHom.ker (aEval (R := K)).toRingHom) := by
  apply range_comap_of_surjective
  intro r
  exact ⟨algebraMap K _ r, (aEval (R := K)).commutes r⟩

/-- The closed origin of the one-gon chart is cut out by evaluation. -/
theorem range_bOrigin : Set.range (bOrigin K) =
    PrimeSpectrum.zeroLocus (RingHom.ker (bEval (R := K)).toRingHom) := by
  apply range_comap_of_surjective
  intro r
  exact ⟨algebraMap K _ r, (bEval (R := K)).commutes r⟩

end FLT.Mazur.PolygonNodePresentation
