/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.PolygonStageLineLayer
public import FLT.Mazur.PolygonStageRestrictionIdeal

/-!
# Principal affine coordinates of the actual stage parameter ideal

The extended parameter ideal is generated by the original structural
parameter section. Its powers use the powers of that same section.
-/

@[expose] public noncomputable section

open CategoryTheory AlgebraicGeometry

namespace FLT.Mazur.PolygonInfinitesimalStages

open FCurve ModuleLineBundleTensorPullback BaseAdicThickening

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

variable (R : Type) [CommRing R] (m n : ℕ) (h : 2 ≤ n)

/-- The actual smoothing parameter viewed as a global structural section. -/
def stageParameterSection : Γ((family R m n h).left, ⊤) :=
  stageScalars R m n h (parameter R m)

/-- The power ideal is generated by the corresponding original parameter section. -/
theorem stageParameterPower_ideal (k : ℕ) (U : (family R m n h).left.affineOpens) :
    (stageParameterIdeal R m n h ^ k).ideal U =
      Ideal.span {((family R m n h).left.presheaf.map U.1.leTop.op
        (stageParameterSection R m n h ^ k))} := by
  rw [stageParameterIdeal, extendedPower_ideal, Ideal.span_singleton_pow,
    Ideal.map_span, Set.image_singleton]
  congr 2
  rw [map_pow, map_pow]
  rfl

/-- The first parameter ideal has its original principal generator on every affine open. -/
theorem stageParameterIdeal_ideal (U : (family R m n h).left.affineOpens) :
    (stageParameterIdeal R m n h).ideal U =
      Ideal.span {((family R m n h).left.presheaf.map U.1.leTop.op
        (stageParameterSection R m n h))} := by
  simpa only [pow_one] using stageParameterPower_ideal R m n h 1 U

/-- The affine last-power annihilator is the actual parameter ideal acting on the line. -/
theorem boundaryPower_last_annihilator (d : ℕ)
    (U : (family R (m + 1) n h).left.affineOpens)
    (s : Γ(tensorPower (boundaryLine R (m + 1) n h) d, U.1)) :
    (family R (m + 1) n h).left.presheaf.map U.1.leTop.op
        (stageParameterSection R (m + 1) n h ^ (m + 1)) • s = 0 ↔
      s ∈ (stageParameterIdeal R (m + 1) n h).ideal U •
        (⊤ : Submodule Γ((family R (m + 1) n h).left, U.1)
          Γ(tensorPower (boundaryLine R (m + 1) n h) d, U.1)) := by
  let _ := boundaryPowerSections_flat R (m + 1) n h d U.1 U.2
  rw [stageParameterIdeal_ideal, Submodule.ideal_span_singleton_smul]
  simp only [Submodule.mem_smul_pointwise_iff_exists, Submodule.mem_top, true_and]
  have he := flat_last_smul_eq_zero_iff R m
    (boundaryPowerSections R (m + 1) n h d U.1) s
  change (family R (m + 1) n h).left.presheaf.map U.1.leTop.op
      (stageScalars R (m + 1) n h (parameter R (m + 1) ^ (m + 1))) • s = 0 ↔
    ∃ y, (family R (m + 1) n h).left.presheaf.map U.1.leTop.op
      (stageScalars R (m + 1) n h (parameter R (m + 1))) • y = s at he
  simpa only [stageParameterSection, map_pow] using he

end FLT.Mazur.PolygonInfinitesimalStages
