/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.PolygonCompatibleVeronese

/-!
# The actual parameter ideal of the compatible Veronese

The retained complete-base algebra map determines its parameter ideal.
Every original stage evaluation kills the prescribed power of that ideal.
-/

@[expose] public noncomputable section

open CategoryTheory AlgebraicGeometry

namespace FLT.Mazur.PolygonInfinitesimalStages

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

attribute [local irreducible] compatibleEval

variable (R : Type) [CommRing R] (n : ℕ) (h : 2 ≤ n) (q : ℕ)

/-- The Veronese retains the complete-base scalar map at every original stage. -/
theorem compatibleVeroneseEval_algebraMap (m : ℕ) (r : PowerSeries R) :
    compatibleVeroneseEval R n h q m
      (algebraMap (PowerSeries R) (CompatibleVeroneseSections R n h q) r) =
        boundarySeriesScalars R n h m r := by
  change compatibleEval R n h m (DirectSum.coeRingHom (compatibleVeroneseDegree R n h q) _) = _
  rw [show DirectSum.coeRingHom (compatibleVeroneseDegree R n h q)
      (algebraMap (PowerSeries R) (CompatibleVeroneseSections R n h q) r) =
    algebraMap (PowerSeries R) (CompatibleSections R n h) r from
      (DirectSum.coeAlgHom (compatibleVeroneseDegree R n h q)).commutes r]
  exact compatibleEval_algebraMap R n h m r

/-- The parameter ideal is generated by the original complete-base parameter. -/
def compatibleVeroneseParameterIdeal : Ideal (CompatibleVeroneseSections R n h q) :=
  Ideal.span {algebraMap (PowerSeries R) (CompatibleVeroneseSections R n h q) PowerSeries.X}

/-- The original stage evaluation kills the corresponding actual parameter-ideal power. -/
theorem compatibleVeroneseParameterIdeal_le_ker (m : ℕ) :
    compatibleVeroneseParameterIdeal R n h q ^ (m + 1) ≤
      RingHom.ker (compatibleVeroneseEval R n h q m) := by
  rw [compatibleVeroneseParameterIdeal, Ideal.span_singleton_pow, Ideal.span_singleton_le_iff_mem]
  change compatibleVeroneseEval R n h q m
    ((algebraMap (PowerSeries R) (CompatibleVeroneseSections R n h q) PowerSeries.X) ^
      (m + 1)) = 0
  rw [← map_pow, compatibleVeroneseEval_algebraMap]
  apply boundarySeriesScalars_vanish
  rw [parameterIdeal, Ideal.span_singleton_pow]
  exact Ideal.subset_span (Set.mem_singleton _)

end FLT.Mazur.PolygonInfinitesimalStages
