/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.PolygonVeroneseEvaluationKernel

/-!
# Adic reduction to the original stage Veronese rings

Define the stage Veronese independently from the actual homogeneous stage
sections and their original multiplication. Evaluation has exactly this
image and its proved kernel is the actual parameter-ideal power.
-/

@[expose] public noncomputable section

open CategoryTheory AlgebraicGeometry
open scoped DirectSum

namespace FLT.Mazur.PolygonInfinitesimalStages

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

attribute [local irreducible] compatibleEval boundaryLine family

variable (K : Type) [Field K] (n : ℕ) (h : 2 ≤ n)

/-- The original stage ring generated by its retained tensor degrees. -/
def boundaryVeroneseRing (q m : ℕ) : Subring (boundaryGradedSections K n h m) :=
  Subring.closure (⋃ d : ℕ, (SectionGradedSum.grade (boundaryLine K m n h) ⊤ (q * d) : Set _))

/-- Every actual compatible Veronese evaluation belongs to the independently defined stage ring. -/
theorem compatibleVeroneseEval_mem (q m : ℕ) (s : CompatibleVeroneseSections K n h q) :
    compatibleVeroneseEval K n h q m s ∈ boundaryVeroneseRing K n h q m := by
  induction s using DirectSum.induction_on with
  | zero => rw [map_zero]; exact (boundaryVeroneseRing K n h q m).zero_mem
  | of d s =>
    rw [compatibleVeroneseEval_of]
    apply Subring.subset_closure
    exact Set.mem_iUnion.mpr ⟨d, s.property m⟩
  | add s t hs ht =>
    rw [map_add]
    exact (boundaryVeroneseRing K n h q m).add_mem hs ht

variable [NeZero n]

/-- Evaluation reaches exactly the original stage Veronese, in every retained degree. -/
theorem exactVeroneseEval_range (m : ℕ) :
    (compatibleVeroneseEval K n h (exactVeroneseStep K n h) m).range =
      boundaryVeroneseRing K n h (exactVeroneseStep K n h) m := by
  apply le_antisymm
  · rintro s ⟨t, rfl⟩
    exact compatibleVeroneseEval_mem K n h _ m t
  · apply Subring.closure_le.mpr
    intro s hs
    obtain ⟨d, hd⟩ := Set.mem_iUnion.mp hs
    obtain ⟨t, ht⟩ := exactVeroneseDegree_surjective K n h d m ⟨s, hd⟩
    refine ⟨DirectSum.of _ d t, ?_⟩
    exact (compatibleVeroneseEval_of K n h _ m d t).trans (congrArg Subtype.val ht)

/-- The actual parameter-adic quotient is the independently defined original stage Veronese. -/
def exactVeroneseAdicReduction (m : ℕ) :
    (CompatibleVeroneseSections K n h (exactVeroneseStep K n h) ⧸
      compatibleVeroneseParameterIdeal K n h (exactVeroneseStep K n h) ^ (m + 1)) ≃+*
        boundaryVeroneseRing K n h (exactVeroneseStep K n h) m :=
  ((Ideal.quotEquivOfEq (exactVeroneseEval_ker K n h m).symm).trans
    (RingHom.quotientKerEquivRange
      (compatibleVeroneseEval K n h (exactVeroneseStep K n h) m))).trans
    (RingEquiv.subringCongr (exactVeroneseEval_range K n h m))

/-- The ring isomorphism retains the actual evaluation on every representative. -/
theorem exactVeroneseAdicReduction_mk (m : ℕ)
    (s : CompatibleVeroneseSections K n h (exactVeroneseStep K n h)) :
    (exactVeroneseAdicReduction K n h m (Ideal.Quotient.mk _ s)).val =
      compatibleVeroneseEval K n h (exactVeroneseStep K n h) m s := rfl

/-- Reduction retains the original complete-base coefficients inside the original stage ring. -/
theorem exactVeroneseAdicReduction_scalar (m : ℕ) (r : PowerSeries K) :
    (exactVeroneseAdicReduction K n h m (Ideal.Quotient.mk _
      (algebraMap (PowerSeries K)
        (CompatibleVeroneseSections K n h (exactVeroneseStep K n h)) r))).val =
      boundarySeriesScalars K n h m r := by
  rw [exactVeroneseAdicReduction_mk, compatibleVeroneseEval_algebraMap]

/-- The recovered rings retain every original stage map on all original representatives. -/
theorem exactVeroneseAdicReduction_transition {a b : ℕ} (f : a ⟶ b)
    (s : CompatibleVeroneseSections K n h (exactVeroneseStep K n h)) :
    boundarySectionsMap K n h f
      (exactVeroneseAdicReduction K n h b (Ideal.Quotient.mk _ s)).val =
        (exactVeroneseAdicReduction K n h a (Ideal.Quotient.mk _ s)).val := by
  rw [exactVeroneseAdicReduction_mk, exactVeroneseAdicReduction_mk]
  exact DFunLike.congr_fun (compatibleVeroneseEval_transition K n h _ f) s

end FLT.Mazur.PolygonInfinitesimalStages
