/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.PolygonNodePresentation
public import Mathlib.AlgebraicGeometry.Morphisms.Finite
public import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic
/-!
# Finite normalization algebras of the polygon charts

The split node embeds into the product of its branch rings with two module
generators. The one-gon embeds into its polynomial normalization, generated
by the integral coordinate X. Both maps are finite and surjective on spectra
over arbitrary commutative coefficient rings.
-/

@[expose] public noncomputable section
set_option backward.isDefEq.respectTransparency false
open AlgebraicGeometry CategoryTheory Polynomial
namespace FLT.Mazur.PolygonNormalizationAlgebra
open PolygonNodeEqualizer PolygonNodePresentation
variable {R : Type*} [CommRing R]

/-- The branch product is generated by one and the first-branch idempotent. -/
theorem node_span :
    Submodule.span (A (R := R)) ({1, (1, 0)} : Set (R[X] × R[X])) = ⊤ := by
  apply top_unique
  intro p _
  let c : A (R := R) := algebraMap R _ (p.1.eval 0 - p.2.eval 0)
  let q : A (R := R) := ⟨(p.1 - C (p.1.eval 0 - p.2.eval 0), p.2), by simp⟩
  have h : p = q • (1 : R[X] × R[X]) + c • (1, 0) := by
    apply Prod.ext <;> simp [q, c, Algebra.smul_def]
  rw [h]
  exact Submodule.add_mem _
    (Submodule.smul_mem _ _ (Submodule.subset_span (by simp)))
    (Submodule.smul_mem _ _ (Submodule.subset_span (by simp)))

instance node_finite : Module.Finite (A (R := R)) (R[X] × R[X]) := by
  classical
  apply Module.Finite.of_fg_top
  exact ⟨{1, (1, 0)}, by simpa using node_span (R := R)⟩

/-- The normalization coordinate generates the polynomial algebra over the one-gon. -/
theorem oneGon_adjoin : Algebra.adjoin (B (R := R)) ({X} : Set R[X]) = ⊤ := by
  apply top_unique
  intro p hp
  clear hp
  induction p using Polynomial.induction_on' with
  | add p q hp hq => exact add_mem hp hq
  | monomial n r =>
    rw [← C_mul_X_pow_eq_monomial]
    exact mul_mem
      ((Algebra.adjoin (B (R := R)) {X}).algebraMap_mem (algebraMap R _ r))
      (pow_mem (Algebra.subset_adjoin (by simp)) _)

/-- The normalization coordinate satisfies the monic equation t²-t-u. -/
theorem oneGon_integral_X : IsIntegral (B (R := R)) (X : R[X]) := by
  refine ⟨X ^ 2 - (X + C u), monic_X_pow_sub ?_, ?_⟩
  · exact lt_of_le_of_lt (degree_add_le _ _) (by
      exact max_lt (lt_of_le_of_lt degree_X_le (by norm_num))
        (lt_of_le_of_lt degree_C_le (by norm_num)))
  · change aeval (X : R[X]) (X ^ 2 - (X + C (u (R := R)))) = 0
    simp only [aeval_def, eval₂_sub, eval₂_pow, eval₂_add, eval₂_X, eval₂_C]
    change (X : R[X]) ^ 2 - (X + X * (X - 1)) = 0
    ring

instance oneGon_finite : Module.Finite (B (R := R)) R[X] := by
  have h := oneGon_integral_X (R := R) |>.fg_adjoin_singleton
  rw [oneGon_adjoin] at h
  exact Module.Finite.of_fg_top h

/-- The split-node normalization is a finite ring map. -/
theorem node_inclusion_finite : (inclusion (R := R)).toRingHom.Finite := by
  change (algebraMap (A (R := R)) (R[X] × R[X])).Finite
  rw [RingHom.finite_algebraMap]
  infer_instance

/-- The one-gon normalization is a finite ring map. -/
theorem oneGon_inclusion_finite : (B (R := R)).val.toRingHom.Finite := by
  change (algebraMap (B (R := R)) R[X]).Finite
  rw [RingHom.finite_algebraMap]
  infer_instance

/-- Every prime of the node has a prime above it on a branch. -/
theorem node_comap_surjective :
    Function.Surjective (PrimeSpectrum.comap (inclusion (R := R)).toRingHom) :=
  (node_inclusion_finite (R := R)).to_isIntegral.comap_surjective inclusion_injective

/-- Every prime of the one-gon lifts to its affine normalization. -/
theorem oneGon_comap_surjective :
    Function.Surjective (PrimeSpectrum.comap (B (R := R)).val.toRingHom) :=
  (oneGon_inclusion_finite (R := R)).to_isIntegral.comap_surjective Subtype.val_injective
/-- Finiteness of the affine split-node normalization as a scheme morphism. -/
instance node_spec_finite : IsFinite (Spec.map
    (CommRingCat.ofHom (inclusion (R := R)).toRingHom)) := by
  rw [IsFinite.SpecMap_iff]
  exact node_inclusion_finite

/-- Finiteness of the affine one-gon normalization as a scheme morphism. -/
instance oneGon_spec_finite : IsFinite (Spec.map
    (CommRingCat.ofHom (B (R := R)).val.toRingHom)) := by
  rw [IsFinite.SpecMap_iff]
  exact oneGon_inclusion_finite

end FLT.Mazur.PolygonNormalizationAlgebra
