/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.RingTheory.PowerSeries.Trunc
public import Mathlib.RingTheory.AdjoinRoot

/-!
# Power series modulo a power of the parameter

Truncation followed by the polynomial quotient is an algebra homomorphism.
Its kernel is exactly the corresponding power of the power-series parameter.
-/

@[expose] public noncomputable section

open Polynomial

namespace FLT.Mazur.PowerSeriesTruncatedPolynomial

variable (R : Type*) [CommRing R] (m : ℕ)

/-- Truncate a series and take its class modulo the prescribed parameter power. -/
def toStage : PowerSeries R →ₐ[R] AdjoinRoot ((Polynomial.X : R[X]) ^ (m + 1)) where
  toFun f := AdjoinRoot.mk _ (PowerSeries.trunc (m + 1) f)
  map_zero' := by simp
  map_one' := by simp
  map_add' f g := by simp
  map_mul' f g := by
    rw [← map_mul, AdjoinRoot.mk_eq_mk, Polynomial.X_pow_dvd_iff]
    intro d hd
    rw [Polynomial.coeff_sub, PowerSeries.coeff_trunc, ite_eq_left hd]
    apply sub_eq_zero.mpr
    simpa only [← Polynomial.coe_mul, Polynomial.coeff_coe] using
      PowerSeries.coeff_mul_eq_coeff_trunc_mul_trunc f g hd
  commutes' r := by
    change AdjoinRoot.mk _ (PowerSeries.trunc (m + 1) (PowerSeries.C r)) = _
    rw [PowerSeries.trunc_C]
    rfl

/-- Polynomial series retain their original class in the truncated polynomial ring. -/
@[simp] theorem toStage_coe (p : R[X]) :
    toStage R m (p : PowerSeries R) = AdjoinRoot.mk _ p := by
  change AdjoinRoot.mk _ _ = _
  rw [AdjoinRoot.mk_eq_mk, Polynomial.X_pow_dvd_iff]
  intro d hd
  simp [PowerSeries.coeff_trunc, hd]

/-- The series parameter maps to the actual root of the truncated polynomial ring. -/
@[simp] theorem toStage_X :
    toStage R m PowerSeries.X = AdjoinRoot.root ((Polynomial.X : R[X]) ^ (m + 1)) := by
  rw [← Polynomial.coe_X, toStage_coe]
  rfl

/-- Every truncated polynomial class lifts to a power series. -/
theorem toStage_surjective : Function.Surjective (toStage R m) := by
  intro x
  obtain ⟨p, rfl⟩ := AdjoinRoot.mk_surjective x
  exact ⟨(p : PowerSeries R), toStage_coe R m p⟩

/-- Vanishing at a stage means precisely that all retained coefficients vanish. -/
theorem toStage_eq_zero_iff (f : PowerSeries R) :
    toStage R m f = 0 ↔ ∀ d < m + 1, PowerSeries.coeff d f = 0 := by
  change AdjoinRoot.mk _ _ = 0 ↔ _
  rw [AdjoinRoot.mk_eq_zero, Polynomial.X_pow_dvd_iff]
  simp only [PowerSeries.coeff_trunc]
  exact forall_congr' fun d ↦ imp_congr_right fun hd ↦ by rw [ite_eq_left hd]

/-- The actual kernel is the principal power-series ideal generated by the parameter power. -/
theorem ker_toStage :
    RingHom.ker (toStage R m).toRingHom =
      Ideal.span {(PowerSeries.X : PowerSeries R) ^ (m + 1)} := by
  ext f
  rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
    toStage_eq_zero_iff, Ideal.mem_span_singleton, PowerSeries.X_pow_dvd_iff]

end FLT.Mazur.PowerSeriesTruncatedPolynomial
