/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.NormalizedSectionLinePrincipalRestriction
public import FLT.Mazur.NormalizedSectionLineRechart

/-!
# The actual universal line on each projective coordinate chart

The coordinate ratios generate a split line in the free coordinate module.
Pulling this line back by any actual affine chart morphism recovers the
classified section line, including its inclusion in the ambient sheaf.
-/

@[expose] public noncomputable section
open CategoryTheory AlgebraicGeometry
open Scheme.Modules
universe u
set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true
namespace FLT.Mazur.ProjectiveSpace
attribute [local instance] MvPolynomial.gradedAlgebra
open NormalizedSectionLine
variable (R : Type u) [CommRing R] (ι : Type u)

/-- The actual submodule generated by the universal normalized coordinate tuple. -/
def universalChartLine (i : ι) : Chart (chartRing R ι i) ι i :=
  ofTuple (chartRing R ι i) ι i (coordinate R ι i) (coordinate_self R ι i)

/-- Its unique normalized generator consists of the original homogeneous coordinate ratios. -/
lemma universalChartLine_generator (i : ι) :
    generator (chartRing R ι i) ι i (universalChartLine R ι i) = coordinate R ι i :=
  generator_ofTuple _ _ _ _ _

/-- Every genuine affine chart morphism recovers its classified line by scalar extension. -/
lemma universalChartLine_classify {S : Type u} [CommRing S] (f : R →+* S) (i : ι)
    (p : AffineChartPoint R ι f i) :
    baseChange (Spec.preimage p.val).hom i (universalChartLine R ι i) =
      sectionLineChartEquiv R ι f i p := by
  apply (tupleEquiv S ι i).symm.injective
  apply Subtype.ext
  funext j
  change generator S ι i _ j = generator S ι i _ j
  rw [generator_baseChange, universalChartLine_generator, sectionLineChartEquiv_generator]

/-- The universal chart line as an actual split sheaf subobject. -/
abbrev universalChartLineSheaf (i : ι) : (Spec (.of (chartRing R ι i))).Modules :=
  sheaf i (universalChartLine R ι i)

/-- Its actual inclusion into the coordinate sheaf. -/
abbrev universalChartLineInclusion (i : ι) := sheafInclusion i (universalChartLine R ι i)

/-- Pullback of the chart line is the sheaf of the extended coordinate submodule. -/
def universalChartLinePullback {S : Type u} [CommRing S] (i : ι)
    (φ : chartRing R ι i →+* S) :
    (pullback (Spec.map (CommRingCat.ofHom φ))).obj (universalChartLineSheaf R ι i) ≅
      sheaf i (baseChange φ i (universalChartLine R ι i)) :=
  sheafBaseChange φ i (universalChartLine R ι i)

/-- This identification also recovers the actual ambient inclusion. -/
lemma universalChartLinePullback_inclusion [Finite ι] {S : Type u} [CommRing S] (i : ι)
    (φ : chartRing R ι i →+* S) :
    (universalChartLinePullback R ι i φ).hom ≫
        sheafInclusion i (baseChange φ i (universalChartLine R ι i)) =
      (pullback (Spec.map (CommRingCat.ofHom φ))).map (universalChartLineInclusion R ι i) ≫
        (vectorSheafBaseChange ι φ).hom :=
  sheafBaseChange_inclusion ι φ i (universalChartLine R ι i)

end FLT.Mazur.ProjectiveSpace
