/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.AmpleHighDegreeSectionCover
public import FLT.Mazur.ClosedPointFiberSectionLifting
public import FLT.Mazur.ProperLocalFiberCover
public import FLT.Mazur.GlobalEvaluationSpan

/-!
# Lifted generators on a proper family over a local ring

An ample closed fiber supplies a finite affine section cover in a degree
beyond the lifting bound. Its global lifts generate everywhere on the
proper local family; their restrictions retain the original affine opens.
-/

@[expose] public noncomputable section

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

open CategoryTheory AlgebraicGeometry TopologicalSpace
open Scheme.Modules

namespace FLT.Mazur.FCurve

open ModuleLineBundleTensorPullback

variable {R : CommRingCat.{0}} [IsNoetherianRing R] [IsLocalRing R]
  {X : Scheme.{0}} [X.IsSeparated] (f : X ⟶ Spec R) [IsProper f]
  {L : X.Modules} (hline : LocallyFreeRankOne L)
  (hL : AmpleLineBundle ((pullback (f.fiberι (IsLocalRing.closedPoint R))).obj L))

include hline hL

/-- Large positive powers have finitely many lifted generators with affine closed-fiber opens. -/
theorem exists_lifted_closedFiber_cover (N : ℕ) :
    ∃ (n : ℕ), N ≤ n ∧ 0 < n ∧ ∃ (ι : Type) (_ : Finite ι)
      (t : ι → Γ(tensorPower L n, ⊤)),
      (∀ i, IsAffineOpen (f.fiberι (IsLocalRing.closedPoint R) ⁻¹ᵁ
        sectionGeneratorOpen (tensorPower L n) (t i))) ∧
      (⨆ i, sectionGeneratorOpen (tensorPower L n) (t i)) = ⊤ := by
  let p := IsLocalRing.closedPoint R
  let _ : p.asIdeal.IsMaximal := inferInstanceAs (IsLocalRing.maximalIdeal R).IsMaximal
  obtain ⟨B, hB⟩ := BaseAdicCohomology.fiber_sections_uniform_surjective f p hline hL
  obtain ⟨n, hn, hn0, ι, hι, s, haff, hcover⟩ := hL.high_degree_section_cover (max N B)
  let e := tensorPowerIso (f.fiberι p) L n
  have hlift (i : ι) := hB n (le_trans (le_max_right N B) hn) (e.inv.app ⊤ (s i))
  choose t ht using hlift
  have hopen (i : ι) : f.fiberι p ⁻¹ᵁ sectionGeneratorOpen (tensorPower L n) (t i) =
      sectionGeneratorOpen (tensorPower ((pullback (f.fiberι p)).obj L) n) (s i) := by
    rw [← sectionGeneratorOpen_pullGlobal (hline.tensorPower n), ht,
      ← sectionGeneratorOpen_iso e]
    congr 1
    exact ConcreteCategory.congr_hom (congrArg (fun k ↦ k.app ⊤) e.inv_hom_id) (s i)
  refine ⟨n, le_trans (le_max_left N B) hn, hn0, ι, hι, t,
    fun i ↦ (hopen i).symm ▸ haff i, ?_⟩
  apply Approximation.iSup_eq_top_of_proper_closedFiber_cover f
  intro x
  have hx : x ∈ ⨆ i, sectionGeneratorOpen
      (tensorPower ((pullback (f.fiberι p)).obj L) n) (s i) := by
    rw [hcover]
    trivial
  obtain ⟨i, hi⟩ := Opens.mem_iSup.mp hx
  refine ⟨i, ?_⟩
  change x ∈ f.fiberι p ⁻¹ᵁ sectionGeneratorOpen (tensorPower L n) (t i)
  rwa [hopen i]

/-- Some arbitrarily high power is generated by a finite family of actual global sections. -/
theorem exists_high_finite_evaluation (N : ℕ) :
    ∃ (n : ℕ), N ≤ n ∧ 0 < n ∧ ∃ (ι : Type) (_ : Finite ι)
      (t : ι → Γ(tensorPower L n, ⊤)),
        Epi (ProjectiveSpace.globalEvaluation (tensorPower L n) t) := by
  obtain ⟨n, hn, hn0, ι, hι, t, _, hcover⟩ := exists_lifted_closedFiber_cover f hline hL N
  refine ⟨n, hn, hn0, ι, hι, t, ?_⟩
  exact globalEvaluation_epi_of_sectionHom_isIso t
    (fun i ↦ sectionGeneratorOpen (tensorPower L n) (t i)) hcover id
    (fun i ↦ sectionHom_generatorOpen_isIso (tensorPower L n) (t i))

end FLT.Mazur.FCurve
