/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.RingTheory.Artinian.Ring
public import Mathlib.RingTheory.LocalRing.Quotient
public import Mathlib.RingTheory.Ideal.Span

/-!
# Finite colength ideals in a local ring with a regular parameter

If the maximal ideal is generated by one regular element, every ideal with
Artinian quotient has a regular principal generator. The argument works
without assuming the local ring is a domain or is Noetherian.
-/

@[expose] public noncomputable section
namespace FLT.Mazur.FCurve
open IsLocalRing

variable {B : Type*} [CommRing B] [IsLocalRing B]

/-- An ideal containing a parameter power is itself generated by a smaller power. -/
theorem ideal_eq_parameter_power (t : B) (ht : maximalIdeal B = Ideal.span {t})
    (n : ℕ) (I : Ideal B) (hI : t ^ n ∈ I) :
    ∃ k ≤ n, I = Ideal.span {t ^ k} := by
  induction n generalizing I with
  | zero =>
    have htop : I = ⊤ := Ideal.eq_top_of_isUnit_mem I (by simpa using hI) isUnit_one
    exact ⟨0, le_refl _, by simp [htop]⟩
  | succ n ih =>
    by_cases htop : I = ⊤
    · exact ⟨0, Nat.zero_le _, by simp [htop]⟩
    let J : Ideal B := Submodule.comap (LinearMap.mulRight B t) I
    have hn : t ^ n ∈ J := by
      change t ^ n * t ∈ I
      simpa only [pow_succ] using hI
    obtain ⟨k, hk, hJ⟩ := ih J hn
    refine ⟨k + 1, Nat.succ_le_succ hk, le_antisymm ?_ ?_⟩
    · intro x hx
      have hxm : x ∈ Ideal.span {t} := ht ▸ le_maximalIdeal htop hx
      obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hxm
      have hbJ : b ∈ J := by change b * t ∈ I; rwa [hb]
      rw [hJ] at hbJ
      obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hbJ
      apply Ideal.mem_span_singleton'.mpr
      exact ⟨c, by rw [pow_succ, ← mul_assoc, hc, hb]⟩
    · apply Ideal.span_le.mpr
      rintro x rfl
      have hkJ : t ^ k ∈ J := hJ ▸ Ideal.subset_span (Set.mem_singleton _)
      change t ^ k * t ∈ I at hkJ
      change t ^ (k + 1) ∈ I
      rw [pow_succ]
      exact hkJ

/-- An Artinian quotient contains a power of each element of the maximal ideal. -/
theorem parameter_power_mem_of_artinian_quotient (I : Ideal B) [IsArtinianRing (B ⧸ I)]
    (t : B) (ht : t ∈ maximalIdeal B) : ∃ n : ℕ, t ^ n ∈ I := by
  by_cases hI : I = ⊤
  · exact ⟨0, hI ▸ trivial⟩
  let _ : Nontrivial (B ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hI
  let _ : IsLocalRing (B ⧸ I) := .of_surjective' _ Ideal.Quotient.mk_surjective
  have hm : Ideal.Quotient.mk I t ∈ maximalIdeal (B ⧸ I) := by
    rw [← map_maximalIdeal_of_surjective (Ideal.Quotient.mk I)
      Ideal.Quotient.mk_surjective]
    exact Ideal.mem_map_of_mem (Ideal.Quotient.mk I) ht
  have hj : IsNilpotent (maximalIdeal (B ⧸ I)) := by
    rw [← jacobson_eq_maximalIdeal _ bot_ne_top]
    exact IsArtinianRing.isNilpotent_jacobson_bot
  obtain ⟨n, hn⟩ := hj
  refine ⟨n, Ideal.Quotient.eq_zero_iff_mem.mp ?_⟩
  rw [map_pow]
  have h := Ideal.pow_mem_pow hm n
  rwa [hn, Ideal.zero_eq_bot, Ideal.mem_bot] at h

/-- Every finite colength ideal has a regular equation when the local parameter is regular. -/
theorem regular_generator_of_artinian_quotient (t : B) (hr : IsRegular t)
    (ht : maximalIdeal B = Ideal.span {t}) (I : Ideal B) [IsArtinianRing (B ⧸ I)] :
    ∃ a : B, IsRegular a ∧ I = Ideal.span {a} := by
  obtain ⟨n, hn⟩ := parameter_power_mem_of_artinian_quotient I t
    (ht ▸ Ideal.subset_span (Set.mem_singleton _))
  obtain ⟨k, _, hk⟩ := ideal_eq_parameter_power t ht n I hn
  exact ⟨t ^ k, hr.pow k, hk⟩

end FLT.Mazur.FCurve
