/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.RingTheory.Flat.TorsionFree
public import Mathlib.RingTheory.Ideal.IdempotentFG
public import Mathlib.RingTheory.Polynomial.Quotient
public import Mathlib.RingTheory.RingHom.Etale

/-!
# Local equations for sections in an étale coordinate

The kernel of an augmentation is generated locally along the section by the
centered coordinate. Flatness of the coordinate and localization gives regularity.
-/

@[expose] public noncomputable section

open Polynomial

namespace FLT.Mazur.FCurve

variable {R B : Type*} [CommRing R] [CommRing B] [Algebra R B]

/-- An augmentation of a finitely presented unramified algebra has idempotent kernel. -/
lemma augmentation_kernel_idempotent [Algebra.FormallyUnramified R B]
    [Algebra.FinitePresentation R B] (ε : B →ₐ[R] R) :
    ∃ e : B, IsIdempotentElem e ∧ RingHom.ker ε.toRingHom = Ideal.span {e} := by
  have hε : Function.Surjective ε := fun r ↦ ⟨algebraMap R B r, ε.commutes r⟩
  let := ε.toAlgebra
  have : IsScalarTower R B R := .of_algebraMap_eq' ε.comp_algebraMap.symm
  have : Algebra.FormallySmooth B R := .of_restrictScalars R B R
  exact (Ideal.isIdempotentElem_iff_of_fg _
    (Algebra.FinitePresentation.ker_fG_of_surjective ε hε)).mp
      ((Algebra.FormallySmooth.iff_of_surjective hε).mp inferInstance)

/-- The centered coordinate belongs to the augmentation kernel. -/
lemma coordinate_mem_augmentation_kernel (g : R[X] →ₐ[R] B) (ε : B →ₐ[R] R) :
    g (X - C (ε (g X))) ∈ RingHom.ker ε.toRingHom := by
  have hC (r : R) : g (C r) = algebraMap R B r := g.commutes r
  simp [hC]

/-- Modulo the centered coordinate, the algebra is formally unramified over the base. -/
lemma coordinate_quotient_formallyUnramified (g : R[X] →ₐ[R] B)
    (hg : g.toRingHom.Etale) (a : R) :
    Algebra.FormallyUnramified R (B ⧸ Ideal.span {g (X - C a)}) := by
  let J : Ideal B := Ideal.span {g (X - C a)}
  let π := Ideal.Quotient.mk J
  have hC (r : R) : g (C r) = algebraMap R B r := g.commutes r
  have hcomp : (π.comp g.toRingHom).FormallyUnramified :=
    hg.formallyUnramified.comp (.of_surjective Ideal.Quotient.mk_surjective)
  have heq : π.comp g.toRingHom =
      (algebraMap R (B ⧸ J)).comp (Polynomial.evalRingHom a) := by
    apply Polynomial.ringHom_ext
    · intro r
      simp [π, hC, ← Ideal.Quotient.algebraMap_eq,
        ← IsScalarTower.algebraMap_apply]
    · have ht : π (g (X - C a)) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (by simp))
      simpa [π, map_sub, sub_eq_zero, hC,
        ← Ideal.Quotient.algebraMap_eq, ← IsScalarTower.algebraMap_apply] using ht
  rw [heq] at hcomp
  exact RingHom.formallyUnramified_algebraMap.mp hcomp.of_comp

/-- Flatness of an étale coordinate makes its centered equation regular. -/
lemma isRegular_etale_coordinate (g : R[X] →ₐ[R] B)
    (hg : g.toRingHom.Etale) (a : R) : IsRegular (g (X - C a)) := by
  let := g.toAlgebra
  have : Module.Flat R[X] B := (RingHom.Etale.iff_flat_and_formallyUnramified.mp hg).1
  have hr := Module.Flat.isSMulRegular_of_isRegular (M := B) (monic_X_sub_C a).isRegular
  exact (Commute.isRegular_iff (Commute.all _)).mpr hr

/-- Regularity persists on every principal open of an étale coordinate chart. -/
lemma isRegular_localized_etale_coordinate (g : R[X] →ₐ[R] B)
    (hg : g.toRingHom.Etale) (a : R) (h : B) :
    IsRegular (algebraMap B (Localization.Away h) (g (X - C a))) := by
  have hr := Module.Flat.isSMulRegular_of_isRegular (M := Localization.Away h)
    (isRegular_etale_coordinate g hg a)
  apply (Commute.isRegular_iff (Commute.all _)).mpr
  simpa only [IsSMulRegular, IsLeftRegular, Algebra.smul_def] using hr

/-- An idempotent kernel in a quotient provides a neighborhood where the original
kernel is generated by the quotient equation. -/
lemma exists_localized_kernel_eq_span (ε : B →ₐ[R] R) (t : B)
    (ht : t ∈ RingHom.ker ε.toRingHom)
    [Algebra.FormallyUnramified R (B ⧸ Ideal.span {t})]
    [Algebra.FinitePresentation R (B ⧸ Ideal.span {t})]
    (q : Ideal B) [q.IsPrime] (hq : RingHom.ker ε.toRingHom ≤ q) :
    ∃ h : B, h ∉ q ∧
      (RingHom.ker ε.toRingHom).map (algebraMap B (Localization.Away h)) =
        Ideal.span {algebraMap B (Localization.Away h) t} := by
  let J : Ideal B := Ideal.span {t}
  have hJ : J ≤ RingHom.ker ε.toRingHom := Ideal.span_le.mpr (by simpa using ht)
  let ε' : (B ⧸ J) →ₐ[R] R := Ideal.Quotient.liftₐ J ε hJ
  obtain ⟨e, he, hker⟩ := augmentation_kernel_idempotent ε'
  obtain ⟨b, hb⟩ := Ideal.Quotient.mk_surjective e
  have hbker : b ∈ RingHom.ker ε.toRingHom := by
    have heker : e ∈ RingHom.ker ε'.toRingHom := by
      rw [hker]
      exact Ideal.subset_span (by simp)
    change ε' (Ideal.Quotient.mk J b) = 0
    rw [hb]
    exact heker
  refine ⟨1 - b, ?_, ?_⟩
  · intro h
    exact q.one_notMem (by simpa using q.add_mem h (hq hbker))
  · let f := algebraMap B (Localization.Away (1 - b))
    have hkill (x : B) (hx : x ∈ RingHom.ker ε.toRingHom) : (1 - b) * x ∈ J := by
      apply Ideal.Quotient.eq_zero_iff_mem.mp
      rw [map_mul, map_sub, map_one, hb]
      have hx' : Ideal.Quotient.mk J x ∈ RingHom.ker ε'.toRingHom := hx
      rw [hker, Ideal.mem_span_singleton] at hx'
      obtain ⟨y, hy⟩ := hx'
      rw [hy, ← mul_assoc]
      simp [sub_mul, he.eq]
    apply le_antisymm
    · apply Ideal.map_le_iff_le_comap.mpr
      intro x hx
      change f x ∈ Ideal.span {f t}
      apply (Ideal.unit_mul_mem_iff_mem _
        (IsLocalization.Away.algebraMap_isUnit (1 - b))).mp
      rw [← map_mul]
      have hm := Ideal.mem_map_of_mem f (hkill x hx)
      simpa [J, Ideal.map_span] using hm
    · apply Ideal.span_le.mpr
      simpa using Ideal.mem_map_of_mem f ht

/-- The augmentation kernel is locally generated by the regular centered coordinate. -/
theorem exists_etale_coordinate_kernel_eq (g : R[X] →ₐ[R] B)
    (hg : g.toRingHom.Etale) (ε : B →ₐ[R] R)
    (q : Ideal B) [q.IsPrime] (hq : RingHom.ker ε.toRingHom ≤ q) :
    ∃ h : B, h ∉ q ∧
      (RingHom.ker ε.toRingHom).map (algebraMap B (Localization.Away h)) =
        Ideal.span {algebraMap B (Localization.Away h) (g (X - C (ε (g X))))} ∧
      IsRegular (algebraMap B (Localization.Away h) (g (X - C (ε (g X))))) := by
  let := g.toAlgebra
  have : IsScalarTower R R[X] B := .of_algebraMap_eq' g.comp_algebraMap.symm
  have : Algebra.Etale R[X] B := hg
  have : Algebra.FinitePresentation R B := Algebra.FinitePresentation.trans R R[X] B
  have : Algebra.FinitePresentation R (B ⧸ Ideal.span {g (X - C (ε (g X)))}) :=
    Algebra.FinitePresentation.quotient (Submodule.fg_span_singleton _)
  have := coordinate_quotient_formallyUnramified g hg (ε (g X))
  obtain ⟨h, hh, heq⟩ := exists_localized_kernel_eq_span ε _
    (coordinate_mem_augmentation_kernel g ε) q hq
  exact ⟨h, hh, heq, isRegular_localized_etale_coordinate g hg _ h⟩

end FLT.Mazur.FCurve
