/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.SectionGradedBaseChangePullback
public import FLT.Mazur.SectionGradedProjIntrinsicSquare

/-!
# The actual section-pullback Proj projection

Flat affine base change makes the section-pullback ring map induce a global
Proj morphism. It equals the transported projection after identifying the
two presentations of the original grading.
-/

@[expose] public noncomputable section
open CategoryTheory AlgebraicGeometry HomogeneousIdeal
open Scheme.Modules
namespace FLT.Mazur.SectionGradedProjBaseChangeProjection
open FCurve SectionGradedSum SectionGradedBaseChange
set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true
variable {P X T S : Scheme.{0}} [CompactSpace X] [X.IsSeparated] [IsAffine T] [IsAffine S]
  {p : P ⟶ X} {q : P ⟶ T} {f : X ⟶ S} {g : T ⟶ S} [Flat g]
  (h : IsPullback p q f g) (L : X.Modules) [hL : Fact (LocallyFreeRankOne L)]

/-- Pullback preserves the line-bundle condition. -/
local instance pulledLine : Fact (LocallyFreeRankOne ((pullback p).obj L)) :=
  ⟨hL.out.pullback p⟩

/-- The original section-pullback graded map is the composite defining the comparison. -/
lemma composite_eq :
    letI : Algebra Γ(S, ⊤) Γ(T, ⊤) := g.appTop.hom.toAlgebra
    ((GradedProjRingEquiv.forward (tensorGrade f L g) (grade ((pullback p).obj L) ⊤)
      (sectionsAlgEquiv h L hL.out).toRingEquiv
      (SectionGradedProjBaseChangeEquiv.sectionsAlgEquiv_mem_tensorGrade_iff h L)).comp
        (GradedProjBaseChangeMap.inclusion (B := Γ(T, ⊤)) (baseGrade f L))).comp
          (GradedProjRingEquiv.backward (baseGrade f L) (grade L ⊤)
            (RingEquiv.refl _) (fun _ _ ↦ Iff.rfl)) =
      SectionGradedPullback.gradedRingHom p L := by
  let : Algebra Γ(S, ⊤) Γ(T, ⊤) := g.appTop.hom.toAlgebra
  ext s : 1
  exact SectionGradedBaseChangePullback.sectionsAlgEquiv_one_tmul h L s

include h in
/-- Positive pulled-back sections lie in the ideal generated by original positive sections. -/
lemma irrelevant_le_map :
    (grade ((pullback p).obj L) ⊤)₊ ≤
      (grade L ⊤)₊.map (SectionGradedPullback.gradedRingHom p L) := by
  let : Algebra Γ(S, ⊤) Γ(T, ⊤) := g.appTop.hom.toAlgebra
  let φ : tensorGrade f L g →+*ᵍ grade ((pullback p).obj L) ⊤ :=
    GradedProjRingEquiv.forward (tensorGrade f L g) (grade ((pullback p).obj L) ⊤)
    (sectionsAlgEquiv h L hL.out).toRingEquiv
    (SectionGradedProjBaseChangeEquiv.sectionsAlgEquiv_mem_tensorGrade_iff h L)
  let ψ : baseGrade f L →+*ᵍ tensorGrade f L g :=
    GradedProjBaseChangeMap.inclusion (B := Γ(T, ⊤)) (baseGrade f L)
  let θ : grade L ⊤ →+*ᵍ baseGrade f L := GradedProjRingEquiv.backward (baseGrade f L) (grade L ⊤)
    (RingEquiv.refl _) (fun _ _ ↦ Iff.rfl)
  have hc : (φ.comp ψ).comp θ = SectionGradedPullback.gradedRingHom p L := composite_eq h L
  have ht : (grade ((pullback p).obj L) ⊤)₊ ≤ (grade L ⊤)₊.map ((φ.comp ψ).comp θ) :=
    HomogeneousIdeal.irrelevant_le_map_comp
      (GradedProjRingEquiv.irrelevant_le_backward _ _ _ _)
      (HomogeneousIdeal.irrelevant_le_map_comp (GradedProjBaseChangeMap.irrelevant_le_map _)
        (GradedProjRingEquiv.irrelevant_le_forward _ _ _ _))
  rwa [hc] at ht


/-- The transported projection equals the Proj map of the actual section pullback. -/
lemma projection_eq :
    SectionGradedProjBaseChangeSquare.projection h L ≫ (SectionGradedProjGrading.iso f L).inv =
      Proj.map (SectionGradedPullback.gradedRingHom p L) (irrelevant_le_map h L) := by
  let : Algebra Γ(S, ⊤) Γ(T, ⊤) := g.appTop.hom.toAlgebra
  change (Proj.map _ _ ≫ Proj.map _ _) ≫ Proj.map _ _ = _
  rw [← Proj.map_comp, ← Proj.map_comp]
  congr 1
  exact composite_eq h L

end FLT.Mazur.SectionGradedProjBaseChangeProjection
