/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.ProjectiveOverlapModuleLocalization
public import FLT.Mazur.SegreChartMaps
public import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Determinantal quotients for affine Segre charts

The kernel of the affine Segre map is generated by the two-by-two minors.
Thus each product of standard charts is the corresponding determinantal
closed subscheme of a standard chart of the target projective space.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory MvPolynomial HomogeneousLocalization
open scoped TensorProduct

universe u

set_option backward.isDefEq.respectTransparency false

namespace FLT.Mazur.ProjectiveSpace

variable (R : Type u) [CommRing R] (ι κ : Type u)

attribute [local instance] MvPolynomial.gradedAlgebra

/-- A two-by-two minor of the normalized target coordinates. -/
def segreMinor (i : ι) (j : κ) (p q : ι × κ) : chartRing R (ι × κ) (i, j) :=
  coordinate R (ι × κ) (i, j) p * coordinate R (ι × κ) (i, j) q -
    coordinate R (ι × κ) (i, j) (p.1, q.2) * coordinate R (ι × κ) (i, j) (q.1, p.2)

/-- The determinantal ideal in a standard target chart. -/
def segreMinorIdeal (i : ι) (j : κ) : Ideal (chartRing R (ι × κ) (i, j)) :=
  Ideal.span (Set.range (fun pq : (ι × κ) × (ι × κ) ↦ segreMinor R ι κ i j pq.1 pq.2))

lemma segreMinor_mem (i : ι) (j : κ) (p q : ι × κ) :
    segreMinor R ι κ i j p q ∈ segreMinorIdeal R ι κ i j :=
  Ideal.subset_span ⟨(p, q), rfl⟩

lemma segreMinorIdeal_le_ker (i : ι) (j : κ) :
    segreMinorIdeal R ι κ i j ≤ RingHom.ker (segreChartMap R ι κ i j) := by
  apply Ideal.span_le.mpr
  rintro _ ⟨⟨p, q⟩, rfl⟩
  apply RingHom.mem_ker.mpr
  simp only [segreMinor, map_sub, map_mul, segreChartMap_coordinate]
  exact segreCoordinate_minor R ι κ i p.1 q.1 j p.2 q.2

/-- The quotient by all two-by-two minors on one target chart. -/
abbrev segreQuotient (i : ι) (j : κ) :=
  chartRing R (ι × κ) (i, j) ⧸ segreMinorIdeal R ι κ i j

/-- The column through the pivot defines the first source chart in the quotient. -/
def segreQuotientLeft (i : ι) (j : κ) : chartRing R ι i →ₐ[R] segreQuotient R ι κ i j :=
  { chartEval R ι (algebraMap R _)
      (fun a ↦ Ideal.Quotient.mk _ (coordinate R (ι × κ) (i, j) (a, j))) i
      (by simp) with
    commutes' := chartEval_scalar R ι _ _ _ _ }

/-- The row through the pivot defines the second source chart in the quotient. -/
def segreQuotientRight (i : ι) (j : κ) : chartRing R κ j →ₐ[R] segreQuotient R ι κ i j :=
  { chartEval R κ (algebraMap R _)
      (fun b ↦ Ideal.Quotient.mk _ (coordinate R (ι × κ) (i, j) (i, b))) j
      (by simp) with
    commutes' := chartEval_scalar R κ _ _ _ _ }

/-- Reconstruct the two source coordinate vectors from the pivot row and column. -/
def segreQuotientRetraction (i : ι) (j : κ) :
    segreSourceRing R ι κ i j →ₐ[R] segreQuotient R ι κ i j :=
  Algebra.TensorProduct.lift (segreQuotientLeft R ι κ i j) (segreQuotientRight R ι κ i j)
    (fun _ _ ↦ .all _ _)

lemma segreQuotient_coordinate (i : ι) (j : κ) (p : ι × κ) :
    Ideal.Quotient.mk (segreMinorIdeal R ι κ i j) (coordinate R (ι × κ) (i, j) p) =
      Ideal.Quotient.mk _ (coordinate R (ι × κ) (i, j) (p.1, j)) *
        Ideal.Quotient.mk _ (coordinate R (ι × κ) (i, j) (i, p.2)) := by
  have h := (Ideal.Quotient.eq_zero_iff_mem).mpr (segreMinor_mem R ι κ i j p (i, j))
  simpa only [segreMinor, coordinate_self, mul_one, map_sub, map_mul, sub_eq_zero] using h

/-- The reconstruction recovers every target coordinate modulo the minors. -/
lemma segreQuotientRetraction_comp (i : ι) (j : κ) :
    ((segreQuotientRetraction R ι κ i j).comp (segreChartMap R ι κ i j)).toRingHom =
      Ideal.Quotient.mk (segreMinorIdeal R ι κ i j) := by
  apply chartRing_hom_ext
  · intro r
    change ((segreQuotientRetraction R ι κ i j).comp
      (segreChartMap R ι κ i j)) (algebraMap R _ r) = _
    exact AlgHom.commutes _ r
  · intro p
    change segreQuotientRetraction R ι κ i j
      (segreChartMap R ι κ i j (coordinate R (ι × κ) (i, j) p)) = _
    rw [segreChartMap_coordinate]
    simp only [segreQuotientRetraction, segreCoordinate, Algebra.TensorProduct.lift_tmul,
      segreQuotientLeft, segreQuotientRight, AlgHom.coe_mk, chartEval_coordinate]
    exact (segreQuotient_coordinate R ι κ i j p).symm

/-- There are no further equations on an affine Segre chart beyond the minors. -/
lemma segreChartMap_ker (i : ι) (j : κ) :
    RingHom.ker (segreChartMap R ι κ i j) = segreMinorIdeal R ι κ i j := by
  apply le_antisymm ?_ (segreMinorIdeal_le_ker R ι κ i j)
  intro z hz
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  have h := DFunLike.congr_fun (segreQuotientRetraction_comp R ι κ i j) z
  change segreQuotientRetraction R ι κ i j (segreChartMap R ι κ i j z) = _ at h
  rw [RingHom.mem_ker.mp hz, map_zero] at h
  exact h.symm

/-- The determinantal quotient is the coordinate ring of the product chart. -/
def segreChartQuotientEquiv (i : ι) (j : κ) :
    segreQuotient R ι κ i j ≃+* segreSourceRing R ι κ i j :=
  (Ideal.quotEquivOfEq (segreChartMap_ker R ι κ i j).symm).trans
    (RingHom.quotientKerEquivOfSurjective (segreChartMap_surjective R ι κ i j))

@[simp]
lemma segreChartQuotientEquiv_mk (i : ι) (j : κ) (z : chartRing R (ι × κ) (i, j)) :
    segreChartQuotientEquiv R ι κ i j (Ideal.Quotient.mk _ z) =
      segreChartMap R ι κ i j z := by
  rfl

/-- The affine Segre morphism into the corresponding target standard chart. -/
def segreChartMorphism (i : ι) (j : κ) :
    Spec (.of (segreSourceRing R ι κ i j)) ⟶ (chart R (ι × κ) (i, j)).toScheme :=
  Spec.map (CommRingCat.ofHom (segreChartMap R ι κ i j).toRingHom) ≫
    (chartIso R (ι × κ) (i, j)).inv

instance segreChartMorphism_isClosedImmersion (i : ι) (j : κ) :
    IsClosedImmersion (segreChartMorphism R ι κ i j) := by
  have : IsClosedImmersion (Spec.map (CommRingCat.ofHom
      (segreChartMap R ι κ i j).toRingHom)) :=
    IsClosedImmersion.spec_of_surjective _ (segreChartMap_surjective R ι κ i j)
  dsimp only [segreChartMorphism]
  infer_instance

/-- The affine Segre morphism followed by the target chart inclusion. -/
def segreChartToProjective (i : ι) (j : κ) :
    Spec (.of (segreSourceRing R ι κ i j)) ⟶ space R (ι × κ) :=
  segreChartMorphism R ι κ i j ≫ (chart R (ι × κ) (i, j)).ι

/-- Every target standard chart has the expected preimage, including other pivots. -/
lemma segreChartToProjective_preimage (i : ι) (j : κ) (p : ι × κ) :
    segreChartToProjective R ι κ i j ⁻¹ᵁ chart R (ι × κ) p =
      PrimeSpectrum.basicOpen (segreCoordinate R ι κ i j p) := by
  change (Spec.map (CommRingCat.ofHom (segreChartMap R ι κ i j).toRingHom) ≫
    chartMap R (ι × κ) (i, j)) ⁻¹ᵁ chart R (ι × κ) p = _
  rw [Scheme.Hom.comp_preimage, chartMap_preimage_chart, SpecMap_preimage_basicOpen]
  congr 1
  exact segreChartMap_coordinate R ι κ i j p

/-- The target chart condition is the intersection of the two source chart conditions. -/
lemma segreChartToProjective_preimage_factors (i k : ι) (j l : κ) :
    segreChartToProjective R ι κ i j ⁻¹ᵁ chart R (ι × κ) (k, l) =
      PrimeSpectrum.basicOpen (coordinate R ι i k ⊗ₜ[R] (1 : chartRing R κ j)) ⊓
        PrimeSpectrum.basicOpen ((1 : chartRing R ι i) ⊗ₜ[R] coordinate R κ j l) := by
  rw [segreChartToProjective_preimage, ← PrimeSpectrum.basicOpen_mul]
  simp only [segreCoordinate, Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]

/-- The affine scheme maps agree on the spectra of the product-overlap rings. -/
lemma segreChartToProjective_overlap (i k : ι) (j l : κ) :
    Spec.map (CommRingCat.ofHom (segreOverlapLeft R ι κ i k j l).toRingHom) ≫
        segreChartToProjective R ι κ i j =
      Spec.map (CommRingCat.ofHom (segreOverlapRight R ι κ i k j l).toRingHom) ≫
        segreChartToProjective R ι κ k l := by
  have hleft : Spec.map (CommRingCat.ofHom
      (chartOverlapLeft R (ι × κ) (i, j) (k, l)).toRingHom) ≫
        chartMap R (ι × κ) (i, j) = overlapMap R (ι × κ) (i, j) (k, l) :=
    toOverlap_chartMap R (ι × κ) (i, j) (k, l)
  have hright : Spec.map (CommRingCat.ofHom
      (chartOverlapRight R (ι × κ) (i, j) (k, l)).toRingHom) ≫
        chartMap R (ι × κ) (k, l) = overlapMap R (ι × κ) (i, j) (k, l) := by
    exact Proj.SpecMap_awayMap_awayι (grading R (ι × κ)) (isHomogeneous_X R (k, l))
      (by decide) (isHomogeneous_X R (i, j)) (mul_comm (X (i, j)) (X (k, l)))
  change _ ≫ (Spec.map _ ≫ chartMap R (ι × κ) (i, j)) =
    _ ≫ (Spec.map _ ≫ chartMap R (ι × κ) (k, l))
  rw [← Category.assoc, ← Spec.map_comp, ← Category.assoc, ← Spec.map_comp]
  change Spec.map (CommRingCat.ofHom
    (((segreOverlapLeft R ι κ i k j l).comp (segreChartMap R ι κ i j)).toRingHom)) ≫
      chartMap R (ι × κ) (i, j) = Spec.map (CommRingCat.ofHom
        (((segreOverlapRight R ι κ i k j l).comp (segreChartMap R ι κ k l)).toRingHom)) ≫
          chartMap R (ι × κ) (k, l)
  rw [← segreOverlapMap_left, ← segreOverlapMap_right]
  simp only [CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc]
  exact congrArg (fun f ↦ Spec.map (CommRingCat.ofHom
    (segreOverlapMap R ι κ i k j l)) ≫ f) (hleft.trans hright.symm)

end FLT.Mazur.ProjectiveSpace
