/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.NormalizedSectionLineRechart
public import Mathlib.RingTheory.Spectrum.Prime.Topology

/-!
# Coordinate principal cover of an actual split line

A retraction of a line generator forces its coordinates to generate the unit
ideal. Their genuine principal opens therefore cover the affine test scheme.
Each principal localization supplies a normalized section line, constructed
from the original generator rather than an assumed projective point.
-/

@[expose] public noncomputable section
open AlgebraicGeometry TopologicalSpace
universe u
namespace FLT.Mazur.NormalizedSectionLine
variable {R : Type u} [CommRing R] {ι : Type u}

/-- A vector admitting an actual linear retraction has coordinates generating the unit ideal. -/
lemma generator_span_eq_top [Finite ι] (v : ι → R) (r : (ι → R) →ₗ[R] R) (hr : r v = 1) :
    Ideal.span (Set.range v) = ⊤ := by
  let _ := Fintype.ofFinite ι
  rw [Ideal.eq_top_iff_one]
  rw [← hr]
  conv_rhs => rw [← (Pi.basisFun R ι).sum_repr v, map_sum]
  apply Ideal.sum_mem
  intro i hi
  rw [map_smul]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- The actual coordinate principal opens cover the affine spectrum. -/
lemma generator_basicOpen_cover [Finite ι] (v : ι → R) (r : (ι → R) →ₗ[R] R) (hr : r v = 1) :
    (⨆ i, PrimeSpectrum.basicOpen (v i)) = ⊤ := by
  exact PrimeSpectrum.iSup_basicOpen_eq_top_iff.mpr (generator_span_eq_top v r hr)

/-- A unit coordinate normalizes the actual image of the original generating map. -/
def unitCoordinateLine (v : ι → R) (i : ι) (a : Rˣ) (hi : v i = a) : Chart R ι i := by
  let f := LinearMap.toSpanSingleton R (ι → R) v
  refine ⟨LinearMap.range f, ?_, ?_⟩
  · intro x y h
    obtain ⟨b, hb⟩ := x.property
    obtain ⟨c, hc⟩ := y.property
    have hbc : b = c := by
      change x.val i = y.val i at h
      rw [← hb, ← hc] at h
      change b * v i = c * v i at h
      rw [hi] at h
      exact a.isUnit.mul_right_cancel h
    apply Subtype.ext
    rw [← hb, ← hc, hbc]
  · intro b
    refine ⟨⟨f (b * ↑a⁻¹), ⟨_, rfl⟩⟩, ?_⟩
    change (b * ↑a⁻¹) * v i = b
    rw [hi, mul_assoc, Units.inv_mul, mul_one]

/-- Its value is the actual image of the generating linear map. -/
lemma unitCoordinateLine_val (v : ι → R) (i : ι) (a : Rˣ) (hi : v i = a) :
    (unitCoordinateLine v i a hi).val =
      LinearMap.range (LinearMap.toSpanSingleton R (ι → R) v) := rfl

/-- The original generator is recovered by the chosen coordinate unit. -/
lemma unitCoordinateLine_generator (v : ι → R) (i : ι) (a : Rˣ) (hi : v i = a) :
    generator R ι i (unitCoordinateLine v i a hi) = (↑a⁻¹ : R) • v := by
  have hv : v ∈ (unitCoordinateLine v i a hi).val :=
    ⟨1, by simp only [LinearMap.toSpanSingleton_apply, one_smul]⟩
  have h := eq_smul_generator R ι i (unitCoordinateLine v i a hi) ⟨v, hv⟩
  change v = v i • generator R ι i (unitCoordinateLine v i a hi) at h
  rw [hi] at h
  simpa only [smul_smul, Units.inv_mul, one_smul] using
    (congrArg (fun w : ι → R ↦ (↑a⁻¹ : R) • w) h).symm

/-- Each actual coordinate principal open carries a constructed normalized image line. -/
def generatorPrincipalLine (v : ι → R) (i : ι) :
    Chart (Localization.Away (v i)) ι i :=
  unitCoordinateLine (fun j ↦ algebraMap R (Localization.Away (v i)) (v j)) i
    (IsLocalization.Away.algebraMap_isUnit (S := Localization.Away (v i)) (v i)).unit
    (IsLocalization.Away.algebraMap_isUnit
      (S := Localization.Away (v i)) (v i)).unit_spec.symm

/-- The local image is generated by the actual coefficient extension of the original vector. -/
lemma generatorPrincipalLine_val (v : ι → R) (i : ι) :
    (generatorPrincipalLine v i).val = LinearMap.range
      (LinearMap.toSpanSingleton (Localization.Away (v i)) (ι → Localization.Away (v i))
        (fun j ↦ algebraMap R (Localization.Away (v i)) (v j))) := rfl

end FLT.Mazur.NormalizedSectionLine
