/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.Algebra.Ring.Hom.Defs
public import Mathlib.Tactic.Ring

/-!
# Scalar generation across a square-zero principal kernel

Two scalar lifts suffice to generate the source when its reduction kernel
is generated by a square-zero scalar. No finite-module hypothesis is needed.
-/

@[expose] public section

namespace FLT.Mazur.SquareZeroScalarGeneration

universe u v w

variable {S : Type u} {A : Type v} {B : Type w} [CommRing S] [CommRing A] [CommRing B]

/-- Scalar generation of the reduction lifts across a square-zero scalar principal kernel. -/
theorem surjective (c : S →+* A) (q : A →+* B) (r : S)
    (hq : Function.Surjective (q.comp c))
    (hk : ∀ x : A, q x = 0 ↔ ∃ y, c r * y = x)
    (hz : c r * c r = 0) : Function.Surjective c := by
  intro x
  obtain ⟨s, hs⟩ := hq (q x)
  obtain ⟨y, hy⟩ := (hk (x - c s)).mp (by
    rw [map_sub, show q (c s) = q x from hs, sub_self])
  obtain ⟨t, ht⟩ := hq (q y)
  obtain ⟨z, hz'⟩ := (hk (y - c t)).mp (by
    rw [map_sub, show q (c t) = q y from ht, sub_self])
  refine ⟨s + r * t, ?_⟩
  rw [map_add, map_mul]
  have hzero : c r * (y - c t) = 0 := by
    rw [← hz', ← mul_assoc, hz, zero_mul]
  calc
    c s + c r * c t = c s + c r * y := by
      rw [mul_sub, sub_eq_zero] at hzero
      rw [hzero]
    _ = x := by rw [hy]; ring

end FLT.Mazur.SquareZeroScalarGeneration
