/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.WeierstrassProductOverlap
public import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion

/-!
# Surjectivity of the chartwise diagonal algebra

On an overlap the missing inverse of the normalizing coordinate is a coordinate
from the second chart. Thus the two chart rings generate the entire localized
overlap ring, and their tensor product maps onto it.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory

namespace FLT.Mazur.WeierstrassIntegralChart

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

variable {R : Type*} [CommRing R] (W : WeierstrassCurve R) (j k : Fin 3)

/-- The two charts restrict to the same actual principal overlap. -/
def overlapDiagonalAlgebra : ChartProduct W j k →ₐ[R] Overlap W j k :=
  chartProductEvaluation W j k (overlapRestriction W j k) (transitionBase W j k)

/-- Its first restriction is the original localization homomorphism. -/
@[simp] theorem overlapDiagonalAlgebra_left (a : Coordinate W j) :
    overlapDiagonalAlgebra W j k (chartProductLeft W j k a) =
      algebraMap (Coordinate W j) (Overlap W j k) a := by
  exact congrArg (fun f : Coordinate W j →ₐ[R] Overlap W j k => f a)
    (chartProductEvaluation_left W j k (overlapRestriction W j k) (transitionBase W j k))

/-- Its second restriction is the coordinate transition homomorphism. -/
@[simp] theorem overlapDiagonalAlgebra_right (a : Coordinate W k) :
    overlapDiagonalAlgebra W j k (chartProductRight W j k a) =
      transitionBase W j k a := by
  exact congrArg (fun f : Coordinate W k →ₐ[R] Overlap W j k => f a)
    (chartProductEvaluation_right W j k (overlapRestriction W j k) (transitionBase W j k))

/-- The other chart supplies exactly the inverse required by localization. -/
theorem overlapDiagonalAlgebra_inverse :
    overlapDiagonalAlgebra W j k (chartProductRight W j k (coord W k j)) =
      overlapInverse W j k := by
  rw [overlapDiagonalAlgebra_right, transitionBase_coord, overlapCoord_self, mul_one]

/-- Every overlap element is generated by the two chart rings. -/
theorem overlapDiagonalAlgebra_surjective : Function.Surjective (overlapDiagonalAlgebra W j k) := by
  intro z
  obtain ⟨n, a, ha⟩ := IsLocalization.Away.surj (coord W j k) z
  refine ⟨chartProductLeft W j k a * chartProductRight W j k (coord W k j) ^ n, ?_⟩
  rw [map_mul, map_pow, overlapDiagonalAlgebra_left, overlapDiagonalAlgebra_inverse, ← ha]
  change (z * overlapCoord W j k k ^ n) * overlapInverse W j k ^ n = z
  rw [mul_assoc, ← mul_pow, mul_comm (overlapCoord W j k k), overlapInverse_mul,
    one_pow, mul_one]

/-- The overlap embeds as a closed subscheme of the product of its two charts. -/
instance overlapDiagonalAlgebra_closedImmersion :
    IsClosedImmersion (Spec.map (CommRingCat.ofHom (overlapDiagonalAlgebra W j k).toRingHom)) :=
  IsClosedImmersion.spec_of_surjective _ (overlapDiagonalAlgebra_surjective W j k)

end FLT.Mazur.WeierstrassIntegralChart
