/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mazur.WeierstrassOriginParameter

/-!
# The original origin has a principal regular ideal

On the explicit principal neighborhood, evaluation at the original zero
section has kernel generated by the original x coordinate. Combined with
its proved regularity, this supplies a local Cartier equation for the origin.
-/

@[expose] public noncomputable section

open Polynomial WeierstrassCurve

namespace FLT.Mazur.WeierstrassIntegralChart

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

variable {R : Type*} [CommRing R] (W : WeierstrassCurve R)

/-- Evaluation of the actual principal neighborhood on the original zero section. -/
def originEvaluation : OriginNeighborhood W →ₐ[R] R :=
  IsLocalization.Away.liftAlgHom (originDenominator W)
    (show IsUnit (chartInfinityEvaluation (S := R) W (originDenominator W)) by simp)

/-- Evaluation retains the original infinity chart map on every original function. -/
@[simp] theorem originEvaluation_restrict (a : Coordinate W 1) :
    originEvaluation W (algebraMap (Coordinate W 1) (OriginNeighborhood W) a) =
      chartInfinityEvaluation (S := R) W a := by
  simp [originEvaluation]

/-- The original x parameter vanishes at the original zero section. -/
@[simp] theorem originEvaluation_x : originEvaluation W (originCoordinate W 0) = 0 := by
  simp [originCoordinate]

/-- The original z coordinate vanishes at the original zero section. -/
@[simp] theorem originEvaluation_z : originEvaluation W (originCoordinate W 2) = 0 := by
  simp [originCoordinate]

/-- The actual z coordinate belongs to the ideal generated by the cube of the parameter. -/
theorem originCoordinate_z_mem_cube :
    originCoordinate W 2 ∈ Ideal.span {originCoordinate W 0 ^ 3} := by
  rw [← originCoordinate_span_z]
  exact Ideal.subset_span (Set.mem_singleton _)

/-- In particular the original z coordinate vanishes modulo the parameter. -/
theorem originCoordinate_z_mem_parameter :
    originCoordinate W 2 ∈ Ideal.span {originCoordinate W 0} := by
  apply (Ideal.span_le.mpr ?_ : Ideal.span {originCoordinate W 0 ^ 3} ≤ _)
    (originCoordinate_z_mem_cube W)
  intro a ha
  rcases Set.mem_singleton_iff.mp ha with rfl
  exact Ideal.pow_mem_of_mem _ (Ideal.subset_span (Set.mem_singleton _)) 3 (by decide)

/-- Modulo the original parameter every actual function is its value on the zero section. -/
theorem originQuotient_eq_evaluation :
    Ideal.Quotient.mkₐ R (Ideal.span {originCoordinate W 0}) =
      (Algebra.ofId R (OriginNeighborhood W ⧸ Ideal.span {originCoordinate W 0})).comp
        (originEvaluation W) := by
  apply IsLocalization.algHom_ext (Submonoid.powers (originDenominator W))
  apply hom_ext
  intro i
  fin_cases i
  · change Ideal.Quotient.mk _ (originCoordinate W 0) = _
    rw [Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (Set.mem_singleton _))]
    change 0 = algebraMap R (OriginNeighborhood W ⧸ Ideal.span {originCoordinate W 0})
      (originEvaluation W (originCoordinate W 0))
    rw [originEvaluation_x, map_zero]
  · simp [AlgHom.comp_apply, coord_self]
  · change Ideal.Quotient.mk _ (originCoordinate W 2) = _
    rw [Ideal.Quotient.eq_zero_iff_mem.mpr (originCoordinate_z_mem_parameter W)]
    change 0 = algebraMap R (OriginNeighborhood W ⧸ Ideal.span {originCoordinate W 0})
      (originEvaluation W (originCoordinate W 2))
    rw [originEvaluation_z, map_zero]

/-- The actual zero section is cut out by one regular parameter on this neighborhood. -/
theorem originEvaluation_kernel :
    RingHom.ker (originEvaluation W).toRingHom = Ideal.span {originCoordinate W 0} := by
  apply le_antisymm
  · intro a ha
    have he := DFunLike.congr_fun (originQuotient_eq_evaluation W) a
    have hz : originEvaluation W a = 0 := ha
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    simpa only [Ideal.Quotient.mkₐ_eq_mk, AlgHom.comp_apply, hz, map_zero] using he
  · rw [Ideal.span_singleton_le_iff_mem]
    exact originEvaluation_x W

end FLT.Mazur.WeierstrassIntegralChart
