/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.WeierstrassModificationYAlgebra

/-!
# Generators of the actual y-direction algebra

The images of r, u and z generate every image of the actual equation algebra.
This criterion identifies its image in the original vertical localization.
-/

@[expose] public noncomputable section

namespace FLT.Mazur.WeierstrassModificationY

set_option backward.isDefEq.respectTransparency false

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
  (W : WeierstrassCurve R) (s b3 b4 b6 : R)

/-- A subalgebra containing all coordinate images contains the whole image. -/
theorem range_le_of_coordinates (f : Coordinate W s b3 b4 b6 →ₐ[R] S)
    (C : Subalgebra R S) (hc : ∀ i, f (coord W s b3 b4 b6 i) ∈ C) : f.range ≤ C := by
  let a : Fin 3 → C := fun i => ⟨f (coord W s b3 b4 b6 i), hc i⟩
  have he : 1 + algebraMap R C W.a₁ * a 1 + algebraMap R C b3 * a 0 =
      a 2 * a 1 ^ 3 + algebraMap R C W.a₂ * a 1 ^ 2 +
        algebraMap R C b4 * a 0 * a 1 + algebraMap R C b6 * a 0 ^ 2 := by
    apply Subtype.ext
    simpa [a] using congrArg f (equation W s b3 b4 b6)
  have hi : a 0 * a 2 = algebraMap R C s := by
    apply Subtype.ext
    simpa [a] using congrArg f (incidence W s b3 b4 b6)
  let g := evaluation W s b3 b4 b6 a he hi
  have hg : C.val.comp g = f := by
    apply hom_ext
    intro i
    simp [g, a]
  rintro z ⟨b, rfl⟩
  have h := congrArg (fun k : Coordinate W s b3 b4 b6 →ₐ[R] S => k b) hg
  change f b ∈ C
  rw [← h]
  exact (g b).property

/-- The actual three coordinates generate the whole equation algebra. -/
theorem coordinates_adjoin : Algebra.adjoin R (Set.range (coord W s b3 b4 b6)) = ⊤ := by
  have h := range_le_of_coordinates W s b3 b4 b6 (AlgHom.id R _)
    (Algebra.adjoin R (Set.range (coord W s b3 b4 b6)))
    (fun i => Algebra.subset_adjoin ⟨i, rfl⟩)
  exact top_unique (fun z _ => h ⟨z, rfl⟩)

/-- Every image is generated by the three actual coordinate images. -/
theorem range_eq_adjoin (f : Coordinate W s b3 b4 b6 →ₐ[R] S) :
    f.range = Algebra.adjoin R (Set.range (fun i => f (coord W s b3 b4 b6 i))) := by
  apply le_antisymm
  · exact range_le_of_coordinates W s b3 b4 b6 f _
      (fun i => Algebra.subset_adjoin ⟨i, rfl⟩)
  · apply Algebra.adjoin_le
    rintro z ⟨i, rfl⟩
    exact ⟨_, rfl⟩

end FLT.Mazur.WeierstrassModificationY
