/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.WeierstrassDilatationCoefficients

/-!
# Generators of the actual divided algebra

The two divided coordinates generate the algebra over its original base.
Consequently their images suffice to identify the image inside a fraction
algebra, without replacing the actual contraction by an abstract isomorphism.
-/

@[expose] public noncomputable section

namespace FLT.Mazur.WeierstrassDilatation

set_option backward.isDefEq.respectTransparency false

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
  (W : WeierstrassCurve R) (s b3 b4 b6 : R)

/-- A subalgebra containing the two coordinate images contains the whole image. -/
theorem range_le_of_coordinates (f : Coordinate W s b3 b4 b6 →ₐ[R] S)
    (C : Subalgebra R S) (hx : f (x W s b3 b4 b6) ∈ C)
    (hy : f (y W s b3 b4 b6) ∈ C) : f.range ≤ C := by
  let u : C := ⟨f (x W s b3 b4 b6), hx⟩
  let v : C := ⟨f (y W s b3 b4 b6), hy⟩
  have he : v ^ 2 + (algebraMap R C W.a₁ * u + algebraMap R C b3) * v =
      algebraMap R C s * u ^ 3 + algebraMap R C W.a₂ * u ^ 2 +
        algebraMap R C b4 * u + algebraMap R C b6 := by
    apply Subtype.ext
    exact equation_map W s b3 b4 b6 f
  let g := evaluation W s b3 b4 b6 u v he
  have hg : C.val.comp g = f := by
    apply hom_ext <;> simp [g, u, v]
  rintro z ⟨a, rfl⟩
  have h := congrArg (fun k : Coordinate W s b3 b4 b6 →ₐ[R] S => k a) hg
  change f a ∈ C
  rw [← h]
  exact (g a).property

/-- The two actual divided coordinates generate the full algebra. -/
theorem coordinates_adjoin :
    Algebra.adjoin R {x W s b3 b4 b6, y W s b3 b4 b6} = ⊤ := by
  have h := range_le_of_coordinates W s b3 b4 b6 (AlgHom.id R _)
    (Algebra.adjoin R {x W s b3 b4 b6, y W s b3 b4 b6})
    (Algebra.subset_adjoin (Set.mem_insert _ _))
    (Algebra.subset_adjoin (Set.mem_insert_of_mem _ (Set.mem_singleton _)))
  exact top_unique (fun z _ => h ⟨z, rfl⟩)

/-- Every image of this algebra is generated by the two actual coordinate images. -/
theorem range_eq_adjoin (f : Coordinate W s b3 b4 b6 →ₐ[R] S) :
    f.range = Algebra.adjoin R {f (x W s b3 b4 b6), f (y W s b3 b4 b6)} := by
  apply le_antisymm
  · apply range_le_of_coordinates
    · exact Algebra.subset_adjoin (Set.mem_insert _ _)
    · exact Algebra.subset_adjoin (Set.mem_insert_of_mem _ (Set.mem_singleton _))
  · apply Algebra.adjoin_le
    intro z hz
    rcases Set.mem_insert_iff.mp hz with rfl | hz
    · exact ⟨_, rfl⟩
    · have hz' := Set.mem_singleton_iff.mp hz
      subst z
      exact ⟨_, rfl⟩

end FLT.Mazur.WeierstrassDilatation
