/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.WeierstrassProjectiveChartAlgebra
public import FLT.Mazur.ProjectiveProductChartOverlaps

/-!
# The exact defining equation in every projective chart

The kernel of the ambient chart quotient is precisely the principal ideal
generated by the dehomogenized Weierstrass cubic. The proof constructs the
reverse map from the normalized chart to that hypersurface quotient.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory MvPolynomial

namespace FLT.Mazur.WeierstrassIntegralChart

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true
attribute [local instance] MvPolynomial.gradedAlgebra

universe u
variable {R : Type u} [CommRing R] (W : WeierstrassCurve R) (j : Fin 3)

/-- The genuine cubic's principal ideal in its projective affine chart. -/
def projectiveChartIdeal : Ideal (ProjectiveSpace.chartRing R (Fin 3) j) :=
  Ideal.span {projectiveChartEquation W j}

/-- The normalized cubic chart maps back to the quotient by its single ambient equation. -/
def chartToProjectiveQuotient :
    Coordinate W j →ₐ[R] ProjectiveSpace.chartRing R (Fin 3) j ⧸ projectiveChartIdeal W j :=
  Ideal.Quotient.liftₐ (relations W j)
    ((Ideal.Quotient.mkₐ R (projectiveChartIdeal W j)).comp
      (aeval (ProjectiveSpace.coordinate R (Fin 3) j))) (by
    change relations W j ≤ RingHom.ker
      (((Ideal.Quotient.mkₐ R (projectiveChartIdeal W j)).comp
        (aeval (ProjectiveSpace.coordinate R (Fin 3) j))).toRingHom)
    apply Ideal.span_le.mpr
    intro p hp
    rcases Set.mem_insert_iff.mp hp with rfl | hp
    · change Ideal.Quotient.mk (projectiveChartIdeal W j) (projectiveChartEquation W j) = 0
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (Set.mem_singleton _))
    · have hp' : p = X j - 1 := Set.mem_singleton_iff.mp hp
      subst p
      change ((Ideal.Quotient.mkₐ R (projectiveChartIdeal W j)).comp
        (aeval (ProjectiveSpace.coordinate R (Fin 3) j))) (X j - 1) = 0
      simp only [AlgHom.comp_apply, map_sub, map_one, aeval_X,
        ProjectiveSpace.coordinate_self, sub_self])

/-- The reverse map sends a cubic coordinate to the class of its ambient ratio. -/
@[simp] theorem chartToProjectiveQuotient_coord (i : Fin 3) :
    chartToProjectiveQuotient W j (coord W j i) =
      Ideal.Quotient.mk (projectiveChartIdeal W j) (ProjectiveSpace.coordinate R (Fin 3) j i) := by
  change ((Ideal.Quotient.mkₐ R (projectiveChartIdeal W j)).comp
    (aeval (ProjectiveSpace.coordinate R (Fin 3) j))) (X i) = _
  rw [AlgHom.comp_apply, aeval_X]
  rfl

/-- Composing the ambient map with the reverse map is exactly the principal quotient. -/
theorem chartToProjectiveQuotient_comp :
    (chartToProjectiveQuotient W j).comp (projectiveChartAlgebra W j) =
      Ideal.Quotient.mkₐ R (projectiveChartIdeal W j) := by
  apply AlgHom.coe_ringHom_injective
  apply ProjectiveSpace.chartRing_hom_ext R (Fin 3) j
  · intro r
    exact (((chartToProjectiveQuotient W j).comp (projectiveChartAlgebra W j)).commutes r).trans
      ((Ideal.Quotient.mkₐ R (projectiveChartIdeal W j)).commutes r).symm
  · intro i
    change chartToProjectiveQuotient W j
      (projectiveChartAlgebra W j (ProjectiveSpace.coordinate R (Fin 3) j i)) = _
    rw [projectiveChartAlgebra_coordinate, chartToProjectiveQuotient_coord]
    rfl

/-- The closed immersion has exactly the cubic ideal, without any extra equations. -/
theorem projectiveChartAlgebra_ker :
    RingHom.ker (projectiveChartAlgebra W j).toRingHom = projectiveChartIdeal W j := by
  apply le_antisymm
  · intro p hp
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    have h := DFunLike.congr_fun (chartToProjectiveQuotient_comp W j) p
    change chartToProjectiveQuotient W j (projectiveChartAlgebra W j p) = _ at h
    rw [show projectiveChartAlgebra W j p = 0 from hp, map_zero] at h
    exact h.symm
  · apply Ideal.span_le.mpr
    intro p hp
    have hp' : p = projectiveChartEquation W j := Set.mem_singleton_iff.mp hp
    subst p
    exact projectiveChartAlgebra_equation W j

/-- The cubic chart is canonically the ambient projective hypersurface chart. -/
def projectiveHypersurfaceChartEquiv :
    (ProjectiveSpace.chartRing R (Fin 3) j ⧸ projectiveChartIdeal W j) ≃ₐ[R] Coordinate W j :=
  Ideal.quotientEquivAlgOfEq R (projectiveChartAlgebra_ker W j).symm |>.trans
    (Ideal.quotientKerAlgEquivOfSurjective (projectiveChartAlgebra_surjective W j))

end FLT.Mazur.WeierstrassIntegralChart
