/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mazur.BlowupReesGeneratorCover
public import FLT.Mazur.WeierstrassModificationReesProjGluing

/-!
# The original three Weierstrass directions cover Rees Proj

The center is generated by s,x,y in the original cubic coordinate ring.
Their actual fraction charts cover Proj. The global fraction-atlas map is
therefore surjective, using the already constructed entire vertical chart.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory

namespace FLT.Mazur.WeierstrassModificationReesCoordinates

set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true

universe u
variable {R : Type u} [CommRing R] (W : WeierstrassCurve R) (s : R)

local notation "A" => WeierstrassIntegralChart.Coordinate W 2
local notation "I" => WeierstrassDilatation.modificationCenter W s

/-- The original scale, horizontal and vertical generators of the center. -/
def centerGenerators : Fin 3 → A :=
  ![algebraMap R A s, WeierstrassIntegralChart.coord W 2 0,
    WeierstrassIntegralChart.coord W 2 1]

/-- All three original generators belong to the modification center. -/
theorem centerGenerators_mem (i : Fin 3) : centerGenerators W s i ∈ I := by
  fin_cases i <;> exact Ideal.subset_span (by simp [centerGenerators])

/-- The original three generators span precisely the original center. -/
theorem centerGenerators_span : Ideal.span (Set.range (centerGenerators W s)) = I := by
  simp only [centerGenerators, Matrix.range_cons, Matrix.range_empty, Set.union_empty,
    Set.singleton_union, WeierstrassDilatation.modificationCenter]

set_option backward.isDefEq.respectTransparency true in
/-- The entire three original fraction charts cover the actual Rees Proj. -/
def originalProjCover : (BlowupRees.proj I).OpenCover :=
  BlowupRees.fractionGeneratorCover I (centerGenerators W s) (centerGenerators_mem W s)
    (centerGenerators_span W s)

/-- Every actual Proj point lies in one of the three original fraction directions. -/
theorem originalProj_charts_cover (z : BlowupRees.proj I) :
    (∃ a, scaleProjInclusion W s a = z) ∨
      (∃ a, horizontalProjInclusion W s a = z) ∨
        ∃ a, verticalProjInclusion W s a = z := by
  obtain ⟨i, a, ha⟩ := (originalProjCover W s).exists_eq z
  change Fin 3 at i
  fin_cases i
  · exact Or.inl ⟨a, ha⟩
  · exact Or.inr (Or.inl ⟨a, ha⟩)
  · exact Or.inr (Or.inr ⟨a, ha⟩)

variable [IsDomain R] [IsBezout R] (b3 b4 b6 : R)
  (h3 : W.a₃ = s * b3) (h4 : W.a₄ = s * b4) (h6 : W.a₆ = s ^ 2 * b6) (hs : s ≠ 0)

/-- The global fraction-atlas map reaches every point of the original Rees Proj. -/
theorem fractionAtlasToProj_surjective :
    Function.Surjective (fractionAtlasToProj W s b3 b4 b6 h3 h4 h6 hs) := by
  intro z
  rcases originalProj_charts_cover W s z with ⟨a, ha⟩ | ⟨a, ha⟩ | ⟨a, ha⟩
  · refine ⟨scaleChart W s b3 b4 b6 h3 h4 h6 hs a, ?_⟩
    change (scaleChart W s b3 b4 b6 h3 h4 h6 hs ≫
      fractionAtlasToProj W s b3 b4 b6 h3 h4 h6 hs) a = z
    rwa [scaleChart_toProj]
  · refine ⟨horizontalChart W s b3 b4 b6 h3 h4 h6 hs a, ?_⟩
    change (horizontalChart W s b3 b4 b6 h3 h4 h6 hs ≫
      fractionAtlasToProj W s b3 b4 b6 h3 h4 h6 hs) a = z
    rwa [horizontalChart_toProj]
  · refine ⟨verticalChart W s b3 b4 b6 h3 h4 h6 hs a, ?_⟩
    change (verticalChart W s b3 b4 b6 h3 h4 h6 hs ≫
      fractionAtlasToProj W s b3 b4 b6 h3 h4 h6 hs) a = z
    rwa [verticalChart_toProj]

end FLT.Mazur.WeierstrassModificationReesCoordinates
