/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.TateCurve.Elliptic
public import FLT.TateCurve.Expansion
public import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# The point-valued Tate uniformization map

The coordinate equation and ellipticity define a nonsingular point away from
`q^ℤ`; the cyclic subgroup maps to infinity. Periodicity descends this map to
`Kˣ/q^ℤ`. The addition law and bijectivity remain separate theorems.
-/

@[expose] public section

open ValuativeRel

namespace TateCurve

variable {K : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- Away from the powers of `q`, the Tate coordinates give a nonsingular affine point. -/
theorem tateCoordinates_nonsingular (q u : Kˣ) (hq : valuation K (q : K) < 1)
    (hu : u ∉ Subgroup.zpowers q) :
    (WeierstrassCurve.tateCurve (q : K)).toAffine.Nonsingular
      (tateX (u : K) (q : K)) (tateY (u : K) (q : K)) :=
  (WeierstrassCurve.Affine.equation_iff_nonsingular_of_Δ_ne_zero
    (tateCurve_Δ_ne_zero q.ne_zero hq)).mp (tateCoordinates_equation q u hq hu)

/-- The Tate map to nonsingular points, sending the powers of the parameter to infinity. -/
noncomputable def uniformizationPoint (q : Kˣ) (hq : valuation K (q : K) < 1)
    (u : Kˣ) : (WeierstrassCurve.tateCurve (q : K)).toAffine.Point := by
  classical
  exact if hu : u ∈ Subgroup.zpowers q then .zero else
    .some (tateX (u : K) (q : K)) (tateY (u : K) (q : K))
      (tateCoordinates_nonsingular q u hq hu)

/-- Exactly the cyclic subgroup generated by the parameter maps to infinity. -/
@[simp]
theorem uniformizationPoint_eq_zero (q u : Kˣ) (hq : valuation K (q : K) < 1) :
    uniformizationPoint q hq u = .zero ↔ u ∈ Subgroup.zpowers q := by
  classical
  by_cases hu : u ∈ Subgroup.zpowers q <;> simp [uniformizationPoint, hu]

/-- The point-valued Tate map is unchanged by multiplying its argument by powers of `q`. -/
theorem uniformizationPoint_zpow_mul (q u : Kˣ) (hq : valuation K (q : K) < 1) (m : ℤ) :
    uniformizationPoint q hq (q ^ m * u) = uniformizationPoint q hq u := by
  classical
  have hm : q ^ m ∈ Subgroup.zpowers q := Subgroup.zpow_mem _ (Subgroup.mem_zpowers q) m
  have hmem : q ^ m * u ∈ Subgroup.zpowers q ↔ u ∈ Subgroup.zpowers q := by
    constructor
    · intro h
      have := (Subgroup.zpowers q).mul_mem ((Subgroup.zpowers q).inv_mem hm) h
      simpa using this
    · exact (Subgroup.zpowers q).mul_mem hm
  by_cases hu : u ∈ Subgroup.zpowers q
  · simp [uniformizationPoint, hu, hmem.mpr hu]
  · simp [uniformizationPoint, hu, mt hmem.mp hu, Units.val_mul,
      Units.val_zpow_eq_zpow_val, tateX_zpow_mul _ q.ne_zero, tateY_zpow_mul _ q.ne_zero]

/-- Inversion of a unit becomes elliptic negation under the Tate point map. -/
theorem uniformizationPoint_inv (q u : Kˣ) (hq : valuation K (q : K) < 1) :
    uniformizationPoint q hq u⁻¹ = -uniformizationPoint q hq u := by
  classical
  let : UniformSpace K := IsTopologicalAddGroup.rightUniformSpace K
  have : IsUniformAddGroup K := isUniformAddGroup_of_addCommGroup
  have hmem : u⁻¹ ∈ Subgroup.zpowers q ↔ u ∈ Subgroup.zpowers q :=
    (Subgroup.zpowers q).inv_mem_iff
  by_cases hu : u ∈ Subgroup.zpowers q
  · simp [uniformizationPoint, hu, hmem.mpr hu, ← WeierstrassCurve.Affine.Point.zero_def]
  · simp only [uniformizationPoint, dite_eq_right hu, dite_eq_right (mt hmem.mp hu)]
    change WeierstrassCurve.Affine.Point.some _ _ _ =
      WeierstrassCurve.Affine.Point.some _ _ _
    simp only [WeierstrassCurve.Affine.Point.some.injEq, Units.val_inv_eq_inv_val,
      tateX_inv q.ne_zero u.ne_zero,
      tateY_inv q.ne_zero u.ne_zero (tendsto_pow_nhds_zero hq), true_and]
    simp [WeierstrassCurve.Affine.negY, WeierstrassCurve.tateCurve]

/-- The Tate map descends to a map from the quotient to nonsingular curve points. -/
noncomputable def quotientPoint (q : Kˣ) (hq : valuation K (q : K) < 1) :
    Kˣ ⧸ Subgroup.zpowers q → (WeierstrassCurve.tateCurve (q : K)).toAffine.Point :=
  Quotient.lift (uniformizationPoint q hq) (by
    intro u v huv
    obtain ⟨m, hm⟩ := Subgroup.mem_zpowers_iff.mp (QuotientGroup.leftRel_apply.mp huv)
    have hv : v = q ^ m * u := by
      rw [hm]
      simp [mul_comm]
    rw [hv, uniformizationPoint_zpow_mul])

/-- The quotient map agrees with the point-valued Tate map on representatives. -/
@[simp]
theorem quotientPoint_mk (q u : Kˣ) (hq : valuation K (q : K) < 1) :
    quotientPoint q hq (u : Kˣ ⧸ Subgroup.zpowers q) = uniformizationPoint q hq u := rfl

/-- Only the identity class maps to infinity under the quotient Tate map. -/
@[simp]
theorem quotientPoint_eq_zero (q : Kˣ) (hq : valuation K (q : K) < 1)
    (u : Kˣ ⧸ Subgroup.zpowers q) : quotientPoint q hq u = .zero ↔ u = 1 := by
  induction u using Quotient.inductionOn with
  | h u => rw [quotientPoint_mk, uniformizationPoint_eq_zero, QuotientGroup.eq_one_iff]

end TateCurve
