/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.Topology.Algebra.InfiniteSum.Nonarchimedean
public import Mathlib.Topology.Algebra.InfiniteSum.NatInt
public import Mathlib.Topology.Algebra.Field

import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring

/-!+# Nonarchimedean Tate coordinate series

The two coordinate series are indexed by the integers. Their positive tails tend to
zero when the powers of `q` do; inversion of the rational summands gives the same
conclusion for their negative tails. Completeness and the nonarchimedean topology
then give unconditional convergence.

The correction term is `∑_{n ≥ 1} qⁿ/(1-qⁿ)²`, the Lambert-series expression for
`s₁(q)`. These coordinates have poles at `q^ℤ`; totalized division assigns junk
values there. Constructing points on the Tate curve requires excluding those poles.
-/

@[expose] public section

open Filter
open scoped Topology

namespace TateCurve

section Algebra

variable {K : Type*} [Field K]

/-- The rational summand in the Tate `x`-coordinate. -/
def xTerm (v : K) : K := v / (1 - v) ^ 2

/-- The rational summand in the Tate `y`-coordinate. -/
def yTerm (v : K) : K := v ^ 2 / (1 - v) ^ 3

/-- Inverting the argument preserves the `x` summand, including its junk value at `1`. -/
theorem xTerm_inv {v : K} (hv : v ≠ 0) : xTerm v⁻¹ = xTerm v := by
  by_cases hv1 : v = 1
  · simp [xTerm, hv1]
  · have h1 : 1 - v ≠ 0 := sub_ne_zero.mpr (Ne.symm hv1)
    have hi : 1 - v⁻¹ ≠ 0 := by simpa [sub_eq_zero] using hv1
    dsimp [xTerm]
    apply (div_eq_div_iff (pow_ne_zero _ hi) (pow_ne_zero _ h1)).mpr
    field_simp
    ring

/-- Inversion transforms the `y` summand into a rational function vanishing at zero. -/
theorem yTerm_inv {v : K} (hv : v ≠ 0) : yTerm v⁻¹ = -v / (1 - v) ^ 3 := by
  by_cases hv1 : v = 1
  · simp [yTerm, hv1]
  · have h1 : 1 - v ≠ 0 := sub_ne_zero.mpr (Ne.symm hv1)
    have hi : 1 - v⁻¹ ≠ 0 := by simpa [sub_eq_zero] using hv1
    dsimp [yTerm]
    apply (div_eq_div_iff (pow_ne_zero _ hi) (pow_ne_zero _ h1)).mpr
    field_simp
    ring

/-- Inverting a Tate summand gives the coordinate formula for elliptic negation. -/
theorem yTerm_inv_eq {v : K} (hv : v ≠ 0) :
    yTerm v⁻¹ = -yTerm v - xTerm v := by
  rw [yTerm_inv hv]
  by_cases hv1 : v = 1
  · simp [xTerm, yTerm, hv1]
  · dsimp [xTerm, yTerm]
    field_simp [sub_ne_zero.mpr (Ne.symm hv1)]
    ring

/-- Away from the cyclic subgroup generated by `q`, every coordinate denominator is nonzero. -/
theorem one_sub_zpow_mul_ne_zero (q u : Kˣ) (hu : u ∉ Subgroup.zpowers q) (n : ℤ) :
    1 - (q : K) ^ n * (u : K) ≠ 0 := by
  intro h
  have hunit : q ^ n * u = 1 := Units.ext (by simpa using (sub_eq_zero.mp h).symm)
  apply hu
  refine Subgroup.mem_zpowers_iff.mpr ⟨-n, ?_⟩
  rw [zpow_neg]
  exact inv_eq_of_mul_eq_one_right hunit

end Algebra

section Coordinates

variable {K : Type*} [Field K] [TopologicalSpace K]

/-- The Lambert correction `s₁(q) = ∑_{n ≥ 1} qⁿ/(1-qⁿ)²` in the Tate coordinates. -/
noncomputable def tateCorrection (q : K) : K := ∑' n : ℕ, xTerm (q ^ (n + 1))

/-- The Tate `x`-coordinate, with junk values at the poles `u ∈ q^ℤ`. -/
noncomputable def tateX (u q : K) : K :=
  (∑' n : ℤ, xTerm (q ^ n * u)) - 2 * tateCorrection q

/-- The Tate `y`-coordinate, with junk values at the poles `u ∈ q^ℤ`. -/
noncomputable def tateY (u q : K) : K :=
  (∑' n : ℤ, yTerm (q ^ n * u)) + tateCorrection q

/-- Multiplying the argument by an integral power of `q` preserves the `x`-coordinate. -/
theorem tateX_zpow_mul (u : K) {q : K} (hq0 : q ≠ 0) (m : ℤ) :
    tateX (q ^ m * u) q = tateX u q := by
  have h := (Equiv.addRight m).tsum_eq (fun n : ℤ ↦ xTerm (q ^ n * u))
  change (∑' n : ℤ, xTerm (q ^ (n + m) * u)) = _ at h
  simpa only [tateX, zpow_add₀ hq0, mul_assoc] using
    congrArg (fun s ↦ s - 2 * tateCorrection q) h

/-- Multiplying the argument by an integral power of `q` preserves the `y`-coordinate. -/
theorem tateY_zpow_mul (u : K) {q : K} (hq0 : q ≠ 0) (m : ℤ) :
    tateY (q ^ m * u) q = tateY u q := by
  have h := (Equiv.addRight m).tsum_eq (fun n : ℤ ↦ yTerm (q ^ n * u))
  change (∑' n : ℤ, yTerm (q ^ (n + m) * u)) = _ at h
  simpa only [tateY, zpow_add₀ hq0, mul_assoc] using
    congrArg (fun s ↦ s + tateCorrection q) h

/-- Inverting the argument preserves the Tate `x`-coordinate. -/
theorem tateX_inv {q u : K} (hq0 : q ≠ 0) (hu0 : u ≠ 0) :
    tateX u⁻¹ q = tateX u q := by
  unfold tateX
  congr 1
  rw [← tsum_comp_neg (fun n : ℤ ↦ xTerm (q ^ n * u⁻¹))]
  apply tsum_congr
  intro n
  rw [show q ^ (-n) * u⁻¹ = (q ^ n * u)⁻¹ by simp [mul_comm]]
  exact xTerm_inv (mul_ne_zero (zpow_ne_zero _ hq0) hu0)

end Coordinates

section Convergence

variable {K : Type*} [Field K] [UniformSpace K] [IsUniformAddGroup K]
  [IsTopologicalDivisionRing K] [NonarchimedeanAddGroup K] [CompleteSpace K]

/-- Rational tails with positive numerator degree are summable when powers of `q`
tend to zero. Finitely many vanishing denominators do not affect summability. -/
theorem summable_tate_tail {q : K}
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) (u : K)
    {j : ℕ} (hj : j ≠ 0) (d : ℕ) :
    Summable (fun n : ℕ ↦ (q ^ n * u) ^ j / (1 - q ^ n * u) ^ d) := by
  apply NonarchimedeanAddGroup.summable_of_tendsto_cofinite_zero
  rw [Nat.cofinite_eq_atTop]
  have ht : Tendsto (fun n : ℕ ↦ q ^ n * u) atTop (𝓝 0) := by
    simpa using hq.mul_const u
  simpa [zero_pow hj] using!
    (ht.pow j).div ((tendsto_const_nhds.sub ht).pow d) (by simp)

/-- The integer-indexed series defining the Tate `x`-coordinate converges. -/
theorem summable_tate_x {q u : K} (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    Summable (fun n : ℤ ↦ xTerm (q ^ n * u)) := by
  rw [summable_int_iff_summable_nat_and_neg]
  constructor
  · simpa [xTerm] using summable_tate_tail hq u (j := 1) one_ne_zero 2
  · have h := summable_tate_tail hq u⁻¹ (j := 1) one_ne_zero 2
    refine h.congr fun n ↦ ?_
    rw [show q ^ (-(n : ℤ)) * u = (q ^ n * u⁻¹)⁻¹ by simp [mul_comm], xTerm_inv
      (mul_ne_zero (pow_ne_zero _ hq0) (inv_ne_zero hu0))]
    simp [xTerm]

/-- The integer-indexed series defining the Tate `y`-coordinate converges. -/
theorem summable_tate_y {q u : K} (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    Summable (fun n : ℤ ↦ yTerm (q ^ n * u)) := by
  rw [summable_int_iff_summable_nat_and_neg]
  constructor
  · simpa [yTerm] using summable_tate_tail hq u (j := 2) (by decide) 3
  · have h := (summable_tate_tail hq u⁻¹ (j := 1) one_ne_zero 3).neg
    refine h.congr fun n ↦ ?_
    rw [show q ^ (-(n : ℤ)) * u = (q ^ n * u⁻¹)⁻¹ by simp [mul_comm], yTerm_inv
      (mul_ne_zero (pow_ne_zero _ hq0) (inv_ne_zero hu0))]
    simp [neg_div]

/-- The correction series in the Tate coordinates converges. -/
theorem summable_tate_correction {q : K}
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    Summable (fun n : ℕ ↦ xTerm (q ^ (n + 1))) := by
  have h : Summable (fun n : ℕ ↦ xTerm (q ^ n)) := by
    simpa [xTerm] using summable_tate_tail hq 1 (j := 1) one_ne_zero 2
  exact (summable_nat_add_iff (f := fun n : ℕ ↦ xTerm (q ^ n)) 1).mpr h

variable [T2Space K]

/-- Inverting the argument acts on Tate coordinates as elliptic negation:
`(x, y) ↦ (x, -y-x)` for a Weierstrass equation with `a₁ = 1` and `a₃ = 0`. -/
theorem tateY_inv {q u : K} (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    tateY u⁻¹ q = -tateY u q - tateX u q := by
  have hterms : (∑' n : ℤ, yTerm (q ^ n * u⁻¹)) =
      -(∑' n : ℤ, yTerm (q ^ n * u)) - ∑' n : ℤ, xTerm (q ^ n * u) := by
    rw [← tsum_comp_neg (fun n : ℤ ↦ yTerm (q ^ n * u⁻¹))]
    have heq : ∀ n : ℤ, yTerm (q ^ (-n) * u⁻¹) =
        -yTerm (q ^ n * u) - xTerm (q ^ n * u) := by
      intro n
      rw [show q ^ (-n) * u⁻¹ = (q ^ n * u)⁻¹ by simp [mul_comm]]
      exact yTerm_inv_eq (mul_ne_zero (zpow_ne_zero _ hq0) hu0)
    rw [tsum_congr heq, ((summable_tate_y hq0 hu0 hq).neg).tsum_sub
      (summable_tate_x hq0 hu0 hq), tsum_neg]
  simp only [tateY, tateX, hterms]
  ring

omit [T2Space K] in
section

variable {L : Type*} [Field L] [TopologicalSpace L] [T2Space L]

/-- The correction series commutes with continuous field homomorphisms. -/
theorem map_tateCorrection (f : K →+* L) (hf : Continuous f) {q : K}
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    f (tateCorrection q) = tateCorrection (f q) := by
  rw [tateCorrection, (summable_tate_correction hq).map_tsum f hf]
  simp [tateCorrection, xTerm]

/-- The convergent Tate `x`-coordinate commutes with continuous field homomorphisms. -/
theorem map_tateX (f : K →+* L) (hf : Continuous f) {u q : K}
    (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    f (tateX u q) = tateX (f u) (f q) := by
  rw [tateX, map_sub, map_mul, map_ofNat,
    (summable_tate_x hq0 hu0 hq).map_tsum f hf, map_tateCorrection f hf hq]
  simp [tateX, xTerm]

/-- The convergent Tate `y`-coordinate commutes with continuous field homomorphisms. -/
theorem map_tateY (f : K →+* L) (hf : Continuous f) {u q : K}
    (hq0 : q ≠ 0) (hu0 : u ≠ 0)
    (hq : Tendsto (fun n : ℕ ↦ q ^ n) atTop (𝓝 0)) :
    f (tateY u q) = tateY (f u) (f q) := by
  rw [tateY, map_add, (summable_tate_y hq0 hu0 hq).map_tsum f hf,
    map_tateCorrection f hf hq]
  simp [tateY, yTerm]

end

end Convergence

end TateCurve
