/-
Copyright (c) 2026 FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: FLT Project
-/
module

public import FLT.RepresentationTheory.NormalPSubgroup
public import Mathlib.LinearAlgebra.Dimension.Free
public import Mathlib.GroupTheory.OrderOfElement

/-!
# Irreducible representations with a quotient of order dividing two

After a normal p-subgroup is killed, a quotient of order dividing two forces
an irreducible representation to have dimension one. In characteristic three
its action is a character with values in `{1, -1}`.
-/

@[expose] public noncomputable section

namespace Representation

variable {k G V : Type*} [Field k] [Group G] [AddCommGroup V] [Module k V]

/-- An irreducible representation generated by one involution is one-dimensional. -/
theorem finrank_eq_one_of_involution (ρ : Representation k G V) [IsIrreducible ρ]
    (a : G) (ha : ∀ v, ρ a (ρ a v) = v)
    (hG : ∀ g, ρ g = 1 ∨ ρ g = ρ a) : Module.finrank k V = 1 := by
  have : Nontrivial ρ.asModule := IsSimpleModule.nontrivial (MonoidAlgebra k G) _
  have : Nontrivial V := ρ.asModuleEquiv.symm.toEquiv.nontrivial
  obtain ⟨v, hv⟩ := exists_ne (0 : V)
  have heigen : ∃ w : V, w ≠ 0 ∧ ∃ c : k, ρ a w = c • w := by
    by_cases h : ρ a v + v = 0
    · exact ⟨v, hv, -1, by simpa using eq_neg_of_add_eq_zero_left h⟩
    · refine ⟨ρ a v + v, h, 1, ?_⟩
      simp [ha, add_comm]
  obtain ⟨w, hw, c, hc⟩ := heigen
  let S : Subrepresentation ρ :=
    { toSubmodule := Submodule.span k {w}
      apply_mem_toSubmodule := by
        intro g x hx
        obtain ⟨d, rfl⟩ := Submodule.mem_span_singleton.mp hx
        rcases hG g with h | h
        · simpa [h] using Submodule.smul_mem (Submodule.span k {w}) d
            (Submodule.mem_span_singleton_self w)
        · rw [h, map_smul, hc, smul_smul]
          exact Submodule.mem_span_singleton.mpr ⟨d * c, rfl⟩ }
  have hS : S ≠ ⊥ := by
    intro h
    have : w ∈ S := Submodule.mem_span_singleton_self w
    rw [h] at this
    exact hw this
  have htop : S = ⊤ := (eq_bot_or_eq_top S).resolve_left hS
  apply finrank_eq_one w hw
  intro x
  have : x ∈ S := by rw [htop]; trivial
  exact Submodule.mem_span_singleton.mp this

/-- If a representation is trivial on a normal subgroup and the quotient
has order dividing two, irreducibility forces dimension one. -/
theorem finrank_eq_one_of_quotient_card_dvd_two (ρ : Representation k G V)
    [IsIrreducible ρ] (P : Subgroup G) [P.Normal]
    [IsTrivial (ρ.comp P.subtype)] (hcard : Nat.card (G ⧸ P) ∣ 2) :
    Module.finrank k V = 1 := by
  rcases (Nat.dvd_prime (by decide : Nat.Prime 2)).mp hcard with h1 | h2
  · have : Subsingleton (G ⧸ P) := (Nat.card_eq_one_iff_unique.mp h1).1
    apply ρ.finrank_eq_one_of_involution 1 (by intro v; simp)
    intro g
    left
    exact (ρ.apply_eq_of_coe_eq P g 1 (Subsingleton.elim _ _)).trans (map_one ρ)
  · have : Finite (G ⧸ P) := Nat.finite_of_card_ne_zero (by omega)
    obtain ⟨q, hq, huniq⟩ := (Nat.card_eq_two_iff' (1 : G ⧸ P)).mp h2
    obtain ⟨a, rfl⟩ := QuotientGroup.mk'_surjective P q
    have haa : ((a * a : G) : G ⧸ P) = 1 := by
      simpa [h2, pow_two] using (pow_card_eq_one' (x := QuotientGroup.mk' P a))
    apply ρ.finrank_eq_one_of_involution a
    · intro v
      have h := ρ.apply_eq_of_coe_eq P (a * a) 1 haa
      have := congrArg (fun f : Module.End k V ↦ f v) h
      simpa [Module.End.mul_apply] using this
    · intro g
      by_cases hg : (g : G ⧸ P) = 1
      · exact Or.inl ((ρ.apply_eq_of_coe_eq P g 1 hg).trans (map_one ρ))
      · exact Or.inr (ρ.apply_eq_of_coe_eq P g a (huniq _ hg))

/-- The algebraic dimension statement for a normal p-subgroup with quotient
of order dividing two, over any field of characteristic p. -/
theorem finrank_eq_one_of_normal_pSubgroup {p : ℕ} [Fact p.Prime] [CharP k p]
    (ρ : Representation k G V) [IsIrreducible ρ]
    (P : Subgroup G) [P.Normal] [Finite P] (hP : IsPGroup p P)
    (hcard : Nat.card (G ⧸ P) ∣ 2) : Module.finrank k V = 1 := by
  let : IsTrivial (ρ.comp P.subtype) :=
    ⟨fun g ↦ LinearMap.ext (ρ.normal_pSubgroup_acts_trivially P hP g)⟩
  exact ρ.finrank_eq_one_of_quotient_card_dvd_two P hcard

/-- Every one-dimensional representation is scalar multiplication by a
character with values in the units of its coefficient field. -/
theorem exists_character_of_finrank_eq_one (ρ : Representation k G V)
    (hdim : Module.finrank k V = 1) :
    ∃ χ : G →* kˣ, ∀ g v, ρ g v = (χ g : k) • v := by
  let e : k ≃+* Module.End k V := RingEquiv.ofBijective (algebraMap k (Module.End k V))
    (LinearEquiv.smul_id_of_finrank_eq_one hdim).bijective
  let χ : G →* k := e.symm.toMonoidHom.comp ρ
  refine ⟨χ.toHomUnits, ?_⟩
  intro g v
  have h := congrArg (fun f : Module.End k V ↦ f v) (e.apply_symm_apply (ρ g))
  exact h.symm

/-- The representation-theoretic classification used for simple objects in
category D: a normal 3-subgroup with quotient of order dividing two leaves
only a one-dimensional character with values in `{1, -1}`. -/
theorem simple_three_of_normal_threeSubgroup
    {W : Type*} [AddCommGroup W] [Module (ZMod 3) W]
    (ρ : Representation (ZMod 3) G W) [IsIrreducible ρ]
    (P : Subgroup G) [P.Normal] [Finite P] (hP : IsPGroup 3 P)
    (hcard : Nat.card (G ⧸ P) ∣ 2) :
    Module.finrank (ZMod 3) W = 1 ∧
      ∃ χ : G →* (ZMod 3)ˣ,
        (∀ g, χ g = 1 ∨ χ g = -1) ∧
        (∀ g w, ρ g w = (χ g : ZMod 3) • w) := by
  have hdim := ρ.finrank_eq_one_of_normal_pSubgroup P hP hcard
  obtain ⟨χ, hχ⟩ := ρ.exists_character_of_finrank_eq_one hdim
  refine ⟨hdim, χ, ?_, hχ⟩
  intro g
  exact (by decide : ∀ u : (ZMod 3)ˣ, u = 1 ∨ u = -1) (χ g)

end Representation
