/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Deformations.ArithmeticGaloisQuotient
public import Mathlib.FieldTheory.Galois.Infinite
public import Mathlib.FieldTheory.Galois.Profinite
public import Mathlib.Topology.Homeomorph.Lemmas

/-!
# The fixed field and profinite topology of the arithmetic quotient

The closed normal subgroup generated by excluded inertia has an actual
fixed field in the original algebraic closure. Restriction identifies its
Galois group homeomorphically with the arithmetic quotient.
-/

@[expose] public noncomputable section
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
namespace Deformation
variable (p : ℕ)

/-- The original ramification kernel as a closed subgroup of the absolute Galois group. -/
def hardlyRamificationClosedSubgroup : ClosedSubgroup (Field.absoluteGaloisGroup ℚ) :=
  ⟨hardlyRamificationKernel p,
    show IsClosed (hardlyRamificationKernel p : Set (Field.absoluteGaloisGroup ℚ)) from
      inferInstance⟩

instance : (hardlyRamificationClosedSubgroup p).Normal :=
  inferInstanceAs (hardlyRamificationKernel p).Normal

/-- The arithmetic fixed field inside the original rational algebraic closure. -/
def hardlyArithmeticFixedField : IntermediateField ℚ (AlgebraicClosure ℚ) :=
  IntermediateField.fixedField (hardlyRamificationKernel p)

/-- The fixed field recovers precisely the closed kernel, not merely its dense generators. -/
theorem hardlyArithmeticFixedField_fixingSubgroup :
    (hardlyArithmeticFixedField p).fixingSubgroup = hardlyRamificationKernel p :=
  InfiniteGalois.fixingSubgroup_fixedField (hardlyRamificationClosedSubgroup p)

instance : IsGalois ℚ (hardlyArithmeticFixedField p) := by
  apply (InfiniteGalois.normal_iff_isGalois (hardlyArithmeticFixedField p)).mp
  rw [hardlyArithmeticFixedField_fixingSubgroup]
  infer_instance

/-- Restriction is the exact Galois-group isomorphism for the specified arithmetic quotient. -/
def hardlyArithmeticGaloisEquiv : HardlyArithmeticGaloisGroup p ≃*
    Gal(hardlyArithmeticFixedField p/ℚ) :=
  InfiniteGalois.normalAutEquivQuotient (hardlyRamificationClosedSubgroup p)

/-- On original Galois elements the comparison is the usual restriction map. -/
theorem hardlyArithmeticGaloisEquiv_apply (g : Field.absoluteGaloisGroup ℚ) :
    hardlyArithmeticGaloisEquiv p (hardlyArithmeticGaloisProjection p g) =
      AlgEquiv.restrictNormalHom (hardlyArithmeticFixedField p) g := rfl

/-- The comparison respects the quotient and Krull topologies. -/
theorem hardlyArithmeticGaloisEquiv_continuous : Continuous (hardlyArithmeticGaloisEquiv p) :=
  (QuotientGroup.isQuotientMap_mk _).continuous_iff.mpr
    (InfiniteGalois.restrictNormalHom_continuous (hardlyArithmeticFixedField p))

/-- Compactness makes the inverse restriction comparison continuous as well. -/
def hardlyArithmeticGaloisHomeomorph : HardlyArithmeticGaloisGroup p ≃ₜ
    Gal(hardlyArithmeticFixedField p/ℚ) :=
  (hardlyArithmeticGaloisEquiv_continuous p).homeoOfEquivCompactToT2

instance : TotallyDisconnectedSpace (HardlyArithmeticGaloisGroup p) :=
  (hardlyArithmeticGaloisHomeomorph p).symm.totallyDisconnectedSpace

/-- The arithmetic quotient is a profinite space with its original quotient topology. -/
def hardlyArithmeticProfinite : Profinite := Profinite.of (HardlyArithmeticGaloisGroup p)

end Deformation
