/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Deformations.HardlyRamifiedArithmeticResidual
public import Mathlib.GroupTheory.QuotientGroup.Basic
public import Mathlib.Topology.Algebra.Group.Quotient
public import Mathlib.Topology.Algebra.Group.Subgroup

/-!
# The arithmetic quotient unramified outside two and p

Kill the closed normal subgroup generated by the actual inertia images.
Continuous representations unramified outside two and p factor uniquely
through this quotient. Local maps are induced by the original embeddings.
-/

@[expose] public noncomputable section
namespace Deformation
local notation "G" => Field.absoluteGaloisGroup ℚ

/-- The closed normal subgroup generated by inertia outside the allowed primes. -/
def hardlyRamificationKernel (p : ℕ) : Subgroup G :=
  (Subgroup.normalClosure (hardlyAwayInertia p)).topologicalClosure

instance (p : ℕ) : (hardlyRamificationKernel p).Normal :=
  Subgroup.is_normal_topologicalClosure _

instance (p : ℕ) : IsClosed (hardlyRamificationKernel p : Set G) :=
  Subgroup.isClosed_topologicalClosure _

/-- The actual global arithmetic quotient, with its quotient topology. -/
abbrev HardlyArithmeticGaloisGroup (p : ℕ) := G ⧸ hardlyRamificationKernel p

/-- The original absolute Galois group maps continuously onto the arithmetic quotient. -/
def hardlyArithmeticGaloisProjection (p : ℕ) : G →ₜ* HardlyArithmeticGaloisGroup p :=
  ⟨QuotientGroup.mk' _, QuotientGroup.continuous_mk⟩

/-- Every excluded inertia element is killed by the arithmetic projection. -/
theorem hardlyArithmeticGaloisProjection_inertia (p : ℕ) (g : G)
    (hg : g ∈ hardlyAwayInertia p) : hardlyArithmeticGaloisProjection p g = 1 :=
  (QuotientGroup.eq_one_iff g).mpr
    (Subgroup.le_topologicalClosure _ (Subgroup.subset_normalClosure hg))

variable {B : Type*} [Group B] [TopologicalSpace B] [T1Space B]
  (p : ℕ) (τ : G →ₜ* B) (hτ : ∀ g ∈ hardlyAwayInertia p, τ g = 1)

include hτ in
/-- Continuity and the Hausdorff target force the whole closed normal kernel to vanish. -/
theorem hardlyRamificationKernel_le_ker :
    hardlyRamificationKernel p ≤ τ.toMonoidHom.ker :=
  Subgroup.topologicalClosure_minimal _
    (Subgroup.normalClosure_le_normal hτ)
    (isClosed_singleton.preimage τ.continuous)

/-- A continuous arithmetic representation on the specified quotient group. -/
def hardlyArithmeticGaloisDescend : HardlyArithmeticGaloisGroup p →ₜ* B where
  toMonoidHom := QuotientGroup.lift _ τ.toMonoidHom (hardlyRamificationKernel_le_ker p τ hτ)
  continuous_toFun := (QuotientGroup.isQuotientMap_mk _).continuous_iff.mpr τ.continuous

/-- Descent recovers the original representation on every absolute Galois element. -/
theorem hardlyArithmeticGaloisDescend_apply (g : G) :
    hardlyArithmeticGaloisDescend p τ hτ (hardlyArithmeticGaloisProjection p g) = τ g := rfl

/-- The descended continuous representation is unique. -/
theorem hardlyArithmeticGaloisDescend_unique
    (σ : HardlyArithmeticGaloisGroup p →ₜ* B)
    (hσ : ∀ g, σ (hardlyArithmeticGaloisProjection p g) = τ g) :
    σ = hardlyArithmeticGaloisDescend p τ hτ := by
  ext x
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective (hardlyRamificationKernel p) x
  exact hσ g

/-- Each local map uses the same field embedding as the original arithmetic conditions. -/
def hardlyArithmeticLocalMap (q : ℕ) (hq : q.Prime) :
    Field.absoluteGaloisGroup
      (hq.toHeightOneSpectrumRingOfIntegersRat.adicCompletion ℚ) →ₜ*
        HardlyArithmeticGaloisGroup p :=
  (hardlyArithmeticGaloisProjection p).comp (Field.absoluteGaloisGroup.map
    (algebraMap ℚ (hq.toHeightOneSpectrumRingOfIntegersRat.adicCompletion ℚ)))

/-- Localization after descent is exactly the original local restriction. -/
theorem hardlyArithmeticGaloisDescend_local (q : ℕ) (hq : q.Prime) (g) :
    hardlyArithmeticGaloisDescend p τ hτ (hardlyArithmeticLocalMap p q hq g) =
      τ (Field.absoluteGaloisGroup.map
        (algebraMap ℚ (hq.toHeightOneSpectrumRingOfIntegersRat.adicCompletion ℚ)) g) := rfl

end Deformation
