/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Deformations.ContinuousTangent
public import FLT.Mathlib.RingTheory.AugmentationTangentEquiv
public import Mathlib.LinearAlgebra.Dual.Lemmas

/-!
# Tangent separation in a discrete coefficient algebra

After killing the coefficient maximal ideal, the original residue field acts
on the quotient. Cotangent duality there detects the relative square ideal.
The discreteness assumption is explicit and will only be used for open quotients.
-/

@[expose] public noncomputable section
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
open CategoryTheory IsLocalRing
namespace Deformation.ProartinianCat

variable {O : Type} [CommRing O] [IsLocalRing O] [Finite (ResidueField O)]
  (A : ProartinianCat O)
local notation "k" => residueField (𝓞 := O)

/-- The ideal generated by the original coefficient maximal ideal. -/
def coefficientMaximalIdeal : Ideal A := (maximalIdeal O).map (algebraMap O A)

omit [Finite (ResidueField O)] in
/-- Coefficient nonunits remain in the target maximal ideal. -/
theorem coefficientMaximalIdeal_le : coefficientMaximalIdeal A ≤ maximalIdeal A :=
  ((local_hom_TFAE (algebraMap O A)).out 1 3).mp
    (inferInstance : IsLocalHom (algebraMap O A))

/-- The closed relative-square relation will be used in the proartinian topology. -/
def relativeSquareIdeal : Ideal A := coefficientMaximalIdeal A ⊔ maximalIdeal A ^ 2

omit [Finite (ResidueField O)] in
/-- A discrete relative tangent separates every maximal-ideal class outside
its coefficient-plus-square relations. -/
theorem mem_relativeSquareIdeal_of_tangent_zero [DiscreteTopology A]
    {a : A} (ha : a ∈ maximalIdeal A)
    (hzero : ∀ d : continuousTangent O A, d.1 a = 0) : a ∈ relativeSquareIdeal A := by
  let C := coefficientMaximalIdeal A
  let E := A ⧸ C
  let q : A →ₐ[O] E := Ideal.Quotient.mkₐ O C
  have hC : C ≤ RingHom.ker (toResidueField A).hom.toRingHom := by
    change C ≤ RingHom.ker (toResidueField A).hom
    rw [ker_toResidueField]
    exact coefficientMaximalIdeal_le A
  let ε₀ : E →ₐ[O] k := Ideal.Quotient.liftₐ C (toResidueField A).hom.toAlgHom hC
  let : Algebra k E := Ideal.Quotient.algebraQuotientOfLEComap
    (Ideal.le_comap_map : maximalIdeal O ≤ C.comap (algebraMap O A))
  let : IsScalarTower O k E := IsScalarTower.of_algebraMap_eq' (by ext; rfl)
  let ε : E →ₐ[k] k :=
    { ε₀.toRingHom with
      commutes' := by
        intro r
        obtain ⟨o, rfl⟩ := residue_surjective (R := O) r
        exact ε₀.commutes o }
  have heq : (RingHom.ker ε).comap q.toRingHom = maximalIdeal A := by
    change RingHom.ker (toResidueField A).hom.toRingHom = maximalIdeal A
    exact ker_toResidueField A
  have hqa : q a ∈ RingHom.ker ε := by
    change a ∈ (RingHom.ker ε).comap q.toRingHom
    rwa [heq]
  have ht : ε.augmentationCotangent (q a) = 0 := by
    apply (Module.forall_dual_apply_eq_zero_iff k _).mp
    intro φ
    let t := ε.augmentationTangentEquiv φ
    let d : continuousTangent O A :=
      ⟨{ toLinearMap := (t.1.restrictScalars O).comp q.toLinearMap
         cont := continuous_of_discreteTopology }, by
        constructor
        · change t.1 (q 1) = 0
          rw [map_one]
          exact AlgHom.augmentationTangent_one t
        · intro x y
          change t.1 (q (x * y)) = _
          rw [map_mul, t.2]
          rfl⟩
    exact hzero d
  have hsq : q a ∈ RingHom.ker ε ^ 2 := by
    rw [ε.augmentationCotangent_of_mem ⟨q a, hqa⟩] at ht
    exact (Ideal.toCotangent_eq_zero _ _).mp ht
  have hm : (maximalIdeal A).map q.toRingHom = RingHom.ker ε := by
    rw [← heq, Ideal.map_comap_of_surjective q.toRingHom Ideal.Quotient.mk_surjective]
  rw [← hm, ← Ideal.map_pow] at hsq
  have : a ∈ ((maximalIdeal A ^ 2).map q.toRingHom).comap q.toRingHom := hsq
  rw [Ideal.comap_map_of_surjective q.toRingHom Ideal.Quotient.mk_surjective] at this
  change a ∈ maximalIdeal A ^ 2 ⊔ RingHom.ker (Ideal.Quotient.mk C) at this
  simpa only [Ideal.mk_ker, relativeSquareIdeal, C, sup_comm] using this

end Deformation.ProartinianCat
