/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Deformations.ClosedIdealCondition
public import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs

/-!
# The closed fixed-determinant ideal

The equations are imposed on an existing representation over the parameter
ring. Taking their closure does not change their continuous solutions.
-/

@[expose] public noncomputable section
open CategoryTheory
namespace Deformation.ProartinianCat

universe u
variable {O : Type u} [CommRing O] (U : ProartinianCat O)
  {G n : Type*} [Group G] [Fintype n] [DecidableEq n]
  (ρ : G →* GL n U) (δ : G → O)

/-- The closed ideal generated by the prescribed determinant equations. -/
def framedDeterminantIdeal : Ideal U :=
  (Ideal.span (Set.range fun g ↦
    (ρ g : Matrix n n U).det - algebraMap O U (δ g))).closure

/-- The determinant equations define a closed ideal. -/
theorem framedDeterminantIdeal_closed : IsClosed (framedDeterminantIdeal U ρ δ : Set U) :=
  isClosed_closure

/-- Continuous maps kill the ideal exactly when they have the prescribed determinant. -/
theorem kills_framedDeterminantIdeal_iff {A : ProartinianCat O} (f : U ⟶ A) :
    KillsClosedIdeal U (framedDeterminantIdeal U ρ δ) f ↔
      ∀ g, f.hom (ρ g : Matrix n n U).det = algebraMap O A (δ g) := by
  have hc (a : O) : f.hom (algebraMap O U a) = algebraMap O A a :=
    f.hom.toAlgHom.commutes a
  have hker : IsClosed (RingHom.ker f.hom.toRingHom : Set U) :=
    isClosed_eq f.hom.cont continuous_const
  have he : framedDeterminantIdeal U ρ δ ≤ RingHom.ker f.hom.toRingHom ↔
      Ideal.span (Set.range fun g ↦ (ρ g : Matrix n n U).det - algebraMap O U (δ g)) ≤
        RingHom.ker f.hom.toRingHom :=
    ⟨fun h ↦ (show _ ≤ framedDeterminantIdeal U ρ δ from
      fun _ hx ↦ subset_closure hx).trans h, fun h ↦ closure_minimal h hker⟩
  rw [KillsClosedIdeal, he, Ideal.span_le]
  constructor
  · intro h g
    have hz := h (Set.mem_range_self g)
    change f.hom ((ρ g : Matrix n n U).det - algebraMap O U (δ g)) = 0 at hz
    simpa only [map_sub, hc, sub_eq_zero] using hz
  · intro h z hz
    obtain ⟨g, rfl⟩ := hz
    change f.hom ((ρ g : Matrix n n U).det - algebraMap O U (δ g)) = 0
    rw [map_sub, hc, h g, sub_self]

/-- The same criterion stated on the specialized matrix representation. -/
theorem kills_framedDeterminantIdeal_iff_map {A : ProartinianCat O} (f : U ⟶ A) :
    KillsClosedIdeal U (framedDeterminantIdeal U ρ δ) f ↔
      ∀ g, (Matrix.GeneralLinearGroup.map f.hom.toRingHom (ρ g) : Matrix n n A).det =
        algebraMap O A (δ g) := by
  rw [kills_framedDeterminantIdeal_iff]
  apply forall_congr'
  intro g
  have hd := RingHom.map_det f.hom.toRingHom (ρ g : Matrix n n U)
  change f.hom (ρ g : Matrix n n U).det = _ at hd
  rw [hd]
  rfl

/-- An actual solution in a nonzero coefficient ring proves properness. -/
theorem framedDeterminantIdeal_ne_top {A : ProartinianCat O} [Nontrivial A] (f : U ⟶ A)
    (hf : ∀ g, f.hom (ρ g : Matrix n n U).det = algebraMap O A (δ g)) :
    framedDeterminantIdeal U ρ δ ≠ ⊤ := by
  intro htop
  have hk := (kills_framedDeterminantIdeal_iff U ρ δ f).mpr hf
  have hz : f.hom 1 = 0 := hk (htop ▸ Submodule.mem_top)
  simp at hz

variable [IsLocalRing O] [Finite (IsLocalRing.ResidueField O)]
  (hne : framedDeterminantIdeal U ρ δ ≠ ⊤)

/-- The constructed determinant quotient classifies exactly the determinant solutions. -/
def framedDeterminantFactorEquiv (A : ProartinianCat O) :
    (closedIdealQuotient U (framedDeterminantIdeal U ρ δ)
      (framedDeterminantIdeal_closed U ρ δ) hne ⟶ A) ≃
      {f : U ⟶ A // ∀ g, f.hom (ρ g : Matrix n n U).det = algebraMap O A (δ g)} :=
  (closedIdealFactorEquiv U (framedDeterminantIdeal U ρ δ)
    (framedDeterminantIdeal_closed U ρ δ) hne A).trans
    (Equiv.subtypeEquivRight (kills_framedDeterminantIdeal_iff U ρ δ))

end Deformation.ProartinianCat
