/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Deformations.ClosedIdealCondition
public import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs

/-!
# The closed ideal for a specified framed rank-one quotient

The quotient coordinate is fixed as part of the framing. Its equivariance
is imposed by actual matrix equations. This does not assert existence of a
quotient line for an arbitrary deformation.
-/

@[expose] public noncomputable section
open CategoryTheory
namespace Deformation.ProartinianCat

universe u
variable {O : Type u} [CommRing O] (U : ProartinianCat O)
  {G n : Type*} [Group G] [Fintype n] [DecidableEq n]
  (ρ : G →* GL n U) (χ : G →* Oˣ) (q : n)

/-- The matrix equations for the chosen coordinate projection onto `χ`. -/
def framedQuotientDefect (g : G) (j : n) : U :=
  ρ g q j - if j = q then algebraMap O U (χ g : O) else 0

/-- Close the ideal generated by all equivariance equations. -/
def framedQuotientIdeal : Ideal U :=
  (Ideal.span (Set.range fun t : G × n ↦ framedQuotientDefect U ρ χ q t.1 t.2)).closure

/-- The framed quotient condition is closed by construction. -/
theorem framedQuotientIdeal_closed : IsClosed (framedQuotientIdeal U ρ χ q : Set U) :=
  isClosed_closure

/-- Killing this ideal is exactly equivariance of the specified quotient row. -/
theorem kills_framedQuotientIdeal_iff {A : ProartinianCat O} (f : U ⟶ A) :
    KillsClosedIdeal U (framedQuotientIdeal U ρ χ q) f ↔
      ∀ g j, f.hom (ρ g q j) = if j = q then algebraMap O A (χ g : O) else 0 := by
  have hc (a : O) : f.hom (algebraMap O U a) = algebraMap O A a :=
    f.hom.toAlgHom.commutes a
  have hker : IsClosed (RingHom.ker f.hom.toRingHom : Set U) :=
    isClosed_eq f.hom.cont continuous_const
  have he : framedQuotientIdeal U ρ χ q ≤ RingHom.ker f.hom.toRingHom ↔
      Ideal.span (Set.range fun t : G × n ↦ framedQuotientDefect U ρ χ q t.1 t.2) ≤
        RingHom.ker f.hom.toRingHom :=
    ⟨fun h ↦ (show _ ≤ framedQuotientIdeal U ρ χ q from fun _ hx ↦ subset_closure hx).trans h,
      fun h ↦ closure_minimal h hker⟩
  rw [KillsClosedIdeal, he, Ideal.span_le]
  constructor
  · intro h g j
    have hz := h (Set.mem_range_self (g, j))
    change f.hom (framedQuotientDefect U ρ χ q g j) = 0 at hz
    by_cases hj : j = q
    · simpa only [framedQuotientDefect, hj, ite_true, map_sub,
        hc, sub_eq_zero] using hz
    · simpa only [framedQuotientDefect, hj, ite_false, sub_zero] using hz
  · intro h z hz
    obtain ⟨⟨g, j⟩, rfl⟩ := hz
    change f.hom (framedQuotientDefect U ρ χ q g j) = 0
    by_cases hj : j = q
    · simpa only [framedQuotientDefect, hj, ite_true, map_sub,
        hc, sub_eq_zero] using h g j
    · simpa only [framedQuotientDefect, hj, ite_false, sub_zero] using h g j

/-- The row condition is preserved by every continuous coefficient morphism. -/
theorem framedQuotient_row_comp {A B : ProartinianCat O} (f : U ⟶ A) (g : A ⟶ B)
    (hf : ∀ s j, f.hom (ρ s q j) = if j = q then algebraMap O A (χ s : O) else 0) :
    ∀ s j, (f ≫ g).hom (ρ s q j) = if j = q then algebraMap O B (χ s : O) else 0 :=
  (kills_framedQuotientIdeal_iff U ρ χ q (f ≫ g)).mp
    (killsClosedIdeal_comp U _ f g ((kills_framedQuotientIdeal_iff U ρ χ q f).mpr hf))

/-- An actual framed solution in a nonzero ring proves the ideal proper. -/
theorem framedQuotientIdeal_ne_top {A : ProartinianCat O} [Nontrivial A] (f : U ⟶ A)
    (hf : ∀ g j, f.hom (ρ g q j) = if j = q then algebraMap O A (χ g : O) else 0) :
    framedQuotientIdeal U ρ χ q ≠ ⊤ := by
  intro htop
  have hk := (kills_framedQuotientIdeal_iff U ρ χ q f).mpr hf
  have hz : f.hom 1 = 0 := hk (htop ▸ Submodule.mem_top)
  simp at hz

variable [IsLocalRing O] [Finite (IsLocalRing.ResidueField O)]
  (hne : framedQuotientIdeal U ρ χ q ≠ ⊤)

/-- The actual closed quotient classifies the prescribed framed quotient row. -/
def framedQuotientFactorEquiv (A : ProartinianCat O) :
    (closedIdealQuotient U (framedQuotientIdeal U ρ χ q)
      (framedQuotientIdeal_closed U ρ χ q) hne ⟶ A) ≃
      {f : U ⟶ A // ∀ g j, f.hom (ρ g q j) =
        if j = q then algebraMap O A (χ g : O) else 0} :=
  (closedIdealFactorEquiv U (framedQuotientIdeal U ρ χ q)
    (framedQuotientIdeal_closed U ρ χ q) hne A).trans
    (Equiv.subtypeEquivRight (kills_framedQuotientIdeal_iff U ρ χ q))

end Deformation.ProartinianCat
