/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.NumberField.Completion.FieldEquiv
public import Mathlib.FieldTheory.Normal.Basic

/-!
# All completions of a normal extension realize the same local compositum

Normality makes the image of the global field independent of its chosen
embedding into an algebraic closure of the local field.
-/

@[expose] public noncomputable section

namespace AlgHom

variable {K L Ω : Type*} [Field K] [Field L] [Field Ω]
  [Algebra K L] [Algebra K Ω] [Normal K L]

/-- Any two embeddings of a normal extension into a common field have the same image. -/
theorem fieldRange_eq_of_normal (f g : L →ₐ[K] Ω) : f.fieldRange = g.fieldRange := by
  let e := g.equivFieldRange
  let : Normal K g.fieldRange := Normal.of_algEquiv e
  have h : (f.comp e.symm.toAlgHom).fieldRange = f.fieldRange := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact ⟨e.symm y, rfl⟩
    · rintro ⟨y, rfl⟩
      exact ⟨e y, by simp⟩
  exact h.symm.trans (f.comp e.symm.toAlgHom).fieldRange_of_normal

end AlgHom

namespace NumberField

open IsDedekindDomain.HeightOneSpectrum

variable {K : Type*} [Field K] [NumberField K]
  (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
  {F : Type*} [Field F] [Algebra K F]
  (e : v.adicCompletion K ≃ₐ[K] F)
  {L : Type*} [Field L] [NumberField L] [Algebra K L] [FiniteDimensional K L]
  {Ω : Type*} [Field Ω] [Algebra F Ω] [Algebra K Ω] [IsScalarTower K F Ω]

omit [IsScalarTower K F Ω] in
/-- An arbitrary completion embedding over a presentation of the local base has image
generated by its restriction to the global field. -/
theorem fieldRange_eq_adjoin_of_completion_embedding_of_equiv
    (j : L →ₐ[K] Ω) (w : v.Extension (𝓞 L)) :
    letI := completionAlgebraOfEquiv v e w
    ∀ (g : w.1.adicCompletion L →ₐ[F] Ω)
      (_ : ∀ x : L, g (algebraMap L _ x) = j x),
      g.fieldRange = IntermediateField.adjoin F (Set.range j) := by
  let := completionAlgebraOfEquiv v e w
  intro g hg
  let : Algebra (v.adicCompletion K) Ω := Algebra.compHom Ω e.toRingHom
  let g' : w.1.adicCompletion L →ₐ[v.adicCompletion K] Ω := {
    __ := g.toRingHom
    commutes' := fun x ↦ by
      change g (algebraMap (v.adicCompletion K) _ x) = algebraMap F Ω (e x)
      have hx := g.commutes (e x)
      change g (algebraMap (v.adicCompletion K) _ (e.symm (e x))) =
        algebraMap F Ω (e x) at hx
      simpa only [e.symm_apply_apply] using hx }
  apply le_antisymm
  · rintro _ ⟨y, rfl⟩
    have hy : g' y ∈ IntermediateField.adjoin (v.adicCompletion K) (Set.range j) := by
      rw [← fieldRange_eq_adjoin_of_completion_embedding v j w g' hg]
      exact ⟨y, rfl⟩
    suffices h : ∀ z ∈ IntermediateField.adjoin (v.adicCompletion K) (Set.range j),
        z ∈ IntermediateField.adjoin F (Set.range j) from h (g' y) hy
    intro z hz
    induction hz using IntermediateField.adjoin_induction with
    | mem x hx => exact IntermediateField.subset_adjoin F _ hx
    | algebraMap x => exact IntermediateField.algebraMap_mem _ (e x)
    | add x y _ _ hx hy => exact add_mem hx hy
    | inv x _ hx => exact inv_mem hx
    | mul x y _ _ hx hy => exact mul_mem hx hy
  · rw [IntermediateField.adjoin_le_iff]
    rintro _ ⟨x, rfl⟩
    exact ⟨algebraMap L _ x, hg x⟩

/-- Every completion of a normal global extension is isomorphic to the same local
compositum, independently of the prime above the base place. -/
theorem nonempty_completion_equiv_adjoin_of_normal [Normal K L] [IsAlgClosed Ω]
    (j : L →ₐ[K] Ω) (w : v.Extension (𝓞 L)) :
    letI := completionAlgebraOfEquiv v e w
    Nonempty (w.1.adicCompletion L ≃ₐ[F] IntermediateField.adjoin F (Set.range j)) := by
  let := completionAlgebraOfEquiv v e w
  let := completion_finiteDimensional_of_equiv v e w
  let : IsScalarTower K F (w.1.adicCompletion L) := by
    apply IsScalarTower.of_algebraMap_eq
    intro x
    change algebraMap K _ x =
      algebraMap (v.adicCompletion K) _ (e.symm (algebraMap K F x))
    rw [e.symm.commutes]
    exact (w.adicCompletionSemialgHom K L).commutes x |>.symm
  let g : w.1.adicCompletion L →ₐ[F] Ω := IsAlgClosed.lift
  let j' : L →ₐ[K] Ω :=
    (g.restrictScalars K).comp (IsScalarTower.toAlgHom K L (w.1.adicCompletion L))
  have hrange : Set.range j' = Set.range j :=
    congrArg SetLike.coe (j'.fieldRange_eq_of_normal j)
  have h := fieldRange_eq_adjoin_of_completion_embedding_of_equiv v e j' w g (fun _ ↦ rfl)
  rw [hrange] at h
  exact ⟨g.equivFieldRange.trans (IntermediateField.equivOfEq h)⟩

end NumberField
