/-
Copyright (c) 2026 FLT contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: FLT contributors
-/
module

public import FLT.Deformations.DeSmitLenstra.TraceCoefficients
public import FLT.Deformations.ProartinianQuotients
public import Mathlib.CategoryTheory.CofilteredSystem
public import Mathlib.LinearAlgebra.TensorProduct.Free
public import Mathlib.RingTheory.Finiteness.Cardinality
public import Mathlib.RingTheory.Idempotents
public import Mathlib.RingTheory.Ideal.Quotient.PowTransition

/-!
# Compatible idempotents over proartinian coefficient rings

This file lifts an idempotent from the residual quotient of a finite free algebra through all
artinian quotients of a proartinian local coefficient ring.  The finite inverse-system argument is
needed because idempotent lifts need not be unique in a noncommutative algebra.
-/

@[expose] public section

universe u v

namespace Deformation

namespace CompatibleIdempotent

noncomputable section

variable {S A : Type u} {ι : Type v} [CommRing S] [Ring A] [Algebra S A]

/-- The ideal of an `S`-algebra generated by an ideal of `S`. -/
abbrev extendedIdeal (I : Ideal S) : Ideal A := I.map (algebraMap S A)

/-- An ideal extended along the central algebra map is two-sided, even when the algebra is
noncommutative. -/
lemma extendedIdeal_isTwoSided (I : Ideal S) : (extendedIdeal (A := A) I).IsTwoSided := by
  constructor
  intro c a ha
  induction ha using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨r, hr, rfl⟩ := hx
      rw [Algebra.commutes r a]
      exact (extendedIdeal I).mul_mem_left a
        (Ideal.mem_map_of_mem (algebraMap S A) hr)
  | zero => simp
  | add x y _ _ hx hy => simpa [add_mul] using (extendedIdeal I).add_mem hx hy
  | smul c x _ hx =>
      simpa [smul_eq_mul, mul_assoc] using (extendedIdeal I).mul_mem_left c hx

attribute [instance] extendedIdeal_isTwoSided

/-- Extension along a central algebra map preserves products of ideals. -/
lemma extendedIdeal_mul (I J : Ideal S) :
    extendedIdeal (A := A) (I * J) = extendedIdeal (A := A) I * extendedIdeal (A := A) J := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    exact Ideal.mul_le.mpr fun r hr s hs ↦ by
      rw [Ideal.mem_comap, map_mul]
      exact Ideal.mul_mem_mul (Ideal.mem_map_of_mem (algebraMap S A) hr)
        (Ideal.mem_map_of_mem (algebraMap S A) hs)
  · change Ideal.span (algebraMap S A '' (I : Set S)) *
        Ideal.span (algebraMap S A '' (J : Set S)) ≤
        Ideal.span (algebraMap S A '' ((I * J : Ideal S) : Set S))
    let _ : (Ideal.span (algebraMap S A '' (I : Set S))).IsTwoSided := by
      change (extendedIdeal (A := A) I).IsTwoSided
      infer_instance
    rw [Ideal.span_mul_span]
    apply Ideal.span_le.mpr
    rintro _ ⟨_, ⟨r, hr, rfl⟩, _, ⟨s, hs, rfl⟩, rfl⟩
    change algebraMap S A r * algebraMap S A s ∈
      Ideal.span (algebraMap S A '' ((I * J : Ideal S) : Set S))
    rw [← map_mul]
    exact Ideal.mem_map_of_mem (algebraMap S A) (Ideal.mul_mem_mul hr hs)

/-- Extension along a central algebra map preserves powers of ideals. -/
lemma extendedIdeal_pow (I : Ideal S) (n : ℕ) :
    extendedIdeal (A := A) (I ^ n) = extendedIdeal (A := A) I ^ n := by
  induction n with
  | zero =>
      rw [Submodule.pow_zero, Submodule.pow_zero, Ideal.one_eq_top, Ideal.one_eq_top]
      apply (Ideal.eq_top_iff_one _).mpr
      simpa only [map_one] using
        Ideal.mem_map_of_mem (algebraMap S A) (Submodule.mem_top : (1 : S) ∈ (⊤ : Ideal S))
  | succ n ih =>
      calc
        extendedIdeal (A := A) (I ^ (n + 1)) =
            extendedIdeal (A := A) (I * I ^ n) := by
          rw [Ideal.IsTwoSided.pow_succ]
        _ = extendedIdeal (A := A) I * extendedIdeal (A := A) (I ^ n) :=
          extendedIdeal_mul _ _
        _ = extendedIdeal (A := A) I * extendedIdeal (A := A) I ^ n := by rw [ih]
        _ = extendedIdeal (A := A) I ^ (n + 1) :=
          (Ideal.IsTwoSided.pow_succ _).symm

variable [Finite ι] (b : Module.Basis ι S A)

lemma mem_extendedIdeal_iff (I : Ideal S) (x : A) :
    x ∈ extendedIdeal (A := A) I ↔ ∀ i, b.repr x i ∈ I := by
  classical
  let _ := Fintype.ofFinite ι
  constructor
  · intro hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨r, hr, rfl⟩ := hx
        intro i
        have halg : algebraMap S A r = r • (1 : A) := by
          simpa using (Algebra.smul_def r (1 : A)).symm
        rw [halg, map_smul]
        exact I.mul_mem_right _ hr
    | zero => simp
    | add x y _ _ hx hy =>
        intro i
        simpa using I.add_mem (hx i) (hy i)
    | smul c x _ hx =>
        intro j
        have hrepr : b.repr (c * x) j =
            ∑ i, b.repr x i * b.repr (c * b i) j := by
          conv_lhs => rw [← b.sum_repr x]
          simp only [Finset.mul_sum, Algebra.mul_smul_comm, map_sum, map_smul,
            Finsupp.coe_finsetSum, Finsupp.coe_smul, Finset.sum_apply, Pi.smul_apply,
            smul_eq_mul]
        rw [smul_eq_mul, hrepr]
        exact I.sum_mem fun i _ ↦ I.mul_mem_right _ (hx i)
  · intro hx
    rw [← b.sum_repr x]
    exact (extendedIdeal I).sum_mem fun i _ ↦ by
      rw [Algebra.smul_def, Algebra.commutes]
      exact (extendedIdeal I).mul_mem_left (b i)
        (Ideal.mem_map_of_mem (algebraMap S A) (hx i))

/-- Coordinates identify the quotient of a finite free algebra by an extended ideal with a finite
power of the corresponding coefficient-ring quotient.  This is an equivalence of types; the ring
structure remains the quotient ring structure on the left. -/
def quotientEquivPi (I : Ideal S) :
    (A ⧸ extendedIdeal (A := A) I) ≃ (ι → S ⧸ I) := by
  classical
  letI := Fintype.ofFinite ι
  letI : (extendedIdeal (A := A) I).IsTwoSided := extendedIdeal_isTwoSided I
  refine
    { toFun := fun x ↦ Quotient.liftOn' x
        (fun a i ↦ Ideal.Quotient.mk I (b.repr a i)) ?_
      invFun := fun x ↦ Ideal.Quotient.mk (extendedIdeal (A := A) I)
        (b.equivFun.symm fun i ↦ (x i).out)
      left_inv := ?_
      right_inv := ?_ }
  · intro x y hxy
    funext i
    apply Ideal.Quotient.eq.2
    have hmem : x - y ∈ extendedIdeal (A := A) I := by
      simpa [sub_eq_add_neg, add_comm] using
        (extendedIdeal (A := A) I).neg_mem (QuotientAddGroup.leftRel_apply.mp hxy)
    simpa using (mem_extendedIdeal_iff b I (x - y)).mp hmem i
  · rintro ⟨x⟩
    apply Ideal.Quotient.eq.2
    apply (mem_extendedIdeal_iff b I _).mpr
    intro i
    rw [map_sub, Finsupp.sub_apply, ← b.equivFun_apply, LinearEquiv.apply_symm_apply]
    exact Ideal.Quotient.eq.1 (Quotient.out_eq' _)
  · intro x
    funext i
    change Ideal.Quotient.mk I
      (b.repr (b.equivFun.symm fun j ↦ (x j).out) i) = x i
    rw [← b.equivFun_apply, LinearEquiv.apply_symm_apply]
    exact Ideal.Quotient.mk_out _

/-- If a power of `I` is contained in `J`, then the transition from the quotient by `J` to the
quotient by `I` has elementwise nilpotent kernel. -/
lemma quotientTransition_ker_isNilpotent {I J : Ideal S} (hJI : J ≤ I)
    (hpow : ∃ n, I ^ n ≤ J) :
    ∀ x ∈ RingHom.ker
      (Ideal.Quotient.factor (Ideal.map_mono hJI) :
        (A ⧸ extendedIdeal (A := A) J) →+* (A ⧸ extendedIdeal (A := A) I)),
      IsNilpotent x := by
  rintro x hx
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [RingHom.mem_ker, Ideal.Quotient.factor_mk,
    Ideal.Quotient.eq_zero_iff_mem] at hx
  obtain ⟨n, hn⟩ := hpow
  refine ⟨n, Ideal.Quotient.eq_zero_iff_mem.mpr ?_⟩
  have hp : (extendedIdeal (A := A) I) ^ n ≤ extendedIdeal (A := A) J := by
    rw [← extendedIdeal_pow]
    exact Ideal.map_mono hn
  exact hp (Ideal.pow_mem_pow hx n)

section Proartinian

open CategoryTheory
open IsLocalRing

variable {O : Type u} [CommRing O] [IsLocalRing O] [Finite (ResidueField O)]
variable (S : ProartinianCat O) {A : Type u} [Ring A] [Algebra S A]

/-- Proper open ideals are directed toward finer quotients. -/
noncomputable instance openIdealIsDirectedOrder :
    IsDirectedOrder (ProartinianCat.OpenIdeal S) where
  directed I J := by
    let K : ProartinianCat.OpenIdeal S := OrderDual.toDual
      ⟨ProartinianCat.OpenIdeal.ideal I ⊓ ProartinianCat.OpenIdeal.ideal J,
        (ProartinianCat.OpenIdeal.isOpen I).inter (ProartinianCat.OpenIdeal.isOpen J),
        ne_top_of_le_ne_top (ProartinianCat.OpenIdeal.ne_top I) inf_le_left⟩
    refine ⟨K, ?_, ?_⟩
    · exact show ProartinianCat.OpenIdeal.ideal K ≤
        ProartinianCat.OpenIdeal.ideal I from inf_le_left
    · exact show ProartinianCat.OpenIdeal.ideal K ≤
        ProartinianCat.OpenIdeal.ideal J from inf_le_right

/-- The finite algebra quotient attached to a proper open ideal. -/
abbrev quotientAlgebra (I : ProartinianCat.OpenIdeal S) :=
  A ⧸ extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I)

/-- Transition map on the finite algebra quotients. -/
def quotientAlgebraTransition (I J : ProartinianCat.OpenIdeal S) (h : I ≤ J) :
    quotientAlgebra (A := A) S J →+* quotientAlgebra (A := A) S I :=
  Ideal.Quotient.factor (Ideal.map_mono (ProartinianCat.OpenIdeal.ideal_le_ideal h))

omit [IsLocalRing O] [Finite (ResidueField O)] in
@[simp]
lemma quotientAlgebraTransition_mk (I J : ProartinianCat.OpenIdeal S) (h : I ≤ J) (a : A) :
    quotientAlgebraTransition (A := A) S I J h
      (Ideal.Quotient.mk (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal J)) a) =
    Ideal.Quotient.mk (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I)) a :=
  Ideal.Quotient.factor_mk _ _

omit [IsLocalRing O] [Finite (ResidueField O)] in
/-- Every proper open ideal is contained in the maximal ideal, so a power of any proper open ideal
is contained in any other proper open ideal. -/
lemma exists_openIdeal_pow_le (I J : ProartinianCat.OpenIdeal S) :
    ∃ n, ProartinianCat.OpenIdeal.ideal I ^ n ≤ ProartinianCat.OpenIdeal.ideal J := by
  obtain ⟨n, hn⟩ := exists_maximalIdeal_pow_le_of_isProartinian
    (ProartinianCat.OpenIdeal.ideal J) (ProartinianCat.OpenIdeal.isOpen J)
  refine ⟨n, (Ideal.pow_right_mono ?_ n).trans hn⟩
  exact le_maximalIdeal (ProartinianCat.OpenIdeal.ne_top I)

omit [IsLocalRing O] [Finite (ResidueField O)] in
/-- Transition kernels between the artinian algebra quotients are nilpotent. -/
lemma quotientAlgebraTransition_ker_isNilpotent (I J : ProartinianCat.OpenIdeal S) (h : I ≤ J) :
    ∀ x ∈ RingHom.ker (quotientAlgebraTransition (A := A) S I J h), IsNilpotent x :=
  quotientTransition_ker_isNilpotent
    (ProartinianCat.OpenIdeal.ideal_le_ideal h) (exists_openIdeal_pow_le S I J)

theorem quotientAlgebraFinite {i : Type v} [Finite i] (b : Module.Basis i S A)
    (I : ProartinianCat.OpenIdeal S) :
    Finite (quotientAlgebra (A := A) S I) := by
  let _ : Fintype i := Fintype.ofFinite i
  exact Finite.of_equiv (i → S ⧸ ProartinianCat.OpenIdeal.ideal I)
    (quotientEquivPi b (ProartinianCat.OpenIdeal.ideal I)).symm

/-- Idempotents in the finite algebra quotients, as an inverse system of finite types. -/
def idempotentFunctor : ((ProartinianCat.OpenIdeal S)ᵒᵖ) ⥤ Type u where
  obj I := { e : quotientAlgebra (A := A) S I.unop // IsIdempotentElem e }
  map {I J} f := ↾fun e ↦
    ⟨quotientAlgebraTransition (A := A) S J.unop I.unop f.unop.le e,
      e.2.map (quotientAlgebraTransition (A := A) S J.unop I.unop f.unop.le)⟩
  map_id _ := by
    ext e
    obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective e.1
    dsimp
    rw [← ha]
    rfl
  map_comp _ _ := by
    ext e
    obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective e.1
    dsimp
    rw [← ha]
    rfl

theorem idempotentFunctorFinite {i : Type v} [Finite i] (b : Module.Basis i S A)
    (I : (ProartinianCat.OpenIdeal S)ᵒᵖ) : Finite ((idempotentFunctor (A := A) S).obj I) := by
  let _ : Finite (quotientAlgebra (A := A) S I.unop) := quotientAlgebraFinite S b I.unop
  exact Subtype.finite

instance idempotentFunctorNonempty
    (I : (ProartinianCat.OpenIdeal S)ᵒᵖ) : Nonempty ((idempotentFunctor (A := A) S).obj I) :=
  ⟨⟨0, IsIdempotentElem.zero⟩⟩

omit [IsLocalRing O] [Finite (ResidueField O)] in
/-- Every transition map on idempotents is surjective. -/
lemma idempotentFunctor_map_surjective {I J : (ProartinianCat.OpenIdeal S)ᵒᵖ}
    (f : I ⟶ J) : Function.Surjective ((idempotentFunctor (A := A) S).map f) := by
  intro e
  let q := quotientAlgebraTransition (A := A) S J.unop I.unop f.unop.le
  have hq : Function.Surjective q :=
    Ideal.Quotient.factor_surjective (Ideal.map_mono
      (ProartinianCat.OpenIdeal.ideal_le_ideal f.unop.le))
  obtain ⟨e', he', hmap⟩ := exists_isIdempotentElem_eq_of_ker_isNilpotent q
    (quotientAlgebraTransition_ker_isNilpotent S J.unop I.unop f.unop.le)
    e.1 (Set.mem_range.mpr (hq e.1)) e.2
  exact ⟨⟨e', he'⟩, Subtype.ext hmap⟩

/-- A chosen idempotent in one artinian quotient extends to a compatible idempotent in every
proper open-ideal quotient. -/
theorem exists_compatible_idempotents {i : Type v} [Finite i] (b : Module.Basis i S A)
    (I : ProartinianCat.OpenIdeal S) (e : quotientAlgebra (A := A) S I)
    (he : IsIdempotentElem e) :
    ∃ s : (idempotentFunctor (A := A) S).sections, s.val (Opposite.op I) = ⟨e, he⟩ := by
  let _ : ∀ J, Finite ((idempotentFunctor (A := A) S).obj J) :=
    fun J ↦ idempotentFunctorFinite S b J
  exact (idempotentFunctor (A := A) S).eval_section_surjective_of_surjective
    (fun {_ _} f ↦ idempotentFunctor_map_surjective (A := A) S f) (Opposite.op I) ⟨e, he⟩

omit [IsLocalRing O] [Finite (ResidueField O)] in
/-- Taking basis coordinates commutes with transition to a coarser quotient. -/
lemma quotientEquivPi_transition {i : Type v} [Finite i] (b : Module.Basis i S A)
    (I J : ProartinianCat.OpenIdeal S) (h : I ≤ J) (x : quotientAlgebra (A := A) S J) :
    quotientEquivPi b (ProartinianCat.OpenIdeal.ideal I)
        (quotientAlgebraTransition (A := A) S I J h x) =
      fun k ↦ ProartinianCat.openIdealTransition S I J h
        (quotientEquivPi b (ProartinianCat.OpenIdeal.ideal J) x k) := by
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
  rfl

/-- One basis coordinate of a compatible family of quotient idempotents, viewed in the inverse
limit of the coefficient-ring quotients. -/
def sectionCoordinate {i : Type v} [Finite i] (b : Module.Basis i S A)
    (s : (idempotentFunctor (A := A) S).sections) (k : i) :
    ProartinianCat.OpenIdealLimit S where
  val I := quotientEquivPi b (ProartinianCat.OpenIdeal.ideal I)
    (s.val (Opposite.op I)).1 k
  property I J h := by
    have hs : quotientAlgebraTransition (A := A) S I J h
        (s.val (Opposite.op J)).1 = (s.val (Opposite.op I)).1 :=
      congrArg Subtype.val (s.property (homOfLE h).op)
    have ht := congrFun
      (quotientEquivPi_transition (A := A) S b I J h (s.val (Opposite.op J)).1) k
    rw [← ht, hs]

/-- Assemble a compatible family of quotient idempotents coordinatewise in the proartinian inverse
limit. -/
def assembleSection {i : Type v} [Finite i] (b : Module.Basis i S A)
    (s : (idempotentFunctor (A := A) S).sections) : A :=
  b.equivFun.symm fun k ↦
    (ProartinianCat.openIdealLimitRingEquiv S).symm (sectionCoordinate S b s k)

/-- The assembled element reduces to the given section in every proper open-ideal quotient. -/
lemma quotient_assembleSection {i : Type v} [Finite i] (b : Module.Basis i S A)
    (s : (idempotentFunctor (A := A) S).sections) (I : ProartinianCat.OpenIdeal S) :
    Ideal.Quotient.mk (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I))
        (assembleSection S b s) = (s.val (Opposite.op I)).1 := by
  apply (quotientEquivPi b (ProartinianCat.OpenIdeal.ideal I)).injective
  funext k
  change Ideal.Quotient.mk (ProartinianCat.OpenIdeal.ideal I)
      (b.repr (assembleSection S b s) k) =
    quotientEquivPi b (ProartinianCat.OpenIdeal.ideal I) (s.val (Opposite.op I)).1 k
  rw [assembleSection, ← b.equivFun_apply, LinearEquiv.apply_symm_apply]
  have h := congrArg (fun z : ProartinianCat.OpenIdealLimit S ↦ z.val I)
    ((ProartinianCat.openIdealLimitRingEquiv S).apply_symm_apply (sectionCoordinate S b s k))
  exact h

/-- The element assembled from a compatible section is idempotent. -/
lemma assembleSection_isIdempotent {i : Type v} [Finite i] (b : Module.Basis i S A)
    (s : (idempotentFunctor (A := A) S).sections) :
    IsIdempotentElem (assembleSection S b s) := by
  rw [IsIdempotentElem]
  apply b.repr.injective
  ext k
  apply ProartinianCat.toOpenIdealLimit_injective S
  apply InverseLimit.ext_lemma
  intro I
  change Ideal.Quotient.mk (ProartinianCat.OpenIdeal.ideal I)
      (b.repr (assembleSection S b s * assembleSection S b s) k) =
    Ideal.Quotient.mk (ProartinianCat.OpenIdeal.ideal I)
      (b.repr (assembleSection S b s) k)
  apply Ideal.Quotient.eq.2
  have hquot : Ideal.Quotient.mk
      (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I))
        (assembleSection S b s * assembleSection S b s) =
      Ideal.Quotient.mk (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I))
        (assembleSection S b s) := by
    calc
      _ = Ideal.Quotient.mk
            (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I))
            (assembleSection S b s) *
          Ideal.Quotient.mk
            (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I))
            (assembleSection S b s) := map_mul _ _ _
      _ = (s.val (Opposite.op I)).1 * (s.val (Opposite.op I)).1 := by
        rw [quotient_assembleSection S b s I]
      _ = (s.val (Opposite.op I)).1 := (s.val (Opposite.op I)).2.eq
      _ = Ideal.Quotient.mk
            (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I))
            (assembleSection S b s) := (quotient_assembleSection S b s I).symm
  have hmem : assembleSection S b s * assembleSection S b s - assembleSection S b s ∈
      extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I) :=
    Ideal.Quotient.eq.mp hquot
  simpa using (mem_extendedIdeal_iff b (ProartinianCat.OpenIdeal.ideal I) _).mp hmem k

/-- An idempotent in any proper open-ideal quotient of a finite free algebra lifts to an
idempotent of the algebra.  In particular, this applies to a primitive residual matrix
idempotent by taking `I` to be the maximal ideal. -/
theorem exists_isIdempotentElem_lift {i : Type v} [Finite i] (b : Module.Basis i S A)
    (I : ProartinianCat.OpenIdeal S) (e : quotientAlgebra (A := A) S I)
    (he : IsIdempotentElem e) :
    ∃ e' : A, IsIdempotentElem e' ∧
      Ideal.Quotient.mk (extendedIdeal (A := A) (ProartinianCat.OpenIdeal.ideal I)) e' = e := by
  obtain ⟨s, hs⟩ := exists_compatible_idempotents S b I e he
  refine ⟨assembleSection S b s, assembleSection_isIdempotent S b s, ?_⟩
  exact (quotient_assembleSection S b s I).trans (congrArg Subtype.val hs)

/-- The maximal ideal, bundled as a proper open ideal. -/
def maximalOpenIdeal : ProartinianCat.OpenIdeal S :=
  OrderDual.toDual ⟨maximalIdeal S, isOpen_maximalIdeal_of_isProartinian,
    (maximalIdeal.isMaximal S).ne_top⟩

/-- Residual form of `exists_isIdempotentElem_lift`. -/
theorem exists_isIdempotentElem_lift_residue {i : Type v} [Finite i]
    (b : Module.Basis i S A)
    (e : quotientAlgebra (A := A) S (maximalOpenIdeal S)) (he : IsIdempotentElem e) :
    ∃ e' : A, IsIdempotentElem e' ∧
      Ideal.Quotient.mk (extendedIdeal (A := A) (maximalIdeal S)) e' = e :=
  exists_isIdempotentElem_lift S b (maximalOpenIdeal S) e he

end Proartinian

end

end CompatibleIdempotent

end Deformation
