/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Deformations.DeSmitLenstra.UniversalLift

/-!
# The image of the universal trace ring under specialization

The image is exactly the closed algebra generated by traces of the specialized
representation. Compactness makes the image closed; no Noetherianity is used.
-/

@[expose] public noncomputable section
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
open CategoryTheory IsLocalRing
namespace Deformation

universe u
variable (O : Type u) [CommRing O] [IsLocalRing O] [IsNoetherianRing O]
  [Finite (ResidueField O)]
  (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G]
  (n : Type) [Fintype n] [DecidableEq n]
  (rho : G →ₜ* GL n (ProartinianCat.residueField (𝓞 := O)))
  (A : ProartinianCat O) (tau : ContinuousFramedLifts O G n rho A)

/-- Restrict the framed specialization to the actual universal trace ring. -/
def traceSpecialization : universalTraceRingObject O G n rho ⟶ A :=
  universalTraceRingInclusion O G n rho ≫
    profiniteFramedLimitLiftToHom O G n rho A tau

/-- The image of the unframed trace coefficients in this framed target. -/
def traceSpecializationImage : Subalgebra O A :=
  (traceSpecialization O G n rho A tau).hom.toAlgHom.range

omit [TotallyDisconnectedSpace G] in
/-- Universal traces specialize to traces of the given lift. -/
theorem traceSpecialization_trace (g : G) :
    (traceSpecialization O G n rho A tau).hom
      ⟨(profiniteUniversalMatrix O G n rho g).trace, universalTrace_mem O G n rho g⟩ =
        (tau.val g).val.trace := by
  have h := congrArg (fun t : ContinuousFramedLifts O G n rho A ↦ (t.val g).val.trace)
    (profiniteFramedLimitHomToLift_liftToHom O G n rho A tau)
  exact (AddMonoidHom.map_trace
    (profiniteFramedLimitLiftToHom O G n rho A tau).hom.toRingHom.toAddMonoidHom
    (profiniteUniversalMatrix O G n rho g)).trans h

omit [TotallyDisconnectedSpace G] in
/-- The image is closed because its source is compact and its target Hausdorff. -/
theorem traceSpecializationImage_closed :
    IsClosed (traceSpecializationImage O G n rho A tau : Set A) :=
  (traceSpecialization O G n rho A tau).hom.cont.isClosedMap.isClosed_range

omit [TotallyDisconnectedSpace G] in
/-- The image agrees with the closed trace algebra of the specified lift. -/
theorem traceSpecializationImage_eq :
    traceSpecializationImage O G n rho A tau =
      (Algebra.adjoin O (Set.range fun g : G ↦ (tau.val g).val.trace)).topologicalClosure := by
  let F := profiniteFramedLimitLiftToHom O G n rho A tau
  let T := Algebra.adjoin O (Set.range fun g : G ↦
    (profiniteUniversalMatrix O G n rho g).trace)
  have hmap : T.map F.hom.toAlgHom =
      Algebra.adjoin O (Set.range fun g : G ↦ (tau.val g).val.trace) := by
    dsimp only [T]
    rw [← Algebra.adjoin_image]
    congr 1
    rw [← Set.range_comp]
    congr 1
    funext g
    exact traceSpecialization_trace O G n rho A tau g
  calc
    traceSpecializationImage O G n rho A tau = T.topologicalClosure.map F.hom.toAlgHom :=
      Subalgebra.range_comp_val _ _
    _ = (T.map F.hom.toAlgHom).topologicalClosure :=
      (Subalgebra.topologicalClosure_map F.hom F.hom.cont.isClosedMap T).symm
    _ = _ := congrArg Subalgebra.topologicalClosure hmap

omit [TotallyDisconnectedSpace G] in
/-- Conjugate framed lifts have the same image of unframed coefficients. -/
theorem traceSpecializationImage_eq_of_conj
    (tau' : ContinuousFramedLifts O G n rho A) (P : GL n A)
    (hP : ∀ g, tau'.val g = P * tau.val g * P⁻¹) :
    traceSpecializationImage O G n rho A tau' =
      traceSpecializationImage O G n rho A tau := by
  rw [traceSpecializationImage_eq, traceSpecializationImage_eq]
  congr 3
  funext g
  rw [hP g]
  exact Matrix.trace_units_conj _ _

end Deformation
