/-
Copyright (c) 2026 FLT contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: FLT contributors
-/
module

public import FLT.Deformations.DeSmitLenstra.ProfiniteUniversalLift
public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic

/-!
# The closed trace ring of the universal framed lift

We define the closed subalgebra generated by the traces of the universal framed lift and package
it as a local proartinian algebra. This is the coefficient ring used in the trace-descent step of
de Smit--Lenstra, Proposition 2.6.
-/

@[expose] public section

open CategoryTheory IsLocalRing

universe u

namespace Deformation

noncomputable section

private instance subalgebraIsTopologicalRing
    {O R : Type*} [CommRing O] [CommRing R] [Algebra O R]
    [TopologicalSpace R] [IsTopologicalRing R] (S : Subalgebra O R) :
    IsTopologicalRing S :=
  S.toSubring.instIsTopologicalRing

private lemma closedSubalgebra_isLocalRing
    {O R : Type*} [CommRing O] [CommRing R] [Algebra O R] [TopologicalSpace R]
    [IsTopologicalRing R] [IsLinearTopology R R] [CompactSpace R]
    [IsLocalRing R] (S : Subalgebra O R) (hS : IsClosed (S : Set R)) :
    IsLocalRing S := by
  apply S.toSubring.isLocalRing_of_unit
  intro x hx hxunit
  let unit : Rˣ := hxunit.unit
  have hinv : (↑unit⁻¹ : R) ∈ S := by
    change (↑unit⁻¹ : R) ∈ (S : Set R)
    rw [← hS.closure_eq]
    apply mem_closure_iff.mpr
    intro t ht hxt
    have hU : (fun y : R => (↑unit⁻¹ : R) + y) ⁻¹' t ∈ nhds (0 : R) :=
      (ht.preimage (continuous_const.add continuous_id)).mem_nhds (by simpa using hxt)
    obtain ⟨I, hIopen, hIU⟩ := IsLinearTopology.hasBasis_open_ideal.mem_iff.mp hU
    let _ : Finite (R ⧸ I) :=
      AddSubgroup.quotient_finite_of_isOpen I.toAddSubgroup hIopen
    let q : R →+* R ⧸ I := Ideal.Quotient.mk I
    let quotientUnit : (R ⧸ I)ˣ := Units.map q unit
    obtain ⟨m, hmpos, hm⟩ :=
      (isOfFinOrder_of_finite quotientUnit).exists_pow_eq_one
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hmpos.ne'
    have hpow : quotientUnit ^ m = quotientUnit⁻¹ := by
      apply mul_right_cancel (b := quotientUnit)
      simpa [← pow_succ] using hm
    refine ⟨x ^ m, ?_, S.pow_mem hx m⟩
    have hdiff : x ^ m - (↑unit⁻¹ : R) ∈ I := by
      rw [← Ideal.Quotient.eq]
      rw [show x = (unit : R) from rfl]
      exact congrArg Units.val hpow
    simpa using hIU hdiff
  refine ⟨{
    val := ⟨x, hx⟩
    inv := ⟨(↑unit⁻¹ : R), hinv⟩
    val_inv := Subtype.ext unit.val_inv
    inv_val := Subtype.ext unit.inv_val }, rfl⟩

private lemma closedSubalgebra_isProartinian
    {O R : Type*} [CommRing O] [CommRing R] [Algebra O R] [TopologicalSpace R]
    [IsTopologicalRing R] [IsProartinian R] [CompactSpace R]
    (S : Subalgebra O R) (hS : IsClosed (S : Set R)) : IsProartinian S := by
  let _ : IsClosed (S : Set R) := hS
  let _ : CompactSpace S :=
    (isCompact_iff_compactSpace (s := (S : Set R))).mp hS.isCompact
  let _ : IsLinearTopology S S := by
    apply IsLinearTopology.mk_of_hasBasis (R := S) (M := S) (S := Ideal S)
      (p := fun I : Ideal S => IsOpen (I : Set S)) (s := fun I => I)
    rw [Topology.IsInducing.nhds_eq_comap Topology.IsInducing.subtypeVal]
    let h := (IsLinearTopology.hasBasis_open_ideal (R := R)).comap ((↑) : S → R)
    apply h.to_hasBasis
    · intro I hI
      refine ⟨Ideal.comap S.val.toRingHom I, hI.preimage continuous_subtype_val,
        Set.Subset.rfl⟩
    · intro J hJ
      apply h.mem_iff.mp
      have hmem : (J : Set S) ∈ nhds (0 : S) := hJ.mem_nhds J.zero_mem
      rw [Topology.IsInducing.nhds_eq_comap Topology.IsInducing.subtypeVal] at hmem
      exact hmem
  exact {
    toIsLinearTopology := inferInstance
    toT0Space := inferInstance
    toCompleteSpace := inferInstance
    isArtinianRing_quotient := fun I hI => by
      let : Finite (S ⧸ I) :=
        AddSubgroup.quotient_finite_of_isOpen I.toAddSubgroup hI
      infer_instance }

private lemma closedSubalgebra_isResidueAlgebra
    {O R : Type*} [CommRing O] [CommRing R] [Algebra O R]
    [IsLocalRing R] [IsResidueAlgebra O R] (S : Subalgebra O R) [IsLocalRing S] :
    IsResidueAlgebra O S := by
  refine ⟨?_⟩
  intro xbar
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective xbar
  obtain ⟨o, ho⟩ := IsResidueAlgebra.algebraMap_surjective O R
    (IsLocalRing.residue R x.1)
  refine ⟨o, ?_⟩
  change Ideal.Quotient.mk (maximalIdeal S) (algebraMap O S o) =
    Ideal.Quotient.mk (maximalIdeal S) x
  rw [Ideal.Quotient.eq]
  have hamb : algebraMap O R o - x.1 ∈ maximalIdeal R := Ideal.Quotient.eq.mp ho
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] at hamb
  intro hunit
  exact hamb (by simpa using hunit.map S.val)

private lemma closedSubalgebra_algebraMap_isLocalHom
    {O R : Type*} [CommRing O] [CommRing R] [Algebra O R]
    [IsLocalHom (algebraMap O R)] (S : Subalgebra O R) :
    IsLocalHom (algebraMap O S) := by
  constructor
  intro o ho
  have hR : IsUnit (algebraMap O R o) := by
    simpa using ho.map S.val
  rwa [isUnit_map_iff (algebraMap O R)] at hR

variable (O : Type u) [CommRing O] [IsLocalRing O] [IsNoetherianRing O]
variable (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G]
variable (n : Type) [Fintype n] [DecidableEq n]
variable [Finite (ResidueField O)]
variable (rho : G →ₜ* GL n (ProartinianCat.residueField (𝓞 := O)))

local instance :
    IsLocalProartinianAlgebra O (ProfiniteFramedLimit O G n rho) :=
  (profiniteFramedLimitObject O G n rho).isLocalProartinianAlgebra

local instance : CompactSpace (ProfiniteFramedLimit O G n rho) :=
  ProartinianCat.compactSpace (S := profiniteFramedLimitObject O G n rho)

/-- The closed subalgebra generated by traces of the universal framed lift. -/
def universalTraceSubalgebra :
    Subalgebra O (ProfiniteFramedLimit O G n rho) :=
  (Algebra.adjoin O (Set.range fun g : G =>
    (profiniteUniversalMatrix O G n rho g).trace)).topologicalClosure

/-- The underlying ring of the closed trace algebra. -/
abbrev UniversalTraceRing := universalTraceSubalgebra O G n rho

omit [TotallyDisconnectedSpace G] in
private lemma universalTraceSubalgebra_isClosed :
    IsClosed (universalTraceSubalgebra O G n rho :
      Set (ProfiniteFramedLimit O G n rho)) :=
  Subalgebra.isClosed_topologicalClosure _

noncomputable instance : CompactSpace (UniversalTraceRing O G n rho) := by
  exact (isCompact_iff_compactSpace
    (s := (universalTraceSubalgebra O G n rho :
      Set (ProfiniteFramedLimit O G n rho)))).mp
    (universalTraceSubalgebra_isClosed O G n rho).isCompact

instance : IsTopologicalRing (UniversalTraceRing O G n rho) :=
  (universalTraceSubalgebra O G n rho).toSubring.instIsTopologicalRing

instance : IsLocalRing (UniversalTraceRing O G n rho) :=
  closedSubalgebra_isLocalRing _ (universalTraceSubalgebra_isClosed O G n rho)

instance : IsLocalHom (algebraMap O (UniversalTraceRing O G n rho)) :=
  closedSubalgebra_algebraMap_isLocalHom _

instance : IsResidueAlgebra O (UniversalTraceRing O G n rho) :=
  closedSubalgebra_isResidueAlgebra _

instance : IsProartinian (UniversalTraceRing O G n rho) :=
  closedSubalgebra_isProartinian _ (universalTraceSubalgebra_isClosed O G n rho)

instance : IsLocalProartinianAlgebra O (UniversalTraceRing O G n rho) := ⟨⟩

/-- The closed trace ring, as an object of the deformation category. -/
def universalTraceRingObject : ProartinianCat O :=
  ProartinianCat.of O (UniversalTraceRing O G n rho)

omit [TotallyDisconnectedSpace G] in
/-- The trace of every element of the universal framed lift belongs to the closed trace ring. -/
lemma universalTrace_mem (g : G) :
    (profiniteUniversalMatrix O G n rho g).trace ∈
      universalTraceSubalgebra O G n rho :=
  Subalgebra.le_topologicalClosure _ (Algebra.subset_adjoin ⟨g, rfl⟩)

/-- Inclusion of the closed trace ring into the universal framed ring. -/
def universalTraceRingInclusion :
    universalTraceRingObject O G n rho ⟶ profiniteFramedLimitObject O G n rho where
  hom :=
    { toAlgHom := (universalTraceSubalgebra O G n rho).val
      cont := continuous_subtype_val }

end

end Deformation
