/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.AbsoluteGaloisGroup.Unramified
public import FLT.GroupScheme.FiniteFlatSubquotientBaseChange

/-!
# A finite unramified field retaining exactly the inertia action

The fixed field of the product of inertia and the kernel of a finite continuous
action makes every remaining Galois automorphism act like an inertia element.
Consequently invariant subspaces and commuting scalar endomorphisms descend.
-/

@[expose] public noncomputable section

namespace InertiaDescent

variable {K X : Type} [Field K] [PerfectField K] [AddCommGroup X]
  [DistribMulAction (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) X]
  [Finite X] [ContinuousSMulDiscrete (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) X]
  (I : Subgroup (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K)) [I.Normal]

/-- The subgroup generated by inertia and the action kernel. -/
def subgroup : Subgroup (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) :=
  (MulAction.toPermHom (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) X).ker ⊔ I

instance : (subgroup (X := X) I).Normal := inferInstanceAs
  ((MulAction.toPermHom (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) X).ker ⊔ I).Normal

omit [PerfectField K] [I.Normal] in
/-- Finiteness and continuity make the descent subgroup open. -/
theorem subgroup_isOpen :
    IsOpen (subgroup (X := X) I : Set (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K)) := by
  apply Subgroup.isOpen_mono le_sup_left
  have he : ((MulAction.toPermHom (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K) X).ker :
      Set (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K)) = ⋂ x : X, {σ | σ • x = x} := by
    ext σ
    simp only [Set.mem_iInter, Set.mem_ofPred_eq]
    exact Equiv.ext_iff
  rw [he]
  exact isOpen_iInter_of_finite fun x ↦ ContinuousSMulDiscrete.isOpen_smul_eq _ x x

/-- The finite extension over which only the original inertia image remains. -/
def field : IntermediateField K (AlgebraicClosure K) :=
  IntermediateField.fixedField (subgroup (X := X) I)

omit [I.Normal] in
/-- The Galois correspondence recovers the descent subgroup exactly. -/
theorem fixingSubgroup_field : (field (X := X) I).fixingSubgroup = subgroup (X := X) I :=
  InfiniteGalois.fixingSubgroup_fixedField
    ⟨subgroup (X := X) I, (subgroup (X := X) I).isClosed_of_isOpen (subgroup_isOpen I)⟩

omit [I.Normal] in
instance fieldFinite : FiniteDimensional K (field (X := X) I) := by
  apply (InfiniteGalois.isOpen_iff_finite _).mp
  rw [fixingSubgroup_field]
  exact subgroup_isOpen I

instance fieldGalois : IsGalois K (field (X := X) I) := by
  apply (InfiniteGalois.normal_iff_isGalois _).mp
  rw [fixingSubgroup_field]
  infer_instance

omit [I.Normal] in
/-- Every descended automorphism agrees on all points with one inertia element. -/
theorem exists_inertia_action (σ : AlgebraicClosure K ≃ₐ[field (X := X) I] AlgebraicClosure K) :
    ∃ τ : I, ∀ x : X, (σ.restrictScalars K) • x = τ.1 • x := by
  have hσ : σ.restrictScalars K ∈ subgroup (X := X) I := by
    rw [← fixingSubgroup_field]
    exact ((IntermediateField.fixingSubgroupEquiv (field (X := X) I)).symm σ).property
  obtain ⟨a, ha, b, hb, hab⟩ := Subgroup.mem_sup_of_normal_left.mp hσ
  refine ⟨⟨b, hb⟩, fun x ↦ ?_⟩
  rw [← hab, mul_smul]
  exact Equiv.congr_fun ha (b • x)

omit [I.Normal] in
/-- Inertia subquotients descend with their scalar endomorphisms, and acquire
finite-flat models by base change of the original model. -/
theorem subquotient_model {R S U W : Type} [CommRing R] [CommRing S]
    [Algebra R K] [Algebra R S] [Algebra S (field (X := X) I)]
    [IsScalarTower R S (field (X := X) I)]
    [IsDedekindDomain S] [IsFractionRing S (field (X := X) I)]
    [AddCommGroup U] [AddCommGroup W] [DistribMulAction I U] [DistribMulAction I W]
    (hX : GaloisModule.IsFiniteFlat R K (AlgebraicClosure K) X)
    (i : U →+[I] X) (q : U →+[I] W) (hi : Function.Injective i)
    (hq : Function.Surjective q) :
    ∃ dU : DistribMulAction (AlgebraicClosure K ≃ₐ[field (X := X) I] AlgebraicClosure K) U,
    ∃ dW : DistribMulAction (AlgebraicClosure K ≃ₐ[field (X := X) I] AlgebraicClosure K) W,
      letI := dU; letI := dW
      GaloisModule.IsFiniteFlat S (field (X := X) I) (AlgebraicClosure K) W ∧
      (∀ (σ : AlgebraicClosure K ≃ₐ[field (X := X) I] AlgebraicClosure K) u,
        i (σ • u) = (σ.restrictScalars K) • i u ∧ q (σ • u) = σ • q u) ∧
      (∀ (σ : AlgebraicClosure K ≃ₐ[field (X := X) I] AlgebraicClosure K) (t : I),
        (∀ x : X, (σ.restrictScalars K) • x = t.1 • x) → ∀ w : W, σ • w = t • w) ∧
      (∀ (f : W →+[I] W)
        (σ : AlgebraicClosure K ≃ₐ[field (X := X) I] AlgebraicClosure K) w,
        f (σ • w) = σ • f w) := by
  let τ := fun σ ↦ (exists_inertia_action (X := X) I σ).choose
  have hτ := fun σ ↦ (exists_inertia_action (X := X) I σ).choose_spec
  let L := field (X := X) I
  let Y := GaloisModule.RestrictedPoints K L (AlgebraicClosure K) X
  let iY : U →+ Y := i.toAddMonoidHom
  let : SMul (AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K) U := ⟨fun σ u ↦ τ σ • u⟩
  have hiY (σ : AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K) (u : U) :
      iY (σ • u) = σ • iY u := by
    exact (i.map_smul (τ σ) u).trans (hτ σ (i u)).symm
  let dU : DistribMulAction (AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K) U :=
    Function.Injective.distribMulAction iY hi hiY
  let : SMul (AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K) W := ⟨fun σ w ↦ τ σ • w⟩
  let dW : DistribMulAction (AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K) W :=
    Function.Surjective.distribMulAction q.toAddMonoidHom hq
      (fun σ u ↦ q.map_smul (τ σ) u)
  refine ⟨dU, dW, ?_, fun σ u ↦ ⟨hiY σ u, q.map_smul (τ σ) u⟩,
    ?_, fun f σ w ↦ f.map_smul (τ σ) w⟩
  · let i' : U →+[AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K] Y :=
      { iY with map_smul' := hiY }
    let q' : U →+[AlgebraicClosure K ≃ₐ[L] AlgebraicClosure K] W :=
      { q.toAddMonoidHom with map_smul' := fun σ u ↦ q.map_smul (τ σ) u }
    exact hX.subquotient_baseChange i' q' hi hq
  · intro σ t ht w
    obtain ⟨u, rfl⟩ := hq w
    change τ σ • q u = t • q u
    apply (q.map_smul (τ σ) u).symm.trans
    apply Eq.trans _ (q.map_smul t u)
    apply congrArg q
    apply hi
    exact (i.map_smul (τ σ) u).trans ((hτ σ (i u)).symm.trans
      ((ht (i u)).trans (i.map_smul t u).symm))

end InertiaDescent

open NumberField

/-- Local automorphisms preserve the unique maximal ideal, so inertia is normal. -/
instance localInertiaGroup_normal {F : Type} [Field F] [NumberField F]
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 F)) : (localInertiaGroup v).Normal := by
  let B := IntegralClosure (v.adicCompletionIntegers F) (AlgebraicClosure (v.adicCompletion F))
  constructor
  intro a ha b x
  have h := ha (b⁻¹ • x)
  have hm := Ideal.mem_map_of_mem (MulSemiringAction.toRingAut _ B b).toRingHom h
  have ht := IsLocalRing.map_maximalIdeal_le (MulSemiringAction.toRingAut _ B b).toRingHom hm
  change b • (a • (b⁻¹ • x) - b⁻¹ • x) ∈ IsLocalRing.maximalIdeal B at ht
  simp only [smul_sub, smul_inv_smul] at ht
  exact ht

variable {F X : Type} [Field F] [NumberField F]
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 F)) [AddCommGroup X]
    [DistribMulAction (AlgebraicClosure (v.adicCompletion F) ≃ₐ[v.adicCompletion F]
      AlgebraicClosure (v.adicCompletion F)) X]
    [Finite X] [ContinuousSMulDiscrete (AlgebraicClosure (v.adicCompletion F) ≃ₐ[v.adicCompletion F]
      AlgebraicClosure (v.adicCompletion F)) X]

local notation "R₀" => v.adicCompletionIntegers F
local notation "L₀" => InertiaDescent.field (X := X) (localInertiaGroup v)

instance inertiaDescentIntegers_fractionRing : IsFractionRing (IntegralClosure R₀ L₀) L₀ :=
  integralClosure.isFractionRing_of_finite_extension (v.adicCompletion F) L₀

instance inertiaDescentIntegers_dedekind : IsDedekindDomain (IntegralClosure R₀ L₀) :=
  IsIntegralClosure.isDedekindDomain R₀ (v.adicCompletion F) L₀ (integralClosure R₀ L₀)

/-- The descent field for local inertia is unramified: its ramification index is one. -/
theorem inertiaDescentField_ramificationIdx_eq_one :
    (IsLocalRing.maximalIdeal (IntegralClosure (v.adicCompletionIntegers F)
      (InertiaDescent.field (X := X) (localInertiaGroup v)))).ramificationIdx
        (v.adicCompletionIntegers F) = 1 := by
  apply ramificationIdx_eq_one_of_inertia_eq_bot v
    (InertiaDescent.field (X := X) (localInertiaGroup v))
  rw [← map_localInertiaGroup_eq_inertia, Subgroup.map_eq_bot_iff,
    IntermediateField.restrictNormalHom_ker, InertiaDescent.fixingSubgroup_field]
  exact le_sup_right
