/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.AbsoluteGaloisGroup.TameRootsOfUnity
public import Mathlib.FieldTheory.KummerExtension

/-!
# The field generated by the specified tame root

Eisenstein gives the exact degree. Over the rational completion, lifted
roots of unity prove normality of this very field, so it is a finite Galois
model containing the root used by tameCharacter.
-/

@[expose] public noncomputable section
open NumberField IsLocalRing Polynomial IntermediateField
namespace LocalRoot
universe u
variable {K : Type u} [Field K] [NumberField K]
  (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
local notation "F" => v.adicCompletion K
local notation "O" => v.adicCompletionIntegers K
local notation "Ω" => AlgebraicClosure F
local notation "n" => Nat.card (ResidueField O) - 1

/-- The embedded field generated by the exact tame root. -/
def tameRootField : IntermediateField F Ω := F⟮tameUniformizerRoot v⟯

/-- The Eisenstein binomial is the minimal polynomial of the chosen root. -/
theorem tameRoot_minpoly :
    minpoly F (tameUniformizerRoot v) = X ^ n - C (tameUniformizer v).1 := by
  let P : O[X] := X ^ n - C (tameUniformizer v)
  have hm : P.Monic := monic_X_pow_sub_C _ (tameDegree_pos v).ne'
  have hi : Irreducible P :=
    (uniformizer_binomial_eisenstein (tameUniformizer_irreducible v)
      (tameDegree_pos v)).irreducible inferInstance hm.isPrimitive
      (by simpa [P] using tameDegree_pos v)
  have hiF : Irreducible (X ^ n - C (tameUniformizer v).1 : F[X]) := by
    have h := (hm.irreducible_iff_irreducible_map_fraction_map (K := F)).mp hi
    simp only [P, Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X,
      Polynomial.map_C] at h
    change Irreducible (X ^ n - C (algebraMap O F (tameUniformizer v)))
    exact h
  exact (minpoly.eq_of_irreducible_of_monic hiF
    (by simpa using sub_eq_zero.mpr (tameUniformizerRoot_spec v))
    (monic_X_pow_sub_C _ (tameDegree_pos v).ne')).symm

/-- This chosen-root field is finite over the local base. -/
instance tameRootField_finite : FiniteDimensional F (tameRootField v) :=
  IntermediateField.adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral _)

/-- The chosen-root field has the full tame degree, including degree one. -/
theorem tameRootField_finrank : Module.finrank F (tameRootField v) = n := by
  rw [tameRootField, IntermediateField.adjoin.finrank (Algebra.IsIntegral.isIntegral _),
    tameRoot_minpoly, natDegree_X_pow_sub_C]

/-- A primitive tame root in the base makes the chosen-root field normal. -/
theorem tameRootField_normal_of_primitive {ζ : F} (hζ : IsPrimitiveRoot ζ n) :
    Normal F (tameRootField v) := by
  let a : tameRootField v := ⟨tameUniformizerRoot v, mem_adjoin_simple_self _ _⟩
  have ha : a ^ n = algebraMap F (tameRootField v) (tameUniformizer v).1 :=
    Subtype.ext (tameUniformizerRoot_spec v)
  have hs : ((minpoly F (tameUniformizerRoot v)).map
      (algebraMap F (tameRootField v))).Splits := by
    rw [tameRoot_minpoly, Polynomial.map_sub, Polynomial.map_pow,
      Polynomial.map_X, Polynomial.map_C]
    exact X_pow_sub_C_splits_of_isPrimitiveRoot
      (hζ.map_of_injective (algebraMap F (tameRootField v)).injective) ha
  constructor
  intro x
  rw [minpoly_eq]
  exact IntermediateField.splits_of_mem_adjoin F Ω
    (fun y hy ↦ by
      rcases Set.mem_singleton_iff.mp hy with rfl
      exact ⟨Algebra.IsIntegral.isIntegral _, hs⟩) x.property

/-- Normality of the actual rational tame-root field is proved without a roots hypothesis. -/
theorem rationalTameRootField_isGalois (p : ℕ) [Fact p.Prime] :
    IsGalois ((LocalCyclotomic.rationalPlace p).adicCompletion ℚ)
      (tameRootField (LocalCyclotomic.rationalPlace p)) := by
  obtain ⟨ζ, hζ⟩ := rationalCompletion_exists_primitive_tame_root p
  let := tameRootField_normal_of_primitive (LocalCyclotomic.rationalPlace p) hζ
  exact ⟨⟩

end LocalRoot
