/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.AbsoluteGaloisGroup.RootUniformizerDegree
public import FLT.AbsoluteGaloisGroup.TameRootField
public import Mathlib.LinearAlgebra.Dimension.Localization

/-!
# The integral closure in the specified tame-root field

The chosen root is a uniformizer of this actual finite integral closure.
Its ramification index is q - 1 and its residue degree is one. In particular,
the embedded model is totally ramified; none of these properties is an input.
-/

@[expose] public noncomputable section
open NumberField IsLocalRing IntermediateField
namespace LocalRoot
universe u
variable {K : Type u} [Field K] [NumberField K]
  (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
local notation "F" => v.adicCompletion K
local notation "O" => v.adicCompletionIntegers K
local notation "E" => tameRootField v
local notation "n" => Nat.card (ResidueField O) - 1

/-- The integers of the field generated by the chosen tame root. -/
abbrev tameRootIntegers := IntegralClosure O E
local notation "D" => tameRootIntegers v

instance tameRootIntegers_finite : Module.Finite O D :=
  IsIntegralClosure.finite O F E (integralClosure O E)

instance tameRootIntegers_dedekind : IsDedekindDomain D :=
  IsIntegralClosure.isDedekindDomain O F E (integralClosure O E)

instance tameRootIntegers_dvr : IsDiscreteValuationRing D where
  not_a_field' := Ideal.ne_bot_of_liesOver_of_ne_bot
    (IsDiscreteValuationRing.not_a_field O) (maximalIdeal D)

instance tameRootIntegers_faithful : FaithfulSMul O D := by
  rw [faithfulSMul_iff_algebraMap_injective]
  intro x y h
  apply Subtype.ext
  apply (algebraMap F E).injective
  exact congrArg Subtype.val h

instance tameRootIntegers_fraction : IsFractionRing D E :=
  integralClosure.isFractionRing_of_finite_extension F E

/-- The chosen root, now as an element of its actual integral closure. -/
def tameRootInteger : D :=
  ⟨⟨tameUniformizerRoot v, mem_adjoin_simple_self _ _⟩,
    IsIntegral.of_pow (tameDegree_pos v) (by
      have h : (⟨tameUniformizerRoot v, mem_adjoin_simple_self _ _⟩ : E) ^ n =
          algebraMap O E (tameUniformizer v) := Subtype.ext (tameUniformizerRoot_spec v)
      rw [h]
      exact isIntegral_algebraMap)⟩

/-- The root equation holds in the integer ring itself. -/
theorem tameRootInteger_pow :
    tameRootInteger v ^ n = algebraMap O D (tameUniformizer v) := by
  apply Subtype.ext
  exact Subtype.ext (tameUniformizerRoot_spec v)

/-- The root is a uniformizer, and the actual integral closure is totally ramified. -/
theorem tameRootInteger_uniformizer :
    Irreducible (tameRootInteger v) ∧ (maximalIdeal D).ramificationIdx O = n ∧
      (maximalIdeal D).inertiaDeg O = 1 := by
  apply uniformizer_of_root_of_finrank (tameUniformizer_irreducible v) (tameDegree_pos v)
    _ (tameRootInteger_pow v)
  rw [← IsFractionRing.finrank_eq O F D E, tameRootField_finrank]

/-- The root generates the entire integral closure as an algebra. -/
theorem tameRootInteger_adjoin : Algebra.adjoin O {tameRootInteger v} = ⊤ := by
  apply IsDiscreteValuationRing.adjoinUniformizerEqTop _ (tameRootInteger_uniformizer v).1
  have hf := (tameRootInteger_uniformizer v).2.2
  rw [Ideal.inertiaDeg_eq_of_isMaximal (maximalIdeal O) (maximalIdeal D)] at hf
  change Module.finrank (ResidueField O) (ResidueField D) = 1 at hf
  have hs : Function.Surjective (algebraMap (ResidueField O) (ResidueField D)) :=
    (Algebra.finrank_eq_one_iff_bijective_algebraMap.mp hf).2
  intro s
  obtain ⟨z, hz⟩ := hs (residue D s)
  obtain ⟨r, rfl⟩ := residue_surjective (R := O) z
  exact ⟨r, hz⟩

end LocalRoot
