/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.FiniteFlatTangentNaturality

/-! # Cotangent images of the actual extended augmentation ideal -/

@[expose] public noncomputable section
namespace ThreeAdicPlan
variable {R K : Type} [CommRing R] [Field K] [Algebra R K]

/-- Linearizing the ideal generated by an augmentation image gives the cotangent image. -/
theorem ModelHom.cotangent_projection_mem_range {X Y : FF R K} (f : ModelHom X Y)
    {a : X.CoordinateRing} (ha : a ∈ HopfAlgebra.augmentationIdeal f) :
    (Bialgebra.counitAlgHom R X.CoordinateRing).augmentationCotangent a ∈
      LinearMap.range f.cotangentMap := by
  let ε := Bialgebra.counitAlgHom R X.CoordinateRing
  let J : Ideal X.CoordinateRing :=
    { carrier := {a | ε a = 0 ∧ ε.augmentationCotangent a ∈ LinearMap.range f.cotangentMap}
      zero_mem' := ⟨map_zero _, by simp⟩
      add_mem' := by
        rintro a b ⟨ha, ha'⟩ ⟨hb, hb'⟩
        exact ⟨by rw [map_add, ha, hb, add_zero], by
          rw [map_add]; exact Submodule.add_mem _ ha' hb'⟩
      smul_mem' := by
        rintro r a ⟨ha, ha'⟩
        refine ⟨by change ε (r * a) = 0; rw [map_mul, ha, mul_zero], ?_⟩
        change ε.augmentationCotangent (r * a) ∈ _
        rw [ε.augmentationCotangent_mul, ha, zero_smul, add_zero]
        exact Submodule.smul_mem _ _ ha' }
  have hJ : HopfAlgebra.augmentationIdeal f ≤ J := by
    apply Ideal.map_le_iff_le_comap.mpr
    intro b hb
    refine ⟨?_, ?_⟩
    · exact (CoalgHomClass.counit_comp_apply f b).trans hb
    · change ε.augmentationCotangent (f b) ∈ LinearMap.range f.cotangentMap
      rw [← ModelHom.cotangentMap_projection]
      exact LinearMap.mem_range_self _ _
  exact (hJ ha).2

end ThreeAdicPlan
