/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.HeightOneStructure
public import FLT.Mathlib.RingTheory.FrobeniusAugmentation

/-!
# Frobenius fibres in prescribed coordinates

Coordinate derivations identify the Frobenius-fibre kernel in the original
coordinates, so that its pure-power relations can be lifted over the
Frobenius subalgebra without changing generators.
-/

@[expose] public noncomputable section

namespace Derivation

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]
  (p : ℕ) [Fact p.Prime] [CharP A p]

/-- Derivations preserve every ideal generated by Frobenius powers. -/
theorem mem_frobeniusPower (D : Derivation k A A) (I : Ideal A)
    {a : A} (ha : a ∈ I.frobeniusPower p) : D a ∈ I.frobeniusPower p := by
  change a ∈ Ideal.span ((frobenius A p) '' (I : Set A)) at ha
  induction ha using Submodule.span_induction with
  | mem a ha =>
    obtain ⟨b, hb, rfl⟩ := ha
    have hd : D (b ^ p) = 0 := by
      simp [leibniz_pow, smul_eq_mul, nsmul_eq_mul]
    simpa only [frobenius_def, hd] using (I.frobeniusPower p).zero_mem
  | zero => simpa only [map_zero] using (I.frobeniusPower p).zero_mem
  | add a b ha hb hda hdb => exact map_add D a b ▸ (I.frobeniusPower p).add_mem hda hdb
  | smul r a ha hda =>
    change D (r * a) ∈ _
    rw [leibniz]
    exact (I.frobeniusPower p).add_mem
      ((I.frobeniusPower p).mul_mem_left r hda)
      ((I.frobeniusPower p).mul_mem_right (D r) ha)

end Derivation

namespace AlgHom

open MvPolynomial

variable {k A ι : Type*} [Field k] [CommRing A] [Algebra k A] [DecidableEq ι]
  (p : ℕ) [Fact p.Prime] [CharP k p] [CharP A p]

/-- Prescribed augmentation coordinates with dual derivations give the
pure-power presentation of the Frobenius fibre. -/
theorem ker_frobeniusQuotient_aeval_of_coordinate (ε : A →ₐ[k] k)
    (x : ι → A) (hx : ∀ i, ε (x i) = 0)
    (D : ι → Derivation k A A) (hD : ∀ i j, D i (x j) = if i = j then 1 else 0) :
    RingHom.ker ((Ideal.Quotient.mkₐ k ((RingHom.ker ε).frobeniusPower p)).comp
      (aeval (R := k) x)) =
      Ideal.span (Set.range (fun i ↦ (X i : MvPolynomial ι k) ^ p)) := by
  let I := RingHom.ker ε
  let J := I.frobeniusPower p
  let q := Ideal.Quotient.mkₐ k J
  apply eq_span_X_pow_of_pderiv_mem p
  · intro i
    change q (aeval x ((X i) ^ p)) = 0
    rw [map_pow, aeval_X]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr (I.pow_mem_frobeniusPower p (hx i))
  · intro f hf
    have hmem : aeval x f ∈ J := Ideal.Quotient.eq_zero_iff_mem.mp hf
    have hz : ε (aeval x f) = 0 := I.frobeniusPower_le p hmem
    rw [comp_aeval_apply] at hz
    have hfun : (fun i ↦ ε (x i)) = fun _ ↦ 0 := funext hx
    rw [hfun, aeval_zero'] at hz
    exact hz
  · intro i f hf
    change q (aeval x (pderiv i f)) = 0
    rw [← derivation_aeval_of_coordinate x (D i) i (hD i)]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr
      ((D i).mem_frobeniusPower p I (Ideal.Quotient.eq_zero_iff_mem.mp hf))

end AlgHom
