/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.LocalBialgebraDerivations
public import FLT.Mathlib.RingTheory.MvPolynomial.HeightOneIdeal

/-!
# The algebra structure of a finite local height-one group scheme

A finite local commutative bialgebra whose augmentation ideal is killed by
`p`-th powers is a truncated polynomial algebra. The number of variables is
its cotangent dimension. Invariant extensions of a cotangent dual basis,
normalized by their invertible coordinate matrix, make its polynomial kernel
stable under all partial derivatives. The height-one ideal theorem then
identifies the entire kernel, not just a family of relations lying in it.
-/

@[expose] public noncomputable section

namespace MvPolynomial

variable {k A ι : Type*} [CommRing k] [CommRing A] [Algebra k A] [DecidableEq ι]

/-- A derivation with coordinate values equal to a Kronecker delta acts on
polynomial evaluations by the corresponding formal partial derivative. -/
theorem derivation_aeval_of_coordinate (x : ι → A) (D : Derivation k A A) (i : ι)
    (hD : ∀ j, D (x j) = if i = j then 1 else 0) (f : MvPolynomial ι k) :
    D (aeval x f) = aeval x (pderiv i f) := by
  classical
  induction f using MvPolynomial.induction_on with
  | C c => simp
  | add f g hf hg => simp only [map_add, hf, hg]
  | mul_X f j hf =>
    simp only [map_mul, aeval_X, Derivation.leibniz, hD, hf,
      map_add, pderiv_X, Pi.single_apply, smul_eq_mul]
    by_cases hij : i = j
    · subst j
      simp only [ite_true, map_one, mul_one]
    · simp only [hij, Ne.symm hij, ite_false, map_zero, mul_zero, zero_add]

end MvPolynomial

namespace Bialgebra

open MvPolynomial

variable {k A : Type*} [Field k] [CommRing A] [Bialgebra k A]
  [IsLocalRing A] [Module.Finite k A]
variable (p : ℕ) [CharP k p]

/-- A finite local height-one bialgebra has a minimal polynomial presentation
whose entire kernel is generated by the `p`-th powers of its variables. -/
theorem exists_heightOne_presentation
    (hp : ∀ a ∈ RingHom.ker (counitAlgHom k A), a ^ p = 0) :
    ∃ P : Algebra.Generators k A
        (Fin (Module.finrank k (RingHom.ker (counitAlgHom k A)).Cotangent)),
      (∀ i, counitAlgHom k A (P.val i) = 0) ∧
      RingHom.ker (aeval (R := k) P.val) =
        Ideal.span (Set.range (fun i ↦ (X i : P.Ring) ^ p)) := by
  classical
  let ε := counitAlgHom k A
  let I := RingHom.ker ε
  let : Module.Finite k I.Cotangent := Module.Finite.of_surjective
    (I.toCotangent.restrictScalars k) I.toCotangent_surjective
  let b := Module.finBasis k I.Cotangent
  obtain ⟨P, hP⟩ := ε.exists_augmentation_generators_of_basis b
  choose hx hb using hP
  let x (i : Fin (Module.finrank k I.Cotangent)) : I := ⟨P.val i, hx i⟩
  obtain ⟨D, hD⟩ := exists_coordinate_derivations b x hb
  refine ⟨P, fun i ↦ hx i, ?_⟩
  apply eq_span_X_pow_of_pderiv_mem p
  · intro i
    change aeval P.val ((X i) ^ p) = 0
    rw [map_pow, aeval_X]
    exact hp _ (hx i)
  · intro f hf
    have hε : ε (aeval P.val f) = f.coeff 0 := by
      rw [comp_aeval_apply]
      have hz : (fun i ↦ ε (P.val i)) = fun _ ↦ 0 := funext fun i ↦ hx i
      rw [hz, aeval_zero']
      rfl
    rw [show aeval P.val f = 0 from hf, map_zero] at hε
    exact hε.symm
  · intro i f hf
    change aeval P.val (pderiv i f) = 0
    rw [← derivation_aeval_of_coordinate P.val (D i) i (hD i),
      show aeval P.val f = 0 from hf, map_zero]

/-- The algebra of a finite local height-one group scheme is a truncated
polynomial algebra in exactly its cotangent dimension many variables. -/
theorem nonempty_heightOne_algEquiv
    (hp : ∀ a ∈ RingHom.ker (counitAlgHom k A), a ^ p = 0) :
    Nonempty
      ((MvPolynomial (Fin (Module.finrank k (RingHom.ker (counitAlgHom k A)).Cotangent)) k ⧸
        Ideal.span (Set.range (fun i ↦
          (X i : MvPolynomial
            (Fin (Module.finrank k (RingHom.ker (counitAlgHom k A)).Cotangent)) k) ^ p))) ≃ₐ[k]
        A) := by
  obtain ⟨P, _, hP⟩ := exists_heightOne_presentation p hp
  exact ⟨(Ideal.quotientEquivAlgOfEq k hP.symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective P.aeval_val_surjective)⟩

end Bialgebra
