/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.RingTheory.Bialgebra.Convolution
public import Mathlib.RingTheory.Nakayama
public import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
public import Mathlib.Tactic.NoncommRing

/-!
# Rigidity of three-torsion points in a residue kernel

A finite coalgebra has no nontrivial convolution point of order three congruent to
its counit in a local algebra where three is invertible. The proof applies Nakayama
to the ideal generated by the differences from the counit.
-/

@[expose] public noncomputable section

open WithConv Coalgebra

namespace ThreeAdicPlan

variable {R A B : Type*} [CommRing R] [AddCommGroup A] [Module R A]
  [Coalgebra R A] [CommRing B] [Algebra R B]

/-- Convolution multiplies the ideals containing the values of its factors. -/
theorem convolution_mem_ideal_mul (f g : WithConv (A →ₗ[R] B)) (I J : Ideal B)
    (hf : ∀ a, f a ∈ I) (hg : ∀ a, g a ∈ J) (a : A) : (f * g) a ∈ I * J := by
  rw [(ℛ R a).convMul_apply]
  exact Submodule.sum_mem _ fun i _ ↦ Ideal.mul_mem_mul (hf _) (hg _)

/-- A convolution map of order dividing three reducing to the counit over a local
algebra is the counit, provided three is a unit and the source is finite. -/
theorem convolution_eq_one_of_cube_eq_one [Module.Finite R A] [IsLocalRing B]
    (f : WithConv (A →ₗ[R] B)) (hf : f ^ 3 = 1) (h3 : IsUnit (3 : B))
    (hm : ∀ a, (f - 1) a ∈ IsLocalRing.maximalIdeal B) : f = 1 := by
  let d := f - 1
  let I : Ideal B := Ideal.span (Set.range d)
  have hfg : I.FG := (Submodule.fg_range d.ofConv).span
  have hd (a : A) : d a ∈ I := Ideal.subset_span ⟨a, rfl⟩
  have h2 (a : A) : (d ^ 2) a ∈ I * I := by
    rw [pow_two]
    exact convolution_mem_ideal_mul d d I I hd hd a
  have h3d (a : A) : (d ^ 3) a ∈ I * I := by
    rw [pow_succ]
    exact Ideal.mul_le_left (convolution_mem_ideal_mul (d ^ 2) d (I * I) I h2 hd a)
  have hrel : 3 • d = -(d ^ 3 + 3 • d ^ 2) := by
    calc
      3 • d = (f ^ 3 - 1) - (d ^ 3 + 3 • d ^ 2) := by dsimp [d]; noncomm_ring
      _ = -(d ^ 3 + 3 • d ^ 2) := by rw [hf, sub_self, zero_sub]
  have hII : I ≤ I * I := by
    apply Ideal.span_le.mpr
    rintro _ ⟨a, rfl⟩
    apply ((I * I).unit_mul_mem_iff_mem h3).mp
    have he := congrArg (fun g : WithConv (A →ₗ[R] B) ↦ g a) hrel
    change 3 • d a = -((d ^ 3) a + 3 • (d ^ 2) a) at he
    rw [← Nat.cast_smul_eq_nsmul B 3 (d a), smul_eq_mul] at he
    norm_num only [Nat.cast_ofNat] at he
    rw [he]
    exact (I * I).neg_mem ((I * I).add_mem (h3d a) ((I * I).nsmul_mem (h2 a) 3))
  have hbot : I = ⊥ := by
    apply Submodule.eq_bot_of_le_smul_of_le_jacobson_bot I I hfg
    · simpa only [Ideal.smul_eq_mul] using hII
    · exact (Ideal.span_le.mpr (by rintro _ ⟨a, rfl⟩; exact hm a)).trans
        (IsLocalRing.maximalIdeal_le_jacobson ⊥)
  apply sub_eq_zero.mp
  apply WithConv.ext
  apply LinearMap.ext
  intro a
  have h := hd a
  rw [hbot, Ideal.mem_bot] at h
  exact h

end ThreeAdicPlan
