/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.Mathlib.RingTheory.FrobeniusAugmentation
public import Mathlib.RingTheory.HopfAlgebra.Quotient
public import Mathlib.Algebra.CharP.Algebra

/-!
# Frobenius of a commutative Hopf algebra

The Frobenius image is stable under antipode and comultiplication.
The ideal generated by Frobenius powers of the augmentation ideal is a
Hopf ideal, and its quotient has height one.
-/

@[expose] public noncomputable section

open scoped TensorProduct

namespace HopfAlgebra

variable {k A : Type*} [Field k] [CommRing A] [HopfAlgebra k A]
variable (p : ℕ) [Fact p.Prime] [CharP k p] [CharP A p] [PerfectRing k p]

/-- Every iterated Frobenius image is stable under the antipode. -/
theorem antipode_mem_frobeniusImage (n : ℕ) {a : A}
    (ha : a ∈ Algebra.frobeniusImage k A p n) :
    antipode k a ∈ Algebra.frobeniusImage k A p n := by
  obtain ⟨b, rfl⟩ := ha
  exact ⟨antipode k b, (map_pow (antipodeAlgHom k A) b (p ^ n)).symm⟩

/-- Comultiplication carries the Frobenius image into its tensor square. -/
theorem comul_mem_range_frobeniusImage (n : ℕ) {a : A}
    (ha : a ∈ Algebra.frobeniusImage k A p n) :
    Bialgebra.comulAlgHom k A a ∈
      (Algebra.TensorProduct.map (Algebra.frobeniusImage k A p n).val
        (Algebra.frobeniusImage k A p n).val).range := by
  let : Nontrivial A := (Bialgebra.counitAlgHom k A).domain_nontrivial
  let : Nontrivial (A ⊗[k] A) :=
    (Algebra.TensorProduct.lmul' k : A ⊗[k] A →ₐ[k] A).domain_nontrivial
  let : CharP (A ⊗[k] A) p := charP_of_injective_algebraMap
    (algebraMap k (A ⊗[k] A)).injective p
  obtain ⟨b, rfl⟩ := ha
  let C := Algebra.frobeniusImage k A p n
  let r := Coalgebra.Repr.arbitrary k b
  let l (i : A × A) : C := ⟨r.left i ^ p ^ n, ⟨r.left i, rfl⟩⟩
  let t (i : A × A) : C := ⟨r.right i ^ p ^ n, ⟨r.right i, rfl⟩⟩
  refine ⟨∑ i ∈ r.index, l i ⊗ₜ[k] t i, ?_⟩
  change (Algebra.TensorProduct.map C.val C.val) _ =
    Bialgebra.comulAlgHom k A (b ^ p ^ n)
  rw [map_pow]
  change _ = (Coalgebra.comul b) ^ p ^ n
  rw [← r.eq, sum_pow_char_pow]
  simp only [map_sum, Algebra.TensorProduct.map_tmul, Algebra.TensorProduct.tmul_pow, l, t,
    Subalgebra.val_apply]

omit [PerfectRing k p] in
/-- After killing augmentation Frobenius powers, the coproduct of any `p`-th
power is the scalar given by its counit. -/
theorem map_comul_pow_frobeniusQuotient (a : A) :
    let ε := Bialgebra.counitAlgHom k A
    let I := (RingHom.ker ε).frobeniusPower p
    (Algebra.TensorProduct.map (Ideal.Quotient.mkₐ k I) (Ideal.Quotient.mkₐ k I))
      (Bialgebra.comulAlgHom k A (a ^ p)) =
      algebraMap k ((A ⧸ I) ⊗[k] (A ⧸ I)) ((ε a) ^ p) := by
  let ε := Bialgebra.counitAlgHom k A
  let I := (RingHom.ker ε).frobeniusPower p
  let q := Ideal.Quotient.mkₐ k I
  let : Nontrivial A := ε.domain_nontrivial
  let : Nontrivial (A ⊗[k] A) :=
    (Algebra.TensorProduct.lmul' k : A ⊗[k] A →ₐ[k] A).domain_nontrivial
  let : CharP (A ⊗[k] A) p := charP_of_injective_algebraMap
    (algebraMap k (A ⊗[k] A)).injective p
  let r := Coalgebra.Repr.arbitrary k a
  have hc : ∑ i ∈ r.index, ε (r.left i) * ε (r.right i) = ε a := by
    simpa only [map_sum, map_smul, smul_eq_mul, ε, Bialgebra.counitAlgHom_apply] using
      congrArg ε (Coalgebra.sum_counit_smul r)
  have hq (b : A) : q (b ^ p) = algebraMap k (A ⧸ I) ((ε b) ^ p) := by
    simpa only [q, I, Ideal.Quotient.mkₐ_eq_mk, map_pow,
      AlgHom.frobeniusQuotientAugmentation_mk] using
      ε.pow_eq_augmentation_frobeniusQuotient p (q b)
  change (Algebra.TensorProduct.map q q) _ = _
  rw [map_pow]
  change (Algebra.TensorProduct.map q q) ((Coalgebra.comul a) ^ p) = _
  rw [← r.eq, sum_pow_char]
  simp only [map_sum, Algebra.TensorProduct.tmul_pow, Algebra.TensorProduct.map_tmul, hq]
  have ht (c d : k) :
      algebraMap k (A ⧸ I) c ⊗ₜ[k] algebraMap k (A ⧸ I) d =
        algebraMap k ((A ⧸ I) ⊗[k] (A ⧸ I)) (c * d) := by
    simp only [Algebra.algebraMap_eq_smul_one, TensorProduct.smul_tmul,
      TensorProduct.tmul_smul, smul_smul, Algebra.TensorProduct.one_def, mul_comm]
  simp only [ht, ← mul_pow, ← map_sum, ← sum_pow_char, hc]
  rfl

omit [PerfectRing k p] in
/-- Frobenius powers of the augmentation ideal form a Hopf ideal. -/
theorem isHopfIdeal_frobeniusPower_augmentation :
    ((RingHom.ker (Bialgebra.counitAlgHom k A)).frobeniusPower p).IsHopfIdeal k := by
  let ε := Bialgebra.counitAlgHom k A
  let I := (RingHom.ker ε).frobeniusPower p
  let q := Ideal.Quotient.mkₐ k I
  let f := (Algebra.TensorProduct.map q q).comp (Bialgebra.comulAlgHom k A)
  have hf : I ≤ RingHom.ker f := by
    apply Ideal.map_le_iff_le_comap.mpr
    intro a ha
    change f (a ^ p) = 0
    change (Algebra.TensorProduct.map q q) (Bialgebra.comulAlgHom k A (a ^ p)) = 0
    rw [map_comul_pow_frobeniusQuotient p a, show ε a = 0 from ha,
      zero_pow (Fact.out : p.Prime).ne_zero, map_zero]
  have hS : I ≤ I.comap (antipodeAlgHom k A) := by
    apply Ideal.map_le_iff_le_comap.mpr
    intro a ha
    change antipodeAlgHom k A (a ^ p) ∈ I
    rw [map_pow]
    apply Ideal.pow_mem_frobeniusPower
    change ε (antipode k a) = 0
    change Coalgebra.counit (R := k) (antipode k a) = 0
    rw [counit_antipode]
    exact ha
  exact
    { counit_eq_zero := fun _ hx ↦ (RingHom.ker ε).frobeniusPower_le p hx
      map_mkQ_comul_eq_zero := fun _ hx ↦ hf hx
      antipode_mem := fun _ hx ↦ hS hx }

end HopfAlgebra
