/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.HopfShear
public import Mathlib.RingTheory.Ideal.Quotient.Operations
public import Mathlib.LinearAlgebra.TensorProduct.RightExactness

/-!
# The relative torsor isomorphism for commutative Hopf algebras
-/

@[expose] public noncomputable section

open scoped TensorProduct
open Algebra.TensorProduct WithConv

namespace HopfAlgebra

variable {R A B C : Type*} [CommRing R] [CommRing A] [CommRing B] [CommRing C]
  [HopfAlgebra R A] [HopfAlgebra R B] [Algebra R C]

theorem comp_convOne (g : A →ₐ[R] C) :
    g.comp (1 : WithConv (B →ₐ[R] A)).ofConv =
      (1 : WithConv (B →ₐ[R] C)).ofConv := by
  ext b
  simp

theorem conv_antipode_mul (g : A →ₐ[R] C) :
    toConv (g.comp (antipodeAlgHom R A)) * toConv g = 1 := by
  apply ofConv_injective
  calc
    _ = g.comp (toConv (antipodeAlgHom R A) * toConv (AlgHom.id R A)).ofConv := by
      rw [AlgHom.comp_convMul_distrib]
      rfl
    _ = _ := by rw [AlgHom.antipode_id_cancel, comp_convOne]

theorem antipodeAlgHom_comp_bialgHom (f : B →ₐc[R] A) :
    (antipodeAlgHom R A).comp f.toAlgHom = f.toAlgHom.comp (antipodeAlgHom R B) := by
  apply toConv_injective
  apply mul_right_cancel (b := toConv f.toAlgHom)
  rw [conv_antipode_mul]
  apply ofConv_injective
  calc
    _ = (toConv (antipodeAlgHom R A) * toConv (AlgHom.id R A)).ofConv.comp f.toAlgHom := by
      rw [AlgHom.convMul_comp_bialgHom_distrib]
      rfl
    _ = _ := by
      rw [AlgHom.antipode_id_cancel]
      ext b
      simp only [AlgHom.comp_apply, AlgHom.convOne_apply]
      congr 1
      exact CoalgHomClass.counit_comp_apply f b

/-- The ideal generated by the image of the augmentation ideal of `B`. -/
def augmentationIdeal (f : B →ₐc[R] A) : Ideal A :=
  (RingHom.ker (Bialgebra.counitAlgHom R B).toRingHom).map f.toAlgHom.toRingHom

theorem quotient_comp_bialgHom (f : B →ₐc[R] A) :
    (Ideal.Quotient.mkₐ R (augmentationIdeal f)).comp f.toAlgHom =
      (Algebra.ofId R (A ⧸ augmentationIdeal f)).comp (Bialgebra.counitAlgHom R B) := by
  ext b
  apply sub_eq_zero.mp
  change Ideal.Quotient.mk (augmentationIdeal f) (f b) -
    Ideal.Quotient.mk (augmentationIdeal f) (algebraMap R A (Coalgebra.counit b)) = 0
  rw [← map_sub]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  change f.toAlgHom b - algebraMap R A (Coalgebra.counit b) ∈ augmentationIdeal f
  rw [← f.toAlgHom.commutes, ← map_sub]
  apply Ideal.mem_map_of_mem
  change Coalgebra.counit (b - algebraMap R B (Coalgebra.counit b)) = 0
  simp

/-- The coaction followed by the quotient by the extended augmentation ideal. -/
def torsorCoaction (f : B →ₐc[R] A) : A →ₐ[R] A ⊗[R] (A ⧸ augmentationIdeal f) :=
  (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f))).comp
    (Bialgebra.comulAlgHom R A)

theorem torsorCoaction_eq_conv (f : B →ₐc[R] A) :
    torsorCoaction f =
      (toConv (includeLeft : A →ₐ[R] A ⊗[R] (A ⧸ augmentationIdeal f)) *
        toConv (includeRight.comp (Ideal.Quotient.mkₐ R (augmentationIdeal f)))).ofConv := by
  rw [torsorCoaction, comulAlgHom_eq_conv_include, AlgHom.comp_convMul_distrib]
  congr 2

theorem torsorCoaction_comp (f : B →ₐc[R] A) :
    (torsorCoaction f).comp f.toAlgHom =
      (includeLeft : A →ₐ[R] A ⊗[R] (A ⧸ augmentationIdeal f)).comp f.toAlgHom := by
  rw [torsorCoaction_eq_conv, AlgHom.convMul_comp_bialgHom_distrib]
  have h : (includeRight.comp (Ideal.Quotient.mkₐ R (augmentationIdeal f))).comp f.toAlgHom =
      (1 : WithConv (B →ₐ[R] A ⊗[R] (A ⧸ augmentationIdeal f))).ofConv := by
    rw [AlgHom.comp_assoc, quotient_comp_bialgHom]
    ext b
    simp
  rw [h]
  simp

variable [Algebra B A] [IsScalarTower R B A]

/-- The quotient coaction, regarded as a map over `B` using the left action. -/
def torsorCoactionOverBase (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    A →ₐ[B] A ⊗[R] (A ⧸ augmentationIdeal f) where
  __ := (torsorCoaction f).toRingHom
  commutes' b := by
    have h := AlgHom.congr_fun (torsorCoaction_comp f) b
    change torsorCoaction f (algebraMap B A b) = (algebraMap B A b) ⊗ₜ[R] 1
    simpa only [AlgHom.comp_apply, hf, IsScalarTower.toAlgHom_apply,
      includeLeft_apply] using h

/-- The canonical relative Hopf torsor map. -/
def torsorHom (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    A ⊗[B] A →ₐ[A] A ⊗[R] (A ⧸ augmentationIdeal f) :=
  lift (Algebra.ofId A _) (torsorCoactionOverBase f hf) (fun _ _ ↦ .all ..)

/-- The difference of the two universal points of the relative tensor product. -/
def torsorDifference : A →ₐ[R] A ⊗[B] A :=
  (toConv ((includeLeft : A →ₐ[R] A ⊗[B] A).comp (antipodeAlgHom R A)) *
    toConv ((includeRight : A →ₐ[B] A ⊗[B] A).restrictScalars R)).ofConv

theorem torsorDifference_comp (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    (torsorDifference (R := R) (B := B) (A := A)).comp f.toAlgHom =
      (1 : WithConv (B →ₐ[R] A ⊗[B] A)).ofConv := by
  rw [torsorDifference, AlgHom.convMul_comp_bialgHom_distrib]
  have h : ((includeRight : A →ₐ[B] A ⊗[B] A).restrictScalars R).comp f.toAlgHom =
      (includeLeft : A →ₐ[R] A ⊗[B] A).comp f.toAlgHom := by
    ext b
    simp only [AlgHom.comp_apply, hf, IsScalarTower.toAlgHom_apply,
      includeLeft_apply]
    exact (tmul_one_eq_one_tmul b).symm
  rw [AlgHom.comp_assoc, antipodeAlgHom_comp_bialgHom, ← AlgHom.comp_assoc, h,
    conv_antipode_mul]

theorem augmentationIdeal_le_ker_torsorDifference (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    augmentationIdeal f ≤
      RingHom.ker (torsorDifference (R := R) (B := B) (A := A)).toRingHom := by
  apply Ideal.map_le_iff_le_comap.mpr
  intro b hb
  change torsorDifference (f b) = 0
  have h := AlgHom.congr_fun (torsorDifference_comp f hf) b
  change Coalgebra.counit (R := R) b = 0 at hb
  simpa [hb] using h

/-- The difference point factors through the quotient by the augmentation ideal. -/
def torsorQuotientHom (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    (A ⧸ augmentationIdeal f) →ₐ[R] A ⊗[B] A :=
  Ideal.Quotient.liftₐ _ torsorDifference (augmentationIdeal_le_ker_torsorDifference f hf)

/-- The inverse relative torsor map, constructed from the difference point. -/
def torsorInvHom (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    A ⊗[R] (A ⧸ augmentationIdeal f) →ₐ[A] A ⊗[B] A :=
  lift (Algebra.ofId A _) (torsorQuotientHom f hf) (fun _ _ ↦ .all ..)

theorem torsorHom_comp_tensorMap (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    ((torsorHom f hf).restrictScalars R).comp (mapOfCompatibleSMul B R R A A) =
      (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f))).comp
        (shearHom R A) := by
  ext <;> simp [torsorHom, torsorCoactionOverBase, shearHom, torsorCoaction]

theorem torsorDifference_eq_tensorMap_comp :
    torsorDifference (R := R) (B := B) (A := A) =
      (mapOfCompatibleSMul B R R A A).comp
        ((toConv (includeLeft : A →ₐ[R] A ⊗[R] A))⁻¹ * toConv includeRight).ofConv := by
  rw [AlgHom.comp_convMul_distrib]
  rfl

theorem torsorInvHom_comp_tensorQuotient (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    ((torsorInvHom f hf).restrictScalars R).comp
        (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f))) =
      (mapOfCompatibleSMul B R R A A).comp (shearInvHom R A) := by
  ext a
  · simp [torsorInvHom, shearInvHom]
  · change torsorInvHom f hf
      (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f))
        (1 ⊗ₜ[R] a)) = mapOfCompatibleSMul B R R A A (shearInvHom R A (1 ⊗ₜ[R] a))
    simp only [map_tmul, torsorInvHom, lift_tmul, map_one, one_mul]
    change torsorDifference (R := R) (B := B) (A := A) a = _
    rw [torsorDifference_eq_tensorMap_comp]
    simp [shearInvHom, ← Algebra.TensorProduct.one_def]

theorem torsorInvHom_comp_torsorHom (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    (torsorInvHom f hf).comp (torsorHom f hf) = AlgHom.id A (A ⊗[B] A) := by
  apply AlgHom.ext
  intro x
  obtain ⟨y, rfl⟩ := mapOfCompatibleSMul_surjective B R R A A x
  have h₁ := AlgHom.congr_fun (torsorHom_comp_tensorMap f hf) y
  have h₂ := AlgHom.congr_fun (torsorInvHom_comp_tensorQuotient f hf) (shearHom R A y)
  change torsorInvHom f hf (torsorHom f hf (mapOfCompatibleSMul B R R A A y)) = _
  rw [show torsorHom f hf (mapOfCompatibleSMul B R R A A y) = _ from h₁]
  dsimp only [AlgHom.comp_apply]
  rw [show torsorInvHom f hf
    (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f))
      (shearHom R A y)) = _ from h₂]
  exact congrArg (mapOfCompatibleSMul B R R A A)
    (AlgHom.congr_fun shearInvHom_comp_shearHom y)

theorem torsorHom_comp_torsorInvHom (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    (torsorHom f hf).comp (torsorInvHom f hf) =
      AlgHom.id A (A ⊗[R] (A ⧸ augmentationIdeal f)) := by
  apply AlgHom.ext
  intro x
  obtain ⟨y, rfl⟩ := Algebra.TensorProduct.map_surjective
    (f := AlgHom.id R A) (g := Ideal.Quotient.mkₐ R (augmentationIdeal f))
    Function.surjective_id Ideal.Quotient.mk_surjective x
  have h₁ := AlgHom.congr_fun (torsorInvHom_comp_tensorQuotient f hf) y
  have h₂ := AlgHom.congr_fun (torsorHom_comp_tensorMap f hf) (shearInvHom R A y)
  change torsorHom f hf (torsorInvHom f hf
    (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f)) y)) = _
  rw [show torsorInvHom f hf
    (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f)) y) = _
    from h₁]
  dsimp only [AlgHom.comp_apply]
  rw [show torsorHom f hf (mapOfCompatibleSMul B R R A A (shearInvHom R A y)) = _ from h₂]
  exact congrArg
    (Algebra.TensorProduct.map (AlgHom.id R A) (Ideal.Quotient.mkₐ R (augmentationIdeal f)))
    (AlgHom.congr_fun shearHom_comp_shearInvHom y)

/-- The relative Hopf torsor isomorphism over the left copy of `A`.
No flatness, finiteness, or injectivity hypothesis is needed for this isomorphism. -/
def torsorEquiv (f : B →ₐc[R] A)
    (hf : f.toAlgHom = IsScalarTower.toAlgHom R B A) :
    A ⊗[B] A ≃ₐ[A] A ⊗[R] (A ⧸ augmentationIdeal f) :=
  AlgEquiv.ofAlgHom (torsorHom f hf) (torsorInvHom f hf)
    (torsorHom_comp_torsorInvHom f hf) (torsorInvHom_comp_torsorHom f hf)

end HopfAlgebra
