/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.LocalDifferentValuation
public import FLT.Mathlib.RingTheory.PowerBasisConjugateDifferent

/-!
# The local different as a sum of conjugate displacements

For a finite Galois extension of the three-adic field, the different is the
product of the displacement ideals of its nonidentity integral
endomorphisms. Taking normalized ideal orders gives the usual sum formula.
The displacement ideals are defined using all integral elements, so their
definition does not depend on the chosen integral power basis.
-/

@[expose] public noncomputable section

namespace ThreeAdicPlan

open Polynomial

variable (L : Type*) [Field L] [Algebra ℚ_[3] L] [Algebra ℤ_[3] L]
  [IsScalarTower ℤ_[3] ℚ_[3] L] [FiniteDimensional ℚ_[3] L]

/-- There are finitely many endomorphisms of the full ring of integers. -/
instance threeAdicIntegersEndomorphismFintype :
    Fintype (ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L) :=
  PowerBasis.AlgHom.fintype (threeAdicIntegersPowerBasis L)

/-- The ideal generated by all differences between an integer and its image. -/
def threeAdicDisplacementIdeal
    (σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L) :
    Ideal (ThreeAdicIntegers L) := Ideal.span (Set.range fun x ↦ x - σ x)

/-- The normalized order of an integral endomorphism's displacement ideal.
The identity has value zero, following the convention for the zero ideal. -/
def threeAdicDisplacementOrder
    (σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L) : ℚ :=
  normalizedIdealOrder L (threeAdicDisplacementIdeal L σ)

omit [Algebra ℚ_[3] L] [IsScalarTower ℤ_[3] ℚ_[3] L] [FiniteDimensional ℚ_[3] L] in
/-- Any integral power-basis generator generates the displacement ideal. -/
theorem threeAdicDisplacementIdealEqSpan
    (pb : PowerBasis ℤ_[3] (ThreeAdicIntegers L))
    (σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L) :
    threeAdicDisplacementIdeal L σ = Ideal.span {pb.gen - σ pb.gen} :=
  pb.spanSubHomEqSpanGen σ

/-- A nonidentity endomorphism has a nonzero displacement ideal. -/
theorem threeAdicDisplacementIdealNeBot
    (σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L)
    (hσ : σ ≠ AlgHom.id ℤ_[3] (ThreeAdicIntegers L)) :
    threeAdicDisplacementIdeal L σ ≠ ⊥ := by
  rw [threeAdicDisplacementIdealEqSpan L (threeAdicIntegersPowerBasis L),
    ne_eq, Ideal.span_singleton_eq_bot, sub_eq_zero]
  intro h
  exact hσ ((threeAdicIntegersPowerBasis L).algHom_ext h.symm)

/-- The minimal polynomial of an integral generator splits in the integers
of a normal extension. -/
theorem threeAdicIntegralMinpolySplits [Normal ℚ_[3] L]
    (x : ThreeAdicIntegers L) :
    ((minpoly ℤ_[3] x).map (algebraMap ℤ_[3] (ThreeAdicIntegers L))).Splits := by
  have hpoly : (minpoly ℤ_[3] x).map (algebraMap ℤ_[3] ℚ_[3]) =
      minpoly ℚ_[3] (x : L) :=
    (minpoly.isIntegrallyClosed_eq_field_fractions ℚ_[3] L
      (IsIntegralClosure.isIntegral ℤ_[3] L x)).symm
  have hmap : ((minpoly ℤ_[3] x).map
      (algebraMap ℤ_[3] (ThreeAdicIntegers L))).map
      (algebraMap (ThreeAdicIntegers L) L) =
      (minpoly ℚ_[3] (x : L)).map (algebraMap ℚ_[3] L) := by
    rw [← hpoly, map_map, map_map, ← IsScalarTower.algebraMap_eq,
      ← IsScalarTower.algebraMap_eq]
  apply Splits.of_splits_map_of_injective
    (show Function.Injective (algebraMap (ThreeAdicIntegers L) L) from Subtype.val_injective)
  · rw [hmap]
    exact Normal.splits (inferInstance : Normal ℚ_[3] L) (x : L)
  · intro y hy
    have hy' : aeval y (minpoly ℤ_[3] x) = 0 := by
      rw [mem_roots (by rw [hmap]; exact map_ne_zero (minpoly.ne_zero
        (Algebra.IsIntegral.isIntegral (R := ℚ_[3]) (x : L))))] at hy
      simpa only [map_map, ← IsScalarTower.algebraMap_eq, IsRoot,
        eval_map_algebraMap] using hy
    exact ⟨⟨y, ⟨minpoly ℤ_[3] x,
      minpoly.monic (IsIntegralClosure.isIntegral ℤ_[3] L x), hy'⟩⟩, rfl⟩

/-- The integral minimal polynomial has no repeated roots, even when the
different is not a unit. Separability is used over the fraction field. -/
theorem threeAdicIntegralMinpolyRootsNodup [Normal ℚ_[3] L]
    (x : ThreeAdicIntegers L) :
    ((minpoly ℤ_[3] x).aroots (ThreeAdicIntegers L)).Nodup := by
  have hpoly : (minpoly ℤ_[3] x).map (algebraMap ℤ_[3] ℚ_[3]) =
      minpoly ℚ_[3] (x : L) :=
    (minpoly.isIntegrallyClosed_eq_field_fractions ℚ_[3] L
      (IsIntegralClosure.isIntegral ℤ_[3] L x)).symm
  have h := (threeAdicIntegralMinpolySplits L x).roots_map_of_injective
    (show Function.Injective (algebraMap (ThreeAdicIntegers L) L) from Subtype.val_injective)
  have hn : ((((minpoly ℤ_[3] x).map (algebraMap ℤ_[3] (ThreeAdicIntegers L))).map
      (algebraMap (ThreeAdicIntegers L) L)).roots).Nodup := by
    rw [map_map, ← IsScalarTower.algebraMap_eq,
      IsScalarTower.algebraMap_eq ℤ_[3] ℚ_[3] L, ← map_map, hpoly]
    exact nodup_roots (Polynomial.Separable.map
      (Algebra.IsSeparable.isSeparable ℚ_[3] (x : L)))
  rw [h] at hn
  exact Multiset.Nodup.of_map _ hn

/-- Normalized ideal order is additive on products of nonzero ideals. -/
theorem normalizedIdealOrderMul {I J : Ideal (ThreeAdicIntegers L)}
    (hI : I ≠ ⊥) (hJ : J ≠ ⊥) :
    normalizedIdealOrder L (I * J) = normalizedIdealOrder L I + normalizedIdealOrder L J := by
  classical
  simp only [normalizedIdealOrder, threeAdicIdealOrder,
    UniqueFactorizationMonoid.normalizedFactors_mul hI hJ, Multiset.count_add,
    Nat.cast_add, add_div]

/-- Normalized ideal order turns a finite product of nonzero ideals into a sum. -/
theorem normalizedIdealOrderProd {ι : Type*} (s : Finset ι)
    (I : ι → Ideal (ThreeAdicIntegers L)) (hI : ∀ i ∈ s, I i ≠ ⊥) :
    normalizedIdealOrder L (∏ i ∈ s, I i) = ∑ i ∈ s, normalizedIdealOrder L (I i) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    simp only [Finset.prod_empty, Finset.sum_empty, normalizedIdealOrder,
      threeAdicIdealOrder, UniqueFactorizationMonoid.normalizedFactors_one,
      Multiset.count_zero, Nat.cast_zero, zero_div]
  | @insert i s hi ih =>
    rw [Finset.prod_insert hi, Finset.sum_insert hi, normalizedIdealOrderMul L
      (hI i (Finset.mem_insert_self _ _))
      (Finset.prod_ne_zero_iff.mpr (fun j hj ↦ hI j (Finset.mem_insert_of_mem hj))),
      ih (fun j hj ↦ hI j (Finset.mem_insert_of_mem hj))]

open scoped Classical in
/-- The different is the product of all nonidentity displacement ideals. -/
theorem threeAdicDifferentEqProdDisplacement [Normal ℚ_[3] L] :
    differentIdeal ℤ_[3] (ThreeAdicIntegers L) =
      ∏ σ ∈ Finset.univ.erase (AlgHom.id ℤ_[3] (ThreeAdicIntegers L)),
        threeAdicDisplacementIdeal L σ := by
  classical
  let pb := threeAdicIntegersPowerBasis L
  rw [pb.differentIdeal_eq_span_minpoly_derivative ℚ_[3] L,
    pb.minpolyDerivativeEqProdHom (threeAdicIntegralMinpolySplits L pb.gen)
      (threeAdicIntegralMinpolyRootsNodup L pb.gen), ← Ideal.prod_span_singleton]
  exact Finset.prod_congr rfl fun σ _ ↦ (threeAdicDisplacementIdealEqSpan L pb σ).symm

/-- The identity's displacement has order zero under the zero-ideal convention. -/
@[simp] theorem threeAdicDisplacementOrderId :
    threeAdicDisplacementOrder L (AlgHom.id ℤ_[3] (ThreeAdicIntegers L)) = 0 := by
  have hid : threeAdicDisplacementIdeal L
      (AlgHom.id ℤ_[3] (ThreeAdicIntegers L)) = 0 := by
    simp [threeAdicDisplacementIdeal]
  rw [threeAdicDisplacementOrder, hid]
  simp only [normalizedIdealOrder, threeAdicIdealOrder,
    UniqueFactorizationMonoid.normalizedFactors_zero, Multiset.count_zero,
    Nat.cast_zero, zero_div]

/-- Every displacement order is nonnegative. -/
theorem threeAdicDisplacementOrderNonneg
    (σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L) :
    0 ≤ threeAdicDisplacementOrder L σ := by
  unfold threeAdicDisplacementOrder normalizedIdealOrder
  positivity

/-- The normalized different exponent is the sum of normalized displacement
orders. The identity contributes zero. -/
theorem normalizedDifferentExponentEqSumDisplacement [Normal ℚ_[3] L] :
    normalizedDifferentExponent L =
      ∑ σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L,
        threeAdicDisplacementOrder L σ := by
  classical
  unfold normalizedDifferentExponent
  rw [threeAdicDifferentEqProdDisplacement, normalizedIdealOrderProd L _ _
    (fun σ hσ ↦ threeAdicDisplacementIdealNeBot L σ (Finset.mem_erase.mp hσ).1)]
  change (∑ σ ∈ Finset.univ.erase (AlgHom.id ℤ_[3] (ThreeAdicIntegers L)),
    threeAdicDisplacementOrder L σ) = _
  have h := Finset.sum_erase_add _ (threeAdicDisplacementOrder L)
    (Finset.mem_univ (AlgHom.id ℤ_[3] (ThreeAdicIntegers L)))
  simpa only [threeAdicDisplacementOrderId, add_zero] using h

/-- A positive different exponent forces some nonidentity displacement to
have positive order. -/
theorem existsPositiveDisplacementOfDifferentPos [Normal ℚ_[3] L]
    (hd : 0 < normalizedDifferentExponent L) :
    ∃ σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L,
      σ ≠ AlgHom.id ℤ_[3] (ThreeAdicIntegers L) ∧ 0 < threeAdicDisplacementOrder L σ := by
  classical
  rw [normalizedDifferentExponentEqSumDisplacement] at hd
  have hpos : ∃ σ : ThreeAdicIntegers L →ₐ[ℤ_[3]] ThreeAdicIntegers L,
      0 < threeAdicDisplacementOrder L σ := by
    by_contra h
    push Not at h
    exact (not_le_of_gt hd) (Finset.sum_nonpos fun σ _ ↦ h σ)
  obtain ⟨σ, hσ⟩ := hpos
  refine ⟨σ, ?_, hσ⟩
  rintro rfl
  simp at hσ

end ThreeAdicPlan
