/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.FiniteFreeAdicComplete
public import FLT.GroupScheme.LocalDifferentValuation
public import FLT.Mathlib.RingTheory.AdicCompletion.Power
public import Mathlib.RingTheory.Henselian

/-!
# Henselian rings of integers of finite three-adic extensions

The ideal generated by three is a positive power of the maximal ideal.
Finite-free completeness therefore gives maximal-ideal completeness and
lifts every simple residue root.
-/

@[expose] public noncomputable section

namespace ThreeAdicPlan

variable (L : Type*) [Field L] [Algebra ℚ_[3] L] [Algebra ℤ_[3] L]
  [IsScalarTower ℤ_[3] ℚ_[3] L] [FiniteDimensional ℚ_[3] L]

/-- The ring of integers is complete for its maximal ideal. -/
theorem threeAdicIntegersMaximalIdealComplete :
    IsAdicComplete (IsLocalRing.maximalIdeal (ThreeAdicIntegers L)) (ThreeAdicIntegers L) := by
  let A := ThreeAdicIntegers L
  let instCharZero : CharZero A := Algebra.charZero_of_charZero ℤ_[3] A
  have hmap : (IsLocalRing.maximalIdeal ℤ_[3]).map (algebraMap ℤ_[3] A) =
      Ideal.span {(3 : A)} := by
    simp [PadicInt.maximalIdeal_eq_span_p, Ideal.map_span, Set.image_singleton,
      Nat.cast_ofNat, map_ofNat]
  have hpow := ideal_eq_maximalIdeal_pow_threeAdicIdealOrder L
    (Ideal.span {(3 : A)}) (by simp)
  let instComplete : IsAdicComplete
      (IsLocalRing.maximalIdeal A ^ threeAdicIdealOrder L (Ideal.span {(3 : A)})) A := by
    rw [← hpow, ← hmap]
    exact adicComplete_finite_free_algebra (IsLocalRing.maximalIdeal ℤ_[3]) A
  exact IsAdicComplete.ofPow _ (threeAdicIdealOrder_three_pos L)

/-- The full ring of integers of a finite three-adic extension is Henselian. -/
instance threeAdicIntegersHenselian : HenselianLocalRing (ThreeAdicIntegers L) where
  is_henselian f hf a ha hd := by
    let instComplete := threeAdicIntegersMaximalIdealComplete L
    exact HenselianRing.is_henselian f hf a ha (hd.map (IsLocalRing.residue _))

end ThreeAdicPlan
