/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.FiniteFreeAdicComplete
public import FLT.GroupScheme.HenselianIdempotents
public import FLT.GroupScheme.RaynaudExtension
public import Mathlib.NumberTheory.Padics.PadicIntegers
public import Mathlib.RingTheory.LocalRing.Module

/-!
# Component lifting for finite-flat three-adic models

Finite-flat coordinate algebras over `ℤ_[3]` are complete, hence Henselian,
for the ideal `(3)`. Every special-fibre component decomposition therefore
lifts uniquely to an integral algebra decomposition. No generic splitting or
integral section is assumed. The construction here is a decomposition of
algebras; a connected–étale sequence also needs compatibility with the Hopf maps.
-/

@[expose] public noncomputable section

namespace ThreeAdicPlan

/-- The ideal defining the special fibre of a three-adic algebra. -/
def threeAdicSpecialIdeal (A : Type*) [CommRing A] [Algebra ℤ_[3] A] : Ideal A :=
  (IsLocalRing.maximalIdeal ℤ_[3]).map (algebraMap ℤ_[3] A)

/-- The special-fibre ideal is generated by three. -/
theorem threeAdicSpecialIdeal_eq (A : Type*) [CommRing A] [Algebra ℤ_[3] A] :
    threeAdicSpecialIdeal A = Ideal.span {(3 : A)} := by
  simp [threeAdicSpecialIdeal, PadicInt.maximalIdeal_eq_span_p, Ideal.map_span, map_ofNat]

/-- Finite flat three-adic algebras are complete for their special-fibre ideal. -/
theorem threeAdicFiniteFlat_complete (A : Type*) [CommRing A] [Algebra ℤ_[3] A]
    [Module.Finite ℤ_[3] A] [Module.Flat ℤ_[3] A] :
    IsAdicComplete (threeAdicSpecialIdeal A) A := by
  let : Module.Free ℤ_[3] A := Module.free_of_flat_of_isLocalRing
  exact adicComplete_finite_free_algebra (IsLocalRing.maximalIdeal ℤ_[3]) A

/-- The Henselian property needed for component lifting follows from finite flatness. -/
theorem threeAdicFiniteFlat_henselian (A : Type*) [CommRing A] [Algebra ℤ_[3] A]
    [Module.Finite ℤ_[3] A] [Module.Flat ℤ_[3] A] :
    HenselianRing A (threeAdicSpecialIdeal A) := by
  let := threeAdicFiniteFlat_complete A
  infer_instance

/-- Special-fibre idempotents lift uniquely in every existing three-adic model. -/
theorem FF.existsUnique_specialFiber_idempotent (X : FF ℤ_[3] ℚ_[3])
    (e : X.CoordinateRing ⧸ threeAdicSpecialIdeal X.CoordinateRing) (he : IsIdempotentElem e) :
    ∃! x : X.CoordinateRing, IsIdempotentElem x ∧
      Ideal.Quotient.mk (threeAdicSpecialIdeal X.CoordinateRing) x = e := by
  let := threeAdicFiniteFlat_henselian X.CoordinateRing
  exact existsUnique_idempotent_lift _ e he

/-- An integral component decomposition is obtained from any special-fibre decomposition. -/
theorem FF.existsUnique_specialFiber_components (X : FF ℤ_[3] ℚ_[3])
    {ι : Type*} [Fintype ι]
    (e : ι → X.CoordinateRing ⧸ threeAdicSpecialIdeal X.CoordinateRing)
    (he : CompleteOrthogonalIdempotents e) :
    ∃! f : ι → X.CoordinateRing, CompleteOrthogonalIdempotents f ∧
      ∀ i, Ideal.Quotient.mk (threeAdicSpecialIdeal X.CoordinateRing) (f i) = e i := by
  let := threeAdicFiniteFlat_henselian X.CoordinateRing
  exact existsUnique_completeOrthogonalIdempotents_lift _ e he

/-- The lifted product decomposition, stated in the existing local `FF` vocabulary. -/
def FF.specialFiberComponentEquiv (X : FF ℤ_[3] ℚ_[3])
    {ι : Type*} [Fintype ι]
    (e : ι → X.CoordinateRing ⧸ threeAdicSpecialIdeal X.CoordinateRing)
    (he : CompleteOrthogonalIdempotents e) :
    letI := threeAdicFiniteFlat_henselian X.CoordinateRing
    X.CoordinateRing ≃ₐ[ℤ_[3]] Π i, X.CoordinateRing ⧸ Ideal.span
      {1 - henselianComponentIdempotents (threeAdicSpecialIdeal X.CoordinateRing) e he i} := by
  let := threeAdicFiniteFlat_henselian X.CoordinateRing
  exact henselianComponentEquiv _ e he

/-- Integral idempotents, including images under Hopf maps, are determined by
their special-fibre values. The target may in particular be a tensor power. -/
theorem threeAdicFiniteFlat_idempotent_ext {A : Type*} [CommRing A] [Algebra ℤ_[3] A]
    [Module.Finite ℤ_[3] A] [Module.Flat ℤ_[3] A]
    {e f : A} (he : IsIdempotentElem e) (hf : IsIdempotentElem f)
    (h : Ideal.Quotient.mk (threeAdicSpecialIdeal A) e =
      Ideal.Quotient.mk (threeAdicSpecialIdeal A) f) : e = f := by
  let := threeAdicFiniteFlat_henselian A
  exact idempotent_eq_of_quotient_eq _ HenselianRing.jac he hf h

end ThreeAdicPlan
