/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import Mathlib.Algebra.MvPolynomial.CommRing
public import Mathlib.RingTheory.Ideal.Maps

/-! # The coefficient kernel in a polynomial algebra -/

@[expose] public noncomputable section
namespace MvPolynomial
variable {B T ι : Type*} [CommRing B] [CommRing T]

/-- The kernel of coefficient reduction is generated by constant polynomials in its kernel. -/
theorem ker_map_eq_map_C (q : B →+* T) :
    RingHom.ker (map (σ := ι) q) = (RingHom.ker q).map C := by
  apply le_antisymm
  · intro f hf
    have hc (d) : f.coeff d ∈ RingHom.ker q := by
      have h := congrArg (fun g : MvPolynomial ι T ↦ g.coeff d) hf
      simpa only [coeff_map, AddMonoidAlgebra.coeff_zero, Finsupp.zero_apply,
        RingHom.mem_ker] using h
    rw [f.as_sum]
    apply Submodule.sum_mem
    intro d _
    rw [monomial_eq]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ (hc d))
  · rw [Ideal.map_le_iff_le_comap]
    intro b hb
    change map q (C b) = 0
    rw [map_C, show q b = 0 from hb, map_zero]

end MvPolynomial
