/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.RaynaudCyclicMonomials
public import Mathlib.LinearAlgebra.Span.Basic

/-!
# Reducing cyclic monomials to digit exponents

Replacing xᵢ^p by aᵢ xⱼ lowers total degree by p−1. Strong induction
therefore expresses every monomial in the span of those with exponents <p.
-/

@[expose] public noncomputable section
namespace ThreeAdicPlan.CyclicPresentation

variable {R A ι : Type*} [CommRing R] [CommRing A] [Algebra R A]
  [Fintype ι] (x : ι → A) (p : ℕ)

/-- The submodule generated by monomials whose individual exponents are below p. -/
def digitSpan : Submodule R A :=
  Submodule.span R (Set.range (fun d : ι → Fin p ↦ monomial x (fun i ↦ (d i).val)))

/-- Every monomial reduces to the digit span under degree-p cyclic relations. -/
theorem monomial_mem_digitSpan (hp : 1 < p) (next : ι → ι) (a : ι → R)
    (hrel : ∀ i, x i ^ p = a i • x (next i)) (d : ι → ℕ) :
    monomial x d ∈ digitSpan (R := R) x p := by
  classical
  suffices h : ∀ n (d : ι → ℕ), (∑ i, d i) = n → monomial x d ∈ digitSpan (R := R) x p by
    exact h _ d rfl
  intro n
  induction n using Nat.strong_induction_on with
  | h n ih =>
    intro d hd
    by_cases hb : ∀ i, d i < p
    · exact Submodule.subset_span ⟨fun i ↦ ⟨d i, hb i⟩, rfl⟩
    · obtain ⟨i, hi⟩ := not_forall.mp hb
      have hip : p ≤ d i := Nat.le_of_not_gt hi
      let b := d - Pi.single i p
      have hb : b + Pi.single i p = d := sub_single_add d i p hip
      have hdeg : (∑ j, b j) + p = n := by
        rw [← degree_single (ι := ι) i p, ← degree_add, hb, hd]
      let c := b + Pi.single (next i) 1
      have hc : (∑ j, c j) = (∑ j, b j) + 1 := by
        dsimp only [c]
        rw [degree_add, degree_single]
      have hsmall : (∑ j, c j) < n := by omega
      have heq : monomial x d = a i • monomial x c := by
        dsimp only [c]
        rw [← hb, monomial_add, monomial_single, hrel,
          mul_smul_comm, monomial_add, monomial_single, pow_one]
      rw [heq]
      exact (digitSpan (R := R) x p).smul_mem _ (ih _ hsmall c rfl)

end ThreeAdicPlan.CyclicPresentation
