/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.RaynaudHenselianFactor

/-!
# Embedded unramified stages containing a prescribed root

Adjoining the specified root to a Henselian DVR preserves its uniformizer
when the root satisfies a monic polynomial with separable reduction.
-/

@[expose] public noncomputable section

open Polynomial IsLocalRing IsDiscreteValuationRing

namespace RaynaudParameters

variable {R Ω : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  [HenselianLocalRing R] [Field Ω] [Algebra R Ω] [FaithfulSMul R Ω]

/-- The actual subalgebra generated by a prescribed root is a finite unramified
DVR. In particular, the embedding and root are retained, rather than rechosen. -/
theorem adjoin_prescribed_root_unramified {π : R} (hπ : Irreducible π)
    {P : R[X]} (hm : P.Monic) (hs : (P.map (residue R)).Separable)
    (x : Ω) (hx : aeval x P = 0) :
    ∃ (_ : IsDiscreteValuationRing (Algebra.adjoin R {x}))
      (_ : Module.Finite R (Algebra.adjoin R {x}))
      (_ : IsLocalHom (algebraMap R (Algebra.adjoin R {x})))
      (_ : Algebra.FormallyUnramified R (Algebra.adjoin R {x})),
      Irreducible (algebraMap R (Algebra.adjoin R {x}) π) := by
  have hint : IsIntegral R x := ⟨P, hm, hx⟩
  let Q := minpoly R x
  have hQm : Q.Monic := minpoly.monic hint
  have hQs : (Q.map (residue R)).Separable :=
    hs.of_dvd (Polynomial.map_dvd _ (minpoly.isIntegrallyClosed_dvd hint hx))
  have hQi : Irreducible (Q.map (residue R)) :=
    irreducible_map_residue_of_henselian hQm (minpoly.irreducible hint) hQs
  let A := AdjoinRoot Q
  let : IsDomain A := AdjoinRoot.isDomain_of_prime (minpoly.prime_of_isIntegrallyClosed hint)
  obtain ⟨hmax, hdvr, hloc⟩ := AdjoinRoot.isDiscreteValuationRing_of_irreducible_map_residue
    hQm (minpoly.degree_pos hint).ne' hQi
  let : Module.Finite R A := hQm.finite_adjoinRoot
  have hmax' : maximalIdeal A = (maximalIdeal R).map (algebraMap R A) :=
    (eq_maximalIdeal hmax).symm
  let : Fact (Irreducible (Q.map (residue R))) := ⟨hQi⟩
  let : Algebra.IsSeparable (ResidueField R) (AdjoinRoot (Q.map (residue R))) :=
    AdjoinRoot.isSeparable_of_separable hQs
  let er := (AdjoinRoot.residueFieldEquiv hmax').extendScalarsOfSurjective residue_surjective
  let : Algebra.IsSeparable (ResidueField R) (ResidueField A) :=
    Algebra.IsSeparable.of_algHom _ _ er.toAlgHom
  let : Algebra.FormallyUnramified R A :=
    Algebra.FormallyUnramified.of_map_maximalIdeal hmax'.symm
  let e : A ≃ₐ[R] Algebra.adjoin R {x} := minpoly.equivAdjoin hint
  let hD := RingEquivClass.isDiscreteValuationRing e
  let hF : Module.Finite R (Algebra.adjoin R {x}) :=
    Module.Finite.of_surjective e.toLinearMap e.surjective
  let hL : IsLocalHom (algebraMap R (Algebra.adjoin R {x})) := ⟨fun r hr ↦ by
    apply isUnit_of_map_unit (algebraMap R A) r
    simpa using hr.map e.symm.toRingHom⟩
  let hU : Algebra.FormallyUnramified R (Algebra.adjoin R {x}) :=
    Algebra.FormallyUnramified.of_equiv e
  refine ⟨hD, hF, hL, hU, ?_⟩
  have hπA : Irreducible (algebraMap R A π) := by
    apply (irreducible_iff_uniformizer _).mpr
    rw [hmax', hπ.maximalIdeal_eq, Ideal.map_span, Set.image_singleton]
  simpa using hπA.map e.toMulEquiv

end RaynaudParameters
