/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.RaynaudUnramifiedQuotient
public import Mathlib.RingTheory.Localization.Away.Lemmas
public import Mathlib.RingTheory.Flat.Localization

/-!
# Flat scheme-theoretic kernels for unramified quotients

The augmentation ideal of a finite unramified algebra is generated by an
idempotent. Its extension to a finite flat source therefore has a flat quotient.
This concerns the actual scheme-theoretic kernel, before taking flat closure.
-/

@[expose] public noncomputable section

namespace AlgHom

variable {R D : Type*} [CommRing R] [CommRing D] [Algebra R D]

/-- An augmentation of a formally unramified algebra has an idempotent kernel. -/
theorem isIdempotentElem_ker_of_formallyUnramified
    [Algebra.FormallyUnramified R D] (ε : D →ₐ[R] R) :
    IsIdempotentElem (RingHom.ker ε.toRingHom) := by
  let := ε.toAlgebra
  have : IsScalarTower R D R := IsScalarTower.of_algebraMap_eq' ε.comp_algebraMap.symm
  have : Algebra.FormallyEtale D R := Algebra.FormallyEtale.of_restrictScalars (R := R)
  exact (Algebra.FormallyEtale.iff_of_surjective
    (show Function.Surjective (algebraMap D R) from
      fun r ↦ ⟨algebraMap R D r, ε.commutes r⟩)).mp inferInstance

end AlgHom

namespace Ideal

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- Quotienting a flat algebra by a finitely generated idempotent ideal remains
flat over the original base: the quotient is a localization at an idempotent. -/
theorem quotient_flat_of_isIdempotentElem [Module.Flat R A]
    (I : Ideal A) (hI : I.FG) (hidem : IsIdempotentElem I) :
    Module.Flat R (A ⧸ I) := by
  obtain ⟨e, he, rfl⟩ := (I.isIdempotentElem_iff_of_fg hI).mp hidem
  have : IsLocalization.Away (1 - e) (A ⧸ Ideal.span {e}) := by
    have h := IsLocalization.Away.quotient_of_isIdempotentElem he.one_sub
    have hsub : 1 - (1 - e) = e := by ring
    rw [hsub] at h
    exact h
  let : Module.Flat A (A ⧸ Ideal.span {e}) := IsLocalization.flat _ (Submonoid.powers (1 - e))
  exact Module.Flat.trans R A _

end Ideal

namespace ThreeAdicPlan

variable {R K : Type} [CommRing R] [Field K] [Algebra R K]
    [PerfectField K] [IsDedekindDomain R] [IsFractionRing R K] {X Y : FF R K}

/-- Equations of the scheme-theoretic kernel of the contracted quotient map. -/
def GenericGaloisHom.quotientKernelIdeal (q : GenericGaloisHom X Y) : Ideal X.CoordinateRing :=
  (RingHom.ker (Bialgebra.counitAlgHom R q.quotientCoordinates).toRingHom).map
    q.quotientInclusion.toAlgHom.toRingHom

/-- The equations of the kernel of an unramified quotient form an idempotent ideal. -/
theorem GenericGaloisHom.quotientKernelIdeal_isIdempotentElem
    (q : GenericGaloisHom X Y) [Algebra.FormallyUnramified R q.quotientCoordinates] :
    IsIdempotentElem q.quotientKernelIdeal := by
  change _ * _ = _
  rw [GenericGaloisHom.quotientKernelIdeal, ← Ideal.map_mul]
  rw [(Bialgebra.counitAlgHom R q.quotientCoordinates).isIdempotentElem_ker_of_formallyUnramified]

/-- The actual scheme-theoretic kernel of an unramified contracted quotient is
flat over the base; no replacement by its flat closure is involved. -/
theorem GenericGaloisHom.quotientKernel_flat_of_formallyUnramified
    (q : GenericGaloisHom X Y) [Algebra.FormallyUnramified R q.quotientCoordinates] :
    Module.Flat R (X.CoordinateRing ⧸ q.quotientKernelIdeal) := by
  let : IsNoetherianRing X.CoordinateRing := IsNoetherianRing.of_finite R X.CoordinateRing
  exact q.quotientKernelIdeal.quotient_flat_of_isIdempotentElem (IsNoetherian.noetherian _)
    q.quotientKernelIdeal_isIdempotentElem

end ThreeAdicPlan
