/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.GroupScheme.RaynaudMixedDigitParameters
public import FLT.GroupScheme.RaynaudFundamentalCharacterPowers
public import FLT.GroupScheme.RaynaudCyclicCharacterEquations

/-!
# Fundamental coordinates generate every character line

Each digit weight is a Frobenius power. The proved unit monomial
coefficient therefore puts every character generator in the algebra
spanned by the actual fundamental coordinates.
-/

@[expose] public noncomputable section
namespace ThreeAdicPlan
open IsLocalRing CharacterAverage

/-- Every expanded digit weight is a Frobenius power at an index of the digit vector. -/
theorem digitWeights_mem_pow (p : ℕ) (ds : List ℕ) (k : ℕ) (hk : k ∈ digitWeights p ds) :
    ∃ i < ds.length, k = p ^ i := by
  induction ds generalizing k with
  | nil => simp [digitWeights] at hk
  | cons d ds ih =>
    rcases List.mem_append.mp hk with hk | hk
    · have he : k = 1 := (List.mem_replicate.mp hk).2
      exact ⟨0, by simp, by simpa using he⟩
    · obtain ⟨j, hj, rfl⟩ := List.mem_map.mp hk
      obtain ⟨i, hi, rfl⟩ := ih j hj
      exact ⟨i + 1, by simpa using hi, Nat.pow_succ'.symm⟩

variable {R K F : Type} [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
  [HenselianLocalRing R] [IsSepClosed (ResidueField R)] [Field K] [Algebra R K]
  [CharZero K] [IsFractionRing R K] [Field F] [Fintype F] [DecidableEq F]
  [Invertible (Fintype.card Fˣ : R)] (X : FF R K) [Module F X.Points]
  (lift : F → ModelHom X X) (h0 : lift 0 = ModelHom.zero X X)
  (h1 : lift 1 = BialgHom.id R X.CoordinateRing)
  (hmul : ∀ a b, lift (a * b) = (lift b).comp (lift a))
  (hadd : ∀ a b, lift (a + b) = (lift a).add (lift b))
  (p : ℕ) [CharP F p] [CharP (ResidueField R) p]
  (hdim : Module.finrank F X.Points = 1)
  (hlift : ∀ a x, genericHom (lift a) x = a • x) (e : F →+* ResidueField R)

include h0 hadd in
/-- Every positive fundamental power generator is in the algebra of fundamental coordinates. -/
theorem FF.power_characterGenerator_mem_adjoin (n : ℕ) (hn : 0 < n)
    (hnq : n ≤ Fintype.card Fˣ) :
    X.characterGenerator lift h1 hmul p hdim hlift (fundamentalCharacter p e ^ n) ∈
      Algebra.adjoin R (Set.range (X.fundamentalCoordinate p lift h1 hmul hdim hlift e)) := by
  let χ := fundamentalCharacter p e
  let ds := Nat.digits p n
  let S := Algebra.adjoin R
    (Set.range (X.fundamentalCoordinate p lift h1 hmul hdim hlift e))
  have hp : p.Prime := CharP.char_is_prime F p
  obtain ⟨a, _, ha, _⟩ := X.exists_mixed_digit_parameter_units lift h0 h1 hmul hadd p
    hdim hlift χ e (fundamentalCharacter_residue p e) ds
    (fun d hd ↦ Nat.digits_lt_base hp.one_lt hd)
    (by simpa [ds, Nat.ofDigits_digits] using hn.ne') (by simpa [ds, Nat.ofDigits_digits] using hnq)
  have hm : (((digitWeights p ds).reverse.map (fun k ↦ χ ^ k)).map
      (X.characterGenerator lift h1 hmul p hdim hlift)).prod ∈ S := by
    apply S.list_prod_mem
    intro x hx
    obtain ⟨ψ, hψ, rfl⟩ := List.mem_map.mp hx
    obtain ⟨k, hk, rfl⟩ := List.mem_map.mp hψ
    obtain ⟨i, _, rfl⟩ := digitWeights_mem_pow p ds k (List.mem_reverse.mp hk)
    exact Algebra.subset_adjoin ⟨i, rfl⟩
  rw [ha] at hm
  have hu := S.smul_mem hm (a⁻¹ : Rˣ).val
  simpa [ds, χ, S, Nat.ofDigits_digits, smul_smul] using hu

include h0 hadd in
/-- All character generators belong to the algebra generated by fundamental coordinates. -/
theorem FF.characterGenerator_mem_adjoin (ψ : Fˣ →* Rˣ) :
    X.characterGenerator lift h1 hmul p hdim hlift ψ ∈
      Algebra.adjoin R (Set.range (X.fundamentalCoordinate p lift h1 hmul hdim hlift e)) := by
  obtain ⟨n, hn, hnq, rfl⟩ := exists_fundamentalCharacter_power p e ψ
  exact X.power_characterGenerator_mem_adjoin lift h0 h1 hmul hadd p hdim hlift e n hn hnq

end ThreeAdicPlan
