/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.LocalClassFieldTheory.IntegralNormalBasis

/-!
# The Galois-stable integral normal lattice

The R-span of the constructed integral normal basis is a free, finite,
Galois-stable submodule of the integral closure. Openness is a further
topological assertion, not part of this algebraic construction.
-/

@[expose] public noncomputable section

namespace LocalClassFieldTheory

variable (R K L : Type) [CommRing R] [IsDomain R] [Field K] [Field L]
  [Algebra R K] [IsFractionRing R K] [Algebra K L] [Algebra R L]
  [IsScalarTower R K L] [FiniteDimensional K L] [IsGalois K L]

/-- The lattice generated by the integral normal K-basis. -/
def integralNormalLattice : Submodule R L :=
  Submodule.span R (Set.range (integralNormalBasis R K L))

/-- The chosen generators form an actual R-basis of the lattice. -/
def integralNormalLatticeBasis : Module.Basis Gal(L/K) R (integralNormalLattice R K L) :=
  (integralNormalBasis R K L).restrictScalars R

/-- Lattice basis vectors retain their original values in the field. -/
@[simp] theorem integralNormalLatticeBasis_val (g : Gal(L/K)) :
    (integralNormalLatticeBasis R K L g : L) = integralNormalBasis R K L g :=
  Module.Basis.restrictScalars_apply _ _ _

/-- The lattice is contained in the actual integral closure. -/
theorem integralNormalLattice_le_integralClosure :
    integralNormalLattice R K L ≤ (integralClosure R L).toSubmodule := by
  apply Submodule.span_le.mpr
  rintro x ⟨g, rfl⟩
  exact integralNormalBasis_integral R K L g

/-- Every Galois automorphism preserves the constructed lattice. -/
theorem integralNormalLattice_action_mem (g : Gal(L/K)) (x : L)
    (hx : x ∈ integralNormalLattice R K L) : g x ∈ integralNormalLattice R K L := by
  have h : integralNormalLattice R K L ≤ (integralNormalLattice R K L).comap
      (g.restrictScalars R).toLinearMap := by
    apply Submodule.span_le.mpr
    rintro y ⟨h, rfl⟩
    change g (integralNormalBasis R K L h) ∈ integralNormalLattice R K L
    rw [integralNormalBasis_action]
    exact Submodule.subset_span ⟨g * h, rfl⟩
  exact h hx

/-- The lattice is a free R-module. -/
theorem integralNormalLattice_free : Module.Free R (integralNormalLattice R K L) :=
  Module.Free.of_basis (integralNormalLatticeBasis R K L)

/-- The lattice is finite over R. -/
theorem integralNormalLattice_finite : Module.Finite R (integralNormalLattice R K L) :=
  Module.Finite.of_basis (integralNormalLatticeBasis R K L)

end LocalClassFieldTheory
