/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.LocalClassFieldTheory.RationalTorsion

/-!
# The kernel of degree multiplication on Q/Z

The kernel is the cyclic subgroup generated by the positive fraction 1/n.
The existing rational torsion map gives an additive equivalence with Z/n
and computes its cardinality.
-/

@[expose] public noncomputable section

namespace LocalClassFieldTheory

variable (n : ℕ) [NeZero n]

/-- The actual kernel of multiplication by the positive degree. -/
def relativeRestrictionKernel : AddSubgroup (AddCircle (1 : ℚ)) :=
  (n • AddMonoidHom.id (AddCircle (1 : ℚ))).ker

omit [NeZero n] in
/-- Kernel membership is annihilation by the degree. -/
theorem mem_relativeRestrictionKernel (x : AddCircle (1 : ℚ)) :
    x ∈ relativeRestrictionKernel n ↔ n • x = 0 := Iff.rfl

/-- The positive rational torsion map has exactly the degree-multiplication kernel as image. -/
theorem relativeRestrictionKernel_eq_range :
    relativeRestrictionKernel n = (zmodToRatCircle n).range := by
  ext x
  exact (mem_range_zmodToRatCircle n x).symm

/-- The kernel is generated by the positive invariant 1/n. -/
theorem relativeRestrictionKernel_eq_zmultiples :
    relativeRestrictionKernel n =
      AddSubgroup.zmultiples (↑((1 : ℚ) / n) : AddCircle (1 : ℚ)) := by
  rw [relativeRestrictionKernel_eq_range]
  ext x
  constructor
  · rintro ⟨j, rfl⟩
    obtain ⟨k, rfl⟩ := ZMod.intCast_surjective j
    apply AddSubgroup.mem_zmultiples_iff.mpr
    refine ⟨k, ?_⟩
    rw [zmodToRatCircle_intCast, ← AddCircle.coe_zsmul]
    congr 1
    simp [zsmul_eq_mul, div_eq_mul_inv]
  · rintro ⟨k, rfl⟩
    refine ⟨(k : ZMod n), ?_⟩
    change zmodToRatCircle n (k : ZMod n) = k • (↑((1 : ℚ) / n) : AddCircle (1 : ℚ))
    rw [zmodToRatCircle_intCast, ← AddCircle.coe_zsmul]
    congr 1
    simp [zsmul_eq_mul, div_eq_mul_inv]

/-- Positive rational torsion coordinates identify the kernel with Z/n. -/
def relativeRestrictionKernelEquiv : ZMod n ≃+ relativeRestrictionKernel n :=
  AddEquiv.ofBijective
    ((zmodToRatCircle n).codRestrict (relativeRestrictionKernel n)
      (fun j => nsmul_zmodToRatCircle n j))
    ⟨fun x y h => zmodToRatCircle_injective n (congrArg Subtype.val h), fun x => by
      obtain ⟨j, hj⟩ := (mem_range_zmodToRatCircle n x.val).mpr x.property
      exact ⟨j, Subtype.ext hj⟩⟩

/-- The restriction kernel has exactly n elements. -/
theorem card_relativeRestrictionKernel : Nat.card (relativeRestrictionKernel n) = n := by
  rw [← Nat.card_congr (relativeRestrictionKernelEquiv n).toEquiv]
  exact Nat.card_zmod n

end LocalClassFieldTheory
