/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.LocalClassFieldTheory.UnramifiedPolynomial
public import Mathlib.FieldTheory.Normal.Basic
public import Mathlib.RingTheory.Localization.FractionRing

/-!
# Normality of finite unramified Henselian DVR extensions

The fraction field is generated by the integral splitting generator. It is
therefore a splitting field, giving normality without assuming it in the
residue-extension constructor.
-/

@[expose] public noncomputable section

universe u

namespace LocalClassFieldTheory

open Polynomial IsLocalRing

variable {R S K L : Type u} [CommRing R] [CommRing S]
  [Field K] [Field L] [Algebra R K] [Algebra R S] [Algebra S L]
  [IsFractionRing S L] [Algebra K L] [Algebra R L]
  [IsScalarTower R K L] [IsScalarTower R S L]

/-- An integral algebra generator also generates the extension of fraction fields. -/
theorem fraction_adjoin_eq_top (t : S) (ht : Algebra.adjoin R {t} = ⊤) :
    IntermediateField.adjoin K {algebraMap S L t} = ⊤ := by
  let E := IntermediateField.adjoin K {algebraMap S L t}
  have hmem (s : S) : algebraMap S L s ∈ E := by
    have hs : s ∈ Algebra.adjoin R {t} := ht ▸ Algebra.mem_top
    induction hs using Algebra.adjoin_induction with
    | mem x hx =>
      obtain rfl := Set.mem_singleton_iff.mp hx
      exact IntermediateField.subset_adjoin K _ (Set.mem_singleton _)
    | algebraMap r =>
      rw [← IsScalarTower.algebraMap_apply R S L, IsScalarTower.algebraMap_apply R K L]
      exact E.algebraMap_mem _
    | add x y _ _ hx hy => simpa only [map_add] using E.add_mem hx hy
    | mul x y _ _ hx hy => simpa only [map_mul] using E.mul_mem hx hy
  apply top_unique
  intro x _
  obtain ⟨a, b, _, rfl⟩ := IsFractionRing.div_surjective S x
  exact E.div_mem (hmem a) (hmem b)

variable [IsDomain R] [IsDiscreteValuationRing R]
  [IsDomain S] [IsDiscreteValuationRing S] [HenselianLocalRing S]
  [Module.Finite R S] [FaithfulSMul R S] [Algebra.FormallyUnramified R S]
  [Finite (ResidueField R)]

include R S
/-- A finite unramified Henselian DVR extension with finite residue field has normal
fraction extension. The splitting polynomial and generator are constructed. -/
theorem normal_of_unramified : Normal K L := by
  obtain ⟨P, t, hPm, _, _, ht, hgen, hsplit⟩ :=
    exists_splitting_generator (R := R) (S := S)
  let p := P.map (algebraMap R K)
  have hm : p.Monic := hPm.map _
  have hmaps : p.map (algebraMap K L) = (P.map (algebraMap R S)).map (algebraMap S L) := by
    simp only [p, map_map, ← IsScalarTower.algebraMap_eq]
  have hs : (p.map (algebraMap K L)).Splits := by
    rw [hmaps]
    exact hsplit.map _
  have hroot : algebraMap S L t ∈ p.rootSet L := by
    rw [hm.mem_rootSet, ← eval_map_algebraMap, hmaps, eval_map_apply,
      eval_map_algebraMap, ht, map_zero]
  have htop : IntermediateField.adjoin K (p.rootSet L) = ⊤ := by
    apply top_unique
    rw [← fraction_adjoin_eq_top (K := K) t hgen]
    exact IntermediateField.adjoin.mono K _ _ (Set.singleton_subset_iff.mpr hroot)
  have : p.IsSplittingField K L := isSplittingField_iff_intermediateField.mpr ⟨hs, htop⟩
  exact Normal.of_isSplittingField p

end LocalClassFieldTheory
