/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.CubicTorsionQuotientPoints
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.Data.Set.Card
public import Mathlib.Data.Setoid.Basic
/-! # Prime-level scalar quotient and cyclic subgroups

Over an algebraically closed field, points of the actual scalar quotient
are equivalent to subgroups of order p in the elliptic curve group. The
equivalence takes a generator to the subgroup it generates. This remains
a parameter scheme for a fixed Weierstrass model; coordinate changes and
cusp compactification are separate constructions.
-/

@[expose] public noncomputable section
namespace WeierstrassCurve.CubicCharts

/-- Prime-order generators span the same subgroup exactly when related by a unit scalar. -/
theorem primeGenerator_subgroup_fiber {G : Type*} [AddCommGroup G]
    (p : ℕ) [Fact p.Prime] {P Q : G} (hP : addOrderOf P = p) (hQ : addOrderOf Q = p) :
    AddSubgroup.zmultiples P = AddSubgroup.zmultiples Q ↔
      ∃ a : (ZMod p)ˣ, P = a.val.val • Q := by
  classical
  have hp := (Fact.out : p.Prime)
  have hP0 : P ≠ 0 := by
    intro h
    apply hp.ne_one
    simpa [h] using hP.symm
  have : Finite (AddSubgroup.zmultiples Q) :=
    Nat.finite_of_card_ne_zero (by rw [Nat.card_zmultiples, hQ]; exact hp.ne_zero)
  constructor
  · intro h
    have hm : P ∈ AddSubgroup.zmultiples Q := h ▸ AddSubgroup.mem_zmultiples P
    have hfin : IsOfFinAddOrder Q := by
      rw [← addOrderOf_pos_iff, hQ]
      exact hp.pos
    rw [hfin.mem_zmultiples_iff_mem_range_addOrderOf, Finset.mem_image] at hm
    obtain ⟨k, hk, hkp⟩ := hm
    have hlt : k < p := by simpa [hQ] using hk
    have hk0 : k ≠ 0 := by intro h; apply hP0; rw [← hkp, h, zero_nsmul]
    have hz : (k : ZMod p) ≠ 0 := by
      intro h
      have hh := congrArg ZMod.val h
      apply hk0
      simpa [ZMod.val_natCast_of_lt hlt] using hh
    refine ⟨Units.mk0 (k : ZMod p) hz, ?_⟩
    simpa [ZMod.val_natCast_of_lt hlt] using hkp.symm
  · rintro ⟨a, ha⟩
    apply SetLike.coe_injective
    apply Set.eq_of_subset_of_ncard_le
    · exact AddSubgroup.zmultiples_le.mpr (ha ▸
        (AddSubgroup.zmultiples Q).nsmul_mem (AddSubgroup.mem_zmultiples Q) _)
    · change Nat.card (AddSubgroup.zmultiples Q) ≤ Nat.card (AddSubgroup.zmultiples P)
      simp [Nat.card_zmultiples, hP, hQ]
    · exact Set.toFinite _


/-- A subgroup of prime cardinality has a generator of that prime order. -/
theorem primeSubgroup_has_generator {G : Type*} [AddCommGroup G]
    (p : ℕ) [Fact p.Prime] (H : AddSubgroup G) (hH : Nat.card H = p) :
    ∃ P : G, addOrderOf P = p ∧ AddSubgroup.zmultiples P = H := by
  let : IsAddCyclic H := isAddCyclic_of_prime_card hH
  obtain ⟨P, hP⟩ := isAddCyclic_iff_exists_zmultiples_eq_top.mp
    (inferInstance : IsAddCyclic H)
  refine ⟨P.val, ?_, ?_⟩
  · rw [AddSubgroup.addOrderOf_coe, addOrderOf_eq_card_of_zmultiples_eq_top hP, hH]
  · apply le_antisymm
    · exact AddSubgroup.zmultiples_le.mpr P.property
    · intro x hx
      have hx' : (⟨x, hx⟩ : H) ∈ AddSubgroup.zmultiples P := by rw [hP]; trivial
      obtain ⟨m, hm⟩ := hx'
      exact ⟨m, congrArg Subtype.val hm⟩


open AlgebraicGeometry CategoryTheory
universe u
variable {R : Type u} [CommRing R] [IsNoetherianRing R] [IsDomain R]
variable (W : WeierstrassCurve R) [W.IsElliptic]
variable (p : ℕ) [Fact p.Prime] [NeZero p] [Fact (IsUnit (p : R))]
variable (K : Type u) [Field K] [Algebra R K] [DecidableEq K]

omit [DecidableEq K] in
/-- The field-valued fibers may be expressed using the forward scalar action. -/
theorem scalarQuotientFieldPoint_fiber_hom
    (x y : pointSource K ⟶ nonzeroTorsionModel W p) :
    x ≫ scalarQuotientMap W p = y ≫ scalarQuotientMap W p ↔
      ∃ a : (ZMod p)ˣ, x = y ≫ (nonzeroTorsionScalarAction W p a).hom := by
  constructor
  · intro h
    obtain ⟨a, ha⟩ := (scalarQuotientFieldPoint_fiber W p K x y).mp h
    refine ⟨a⁻¹, ?_⟩
    rw [map_inv]
    exact ha
  · rintro ⟨a, rfl⟩
    rw [Category.assoc, scalarQuotientMap_invariant]

/-- The subgroup generated by an actual nonzero prime-torsion point. -/
def primePointSubgroup (x : pointSource K ⟶ nonzeroTorsionModel W p) :
    {H : AddSubgroup (W.map (algebraMap R K)).toAffine.Point // Nat.card H = p} :=
  ⟨AddSubgroup.zmultiples (primeTorsionClassicalEquiv W p Fact.out K x).val, by
    rw [Nat.card_zmultiples]
    exact (primeTorsionClassicalEquiv W p Fact.out K x).property⟩

/-- The quotient identifies exactly the points generating the same prime-order subgroup. -/
theorem primePointSubgroup_fiber
    (x y : pointSource K ⟶ nonzeroTorsionModel W p) :
    x ≫ scalarQuotientMap W p = y ≫ scalarQuotientMap W p ↔
      primePointSubgroup W p K x = primePointSubgroup W p K y := by
  rw [scalarQuotientFieldPoint_fiber_hom, Subtype.ext_iff]
  change (∃ a : (ZMod p)ˣ, x = y ≫ (nonzeroTorsionScalarAction W p a).hom) ↔
    AddSubgroup.zmultiples (primeTorsionClassicalEquiv W p Fact.out K x).val =
      AddSubgroup.zmultiples (primeTorsionClassicalEquiv W p Fact.out K y).val
  rw [primeGenerator_subgroup_fiber p
    (primeTorsionClassicalEquiv W p Fact.out K x).property
    (primeTorsionClassicalEquiv W p Fact.out K y).property]
  apply exists_congr
  intro a
  have hc : (primeTorsionClassicalEquiv W p Fact.out K
      (y ≫ (nonzeroTorsionScalarAction W p a).hom)).val =
      a.val.val • (primeTorsionClassicalEquiv W p Fact.out K y).val :=
    nonzeroTorsionScalarIso_classical W p Fact.out a K y
  rw [← hc]
  exact (primeTorsionClassicalEquiv W p Fact.out K).injective.eq_iff.symm.trans
    Subtype.ext_iff

/-- Every prime-order subgroup of field-valued points has a point on the generator scheme. -/
theorem primePointSubgroup_surjective :
    Function.Surjective (primePointSubgroup W p K) := by
  rintro ⟨H, hH⟩
  obtain ⟨P, hP, hPH⟩ := primeSubgroup_has_generator p H hH
  refine ⟨(primeTorsionClassicalEquiv W p Fact.out K).symm ⟨P, hP⟩, ?_⟩
  apply Subtype.ext
  simpa only [primePointSubgroup, Equiv.apply_symm_apply] using hPH


/-- Geometric points of the scalar quotient classify prime-order subgroups. -/
def scalarQuotientPrimeSubgroupEquiv [IsAlgClosed K] :
    (pointSource K ⟶ scalarQuotientModel W p) ≃
      {H : AddSubgroup (W.map (algebraMap R K)).toAffine.Point // Nat.card H = p} :=
  (Setoid.quotientKerEquivOfSurjective _ (scalarQuotientFieldPoint_surjective W p K)).symm.trans
    ((Quotient.congrRight (primePointSubgroup_fiber W p K)).trans
      (Setoid.quotientKerEquivOfSurjective _ (primePointSubgroup_surjective W p K)))


/-- The geometric classification sends each generator to the subgroup it spans. -/
theorem scalarQuotientPrimeSubgroupEquiv_generator [IsAlgClosed K]
    (x : pointSource K ⟶ nonzeroTorsionModel W p) :
    scalarQuotientPrimeSubgroupEquiv W p K (x ≫ scalarQuotientMap W p) =
      primePointSubgroup W p K x := by
  change primePointSubgroup W p K
    (Function.surjInv (scalarQuotientFieldPoint_surjective W p K)
      (x ≫ scalarQuotientMap W p)) = primePointSubgroup W p K x
  apply (primePointSubgroup_fiber W p K _ x).mp
  exact Function.rightInverse_surjInv (scalarQuotientFieldPoint_surjective W p K) _

end WeierstrassCurve.CubicCharts

