/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.MultiplicationInfinity
public import Mathlib.LinearAlgebra.Dimension.Localization
public import Mathlib.FieldTheory.Relrank
/-!
# Degree of the x-coordinate subfield

The function field is quadratic over the field generated by its x-coordinate.
-/

@[expose] public section

open Polynomial IntermediateField
open scoped WeierstrassCurve.Affine
namespace WeierstrassCurve.Affine.FunctionField
variable {F : Type*} [Field F] (W : Affine F)
/-- The intermediate field generated by the generic x-coordinate. -/
noncomputable def xField : IntermediateField F W.FunctionField := F⟮genericX W⟯
/-- Polynomials act on the x-coordinate subfield by evaluation at x. -/
noncomputable instance : Algebra F[X] (xField W) :=
  (aeval (⟨genericX W, mem_adjoin_simple_self F _⟩ : xField W)).toAlgebra
/-- Evaluation at x agrees with the polynomial action on the function field. -/
instance : IsScalarTower F[X] (xField W) W.FunctionField := by
  apply IsScalarTower.of_algebraMap_eq'
  apply RingHom.ext
  intro p
  change algebraMap F[X] W.FunctionField p = (xField W).val (aeval _ p)
  rw [← aeval_algHom_apply]
  exact (aeval_genericX W p).symm
/-- The generic x-coordinate is transcendental, so polynomial evaluation is faithful. -/
instance : FaithfulSMul F[X] (xField W) := by
  apply (faithfulSMul_iff_algebraMap_injective F[X] (xField W)).mpr
  intro p q he
  apply transcendental_iff_injective.mp (genericX_transcendental W)
  have hh := congrArg (xField W).val he
  change (xField W).val (aeval _ p) = (xField W).val (aeval _ q) at hh
  rw [← aeval_algHom_apply, ← aeval_algHom_apply] at hh
  exact hh
/-- The x-coordinate subfield is the fraction field of its polynomial subring. -/
instance : IsFractionRing F[X] (xField W) := by
  apply IsFractionRing.of_field
  intro f
  obtain ⟨p, q, he⟩ := (mem_adjoin_simple_iff F (f : W.FunctionField)).mp f.property
  refine ⟨p, q, ?_⟩
  apply Subtype.ext
  change (f : W.FunctionField) = (xField W).val (aeval _ p) / (xField W).val (aeval _ q)
  rw [← aeval_algHom_apply, ← aeval_algHom_apply]
  exact he
/-- The function field has degree two over its x-coordinate subfield. -/
theorem finrank_xField : Module.finrank (xField W) W.FunctionField = 2 := by
  rw [IsFractionRing.finrank_eq F[X] (xField W) W.CoordinateRing W.FunctionField]
  exact Module.finrank_eq_card_basis (CoordinateRing.basis W)
end WeierstrassCurve.Affine.FunctionField
