/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.FunctionFieldDegree
/-!
# A degree bound for multiplication on the function field

The division-polynomial relation bounds the degree on x-coordinate subfields.
The two quadratic extensions cancel in the tower, giving degree at most n².
-/

@[expose] public section

open Polynomial IntermediateField
open scoped WeierstrassCurve.Affine
namespace WeierstrassCurve.Affine.FunctionField
variable {F : Type*} [Field F] [IsAlgClosed F]
  (W : Affine F) [W.IsElliptic]
/-- The intermediate field generated by the multiplied x-coordinate. -/
noncomputable def multiplicationXField (n : ℕ) (hn : n ≠ 0) :
    IntermediateField F W.FunctionField :=
  F⟮nsmulPullback W n hn (genericX W)⟯
/-- The division-polynomial relation over the multiplied x-coordinate field. -/
noncomputable def multiplicationPolynomial (n : ℕ) (hn : n ≠ 0) :
    (multiplicationXField W n hn)[X] :=
  (W.Φ n).map (algebraMap F _) -
    C (⟨nsmulPullback W n hn (genericX W), mem_adjoin_simple_self F _⟩ :
      multiplicationXField W n hn) *
      (W.ΨSq n).map (algebraMap F _)
/-- The multiplication relation has degree n². -/
theorem multiplicationPolynomial_natDegree (n : ℕ) (hn : n ≠ 0) :
    (multiplicationPolynomial W n hn).natDegree = n ^ 2 := by
  have hlt : (C (⟨nsmulPullback W n hn (genericX W), mem_adjoin_simple_self F _⟩ :
      multiplicationXField W n hn) * (W.ΨSq n).map (algebraMap F _)).natDegree <
      ((W.Φ n).map (algebraMap F (multiplicationXField W n hn))).natDegree := by
    apply lt_of_le_of_lt (natDegree_C_mul_le _ _)
    rw [natDegree_map, natDegree_map, W.natDegree_Φ]
    have hh := W.natDegree_ΨSq_le n
    simp only [Int.natAbs_natCast] at *
    exact lt_of_le_of_lt hh (Nat.sub_lt (pow_pos (Nat.pos_of_ne_zero hn) 2) zero_lt_one)
  rw [multiplicationPolynomial, natDegree_sub_eq_left_of_natDegree_lt hlt,
    natDegree_map, W.natDegree_Φ]
  simp
/-- The generic x-coordinate satisfies the multiplication relation. -/
theorem multiplicationPolynomial_aeval (n : ℕ) (hn : n ≠ 0) :
    aeval (genericX W) (multiplicationPolynomial W n hn) = 0 := by
  simp only [multiplicationPolynomial, aeval_sub, aeval_map_algebraMap, map_mul, aeval_C,
    IntermediateField.algebraMap_apply]
  rw [nsmulPullback_genericX_eq W n hn, div_mul_cancel₀]
  · exact sub_self _
  · simpa only [map_zero] using (transcendental_iff_injective.mp (genericX_transcendental W)).ne
      (W.ΨSq_ne_zero_of_isElliptic (Int.natCast_ne_zero.mpr hn))
/-- The multiplied x-coordinate is rational in the original x-coordinate. -/
theorem multiplicationXField_le (n : ℕ) (hn : n ≠ 0) : multiplicationXField W n hn ≤ xField W := by
  apply adjoin_simple_le_iff.mpr
  rw [nsmulPullback_genericX_eq]
  apply (xField W).div_mem
  all_goals
    apply algebra_adjoin_le_adjoin F {genericX W}
    rw [Algebra.adjoin_singleton_eq_range_aeval]
    exact ⟨_, rfl⟩

/-- The degree between x-coordinate fields is positive and at most n². -/
theorem multiplicationXField_relfinrank_bounds (n : ℕ) (hn : n ≠ 0) :
    0 < relfinrank (multiplicationXField W n hn) (xField W) ∧
      relfinrank (multiplicationXField W n hn) (xField W) ≤ n ^ 2 := by
  let B := multiplicationXField W n hn
  have hp0 : multiplicationPolynomial W n hn ≠ 0 := ne_zero_of_natDegree_gt (by
    rw [multiplicationPolynomial_natDegree]; exact pow_pos (Nat.pos_of_ne_zero hn) 2)
  have hi : IsIntegral B (genericX W) :=
    (show IsAlgebraic B (genericX W) from
      ⟨multiplicationPolynomial W n hn, hp0, multiplicationPolynomial_aeval W n hn⟩).isIntegral
  have hgen : B⟮genericX W⟯ =
      (multiplicationXField W n hn).extendScalars (multiplicationXField_le W n hn) := by
    apply restrictScalars_injective F
    rw [restrictScalars_adjoin_eq_sup]
    exact sup_eq_right.mpr (multiplicationXField_le W n hn)
  rw [relfinrank_eq_finrank_of_le (multiplicationXField_le W n hn), ← hgen, adjoin.finrank hi]
  refine ⟨minpoly.natDegree_pos hi, ?_⟩
  exact (natDegree_le_of_dvd
    (minpoly.dvd B (genericX W) (multiplicationPolynomial_aeval W n hn)) hp0).trans_eq
    (multiplicationPolynomial_natDegree W n hn)
/-- The multiplied x-coordinate field is the image of the x-coordinate field. -/
theorem multiplicationXField_eq_map (n : ℕ) (hn : n ≠ 0) :
    multiplicationXField W n hn = (xField W).map (nsmulPullback W n hn) := by
  rw [xField, adjoin_map, Set.image_singleton]
  rfl

/-- The multiplication image has finite positive index at most n². -/
theorem finrank_nsmulPullback_bounds (n : ℕ) (hn : n ≠ 0) :
    0 < Module.finrank (nsmulPullback W n hn).fieldRange W.FunctionField ∧
      Module.finrank (nsmulPullback W n hn).fieldRange W.FunctionField ≤ n ^ 2 := by
  have ht := relfinrank_mul_finrank_top (multiplicationXField_le W n hn)
  rw [finrank_xField W] at ht
  have hle : (xField W).map (nsmulPullback W n hn) ≤
      (⊤ : IntermediateField F W.FunctionField).map (nsmulPullback W n hn) :=
    map_mono _ le_top
  have hm := relfinrank_mul_finrank_top hle
  rw [relfinrank_map_map, relfinrank_top_right, finrank_xField W,
    ← multiplicationXField_eq_map] at hm
  have hmap : (⊤ : IntermediateField F W.FunctionField).map (nsmulPullback W n hn) =
      (nsmulPullback W n hn).fieldRange := by
    ext x
    simp [IntermediateField.mem_map, AlgHom.mem_fieldRange]
  rw [hmap] at hm
  have he : Module.finrank (nsmulPullback W n hn).fieldRange W.FunctionField =
      relfinrank (multiplicationXField W n hn) (xField W) := by omega
  rw [he]
  exact multiplicationXField_relfinrank_bounds W n hn
end WeierstrassCurve.Affine.FunctionField
