/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.Multiplication
public import FLT.EllipticCurve.TorsionFiber

/-!
# Extracting roots from principal multiplication-fiber ideals

Generators of the same fractional ideal differ by a ground-field constant.
Over an algebraically closed field this constant can be absorbed into an nth
root. Together with principality of the fiber difference, this reduces the
root construction to the fractional-ideal pullback identity stated in
`exists_pow_eq_pullback_of_span_eq_fiberIdeal`.
-/

@[expose] public section

open scoped nonZeroDivisors
namespace WeierstrassCurve.Affine.FunctionField
variable {F : Type*} [Field F] {W : WeierstrassCurve.Affine F}
/-- Rational functions with the same affine principal fractional ideal differ
by a nonzero ground-field constant. -/
theorem exists_eq_const_mul_of_span_eq {f g : W.FunctionField}
    (h : FractionalIdeal.spanSingleton W.CoordinateRing⁰ f =
      FractionalIdeal.spanSingleton W.CoordinateRing⁰ g) :
    ∃ c : F, c ≠ 0 ∧ g = algebraMap F W.FunctionField c * f := by
  obtain ⟨u, hu⟩ := FractionalIdeal.spanSingleton_eq_spanSingleton.mp h
  obtain ⟨c, hc, he⟩ := CoordinateRing.exists_eq_algebraMap_of_isUnit u.isUnit
  refine ⟨c, hc, ?_⟩
  rw [← hu, Units.smul_def, Algebra.smul_def]
  change algebraMap W.CoordinateRing W.FunctionField (u : W.CoordinateRing) * f = _
  rw [← he, ← IsScalarTower.algebraMap_apply]

/-- Over an algebraically closed ground field, equality of the principal ideals
of g^n and f gives an exact nth root of f after rescaling g. -/
theorem exists_pow_eq_of_span_eq [IsAlgClosed F] {n : ℕ} (hn : n ≠ 0)
    {f g : W.FunctionField} (hg : g ≠ 0)
    (h : FractionalIdeal.spanSingleton W.CoordinateRing⁰ (g ^ n) =
      FractionalIdeal.spanSingleton W.CoordinateRing⁰ f) :
    ∃ r : W.FunctionField, r ≠ 0 ∧ r ^ n = f := by
  obtain ⟨c, hc, he⟩ := exists_eq_const_mul_of_span_eq h
  obtain ⟨a, ha⟩ := IsAlgClosed.exists_pow_nat_eq c (Nat.pos_of_ne_zero hn)
  have ha0 : a ≠ 0 := by intro hz; rw [hz, zero_pow hn] at ha; exact hc ha.symm
  refine ⟨algebraMap F W.FunctionField a * g,
    mul_ne_zero ((map_ne_zero (algebraMap F W.FunctionField)).mpr ha0) hg, ?_⟩
  rw [mul_pow, ← map_pow, ha, ← he]

/-- A principal fractional ideal whose nth power is generated by f supplies
an exact nth root of f over an algebraically closed ground field. -/
theorem exists_pow_eq_of_principal_ideal [IsAlgClosed F] {n : ℕ} (hn : n ≠ 0)
    (I : (FractionalIdeal W.CoordinateRing⁰ W.FunctionField)ˣ)
    (hI : ClassGroup.mk W.FunctionField I = 1) {f : W.FunctionField}
    (hf : FractionalIdeal.spanSingleton W.CoordinateRing⁰ f =
      (I : FractionalIdeal W.CoordinateRing⁰ W.FunctionField) ^ n) :
    ∃ g : W.FunctionField, g ≠ 0 ∧ g ^ n = f := by
  obtain ⟨g, hg, he⟩ := (Point.exists_generator_iff I).mpr hI
  apply exists_pow_eq_of_span_eq hn hg
  rw [← FractionalIdeal.spanSingleton_pow, he, hf]

variable [DecidableEq F] [W.IsElliptic] [IsAlgClosed F]

/-- The multiplication pullback has an nth root if its principal fractional
ideal is the nth power of the difference of the two multiplication fibers.
The hypothesis is the divisor transport step; it is not proved here. -/
theorem exists_pow_eq_pullback_of_span_eq_fiberIdeal {n : ℕ} (hn : n ≠ 0)
    (hchar : (n : F) ≠ 0) (Q : W.Point) (hQ : n • (n • Q) = 0)
    (f : W.FunctionField)
    (hf : FractionalIdeal.spanSingleton W.CoordinateRing⁰ (nsmulPullback W n hn f) =
      (Point.fiberIdeal W n hn Q : FractionalIdeal W.CoordinateRing⁰ W.FunctionField) ^ n) :
    ∃ g : W.FunctionField, g ≠ 0 ∧ g ^ n = nsmulPullback W n hn f := by
  obtain ⟨g, hg, he⟩ := Point.exists_generator_fiberIdeal W hn hchar Q hQ
  apply exists_pow_eq_of_span_eq hn hg
  rw [← FractionalIdeal.spanSingleton_pow, he, hf]

end WeierstrassCurve.Affine.FunctionField
