/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.OddTorsionModel
public import FLT.GroupScheme.FiniteFlat

/-!
# The coordinate order of translated odd torsion

Evaluate the affine envelope on odd torsion translated by an integral nonzero
two-torsion point. Its image is a finite flat algebra over a Dedekind domain.
This constructs the underlying integral algebra, without asserting that
comultiplication preserves it.
-/

@[expose] public section

open Polynomial
namespace WeierstrassCurve

/-- Affine coordinates of a point, with the dummy value `(0,0)` at infinity.
Applications to a multiplication fibre prove that infinity cannot occur. -/
def Affine.Point.coordinates {k : Type*} [Field k] {E : WeierstrassCurve k} :
    E.toAffine.Point → k × k
  | .zero => (0, 0)
  | .some x y _ => (x, y)

universe u
variable {R k : Type u} [CommRing R] [Field k] [Algebra R k] [DecidableEq k]
    (W : WeierstrassCurve R) {n : ℕ} (hn : Odd n) (ξ η : R)
    (hT : (W.map (algebraMap R k)).toAffine.Nonsingular
      (algebraMap R k ξ) (algebraMap R k η))
    (htwo : 2 • Affine.Point.some _ _ hT = 0)

/-- The odd-torsion point set on the chosen geometric field. -/
abbrev oddTorsionPointSet (n : ℕ) :=
  AddSubgroup.torsionBy (W.map (algebraMap R k)).toAffine.Point (n : ℤ)

/-- The coordinates of an odd-torsion point translated into the affine chart. -/
def translatedTorsionCoordinates (P : W.oddTorsionPointSet (k := k) n) : k × k :=
  (P.val + Affine.Point.some _ _ hT).coordinates

include hn htwo in
/-- Translated odd-torsion coordinates satisfy the envelope's equations. -/
theorem translatedTorsionCoordinates_relations (P : W.oddTorsionPointSet (k := k) n) :
    aeval (W.translatedTorsionCoordinates ξ η hT P).1
      (W.multiplicationFiberPolynomial n ξ) = 0 ∧
    (W.map (algebraMap R k)).toAffine.Equation
      (W.translatedTorsionCoordinates ξ η hT P).1
      (W.translatedTorsionCoordinates ξ η hT P).2 := by
  obtain ⟨x, y, h, he, hx⟩ :=
    (W.map (algebraMap R k)).exists_affine_odd_torsion_translate hn hT htwo P.val (by
      simpa only [oddTorsionPointSet, AddSubgroup.torsionBy.nsmul_iff] using P.property)
  simp only [translatedTorsionCoordinates, he, Affine.Point.coordinates]
  refine ⟨?_, h.1⟩
  simpa only [map_multiplicationFiberPolynomial, Polynomial.IsRoot,
    eval_map_algebraMap] using hx

/-- Evaluation of the finite free envelope on all translated odd-torsion points. -/
noncomputable def translatedTorsionEvaluation :
    W.torsionEnvelope n ξ →ₐ[R] (W.oddTorsionPointSet (k := k) n → k) :=
  AlgHom.pi fun P => W.torsionEnvelopeLift n ξ
    (W.translatedTorsionCoordinates ξ η hT P).1
    (W.translatedTorsionCoordinates ξ η hT P).2
    (W.translatedTorsionCoordinates_relations hn ξ η hT htwo P).1
    (W.translatedTorsionCoordinates_relations hn ξ η hT htwo P).2

/-- The integral algebra of functions generated by translated torsion coordinates. -/
noncomputable def oddTorsionCoordinateOrder :
    Subalgebra R (W.oddTorsionPointSet (k := k) n → k) :=
  (W.translatedTorsionEvaluation hn ξ η hT htwo).range

/-- The translated coordinate order is finite flat over a Dedekind domain.
This is a statement about its underlying algebra; a Hopf structure still
requires compatibility with addition of torsion points. -/
theorem finiteFlat_oddTorsionCoordinateOrder [IsDedekindDomain R]
    [Module.IsTorsionFree R k] :
    HopfAlgebra.IsFiniteFlat R (W.oddTorsionCoordinateOrder hn ξ η hT htwo) := by
  have hn0 : (n : ℤ) ≠ 0 := by
    obtain ⟨m, hm⟩ := hn
    omega
  let := W.finite_torsionEnvelope hn0 ξ
  let := W.flat_torsionEnvelope hn0 ξ
  have hA : HopfAlgebra.IsFiniteFlat R (W.torsionEnvelope n ξ) := ⟨⟩
  exact hA.range (W.translatedTorsionEvaluation hn ξ η hT htwo)

end WeierstrassCurve
