/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.CoordinateRing

/-!
# Functions attached to torsion points

If an affine point `P` is killed by `n`, its point ideal raised to the `n`th power
is generated by a nonzero coordinate-ring element; the converse also holds.
For positive `n`, this function vanishes only at `P` on the affine curve, and
normalizing its value to one at any other affine point makes it unique.
The defining ideals commute with field homomorphisms. The chord/tangent and
vertical-line identities give product relations for these functions.

These results are inputs to a divisor construction of the Weil pairing. The
order at infinity, evaluation on translated divisors, reciprocity and the
pairing laws are separate obligations.
-/

@[expose] public section

open scoped nonZeroDivisors
open Polynomial

namespace WeierstrassCurve.Affine.Point

variable {F : Type*} [Field F] [DecidableEq F] {W : WeierstrassCurve.Affine F}

/-- The `n`th power of the point ideal of an affine `n`-torsion point has a
nonzero generator in the coordinate ring. -/
theorem exists_torsionFunction {x y : F} (h : W.Nonsingular x y) (n : ℕ)
    (hP : n • (some x y h : W.Point) = 0) :
    ∃ f : W.CoordinateRing, f ≠ 0 ∧
      CoordinateRing.XYIdeal W x (C y) ^ n = Ideal.span {f} := by
  have hclass : ClassGroup.mk W.FunctionField (CoordinateRing.XYIdeal' h ^ n) = 1 := by
    rw [map_pow]
    change n • toClass (some x y h) = 0
    rw [← map_nsmul, hP]
    exact toClass_zero
  apply (ClassGroup.mk_eq_one_of_coe_ideal (I := CoordinateRing.XYIdeal' h ^ n) ?_).mp hclass
  rw [Units.val_pow_eq_pow_val, CoordinateRing.XYIdeal'_eq, FractionalIdeal.coeIdeal_pow]

/-- An affine point is killed by `n` exactly when its point ideal to the `n`th
power has a nonzero generator. -/
theorem nsmul_eq_zero_iff_exists_torsionFunction {x y : F} (h : W.Nonsingular x y) (n : ℕ) :
    n • (some x y h : W.Point) = 0 ↔
    ∃ f : W.CoordinateRing, f ≠ 0 ∧
      CoordinateRing.XYIdeal W x (C y) ^ n = Ideal.span {f} := by
  refine ⟨exists_torsionFunction h n, ?_⟩
  intro hf
  apply toClass_injective
  rw [map_nsmul, toClass_zero]
  change ClassGroup.mk W.FunctionField (CoordinateRing.XYIdeal' h) ^ n = 1
  rw [← map_pow]
  apply (ClassGroup.mk_eq_one_of_coe_ideal (I := CoordinateRing.XYIdeal' h ^ n) ?_).mpr hf
  rw [Units.val_pow_eq_pow_val, CoordinateRing.XYIdeal'_eq, FractionalIdeal.coeIdeal_pow]

end WeierstrassCurve.Affine.Point

namespace WeierstrassCurve.Affine.CoordinateRing

variable {F : Type*} [Field F] {W : WeierstrassCurve.Affine F}

/-- A generator of a positive power of a point ideal vanishes at exactly that
affine point. This identifies the affine support of a torsion function. -/
theorem evalEval_eq_zero_iff_of_torsionFunction {x y x' y' : F} (h : W.Equation x' y')
    {n : ℕ} (hn : n ≠ 0) {f : W.CoordinateRing} (hf : XYIdeal W x (C y) ^ n = Ideal.span {f}) :
    AdjoinRoot.evalEval h f = 0 ↔ x = x' ∧ y = y' := by
  have hker : RingHom.ker (AdjoinRoot.evalEval h) = XYIdeal W x' (C y') := by
    ext a
    exact evalEval_eq_zero_iff h a
  have : (XYIdeal W x' (C y')).IsPrime := hker ▸ RingHom.ker_isPrime _
  rw [evalEval_eq_zero_iff, ← Ideal.span_singleton_le_iff_mem, ← hf,
    Ideal.IsPrime.pow_le_iff hn, XYIdeal_le_XYIdeal_iff h]

/-- Applying a field homomorphism preserves the defining ideal of a torsion function. -/
theorem map_torsionFunction {L : Type*} [Field L] (φ : F →+* L)
    {x y : F} {n : ℕ} {f : W.CoordinateRing}
    (hf : XYIdeal W x (C y) ^ n = Ideal.span {f}) :
    XYIdeal (W.map φ) (φ x) (C (φ y)) ^ n = Ideal.span {map W φ f} := by
  rw [← map_XYIdeal, ← Ideal.map_pow, hf, Ideal.map_span, Set.image_singleton]

/-- The chord or tangent relation gives the product identity for torsion functions
at two points and their sum, up to a nonzero ground-field scalar. -/
theorem torsionFunction_add_relation [DecidableEq F] {x₁ y₁ x₂ y₂ : F}
    (h₁ : W.Equation x₁ y₁) (h₂ : W.Equation x₂ y₂)
    (hxy : ¬(x₁ = x₂ ∧ y₁ = W.negY x₂ y₂)) (n : ℕ)
    {f₁ f₂ f₃ : W.CoordinateRing}
    (hf₁ : XYIdeal W x₁ (C y₁) ^ n = Ideal.span {f₁})
    (hf₂ : XYIdeal W x₂ (C y₂) ^ n = Ideal.span {f₂})
    (hf₃ : XYIdeal W (W.addX x₁ x₂ (W.slope x₁ x₂ y₁ y₂))
      (C (W.addY x₁ x₂ y₁ (W.slope x₁ x₂ y₁ y₂))) ^ n = Ideal.span {f₃}) :
    ∃ c : F, c ≠ 0 ∧
      YClass W (linePolynomial x₁ y₁ (W.slope x₁ x₂ y₁ y₂)) ^ n * f₃ =
        c • (XClass W (W.addX x₁ x₂ (W.slope x₁ x₂ y₁ y₂)) ^ n * (f₁ * f₂)) := by
  have hh := congrArg (fun I : Ideal W.CoordinateRing => I ^ n) (XYIdeal_mul_XYIdeal h₁ h₂ hxy)
  simp only [mul_pow, XIdeal, YIdeal, Ideal.span_singleton_pow, hf₁, hf₂, hf₃,
    Ideal.span_singleton_mul_span_singleton] at hh
  exact exists_eq_smul_of_span_eq hh

/-- The torsion functions at a point and its inverse multiply to a scalar
multiple of the corresponding vertical-line function to the `n`th power. -/
theorem torsionFunction_neg_relation {x y : F} (h : W.Nonsingular x y) (n : ℕ)
    {f g : W.CoordinateRing}
    (hf : XYIdeal W x (C y) ^ n = Ideal.span {f})
    (hg : XYIdeal W x (C (W.negY x y)) ^ n = Ideal.span {g}) :
    ∃ c : F, c ≠ 0 ∧ g * f = c • (XClass W x) ^ n := by
  have hh := congrArg (fun I : Ideal W.CoordinateRing => I ^ n) (XYIdeal_neg_mul h)
  simp only [mul_pow, XIdeal, Ideal.span_singleton_pow, hf, hg,
    Ideal.span_singleton_mul_span_singleton] at hh
  exact exists_eq_smul_of_span_eq hh.symm

end WeierstrassCurve.Affine.CoordinateRing

namespace WeierstrassCurve.Affine.Point

open CoordinateRing

variable {F : Type*} [Field F] [DecidableEq F] {W : WeierstrassCurve.Affine F}

/-- A torsion function has a unique generator normalized to one at any other
affine point. No choice of a scalar remains after this normalization. -/
theorem existsUnique_normalized_torsionFunction {x y x' y' : F} (hP : W.Nonsingular x y)
    {n : ℕ} (hn : n ≠ 0)
    (hPn : n • (some x y hP : W.Point) = 0) (hQ : W.Equation x' y')
    (hPQ : ¬(x = x' ∧ y = y')) :
    ∃! f : W.CoordinateRing,
      XYIdeal W x (C y) ^ n = Ideal.span {f} ∧ AdjoinRoot.evalEval hQ f = 1 := by
  obtain ⟨f, _, hf⟩ := exists_torsionFunction hP n hPn
  have hQf : AdjoinRoot.evalEval hQ f ≠ 0 :=
    fun hz => hPQ ((evalEval_eq_zero_iff_of_torsionFunction hQ hn hf).mp hz)
  have hs : XYIdeal W x (C y) ^ n =
      Ideal.span {(AdjoinRoot.evalEval hQ f)⁻¹ • f} := by
    rw [Algebra.smul_def,
      Ideal.span_singleton_mul_left_unit ((isUnit_iff_ne_zero.mpr (inv_ne_zero hQf)).map
        (algebraMap F W.CoordinateRing))]
    exact hf
  have he : AdjoinRoot.evalEval hQ ((AdjoinRoot.evalEval hQ f)⁻¹ • f) = 1 := by
    rw [CoordinateRing.evalEval_smul, inv_mul_cancel₀ hQf]
  exact ⟨_, ⟨hs, he⟩, fun g hg =>
    CoordinateRing.eq_of_span_eq_of_evalEval_eq_one (hg.1.symm.trans hs) hQ hg.2 he⟩

end WeierstrassCurve.Affine.Point
