/-
Copyright (c) 2026 krandder. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: krandder
-/
module

public import FLT.EllipticCurve.CoordinateRing

/-!
# Functions attached to torsion points

If an affine point `P` is killed by `n`, its point ideal raised to the `n`th power
is generated by a nonzero coordinate-ring element. This is an input to a
divisor construction of the Weil pairing. Evaluation on translated divisors,
reciprocity and the pairing laws are separate obligations.
-/

@[expose] public section

open scoped nonZeroDivisors
open Polynomial

namespace WeierstrassCurve.Affine.Point

variable {F : Type*} [Field F] [DecidableEq F] {W : WeierstrassCurve.Affine F}

/-- The `n`th power of the point ideal of an affine `n`-torsion point has a
nonzero generator in the coordinate ring. -/
theorem exists_torsionFunction {x y : F} (h : W.Nonsingular x y) (n : ℕ)
    (hP : n • (some x y h : W.Point) = 0) :
    ∃ f : W.CoordinateRing, f ≠ 0 ∧
      CoordinateRing.XYIdeal W x (C y) ^ n = Ideal.span {f} := by
  have hclass : ClassGroup.mk W.FunctionField (CoordinateRing.XYIdeal' h ^ n) = 1 := by
    rw [map_pow]
    change n • toClass (some x y h) = 0
    rw [← map_nsmul, hP]
    exact toClass_zero
  apply (ClassGroup.mk_eq_one_of_coe_ideal (I := CoordinateRing.XYIdeal' h ^ n) ?_).mp hclass
  rw [Units.val_pow_eq_pow_val, CoordinateRing.XYIdeal'_eq, FractionalIdeal.coeIdeal_pow]

/-- An affine point is killed by `n` exactly when its point ideal to the `n`th
power has a nonzero generator. -/
theorem nsmul_eq_zero_iff_exists_torsionFunction {x y : F} (h : W.Nonsingular x y) (n : ℕ) :
    n • (some x y h : W.Point) = 0 ↔
    ∃ f : W.CoordinateRing, f ≠ 0 ∧
      CoordinateRing.XYIdeal W x (C y) ^ n = Ideal.span {f} := by
  refine ⟨exists_torsionFunction h n, ?_⟩
  intro hf
  apply toClass_injective
  rw [map_nsmul, toClass_zero]
  change ClassGroup.mk W.FunctionField (CoordinateRing.XYIdeal' h) ^ n = 1
  rw [← map_pow]
  apply (ClassGroup.mk_eq_one_of_coe_ideal (I := CoordinateRing.XYIdeal' h ^ n) ?_).mpr hf
  rw [Units.val_pow_eq_pow_val, CoordinateRing.XYIdeal'_eq, FractionalIdeal.coeIdeal_pow]

end WeierstrassCurve.Affine.Point

namespace WeierstrassCurve.Affine.CoordinateRing

variable {F : Type*} [Field F] {W : WeierstrassCurve.Affine F}

/-- A generator of a positive power of a point ideal vanishes at exactly that
affine point. This identifies the affine support of a torsion function. -/
theorem evalEval_eq_zero_iff_of_torsionFunction {x y x' y' : F} (h : W.Equation x' y')
    {n : ℕ} (hn : n ≠ 0)
    {f : W.CoordinateRing} (hf : XYIdeal W x (C y) ^ n = Ideal.span {f}) :
    AdjoinRoot.evalEval h f = 0 ↔ x = x' ∧ y = y' := by
  have hker : RingHom.ker (AdjoinRoot.evalEval h) = XYIdeal W x' (C y') := by
    ext a
    exact evalEval_eq_zero_iff h a
  have : (XYIdeal W x' (C y')).IsPrime := hker ▸ RingHom.ker_isPrime _
  rw [evalEval_eq_zero_iff, ← Ideal.span_singleton_le_iff_mem, ← hf,
    Ideal.IsPrime.pow_le_iff hn, XYIdeal_le_XYIdeal_iff h]

end WeierstrassCurve.Affine.CoordinateRing
